import type { BookingLocale } from './locales';

const english = {
  title: 'Book a call', language: 'Language', themeToggle: 'Toggle light or dark mode',
  rescheduleTitle: 'Pick a new time', rescheduleSub: 'Choose a new slot that works better for you.',
  videoCall: 'Video call — the join link is in your invite', teamTz: 'Host time zone', back: 'Back to your booking',
  errorTaken: 'That time was just taken — here are the latest openings.',
  errorAlreadyActive: 'You already have a call booked. Check your confirmation email to manage it.',
  errorUnavailable: 'That time is no longer available. Please choose another.',
  errorGraph: 'We could not reach the calendar just now. Please try again in a moment.',
  errorExpired: 'This booking link has expired. Please request a new link from your host.',
  errorGeneric: 'Something went wrong. Please try again.',
  cutoff: 'This call is too soon to change online. Contact your host for help.',
  requestAnother: 'Can’t find a suitable time? Contact your host to arrange one.',
  schedulerDown: 'Our scheduler is briefly unavailable. Please try again in a moment.',
  retry: 'Try again', loadError: 'We could not load open times just now.', noSlots: 'No open times in the next couple of weeks.',
  nextOpenDay: 'Show the next open day', prevMonth: 'Previous month', nextMonth: 'Next month',
  confirmedTitle: 'You’re booked', join: 'Join the call', reschedule: 'Reschedule', cancel: 'Cancel',
  manageNote: 'Need to change it? Reply to your confirmation email.', joinNote: 'The link is also in your calendar invite and confirmation email.',
  confirmCancelTitle: 'Cancel this call?', confirmCancelBody: 'You can book a new time whenever you are ready.',
  confirmCancelYes: 'Yes, cancel', keepIt: 'Keep it', bookedTitle: 'You are booked', canceledTitle: 'Your call is canceled',
  canceledBody: 'No problem — pick a new time whenever you are ready.', bookAgain: 'Book another time',
  degraded: 'Live availability is limited right now. Please try again shortly.',
};

type FlowCopy = Record<keyof typeof english, string>;

// System UI only. Host-authored names, descriptions and questions remain intact.
export const bookingFlowCopy = {
  en: english,
  ar: {
    title: 'احجز مكالمة', language: 'اللغة', themeToggle: 'التبديل بين الوضع الفاتح والداكن',
    rescheduleTitle: 'اختر وقتًا جديدًا', rescheduleSub: 'اختر موعدًا آخر يناسبك.',
    videoCall: 'مكالمة فيديو — رابط الانضمام في الدعوة', teamTz: 'منطقة المضيف الزمنية', back: 'العودة إلى حجزك',
    errorTaken: 'حُجز هذا الوقت للتو — إليك المواعيد المتاحة الآن.', errorAlreadyActive: 'لديك مكالمة محجوزة بالفعل. يمكنك إدارتها من رسالة التأكيد.',
    errorUnavailable: 'لم يعد هذا الوقت متاحًا. اختر وقتًا آخر.', errorGraph: 'تعذّر الاتصال بالتقويم الآن. حاول بعد قليل.',
    errorExpired: 'انتهت صلاحية رابط الحجز. اطلب رابطًا جديدًا من المضيف.', errorGeneric: 'حدث خطأ. حاول مجددًا.',
    cutoff: 'اقترب موعد المكالمة ولا يمكن تغييره عبر الإنترنت. تواصل مع المضيف.', requestAnother: 'لم تجد وقتًا مناسبًا؟ تواصل مع المضيف لترتيب موعد.',
    schedulerDown: 'خدمة الحجز غير متاحة مؤقتًا. حاول بعد قليل.', retry: 'حاول مجددًا', loadError: 'تعذّر تحميل الأوقات المتاحة الآن.', noSlots: 'لا توجد أوقات متاحة خلال الأسبوعين القادمين.',
    nextOpenDay: 'عرض اليوم المتاح التالي', prevMonth: 'الشهر السابق', nextMonth: 'الشهر التالي',
    confirmedTitle: 'تم تأكيد حجزك', join: 'انضم إلى المكالمة', reschedule: 'تغيير الموعد', cancel: 'إلغاء',
    manageNote: 'تحتاج إلى تغيير الموعد؟ رد على رسالة التأكيد.', joinNote: 'الرابط موجود أيضًا في دعوة التقويم ورسالة التأكيد.',
    confirmCancelTitle: 'هل تريد إلغاء المكالمة؟', confirmCancelBody: 'يمكنك حجز وقت جديد متى أردت.', confirmCancelYes: 'نعم، إلغاء', keepIt: 'الاحتفاظ بالحجز',
    bookedTitle: 'مكالمتك محجوزة', canceledTitle: 'أُلغيت مكالمتك', canceledBody: 'لا بأس — اختر وقتًا جديدًا عندما تكون جاهزًا.', bookAgain: 'حجز وقت آخر', degraded: 'الأوقات المتاحة محدودة حاليًا. حاول بعد قليل.',
  },
  fr: {
    title: 'Réserver un appel', language: 'Langue', themeToggle: 'Passer du mode clair au mode sombre',
    rescheduleTitle: 'Choisir un nouvel horaire', rescheduleSub: 'Choisissez un créneau qui vous convient mieux.',
    videoCall: 'Appel vidéo — le lien figure dans votre invitation', teamTz: 'Fuseau horaire de l’hôte', back: 'Retour à votre réservation',
    errorTaken: 'Ce créneau vient d’être réservé. Voici les disponibilités à jour.', errorAlreadyActive: 'Vous avez déjà un appel réservé. Gérez-le depuis votre e-mail de confirmation.',
    errorUnavailable: 'Ce créneau n’est plus disponible. Choisissez-en un autre.', errorGraph: 'Le calendrier est inaccessible pour le moment. Réessayez dans un instant.',
    errorExpired: 'Ce lien a expiré. Demandez un nouveau lien à votre hôte.', errorGeneric: 'Une erreur est survenue. Réessayez.',
    cutoff: 'L’appel est trop proche pour le modifier en ligne. Contactez votre hôte.', requestAnother: 'Aucun horaire ne vous convient ? Contactez votre hôte pour en convenir.',
    schedulerDown: 'Le service de réservation est momentanément indisponible. Réessayez dans un instant.', retry: 'Réessayer', loadError: 'Impossible de charger les créneaux disponibles.', noSlots: 'Aucun créneau disponible dans les deux prochaines semaines.',
    nextOpenDay: 'Afficher le prochain jour disponible', prevMonth: 'Mois précédent', nextMonth: 'Mois suivant',
    confirmedTitle: 'Votre réservation est confirmée', join: 'Rejoindre l’appel', reschedule: 'Reprogrammer', cancel: 'Annuler',
    manageNote: 'Besoin de modifier le rendez-vous ? Répondez à l’e-mail de confirmation.', joinNote: 'Le lien figure aussi dans l’invitation calendrier et l’e-mail de confirmation.',
    confirmCancelTitle: 'Annuler cet appel ?', confirmCancelBody: 'Vous pourrez choisir un autre horaire quand vous le souhaiterez.', confirmCancelYes: 'Oui, annuler', keepIt: 'Conserver le rendez-vous',
    bookedTitle: 'Votre appel est réservé', canceledTitle: 'Votre appel est annulé', canceledBody: 'Aucun souci : choisissez un nouvel horaire quand vous serez prêt.', bookAgain: 'Réserver un autre horaire', degraded: 'Les disponibilités sont limitées pour le moment. Réessayez dans un instant.',
  },
  es: {
    title: 'Reserva una llamada', language: 'Idioma', themeToggle: 'Cambiar entre modo claro y oscuro',
    rescheduleTitle: 'Elige otra hora', rescheduleSub: 'Elige un horario que te venga mejor.', videoCall: 'Videollamada — el enlace está en la invitación', teamTz: 'Zona horaria del anfitrión', back: 'Volver a tu reserva',
    errorTaken: 'Acaban de reservar esa hora. Estos son los horarios actualizados.', errorAlreadyActive: 'Ya tienes una llamada reservada. Puedes gestionarla desde el correo de confirmación.',
    errorUnavailable: 'Esa hora ya no está disponible. Elige otra.', errorGraph: 'No pudimos conectar con el calendario. Vuelve a intentarlo en un momento.',
    errorExpired: 'Este enlace ha caducado. Pide otro al anfitrión.', errorGeneric: 'Algo ha salido mal. Inténtalo de nuevo.',
    cutoff: 'Falta muy poco para la llamada para cambiarla en línea. Contacta con el anfitrión.', requestAnother: '¿No encuentras una hora adecuada? Contacta con el anfitrión para acordarla.',
    schedulerDown: 'El sistema de reservas no está disponible temporalmente. Inténtalo en un momento.', retry: 'Reintentar', loadError: 'No pudimos cargar los horarios disponibles.', noSlots: 'No hay horarios disponibles en las próximas dos semanas.',
    nextOpenDay: 'Ver el próximo día disponible', prevMonth: 'Mes anterior', nextMonth: 'Mes siguiente',
    confirmedTitle: 'Tu reserva está confirmada', join: 'Unirse a la llamada', reschedule: 'Cambiar fecha', cancel: 'Cancelar',
    manageNote: '¿Necesitas cambiarla? Responde al correo de confirmación.', joinNote: 'El enlace también está en la invitación del calendario y el correo de confirmación.',
    confirmCancelTitle: '¿Cancelar esta llamada?', confirmCancelBody: 'Puedes reservar otra hora cuando quieras.', confirmCancelYes: 'Sí, cancelar', keepIt: 'Mantener la reserva',
    bookedTitle: 'Tu llamada está reservada', canceledTitle: 'Tu llamada se ha cancelado', canceledBody: 'No pasa nada: elige otra hora cuando quieras.', bookAgain: 'Reservar otra hora', degraded: 'La disponibilidad está limitada por ahora. Inténtalo en un momento.',
  },
  de: {
    title: 'Gespräch buchen', language: 'Sprache', themeToggle: 'Zwischen hellem und dunklem Modus wechseln',
    rescheduleTitle: 'Neue Uhrzeit wählen', rescheduleSub: 'Wählen Sie einen Termin, der Ihnen besser passt.', videoCall: 'Videoanruf — der Link steht in Ihrer Einladung', teamTz: 'Zeitzone des Gastgebers', back: 'Zurück zu Ihrer Buchung',
    errorTaken: 'Dieser Termin wurde gerade gebucht. Hier sind die aktuellen freien Zeiten.', errorAlreadyActive: 'Sie haben bereits ein Gespräch gebucht. Verwalten Sie es über die Bestätigungs-E-Mail.',
    errorUnavailable: 'Diese Uhrzeit ist nicht mehr verfügbar. Bitte wählen Sie eine andere.', errorGraph: 'Der Kalender ist gerade nicht erreichbar. Bitte versuchen Sie es gleich noch einmal.',
    errorExpired: 'Dieser Buchungslink ist abgelaufen. Bitten Sie Ihren Gastgeber um einen neuen.', errorGeneric: 'Etwas ist schiefgegangen. Bitte versuchen Sie es erneut.',
    cutoff: 'Der Termin ist zu nah, um ihn online zu ändern. Kontaktieren Sie Ihren Gastgeber.', requestAnother: 'Keine passende Zeit dabei? Vereinbaren Sie einen Termin direkt mit Ihrem Gastgeber.',
    schedulerDown: 'Die Terminbuchung ist kurzzeitig nicht verfügbar. Versuchen Sie es gleich erneut.', retry: 'Erneut versuchen', loadError: 'Freie Zeiten konnten nicht geladen werden.', noSlots: 'In den nächsten zwei Wochen gibt es keine freien Termine.',
    nextOpenDay: 'Nächsten verfügbaren Tag anzeigen', prevMonth: 'Vorheriger Monat', nextMonth: 'Nächster Monat',
    confirmedTitle: 'Ihre Buchung ist bestätigt', join: 'Am Gespräch teilnehmen', reschedule: 'Termin verschieben', cancel: 'Absagen',
    manageNote: 'Möchten Sie etwas ändern? Antworten Sie auf Ihre Bestätigungs-E-Mail.', joinNote: 'Der Link steht auch in der Kalendereinladung und der Bestätigungs-E-Mail.',
    confirmCancelTitle: 'Dieses Gespräch absagen?', confirmCancelBody: 'Sie können jederzeit einen neuen Termin buchen.', confirmCancelYes: 'Ja, absagen', keepIt: 'Termin behalten',
    bookedTitle: 'Ihr Gespräch ist gebucht', canceledTitle: 'Ihr Gespräch wurde abgesagt', canceledBody: 'Kein Problem — wählen Sie einen neuen Termin, wenn Sie bereit sind.', bookAgain: 'Anderen Termin buchen', degraded: 'Die Verfügbarkeit ist gerade eingeschränkt. Bitte versuchen Sie es gleich erneut.',
  },
  nl: {
    title: 'Plan een gesprek', language: 'Taal', themeToggle: 'Wisselen tussen lichte en donkere modus',
    rescheduleTitle: 'Kies een nieuwe tijd', rescheduleSub: 'Kies een tijdstip dat je beter uitkomt.', videoCall: 'Videogesprek — de link staat in je uitnodiging', teamTz: 'Tijdzone van de host', back: 'Terug naar je boeking',
    errorTaken: 'Die tijd is net geboekt. Dit zijn de actuele beschikbare tijden.', errorAlreadyActive: 'Je hebt al een gesprek geboekt. Beheer het via je bevestigingsmail.',
    errorUnavailable: 'Die tijd is niet meer beschikbaar. Kies een andere.', errorGraph: 'We kunnen de agenda nu niet bereiken. Probeer het zo opnieuw.',
    errorExpired: 'Deze boekingslink is verlopen. Vraag je host om een nieuwe.', errorGeneric: 'Er ging iets mis. Probeer het opnieuw.',
    cutoff: 'Het gesprek is te binnenkort om online te wijzigen. Neem contact op met je host.', requestAnother: 'Geen geschikte tijd gevonden? Spreek een tijd af met je host.',
    schedulerDown: 'De planner is tijdelijk niet beschikbaar. Probeer het zo opnieuw.', retry: 'Opnieuw proberen', loadError: 'Beschikbare tijden konden niet worden geladen.', noSlots: 'Geen vrije tijden in de komende twee weken.',
    nextOpenDay: 'Toon de volgende beschikbare dag', prevMonth: 'Vorige maand', nextMonth: 'Volgende maand',
    confirmedTitle: 'Je boeking is bevestigd', join: 'Deelnemen aan het gesprek', reschedule: 'Verplaatsen', cancel: 'Annuleren',
    manageNote: 'Wil je iets wijzigen? Antwoord op je bevestigingsmail.', joinNote: 'De link staat ook in je agenda-uitnodiging en bevestigingsmail.',
    confirmCancelTitle: 'Dit gesprek annuleren?', confirmCancelBody: 'Je kunt een nieuwe tijd boeken wanneer je wilt.', confirmCancelYes: 'Ja, annuleren', keepIt: 'Boeking behouden',
    bookedTitle: 'Je gesprek is geboekt', canceledTitle: 'Je gesprek is geannuleerd', canceledBody: 'Geen probleem — kies een nieuwe tijd zodra je er klaar voor bent.', bookAgain: 'Een andere tijd boeken', degraded: 'De beschikbaarheid is momenteel beperkt. Probeer het zo opnieuw.',
  },
  pt: {
    title: 'Agende uma conversa', language: 'Idioma', themeToggle: 'Alternar entre modo claro e escuro',
    rescheduleTitle: 'Escolha outro horário', rescheduleSub: 'Escolha um horário que seja melhor para você.', videoCall: 'Videochamada — o link está no convite', teamTz: 'Fuso horário do anfitrião', back: 'Voltar ao agendamento',
    errorTaken: 'Esse horário acabou de ser reservado. Veja as opções atualizadas.', errorAlreadyActive: 'Você já tem uma conversa agendada. Gerencie pelo e-mail de confirmação.',
    errorUnavailable: 'Esse horário não está mais disponível. Escolha outro.', errorGraph: 'Não foi possível acessar o calendário agora. Tente novamente em instantes.',
    errorExpired: 'Este link expirou. Peça um novo ao anfitrião.', errorGeneric: 'Algo deu errado. Tente novamente.',
    cutoff: 'Falta pouco para a conversa e não é possível alterá-la on-line. Fale com o anfitrião.', requestAnother: 'Não encontrou um bom horário? Combine um diretamente com o anfitrião.',
    schedulerDown: 'O agendamento está temporariamente indisponível. Tente novamente em instantes.', retry: 'Tentar novamente', loadError: 'Não foi possível carregar os horários disponíveis.', noSlots: 'Não há horários disponíveis nas próximas duas semanas.',
    nextOpenDay: 'Ver o próximo dia disponível', prevMonth: 'Mês anterior', nextMonth: 'Próximo mês',
    confirmedTitle: 'Seu agendamento está confirmado', join: 'Entrar na chamada', reschedule: 'Reagendar', cancel: 'Cancelar',
    manageNote: 'Precisa alterar? Responda ao e-mail de confirmação.', joinNote: 'O link também está no convite do calendário e no e-mail de confirmação.',
    confirmCancelTitle: 'Cancelar esta conversa?', confirmCancelBody: 'Você pode escolher outro horário quando quiser.', confirmCancelYes: 'Sim, cancelar', keepIt: 'Manter agendamento',
    bookedTitle: 'Sua conversa está agendada', canceledTitle: 'Sua conversa foi cancelada', canceledBody: 'Sem problema — escolha outro horário quando quiser.', bookAgain: 'Agendar outro horário', degraded: 'A disponibilidade está limitada no momento. Tente novamente em instantes.',
  },
  hi: {
    title: 'कॉल बुक करें', language: 'भाषा', themeToggle: 'लाइट या डार्क मोड बदलें',
    rescheduleTitle: 'नया समय चुनें', rescheduleSub: 'ऐसा समय चुनें जो आपके लिए बेहतर हो।', videoCall: 'वीडियो कॉल — जुड़ने का लिंक निमंत्रण में मिलेगा', teamTz: 'मेज़बान का समय क्षेत्र', back: 'अपनी बुकिंग पर वापस जाएँ',
    errorTaken: 'यह समय अभी बुक हो गया। अब उपलब्ध समय देखें।', errorAlreadyActive: 'आपकी एक कॉल पहले से बुक है। पुष्टि वाले ईमेल से उसे प्रबंधित करें।',
    errorUnavailable: 'यह समय अब उपलब्ध नहीं है। दूसरा समय चुनें।', errorGraph: 'अभी कैलेंडर से संपर्क नहीं हो सका। थोड़ी देर बाद फिर कोशिश करें।',
    errorExpired: 'इस बुकिंग लिंक की अवधि समाप्त हो गई है। मेज़बान से नया लिंक माँगें।', errorGeneric: 'कुछ गड़बड़ हो गई। फिर कोशिश करें।',
    cutoff: 'कॉल का समय बहुत नज़दीक है, इसलिए ऑनलाइन बदलाव संभव नहीं है। मेज़बान से संपर्क करें।', requestAnother: 'सही समय नहीं मिल रहा? मेज़बान से समय तय करें।',
    schedulerDown: 'बुकिंग सेवा अभी उपलब्ध नहीं है। थोड़ी देर बाद फिर कोशिश करें।', retry: 'फिर कोशिश करें', loadError: 'अभी उपलब्ध समय लोड नहीं हो सके।', noSlots: 'अगले दो हफ़्तों में कोई समय उपलब्ध नहीं है।',
    nextOpenDay: 'अगला उपलब्ध दिन देखें', prevMonth: 'पिछला महीना', nextMonth: 'अगला महीना',
    confirmedTitle: 'आपकी बुकिंग पक्की है', join: 'कॉल में जुड़ें', reschedule: 'समय बदलें', cancel: 'रद्द करें',
    manageNote: 'बदलाव चाहिए? पुष्टि वाले ईमेल का जवाब दें।', joinNote: 'यह लिंक कैलेंडर निमंत्रण और पुष्टि वाले ईमेल में भी है।',
    confirmCancelTitle: 'यह कॉल रद्द करें?', confirmCancelBody: 'आप जब चाहें नया समय बुक कर सकते हैं।', confirmCancelYes: 'हाँ, रद्द करें', keepIt: 'बुकिंग रखें',
    bookedTitle: 'आपकी कॉल बुक है', canceledTitle: 'आपकी कॉल रद्द हो गई है', canceledBody: 'कोई बात नहीं — जब तैयार हों, नया समय चुनें।', bookAgain: 'दूसरा समय बुक करें', degraded: 'अभी उपलब्ध समय सीमित हैं। थोड़ी देर बाद फिर कोशिश करें।',
  },
  ur: {
    title: 'کال بک کریں', language: 'زبان', themeToggle: 'لائٹ یا ڈارک موڈ تبدیل کریں',
    rescheduleTitle: 'نیا وقت منتخب کریں', rescheduleSub: 'وہ وقت منتخب کریں جو آپ کے لیے بہتر ہو۔', videoCall: 'ویڈیو کال — شامل ہونے کا لنک دعوت میں ہے', teamTz: 'میزبان کا ٹائم زون', back: 'اپنی بکنگ پر واپس جائیں',
    errorTaken: 'یہ وقت ابھی بک ہو گیا ہے۔ تازہ دستیاب اوقات دیکھیں۔', errorAlreadyActive: 'آپ کی ایک کال پہلے سے بک ہے۔ تصدیقی ای میل سے اسے منظم کریں۔',
    errorUnavailable: 'یہ وقت اب دستیاب نہیں۔ دوسرا وقت منتخب کریں۔', errorGraph: 'ابھی کیلنڈر سے رابطہ نہیں ہو سکا۔ کچھ دیر بعد دوبارہ کوشش کریں۔',
    errorExpired: 'اس بکنگ لنک کی مدت ختم ہو گئی ہے۔ میزبان سے نیا لنک مانگیں۔', errorGeneric: 'کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔',
    cutoff: 'کال کا وقت بہت قریب ہے، آن لائن تبدیلی ممکن نہیں۔ میزبان سے رابطہ کریں۔', requestAnother: 'مناسب وقت نہیں ملا؟ میزبان سے وقت طے کریں۔',
    schedulerDown: 'بکنگ سروس عارضی طور پر دستیاب نہیں۔ کچھ دیر بعد کوشش کریں۔', retry: 'دوبارہ کوشش کریں', loadError: 'دستیاب اوقات لوڈ نہیں ہو سکے۔', noSlots: 'اگلے دو ہفتوں میں کوئی وقت دستیاب نہیں۔',
    nextOpenDay: 'اگلا دستیاب دن دکھائیں', prevMonth: 'پچھلا مہینہ', nextMonth: 'اگلا مہینہ',
    confirmedTitle: 'آپ کی بکنگ کی تصدیق ہو گئی ہے', join: 'کال میں شامل ہوں', reschedule: 'وقت تبدیل کریں', cancel: 'منسوخ کریں',
    manageNote: 'تبدیلی چاہیے؟ تصدیقی ای میل کا جواب دیں۔', joinNote: 'لنک کیلنڈر کی دعوت اور تصدیقی ای میل میں بھی موجود ہے۔',
    confirmCancelTitle: 'یہ کال منسوخ کریں؟', confirmCancelBody: 'آپ جب چاہیں نیا وقت بک کر سکتے ہیں۔', confirmCancelYes: 'ہاں، منسوخ کریں', keepIt: 'بکنگ برقرار رکھیں',
    bookedTitle: 'آپ کی کال بک ہے', canceledTitle: 'آپ کی کال منسوخ ہو گئی ہے', canceledBody: 'کوئی بات نہیں — جب تیار ہوں، نیا وقت منتخب کریں۔', bookAgain: 'دوسرا وقت بک کریں', degraded: 'ابھی دستیاب اوقات محدود ہیں۔ کچھ دیر بعد کوشش کریں۔',
  },
  it: {
    title: 'Prenota una chiamata', language: 'Lingua', themeToggle: 'Passa dalla modalità chiara a quella scura',
    rescheduleTitle: 'Scegli un nuovo orario', rescheduleSub: 'Scegli un orario più comodo per te.', videoCall: 'Videochiamata — il link è nell’invito', teamTz: 'Fuso orario dell’organizzatore', back: 'Torna alla prenotazione',
    errorTaken: 'Questo orario è appena stato prenotato. Ecco le disponibilità aggiornate.', errorAlreadyActive: 'Hai già una chiamata prenotata. Gestiscila dall’e-mail di conferma.',
    errorUnavailable: 'Questo orario non è più disponibile. Scegline un altro.', errorGraph: 'Non riusciamo ad accedere al calendario. Riprova tra poco.',
    errorExpired: 'Questo link è scaduto. Chiedine uno nuovo all’organizzatore.', errorGeneric: 'Qualcosa è andato storto. Riprova.',
    cutoff: 'Manca troppo poco alla chiamata per modificarla online. Contatta l’organizzatore.', requestAnother: 'Non trovi un orario adatto? Concordalo con l’organizzatore.',
    schedulerDown: 'Il servizio di prenotazione non è disponibile al momento. Riprova tra poco.', retry: 'Riprova', loadError: 'Impossibile caricare gli orari disponibili.', noSlots: 'Nessun orario disponibile nelle prossime due settimane.',
    nextOpenDay: 'Mostra il prossimo giorno disponibile', prevMonth: 'Mese precedente', nextMonth: 'Mese successivo',
    confirmedTitle: 'La prenotazione è confermata', join: 'Partecipa alla chiamata', reschedule: 'Sposta appuntamento', cancel: 'Annulla',
    manageNote: 'Vuoi modificare l’appuntamento? Rispondi all’e-mail di conferma.', joinNote: 'Il link è anche nell’invito del calendario e nell’e-mail di conferma.',
    confirmCancelTitle: 'Annullare questa chiamata?', confirmCancelBody: 'Puoi prenotare un altro orario quando vuoi.', confirmCancelYes: 'Sì, annulla', keepIt: 'Mantieni appuntamento',
    bookedTitle: 'La chiamata è prenotata', canceledTitle: 'La chiamata è annullata', canceledBody: 'Nessun problema: scegli un nuovo orario quando vuoi.', bookAgain: 'Prenota un altro orario', degraded: 'La disponibilità è limitata al momento. Riprova tra poco.',
  },
  pl: {
    title: 'Umów rozmowę', language: 'Język', themeToggle: 'Przełącz tryb jasny lub ciemny',
    rescheduleTitle: 'Wybierz nowy termin', rescheduleSub: 'Wybierz termin, który bardziej Ci odpowiada.', videoCall: 'Rozmowa wideo — link znajdziesz w zaproszeniu', teamTz: 'Strefa czasowa gospodarza', back: 'Wróć do rezerwacji',
    errorTaken: 'Ten termin właśnie zarezerwowano. Oto aktualne wolne terminy.', errorAlreadyActive: 'Masz już umówioną rozmowę. Zarządzaj nią przez e-mail z potwierdzeniem.',
    errorUnavailable: 'Ten termin nie jest już dostępny. Wybierz inny.', errorGraph: 'Nie możemy teraz połączyć się z kalendarzem. Spróbuj za chwilę.',
    errorExpired: 'Ten link wygasł. Poproś gospodarza o nowy.', errorGeneric: 'Coś poszło nie tak. Spróbuj ponownie.',
    cutoff: 'Do rozmowy zostało zbyt mało czasu na zmianę online. Skontaktuj się z gospodarzem.', requestAnother: 'Nie widzisz dogodnego terminu? Ustal go z gospodarzem.',
    schedulerDown: 'Rezerwacje są chwilowo niedostępne. Spróbuj za chwilę.', retry: 'Spróbuj ponownie', loadError: 'Nie udało się wczytać wolnych terminów.', noSlots: 'Brak wolnych terminów w najbliższych dwóch tygodniach.',
    nextOpenDay: 'Pokaż następny dostępny dzień', prevMonth: 'Poprzedni miesiąc', nextMonth: 'Następny miesiąc',
    confirmedTitle: 'Rezerwacja potwierdzona', join: 'Dołącz do rozmowy', reschedule: 'Zmień termin', cancel: 'Anuluj',
    manageNote: 'Potrzebujesz zmiany? Odpowiedz na e-mail z potwierdzeniem.', joinNote: 'Link znajduje się też w zaproszeniu kalendarza i e-mailu z potwierdzeniem.',
    confirmCancelTitle: 'Anulować tę rozmowę?', confirmCancelBody: 'Możesz zarezerwować nowy termin, kiedy zechcesz.', confirmCancelYes: 'Tak, anuluj', keepIt: 'Zachowaj rezerwację',
    bookedTitle: 'Rozmowa jest umówiona', canceledTitle: 'Rozmowa została anulowana', canceledBody: 'Nie ma problemu — wybierz nowy termin, gdy będziesz gotowy.', bookAgain: 'Zarezerwuj inny termin', degraded: 'Dostępność jest obecnie ograniczona. Spróbuj za chwilę.',
  },
  tr: {
    title: 'Görüşme planlayın', language: 'Dil', themeToggle: 'Açık veya koyu moda geç',
    rescheduleTitle: 'Yeni bir saat seçin', rescheduleSub: 'Size daha uygun bir saat seçin.', videoCall: 'Görüntülü görüşme — katılım bağlantısı davetinizde', teamTz: 'Ev sahibinin saat dilimi', back: 'Rezervasyonunuza dönün',
    errorTaken: 'Bu saat az önce rezerve edildi. Güncel boş saatleri görebilirsiniz.', errorAlreadyActive: 'Zaten planlanmış bir görüşmeniz var. Onay e-postasından yönetebilirsiniz.',
    errorUnavailable: 'Bu saat artık uygun değil. Lütfen başka bir saat seçin.', errorGraph: 'Takvime şu anda ulaşılamıyor. Biraz sonra tekrar deneyin.',
    errorExpired: 'Bu rezervasyon bağlantısının süresi doldu. Ev sahibinden yeni bir bağlantı isteyin.', errorGeneric: 'Bir sorun oluştu. Lütfen tekrar deneyin.',
    cutoff: 'Görüşmeye çok az kaldığı için çevrimiçi değişiklik yapılamıyor. Ev sahibiyle iletişime geçin.', requestAnother: 'Uygun saat bulamadınız mı? Ev sahibiyle bir saat belirleyin.',
    schedulerDown: 'Rezervasyon sistemi geçici olarak kullanılamıyor. Biraz sonra tekrar deneyin.', retry: 'Tekrar dene', loadError: 'Boş saatler yüklenemedi.', noSlots: 'Önümüzdeki iki hafta içinde boş saat yok.',
    nextOpenDay: 'Sonraki uygun günü göster', prevMonth: 'Önceki ay', nextMonth: 'Sonraki ay',
    confirmedTitle: 'Rezervasyonunuz onaylandı', join: 'Görüşmeye katıl', reschedule: 'Yeniden planla', cancel: 'İptal et',
    manageNote: 'Değişiklik mi gerekiyor? Onay e-postasına yanıt verin.', joinNote: 'Bağlantı, takvim davetinizde ve onay e-postanızda da yer alır.',
    confirmCancelTitle: 'Bu görüşme iptal edilsin mi?', confirmCancelBody: 'Hazır olduğunuzda yeni bir saat seçebilirsiniz.', confirmCancelYes: 'Evet, iptal et', keepIt: 'Rezervasyonu koru',
    bookedTitle: 'Görüşmeniz planlandı', canceledTitle: 'Görüşmeniz iptal edildi', canceledBody: 'Sorun değil — hazır olduğunuzda yeni bir saat seçin.', bookAgain: 'Başka bir saat seç', degraded: 'Uygun saat bilgisi şu anda sınırlı. Biraz sonra tekrar deneyin.',
  },
  'zh-Hans': {
    title: '预约通话', language: '语言', themeToggle: '切换浅色或深色模式',
    rescheduleTitle: '选择新时间', rescheduleSub: '请选择更适合您的时段。', videoCall: '视频通话 — 加入链接在邀请中', teamTz: '主持人时区', back: '返回您的预约',
    errorTaken: '该时段刚刚被预约。以下是最新可选时段。', errorAlreadyActive: '您已有通话预约，可通过确认邮件进行管理。',
    errorUnavailable: '该时段已不可用，请选择其他时段。', errorGraph: '暂时无法连接日历，请稍后重试。',
    errorExpired: '此预约链接已过期，请向主持人索取新链接。', errorGeneric: '出现问题，请重试。',
    cutoff: '距离通话开始太近，无法在线修改。请联系主持人。', requestAnother: '没有合适的时段？请联系主持人另行安排。',
    schedulerDown: '预约服务暂时不可用，请稍后重试。', retry: '重试', loadError: '暂时无法加载可用时段。', noSlots: '未来两周暂无可用时段。',
    nextOpenDay: '查看下一个可用日期', prevMonth: '上个月', nextMonth: '下个月',
    confirmedTitle: '预约已确认', join: '加入通话', reschedule: '改期', cancel: '取消',
    manageNote: '需要修改？请回复确认邮件。', joinNote: '加入链接也在日历邀请和确认邮件中。',
    confirmCancelTitle: '取消此次通话？', confirmCancelBody: '您可以随时预约其他时间。', confirmCancelYes: '确认取消', keepIt: '保留预约',
    bookedTitle: '通话已预约', canceledTitle: '通话已取消', canceledBody: '没关系，准备好后可选择新时间。', bookAgain: '预约其他时间', degraded: '当前可用时段信息受限，请稍后重试。',
  },
  ja: {
    title: '通話を予約', language: '言語', themeToggle: 'ライト・ダークモードを切り替え',
    rescheduleTitle: '新しい日時を選択', rescheduleSub: 'ご都合のよい日時を選んでください。', videoCall: 'ビデオ通話 — 参加リンクは招待に記載', teamTz: '主催者のタイムゾーン', back: '予約に戻る',
    errorTaken: 'この時間は今予約されました。最新の空き時間をご確認ください。', errorAlreadyActive: 'すでに予約があります。確認メールから管理できます。',
    errorUnavailable: 'この時間は予約できなくなりました。別の時間をお選びください。', errorGraph: '現在カレンダーに接続できません。しばらくしてからお試しください。',
    errorExpired: '予約リンクの有効期限が切れています。主催者に新しいリンクを依頼してください。', errorGeneric: '問題が発生しました。もう一度お試しください。',
    cutoff: '開始時刻が近いためオンラインで変更できません。主催者にご連絡ください。', requestAnother: 'ご都合のよい時間がありませんか？主催者にご相談ください。',
    schedulerDown: '予約サービスは一時的に利用できません。しばらくしてからお試しください。', retry: '再試行', loadError: '空き時間を読み込めませんでした。', noSlots: '今後2週間に空き時間はありません。',
    nextOpenDay: '次の予約可能日を表示', prevMonth: '前の月', nextMonth: '次の月',
    confirmedTitle: '予約が確定しました', join: '通話に参加', reschedule: '日時を変更', cancel: 'キャンセル',
    manageNote: '変更をご希望の場合は確認メールにご返信ください。', joinNote: 'リンクはカレンダーの招待と確認メールにも記載されています。',
    confirmCancelTitle: 'この通話をキャンセルしますか？', confirmCancelBody: 'ご都合がつき次第、新しい時間を予約できます。', confirmCancelYes: 'はい、キャンセル', keepIt: '予約を維持',
    bookedTitle: '通話を予約済みです', canceledTitle: '通話をキャンセルしました', canceledBody: 'ご都合がつき次第、新しい時間をお選びください。', bookAgain: '別の時間を予約', degraded: '現在、空き時間の情報が限られています。しばらくしてからお試しください。',
  },
  ko: {
    title: '통화 예약', language: '언어', themeToggle: '라이트 모드 또는 다크 모드 전환',
    rescheduleTitle: '새 시간 선택', rescheduleSub: '더 편한 시간을 선택하세요.', videoCall: '화상 통화 — 참여 링크는 초대장에 있습니다', teamTz: '호스트 시간대', back: '예약으로 돌아가기',
    errorTaken: '방금 다른 사람이 예약한 시간입니다. 최신 가능한 시간을 확인하세요.', errorAlreadyActive: '이미 예약한 통화가 있습니다. 확인 이메일에서 관리하세요.',
    errorUnavailable: '이 시간은 더 이상 예약할 수 없습니다. 다른 시간을 선택하세요.', errorGraph: '현재 캘린더에 연결할 수 없습니다. 잠시 후 다시 시도하세요.',
    errorExpired: '예약 링크가 만료되었습니다. 호스트에게 새 링크를 요청하세요.', errorGeneric: '문제가 발생했습니다. 다시 시도하세요.',
    cutoff: '통화 시작이 임박하여 온라인으로 변경할 수 없습니다. 호스트에게 문의하세요.', requestAnother: '원하는 시간이 없나요? 호스트에게 연락해 시간을 정하세요.',
    schedulerDown: '예약 서비스를 일시적으로 이용할 수 없습니다. 잠시 후 다시 시도하세요.', retry: '다시 시도', loadError: '가능한 시간을 불러오지 못했습니다.', noSlots: '앞으로 2주 동안 가능한 시간이 없습니다.',
    nextOpenDay: '다음 가능한 날짜 보기', prevMonth: '이전 달', nextMonth: '다음 달',
    confirmedTitle: '예약이 확정되었습니다', join: '통화 참여', reschedule: '일정 변경', cancel: '취소',
    manageNote: '변경이 필요하신가요? 확인 이메일에 회신하세요.', joinNote: '링크는 캘린더 초대장과 확인 이메일에도 있습니다.',
    confirmCancelTitle: '이 통화를 취소할까요?', confirmCancelBody: '준비되시면 언제든 새 시간을 예약할 수 있습니다.', confirmCancelYes: '네, 취소합니다', keepIt: '예약 유지',
    bookedTitle: '통화가 예약되었습니다', canceledTitle: '통화가 취소되었습니다', canceledBody: '괜찮습니다. 준비되시면 새 시간을 선택하세요.', bookAgain: '다른 시간 예약', degraded: '현재 가능한 시간 정보가 제한되어 있습니다. 잠시 후 다시 시도하세요.',
  },
  id: {
    title: 'Jadwalkan panggilan', language: 'Bahasa', themeToggle: 'Ganti mode terang atau gelap',
    rescheduleTitle: 'Pilih waktu baru', rescheduleSub: 'Pilih waktu yang lebih cocok untuk Anda.', videoCall: 'Panggilan video — tautan bergabung ada di undangan', teamTz: 'Zona waktu host', back: 'Kembali ke pemesanan',
    errorTaken: 'Waktu itu baru saja dipesan. Berikut pilihan terbaru.', errorAlreadyActive: 'Anda sudah memiliki jadwal panggilan. Kelola melalui email konfirmasi.',
    errorUnavailable: 'Waktu itu tidak lagi tersedia. Pilih waktu lain.', errorGraph: 'Kalender belum dapat diakses. Coba lagi sebentar lagi.',
    errorExpired: 'Tautan ini sudah kedaluwarsa. Minta tautan baru kepada host.', errorGeneric: 'Terjadi masalah. Silakan coba lagi.',
    cutoff: 'Waktu panggilan sudah terlalu dekat untuk diubah secara online. Hubungi host.', requestAnother: 'Tidak menemukan waktu yang cocok? Hubungi host untuk mengaturnya.',
    schedulerDown: 'Layanan penjadwalan sedang tidak tersedia. Coba lagi sebentar lagi.', retry: 'Coba lagi', loadError: 'Waktu yang tersedia belum dapat dimuat.', noSlots: 'Tidak ada waktu kosong dalam dua minggu ke depan.',
    nextOpenDay: 'Lihat hari tersedia berikutnya', prevMonth: 'Bulan sebelumnya', nextMonth: 'Bulan berikutnya',
    confirmedTitle: 'Pemesanan Anda dikonfirmasi', join: 'Gabung ke panggilan', reschedule: 'Jadwalkan ulang', cancel: 'Batalkan',
    manageNote: 'Perlu mengubah jadwal? Balas email konfirmasi Anda.', joinNote: 'Tautan juga ada di undangan kalender dan email konfirmasi.',
    confirmCancelTitle: 'Batalkan panggilan ini?', confirmCancelBody: 'Anda dapat memesan waktu baru kapan saja.', confirmCancelYes: 'Ya, batalkan', keepIt: 'Pertahankan jadwal',
    bookedTitle: 'Panggilan Anda sudah dijadwalkan', canceledTitle: 'Panggilan Anda dibatalkan', canceledBody: 'Tidak masalah — pilih waktu baru saat Anda siap.', bookAgain: 'Pesan waktu lain', degraded: 'Informasi ketersediaan sedang terbatas. Coba lagi sebentar lagi.',
  },
  vi: {
    title: 'Đặt lịch gọi', language: 'Ngôn ngữ', themeToggle: 'Chuyển chế độ sáng hoặc tối',
    rescheduleTitle: 'Chọn giờ mới', rescheduleSub: 'Chọn khung giờ phù hợp hơn với bạn.', videoCall: 'Cuộc gọi video — liên kết tham gia nằm trong thư mời', teamTz: 'Múi giờ của người chủ trì', back: 'Quay lại lịch hẹn',
    errorTaken: 'Khung giờ này vừa được đặt. Đây là các khung giờ còn trống mới nhất.', errorAlreadyActive: 'Bạn đã có lịch gọi. Hãy quản lý qua email xác nhận.',
    errorUnavailable: 'Khung giờ này không còn trống. Hãy chọn giờ khác.', errorGraph: 'Hiện chưa kết nối được với lịch. Vui lòng thử lại sau ít phút.',
    errorExpired: 'Liên kết đã hết hạn. Hãy xin người chủ trì liên kết mới.', errorGeneric: 'Đã xảy ra lỗi. Vui lòng thử lại.',
    cutoff: 'Cuộc gọi sắp bắt đầu nên không thể đổi trực tuyến. Hãy liên hệ người chủ trì.', requestAnother: 'Không tìm thấy giờ phù hợp? Hãy liên hệ người chủ trì để sắp xếp.',
    schedulerDown: 'Dịch vụ đặt lịch tạm thời không khả dụng. Vui lòng thử lại sau ít phút.', retry: 'Thử lại', loadError: 'Chưa tải được các khung giờ trống.', noSlots: 'Không có khung giờ trống trong hai tuần tới.',
    nextOpenDay: 'Xem ngày còn trống tiếp theo', prevMonth: 'Tháng trước', nextMonth: 'Tháng sau',
    confirmedTitle: 'Lịch hẹn đã được xác nhận', join: 'Tham gia cuộc gọi', reschedule: 'Đổi lịch', cancel: 'Hủy',
    manageNote: 'Cần thay đổi? Hãy trả lời email xác nhận.', joinNote: 'Liên kết cũng có trong thư mời lịch và email xác nhận.',
    confirmCancelTitle: 'Hủy cuộc gọi này?', confirmCancelBody: 'Bạn có thể đặt giờ mới khi sẵn sàng.', confirmCancelYes: 'Có, hủy cuộc gọi', keepIt: 'Giữ lịch hẹn',
    bookedTitle: 'Cuộc gọi đã được đặt lịch', canceledTitle: 'Cuộc gọi đã bị hủy', canceledBody: 'Không sao — hãy chọn giờ mới khi bạn sẵn sàng.', bookAgain: 'Đặt giờ khác', degraded: 'Thông tin giờ trống hiện còn hạn chế. Vui lòng thử lại sau ít phút.',
  },
  ro: {
    title: 'Programează un apel', language: 'Limbă', themeToggle: 'Schimbă modul luminos sau întunecat',
    rescheduleTitle: 'Alege o oră nouă', rescheduleSub: 'Alege un interval care îți convine mai bine.', videoCall: 'Apel video — linkul este în invitație', teamTz: 'Fusul orar al gazdei', back: 'Înapoi la programare',
    errorTaken: 'Acest interval tocmai a fost rezervat. Iată disponibilitatea actualizată.', errorAlreadyActive: 'Ai deja un apel programat. Gestionează-l din e-mailul de confirmare.',
    errorUnavailable: 'Acest interval nu mai este disponibil. Alege altul.', errorGraph: 'Nu putem accesa calendarul acum. Încearcă din nou în câteva momente.',
    errorExpired: 'Acest link a expirat. Cere gazdei un link nou.', errorGeneric: 'A apărut o problemă. Încearcă din nou.',
    cutoff: 'Apelul începe prea curând pentru a-l modifica online. Contactează gazda.', requestAnother: 'Nu găsești o oră potrivită? Contactează gazda pentru a o stabili.',
    schedulerDown: 'Programările sunt temporar indisponibile. Încearcă din nou în câteva momente.', retry: 'Încearcă din nou', loadError: 'Nu am putut încărca intervalele disponibile.', noSlots: 'Nu există intervale libere în următoarele două săptămâni.',
    nextOpenDay: 'Arată următoarea zi disponibilă', prevMonth: 'Luna precedentă', nextMonth: 'Luna următoare',
    confirmedTitle: 'Programarea este confirmată', join: 'Intră în apel', reschedule: 'Reprogramează', cancel: 'Anulează',
    manageNote: 'Vrei să modifici programarea? Răspunde la e-mailul de confirmare.', joinNote: 'Linkul este și în invitația din calendar și în e-mailul de confirmare.',
    confirmCancelTitle: 'Anulezi acest apel?', confirmCancelBody: 'Poți alege o oră nouă când dorești.', confirmCancelYes: 'Da, anulează', keepIt: 'Păstrează programarea',
    bookedTitle: 'Apelul este programat', canceledTitle: 'Apelul a fost anulat', canceledBody: 'Nicio problemă — alege o oră nouă când ești pregătit.', bookAgain: 'Programează altă oră', degraded: 'Disponibilitatea este momentan limitată. Încearcă din nou în câteva momente.',
  },
  sv: {
    title: 'Boka ett samtal', language: 'Språk', themeToggle: 'Växla mellan ljust och mörkt läge',
    rescheduleTitle: 'Välj en ny tid', rescheduleSub: 'Välj en tid som passar dig bättre.', videoCall: 'Videosamtal — länken finns i din inbjudan', teamTz: 'Värdens tidszon', back: 'Tillbaka till bokningen',
    errorTaken: 'Den tiden bokades nyss. Här är de senaste lediga tiderna.', errorAlreadyActive: 'Du har redan ett samtal bokat. Hantera det via bekräftelsemejlet.',
    errorUnavailable: 'Den tiden är inte längre ledig. Välj en annan.', errorGraph: 'Vi kan inte nå kalendern just nu. Försök igen om en stund.',
    errorExpired: 'Bokningslänken har gått ut. Be värden om en ny.', errorGeneric: 'Något gick fel. Försök igen.',
    cutoff: 'Samtalet börjar för snart för att ändras online. Kontakta värden.', requestAnother: 'Hittar du ingen passande tid? Kontakta värden för att bestämma en.',
    schedulerDown: 'Bokningen är tillfälligt otillgänglig. Försök igen om en stund.', retry: 'Försök igen', loadError: 'Lediga tider kunde inte hämtas.', noSlots: 'Inga lediga tider de närmaste två veckorna.',
    nextOpenDay: 'Visa nästa lediga dag', prevMonth: 'Föregående månad', nextMonth: 'Nästa månad',
    confirmedTitle: 'Din bokning är bekräftad', join: 'Anslut till samtalet', reschedule: 'Boka om', cancel: 'Avboka',
    manageNote: 'Behöver du ändra? Svara på bekräftelsemejlet.', joinNote: 'Länken finns också i kalenderinbjudan och bekräftelsemejlet.',
    confirmCancelTitle: 'Avboka det här samtalet?', confirmCancelBody: 'Du kan boka en ny tid när du vill.', confirmCancelYes: 'Ja, avboka', keepIt: 'Behåll bokningen',
    bookedTitle: 'Ditt samtal är bokat', canceledTitle: 'Ditt samtal är avbokat', canceledBody: 'Ingen fara — välj en ny tid när du är redo.', bookAgain: 'Boka en annan tid', degraded: 'Tillgängligheten är begränsad just nu. Försök igen om en stund.',
  },
  bn: {
    title: 'কল বুক করুন', language: 'ভাষা', themeToggle: 'লাইট বা ডার্ক মোড বদলান',
    rescheduleTitle: 'নতুন সময় বেছে নিন', rescheduleSub: 'আপনার জন্য সুবিধাজনক সময় বেছে নিন।', videoCall: 'ভিডিও কল — যোগ দেওয়ার লিংক আমন্ত্রণে আছে', teamTz: 'আয়োজকের সময় অঞ্চল', back: 'আপনার বুকিংয়ে ফিরে যান',
    errorTaken: 'এই সময়টি এইমাত্র বুক হয়েছে। এখনকার খালি সময়গুলো দেখুন।', errorAlreadyActive: 'আপনার একটি কল ইতিমধ্যে বুক করা আছে। নিশ্চিতকরণ ইমেইল থেকে পরিচালনা করুন।',
    errorUnavailable: 'এই সময়টি আর খালি নেই। অন্য সময় বেছে নিন।', errorGraph: 'এখন ক্যালেন্ডারে সংযোগ করা যাচ্ছে না। একটু পরে আবার চেষ্টা করুন।',
    errorExpired: 'বুকিং লিংকটির মেয়াদ শেষ। আয়োজকের কাছে নতুন লিংক চান।', errorGeneric: 'একটি সমস্যা হয়েছে। আবার চেষ্টা করুন।',
    cutoff: 'কলের সময় খুব কাছে, তাই অনলাইনে বদলানো যাবে না। আয়োজকের সঙ্গে যোগাযোগ করুন।', requestAnother: 'সুবিধাজনক সময় পাচ্ছেন না? আয়োজকের সঙ্গে সময় ঠিক করুন।',
    schedulerDown: 'বুকিং সেবা সাময়িকভাবে বন্ধ। একটু পরে আবার চেষ্টা করুন।', retry: 'আবার চেষ্টা করুন', loadError: 'খালি সময়গুলো লোড করা যায়নি।', noSlots: 'আগামী দুই সপ্তাহে কোনো সময় খালি নেই।',
    nextOpenDay: 'পরের খালি দিন দেখুন', prevMonth: 'আগের মাস', nextMonth: 'পরের মাস',
    confirmedTitle: 'আপনার বুকিং নিশ্চিত হয়েছে', join: 'কলে যোগ দিন', reschedule: 'সময় বদলান', cancel: 'বাতিল করুন',
    manageNote: 'বদলাতে চান? নিশ্চিতকরণ ইমেইলের উত্তর দিন।', joinNote: 'লিংকটি ক্যালেন্ডার আমন্ত্রণ ও নিশ্চিতকরণ ইমেইলেও আছে।',
    confirmCancelTitle: 'এই কল বাতিল করবেন?', confirmCancelBody: 'আপনি যখন চান নতুন সময় বুক করতে পারেন।', confirmCancelYes: 'হ্যাঁ, বাতিল করুন', keepIt: 'বুকিং রাখুন',
    bookedTitle: 'আপনার কল বুক করা আছে', canceledTitle: 'আপনার কল বাতিল হয়েছে', canceledBody: 'সমস্যা নেই — প্রস্তুত হলে নতুন সময় বেছে নিন।', bookAgain: 'অন্য সময় বুক করুন', degraded: 'এখন খালি সময়ের তথ্য সীমিত। একটু পরে আবার চেষ্টা করুন।',
  },
  th: {
    title: 'จองเวลาพูดคุย', language: 'ภาษา', themeToggle: 'สลับโหมดสว่างหรือมืด',
    rescheduleTitle: 'เลือกเวลาใหม่', rescheduleSub: 'เลือกเวลาที่สะดวกกว่าเดิม', videoCall: 'วิดีโอคอล — ลิงก์เข้าร่วมอยู่ในคำเชิญ', teamTz: 'เขตเวลาของผู้จัด', back: 'กลับไปที่การจอง',
    errorTaken: 'เวลานี้เพิ่งถูกจองไป ดูเวลาว่างล่าสุดได้ที่นี่', errorAlreadyActive: 'คุณมีนัดอยู่แล้ว จัดการได้จากอีเมลยืนยัน',
    errorUnavailable: 'เวลานี้ไม่ว่างแล้ว กรุณาเลือกเวลาอื่น', errorGraph: 'ยังเชื่อมต่อปฏิทินไม่ได้ กรุณาลองอีกครั้งในอีกสักครู่',
    errorExpired: 'ลิงก์จองหมดอายุแล้ว กรุณาขอลิงก์ใหม่จากผู้จัด', errorGeneric: 'เกิดข้อผิดพลาด กรุณาลองอีกครั้ง',
    cutoff: 'ใกล้ถึงเวลานัดแล้วจึงเปลี่ยนออนไลน์ไม่ได้ กรุณาติดต่อผู้จัด', requestAnother: 'ไม่พบเวลาที่สะดวกใช่ไหม ติดต่อผู้จัดเพื่อนัดเวลาได้',
    schedulerDown: 'ระบบจองไม่พร้อมใช้งานชั่วคราว กรุณาลองใหม่ในอีกสักครู่', retry: 'ลองอีกครั้ง', loadError: 'โหลดเวลาว่างไม่ได้ในขณะนี้', noSlots: 'ไม่มีเวลาว่างในสองสัปดาห์ข้างหน้า',
    nextOpenDay: 'ดูวันว่างถัดไป', prevMonth: 'เดือนก่อน', nextMonth: 'เดือนถัดไป',
    confirmedTitle: 'ยืนยันการจองแล้ว', join: 'เข้าร่วมการโทร', reschedule: 'เปลี่ยนเวลานัด', cancel: 'ยกเลิก',
    manageNote: 'ต้องการเปลี่ยนนัดใช่ไหม ตอบกลับอีเมลยืนยันได้เลย', joinNote: 'ลิงก์อยู่ในคำเชิญปฏิทินและอีเมลยืนยันด้วย',
    confirmCancelTitle: 'ยกเลิกนัดนี้ไหม', confirmCancelBody: 'คุณจองเวลาใหม่ได้เมื่อพร้อม', confirmCancelYes: 'ใช่ ยกเลิก', keepIt: 'เก็บนัดไว้',
    bookedTitle: 'จองเวลาพูดคุยแล้ว', canceledTitle: 'ยกเลิกนัดแล้ว', canceledBody: 'ไม่เป็นไร เลือกเวลาใหม่ได้เมื่อพร้อม', bookAgain: 'จองเวลาอื่น', degraded: 'ข้อมูลเวลาว่างมีจำกัดในขณะนี้ กรุณาลองใหม่ในอีกสักครู่',
  },
  ms: {
    title: 'Tempah panggilan', language: 'Bahasa', themeToggle: 'Tukar mod cerah atau gelap',
    rescheduleTitle: 'Pilih masa baharu', rescheduleSub: 'Pilih masa yang lebih sesuai untuk anda.', videoCall: 'Panggilan video — pautan penyertaan ada dalam jemputan', teamTz: 'Zon waktu hos', back: 'Kembali ke tempahan',
    errorTaken: 'Masa ini baru sahaja ditempah. Berikut ialah masa lapang terkini.', errorAlreadyActive: 'Anda sudah mempunyai panggilan ditempah. Uruskannya melalui e-mel pengesahan.',
    errorUnavailable: 'Masa ini tidak lagi tersedia. Pilih masa lain.', errorGraph: 'Kalendar tidak dapat dihubungi sekarang. Cuba lagi sebentar nanti.',
    errorExpired: 'Pautan tempahan telah tamat tempoh. Minta pautan baharu daripada hos.', errorGeneric: 'Sesuatu telah berlaku. Sila cuba lagi.',
    cutoff: 'Panggilan akan bermula terlalu dekat untuk diubah dalam talian. Hubungi hos.', requestAnother: 'Tiada masa yang sesuai? Hubungi hos untuk menetapkannya.',
    schedulerDown: 'Sistem tempahan tidak tersedia buat sementara waktu. Cuba lagi sebentar nanti.', retry: 'Cuba lagi', loadError: 'Masa lapang tidak dapat dimuatkan.', noSlots: 'Tiada masa lapang dalam dua minggu akan datang.',
    nextOpenDay: 'Lihat hari lapang seterusnya', prevMonth: 'Bulan sebelumnya', nextMonth: 'Bulan seterusnya',
    confirmedTitle: 'Tempahan anda disahkan', join: 'Sertai panggilan', reschedule: 'Jadualkan semula', cancel: 'Batalkan',
    manageNote: 'Perlu membuat perubahan? Balas e-mel pengesahan anda.', joinNote: 'Pautan juga ada dalam jemputan kalendar dan e-mel pengesahan.',
    confirmCancelTitle: 'Batalkan panggilan ini?', confirmCancelBody: 'Anda boleh menempah masa baharu apabila bersedia.', confirmCancelYes: 'Ya, batalkan', keepIt: 'Kekalkan tempahan',
    bookedTitle: 'Panggilan anda ditempah', canceledTitle: 'Panggilan anda dibatalkan', canceledBody: 'Tidak mengapa — pilih masa baharu apabila bersedia.', bookAgain: 'Tempah masa lain', degraded: 'Maklumat ketersediaan terhad buat masa ini. Cuba lagi sebentar nanti.',
  },
  pap: {
    title: 'Reserva un yamada', language: 'Idioma', themeToggle: 'Cambia entre modo cla y scur',
    rescheduleTitle: 'Skohe un otro ora', rescheduleSub: 'Skohe un ora cu ta mas conveniente pa bo.', videoCall: 'Yamada di video — e link ta den bo invitacion', teamTz: 'Zona di tempo di e anfitrion', back: 'Bai bek na bo reservacion',
    errorTaken: 'E ora aki a caba di wordo reserva. Mira e oranan disponibel actual.', errorAlreadyActive: 'Bo tin un yamada reserva caba. Usa e e-mail di confirmacion pa maneha e reservacion.',
    errorUnavailable: 'E ora aki no ta disponibel mas. Skohe un otro ora.', errorGraph: 'Nos no por conecta cu e kalender awor. Purba atrobe den un rato.',
    errorExpired: 'E link di reservacion a caduca. Pidi bo anfitrion un link nobo.', errorGeneric: 'Algu a bai robes. Purba atrobe.',
    cutoff: 'E yamada ta mucho cerca pa cambia e online. Contacta bo anfitrion.', requestAnother: 'Bo no ta haya un ora cu ta conveni? Contacta bo anfitrion pa regla un.',
    schedulerDown: 'E sistema di reservacion no ta disponibel pa un rato. Purba atrobe mas despues.', retry: 'Purba atrobe', loadError: 'Nos no por carga e oranan disponibel awor.', noSlots: 'No tin ora disponibel den e dos simannan cu ta bini.',
    nextOpenDay: 'Mustra e siguiente dia disponibel', prevMonth: 'Luna anterior', nextMonth: 'Siguiente luna',
    confirmedTitle: 'Bo reservacion ta confirma', join: 'Drenta e yamada', reschedule: 'Cambia e ora', cancel: 'Cancela',
    manageNote: 'Bo kier cambia e reservacion? Contesta e e-mail di confirmacion.', joinNote: 'E link ta tambe den bo invitacion di kalender y e-mail di confirmacion.',
    confirmCancelTitle: 'Cancela e yamada aki?', confirmCancelBody: 'Bo por reserva un ora nobo ora bo ta cla.', confirmCancelYes: 'Si, cancela', keepIt: 'Mantene e reservacion',
    bookedTitle: 'Bo yamada ta reserva', canceledTitle: 'Bo yamada a wordo cancela', canceledBody: 'No tin problema — skohe un ora nobo ora bo ta cla.', bookAgain: 'Reserva un otro ora', degraded: 'E informacion di ora disponibel ta limita awor. Purba atrobe den un rato.',
  },
  az: {
    title: 'Görüş təyin edin', language: 'Dil', themeToggle: 'Açıq və ya tünd rejimə keçin',
    rescheduleTitle: 'Yeni vaxt seçin', rescheduleSub: 'Sizə daha uyğun vaxt seçin.', videoCall: 'Videozəng — qoşulma keçidi dəvətinizdədir', teamTz: 'Təşkilatçının saat qurşağı', back: 'Görüşünüzə qayıdın',
    errorTaken: 'Bu vaxt indicə rezerv edildi. Yenilənmiş boş vaxtlara baxın.', errorAlreadyActive: 'Artıq təyin edilmiş görüşünüz var. Onu təsdiq e-poçtundan idarə edin.',
    errorUnavailable: 'Bu vaxt artıq əlçatan deyil. Başqa vaxt seçin.', errorGraph: 'Hazırda təqvimə qoşula bilmirik. Bir az sonra yenidən cəhd edin.',
    errorExpired: 'Bu rezervasiya keçidinin müddəti bitib. Təşkilatçıdan yeni keçid istəyin.', errorGeneric: 'Xəta baş verdi. Yenidən cəhd edin.',
    cutoff: 'Görüşə az vaxt qaldığı üçün onu onlayn dəyişmək mümkün deyil. Təşkilatçı ilə əlaqə saxlayın.', requestAnother: 'Uyğun vaxt tapa bilmirsiniz? Vaxtı razılaşdırmaq üçün təşkilatçı ilə əlaqə saxlayın.',
    schedulerDown: 'Rezervasiya xidməti müvəqqəti əlçatan deyil. Bir az sonra yenidən cəhd edin.', retry: 'Yenidən cəhd edin', loadError: 'Boş vaxtları yükləmək mümkün olmadı.', noSlots: 'Növbəti iki həftə ərzində boş vaxt yoxdur.',
    nextOpenDay: 'Növbəti əlçatan günü göstərin', prevMonth: 'Əvvəlki ay', nextMonth: 'Növbəti ay',
    confirmedTitle: 'Görüşünüz təsdiqləndi', join: 'Görüşə qoşulun', reschedule: 'Vaxtı dəyişin', cancel: 'Ləğv edin',
    manageNote: 'Dəyişiklik lazımdır? Təsdiq e-poçtuna cavab verin.', joinNote: 'Keçid təqvim dəvətində və təsdiq e-poçtunda da var.',
    confirmCancelTitle: 'Bu görüş ləğv edilsin?', confirmCancelBody: 'Hazır olduğunuz zaman yeni vaxt seçə bilərsiniz.', confirmCancelYes: 'Bəli, ləğv edin', keepIt: 'Görüşü saxlayın',
    bookedTitle: 'Görüşünüz təyin edilib', canceledTitle: 'Görüşünüz ləğv edildi', canceledBody: 'Problem deyil — hazır olduğunuz zaman yeni vaxt seçin.', bookAgain: 'Başqa vaxt seçin', degraded: 'Hazırda əlçatan vaxt məlumatı məhduddur. Bir az sonra yenidən cəhd edin.',
  },
  ru: {
    title: 'Записаться на звонок', language: 'Язык', themeToggle: 'Переключить светлую или тёмную тему',
    rescheduleTitle: 'Выберите новое время', rescheduleSub: 'Выберите время, которое вам больше подходит.', videoCall: 'Видеозвонок — ссылка будет в приглашении', teamTz: 'Часовой пояс организатора', back: 'Вернуться к записи',
    errorTaken: 'Это время только что заняли. Вот обновлённые свободные варианты.', errorAlreadyActive: 'У вас уже есть запись на звонок. Управлять ей можно из письма с подтверждением.',
    errorUnavailable: 'Это время больше недоступно. Выберите другое.', errorGraph: 'Сейчас не удаётся подключиться к календарю. Повторите попытку чуть позже.',
    errorExpired: 'Срок действия ссылки истёк. Попросите организатора прислать новую.', errorGeneric: 'Что-то пошло не так. Попробуйте ещё раз.',
    cutoff: 'До звонка осталось слишком мало времени для изменения онлайн. Свяжитесь с организатором.', requestAnother: 'Не нашли удобное время? Свяжитесь с организатором, чтобы договориться.',
    schedulerDown: 'Сервис записи временно недоступен. Попробуйте чуть позже.', retry: 'Попробовать снова', loadError: 'Не удалось загрузить свободное время.', noSlots: 'В ближайшие две недели нет свободного времени.',
    nextOpenDay: 'Показать следующий свободный день', prevMonth: 'Предыдущий месяц', nextMonth: 'Следующий месяц',
    confirmedTitle: 'Ваша запись подтверждена', join: 'Присоединиться к звонку', reschedule: 'Перенести', cancel: 'Отменить',
    manageNote: 'Нужно внести изменения? Ответьте на письмо с подтверждением.', joinNote: 'Ссылка также есть в приглашении календаря и письме с подтверждением.',
    confirmCancelTitle: 'Отменить этот звонок?', confirmCancelBody: 'Вы сможете выбрать новое время, когда будете готовы.', confirmCancelYes: 'Да, отменить', keepIt: 'Сохранить запись',
    bookedTitle: 'Вы записаны на звонок', canceledTitle: 'Ваш звонок отменён', canceledBody: 'Ничего страшного — выберите новое время, когда будете готовы.', bookAgain: 'Выбрать другое время', degraded: 'Информация о свободном времени сейчас ограничена. Попробуйте чуть позже.',
  },
} satisfies Record<BookingLocale, FlowCopy>;
