import type { BookingLocale } from './locales';

type PersonalBookingCopy = Record<'codeSent' | 'requestNewCode' | 'verificationHelp' | 'sendCode' | 'tooManyRequests' | 'verificationFailed' | 'invalidCode' | 'savePrivateLink' | 'emailFailed' | 'personalFooter' | 'pageUnavailable' | 'pageUnavailableHelp' | 'contactTeam' | 'eventTypes' | 'yourName' | 'emailAddress' | 'website' | 'codeLabel', string>;

export const personalBookingCopy = {
  "en": {
    "codeSent": "We sent a six-digit code to {email}. It expires in 10 minutes. Your slot is not reserved until you confirm.",
    "requestNewCode": "Change email or request a new code",
    "verificationHelp": "We will email a verification code before creating your calendar invitation.",
    "sendCode": "Send verification code",
    "tooManyRequests": "Too many requests. Please try again later.",
    "verificationFailed": "We could not send your verification code. Refresh the page and try again.",
    "invalidCode": "The code is incorrect or expired. Check your email, or request a new code.",
    "savePrivateLink": "Save this private page link to manage your booking later.",
    "emailFailed": "We could not send the management email; your calendar invitation is still valid.",
    "personalFooter": "Booked through Sundae. A slot is reserved only when your booking is confirmed.",
    "pageUnavailable": "This booking page is unavailable",
    "pageUnavailableHelp": "The page may be paused or the link expired. Contact your host for a new link.",
    "contactTeam": "Contact the team",
    "eventTypes": "Event types",
    "yourName": "Your name",
    "emailAddress": "Email address",
    "website": "Website",
    "codeLabel": "Verification code"
  },
  "ar": {
    "codeSent": "أرسلنا رمزًا من ستة أرقام إلى {email}. تنتهي صلاحيته بعد 10 دقائق. لا يُحجز الموعد حتى تؤكده.",
    "requestNewCode": "تغيير البريد أو طلب رمز جديد",
    "verificationHelp": "سنرسل رمز تحقق قبل إنشاء دعوة التقويم.",
    "sendCode": "إرسال رمز التحقق",
    "tooManyRequests": "طلبات كثيرة. حاول لاحقًا.",
    "verificationFailed": "تعذّر إرسال الرمز. حدّث الصفحة وحاول مجددًا.",
    "invalidCode": "الرمز غير صحيح أو منتهي. تحقق من بريدك أو اطلب رمزًا جديدًا.",
    "savePrivateLink": "احفظ هذا الرابط الخاص لإدارة حجزك لاحقًا.",
    "emailFailed": "تعذّر إرسال بريد إدارة الحجز؛ دعوة التقويم لا تزال صالحة.",
    "personalFooter": "الحجز عبر Sundae. يُحجز الموعد عند تأكيد الحجز فقط.",
    "pageUnavailable": "صفحة الحجز غير متاحة",
    "pageUnavailableHelp": "قد تكون الصفحة متوقفة أو الرابط منتهيًا. تواصل مع المضيف لرابط جديد.",
    "contactTeam": "تواصل مع الفريق",
    "eventTypes": "أنواع الاجتماعات",
    "yourName": "اسمك",
    "emailAddress": "عنوان البريد الإلكتروني",
    "website": "الموقع الإلكتروني",
    "codeLabel": "رمز التحقق"
  },
  "fr": {
    "codeSent": "Un code à six chiffres a été envoyé à {email}. Il expire dans 10 minutes. Le créneau n’est réservé qu’après confirmation.",
    "requestNewCode": "Changer d’e-mail ou demander un nouveau code",
    "verificationHelp": "Un code sera envoyé avant la création de l’invitation calendrier.",
    "sendCode": "Envoyer le code",
    "tooManyRequests": "Trop de demandes. Réessayez plus tard.",
    "verificationFailed": "Impossible d’envoyer le code. Actualisez la page et réessayez.",
    "invalidCode": "Code incorrect ou expiré. Vérifiez vos e-mails ou demandez un nouveau code.",
    "savePrivateLink": "Gardez ce lien privé pour gérer votre réservation.",
    "emailFailed": "L’e-mail de gestion n’a pas pu être envoyé ; l’invitation calendrier reste valide.",
    "personalFooter": "Réservation via Sundae. Le créneau est réservé uniquement après confirmation.",
    "pageUnavailable": "Cette page de réservation est indisponible",
    "pageUnavailableHelp": "La page peut être suspendue ou le lien expiré. Contactez votre hôte pour un nouveau lien.",
    "contactTeam": "Contacter l’équipe",
    "eventTypes": "Types de rendez-vous",
    "yourName": "Votre nom",
    "emailAddress": "Adresse e-mail",
    "website": "Site web",
    "codeLabel": "Code de vérification"
  },
  "es": {
    "codeSent": "Enviamos un código de seis dígitos a {email}. Caduca en 10 minutos. El horario no se reserva hasta confirmar.",
    "requestNewCode": "Cambiar correo o pedir otro código",
    "verificationHelp": "Enviaremos un código antes de crear la invitación de calendario.",
    "sendCode": "Enviar código de verificación",
    "tooManyRequests": "Demasiadas solicitudes. Inténtalo más tarde.",
    "verificationFailed": "No pudimos enviar el código. Actualiza la página e inténtalo de nuevo.",
    "invalidCode": "El código es incorrecto o ha caducado. Revisa tu correo o pide otro.",
    "savePrivateLink": "Guarda este enlace privado para gestionar tu reserva.",
    "emailFailed": "No pudimos enviar el correo de gestión; la invitación de calendario sigue siendo válida.",
    "personalFooter": "Reservado con Sundae. El horario se reserva solo al confirmar.",
    "pageUnavailable": "Esta página de reservas no está disponible",
    "pageUnavailableHelp": "La página puede estar pausada o el enlace caducado. Pide un enlace nuevo al anfitrión.",
    "contactTeam": "Contactar con el equipo",
    "eventTypes": "Tipos de reunión",
    "yourName": "Tu nombre",
    "emailAddress": "Dirección de correo",
    "website": "Sitio web",
    "codeLabel": "Código de verificación"
  },
  "de": {
    "codeSent": "Ein sechsstelliger Code wurde an {email} gesendet. Er gilt 10 Minuten. Der Termin wird erst nach Bestätigung reserviert.",
    "requestNewCode": "E-Mail ändern oder neuen Code anfordern",
    "verificationHelp": "Vor dem Erstellen der Kalendereinladung senden wir einen Bestätigungscode.",
    "sendCode": "Bestätigungscode senden",
    "tooManyRequests": "Zu viele Anfragen. Bitte später versuchen.",
    "verificationFailed": "Code konnte nicht gesendet werden. Seite neu laden und erneut versuchen.",
    "invalidCode": "Code falsch oder abgelaufen. E-Mail prüfen oder neuen Code anfordern.",
    "savePrivateLink": "Speichern Sie diesen privaten Link zur Buchungsverwaltung.",
    "emailFailed": "Die Verwaltungs-E-Mail konnte nicht gesendet werden; die Kalendereinladung bleibt gültig.",
    "personalFooter": "Gebucht über Sundae. Der Termin wird erst nach Bestätigung reserviert.",
    "pageUnavailable": "Diese Buchungsseite ist nicht verfügbar",
    "pageUnavailableHelp": "Die Seite ist möglicherweise pausiert oder der Link abgelaufen. Bitten Sie den Gastgeber um einen neuen Link.",
    "contactTeam": "Team kontaktieren",
    "eventTypes": "Termintypen",
    "yourName": "Ihr Name",
    "emailAddress": "E-Mail-Adresse",
    "website": "Webseite",
    "codeLabel": "Verifizierungscode"
  },
  "nl": {
    "codeSent": "We stuurden een zescijferige code naar {email}. Deze verloopt na 10 minuten. Je tijdstip is pas gereserveerd na bevestiging.",
    "requestNewCode": "E-mail wijzigen of nieuwe code aanvragen",
    "verificationHelp": "We mailen een verificatiecode voordat we de kalenderuitnodiging maken.",
    "sendCode": "Verificatiecode sturen",
    "tooManyRequests": "Te veel verzoeken. Probeer later opnieuw.",
    "verificationFailed": "De code kon niet worden verstuurd. Vernieuw de pagina en probeer opnieuw.",
    "invalidCode": "De code is onjuist of verlopen. Controleer je e-mail of vraag een nieuwe code.",
    "savePrivateLink": "Bewaar deze privélink om je boeking te beheren.",
    "emailFailed": "De beheermail kon niet worden verstuurd; je kalenderuitnodiging blijft geldig.",
    "personalFooter": "Geboekt via Sundae. Een tijdstip is pas gereserveerd na bevestiging.",
    "pageUnavailable": "Deze boekingspagina is niet beschikbaar",
    "pageUnavailableHelp": "De pagina kan gepauzeerd zijn of de link verlopen. Vraag de host om een nieuwe link.",
    "contactTeam": "Neem contact op met het team",
    "eventTypes": "Afspraaktypen",
    "yourName": "Je naam",
    "emailAddress": "E-mailadres",
    "website": "Website",
    "codeLabel": "Verificatiecode"
  },
  "pt": {
    "codeSent": "Enviamos um código de seis dígitos para {email}. Ele expira em 10 minutos. O horário só é reservado após a confirmação.",
    "requestNewCode": "Alterar e-mail ou pedir novo código",
    "verificationHelp": "Enviaremos um código antes de criar o convite de calendário.",
    "sendCode": "Enviar código de verificação",
    "tooManyRequests": "Muitas solicitações. Tente mais tarde.",
    "verificationFailed": "Não foi possível enviar o código. Atualize a página e tente novamente.",
    "invalidCode": "Código incorreto ou expirado. Confira seu e-mail ou peça um novo código.",
    "savePrivateLink": "Guarde este link privado para gerenciar o agendamento.",
    "emailFailed": "Não foi possível enviar o e-mail de gestão; o convite de calendário continua válido.",
    "personalFooter": "Agendado pelo Sundae. O horário só é reservado após a confirmação.",
    "pageUnavailable": "Esta página de agendamento está indisponível",
    "pageUnavailableHelp": "A página pode estar pausada ou o link expirado. Peça um novo link ao anfitrião.",
    "contactTeam": "Fale com a equipe",
    "eventTypes": "Tipos de reunião",
    "yourName": "O seu nome",
    "emailAddress": "Endereço de e-mail",
    "website": "Site",
    "codeLabel": "Código de verificação"
  },
  "it": {
    "codeSent": "Abbiamo inviato un codice a sei cifre a {email}. Scade in 10 minuti. L’orario è riservato solo dopo la conferma.",
    "requestNewCode": "Cambia e-mail o richiedi un nuovo codice",
    "verificationHelp": "Invieremo un codice prima di creare l’invito nel calendario.",
    "sendCode": "Invia codice di verifica",
    "tooManyRequests": "Troppe richieste. Riprova più tardi.",
    "verificationFailed": "Impossibile inviare il codice. Aggiorna la pagina e riprova.",
    "invalidCode": "Codice errato o scaduto. Controlla l’e-mail o richiedine uno nuovo.",
    "savePrivateLink": "Conserva questo link privato per gestire la prenotazione.",
    "emailFailed": "Impossibile inviare l’e-mail di gestione; l’invito nel calendario resta valido.",
    "personalFooter": "Prenotato tramite Sundae. L’orario è riservato solo dopo la conferma.",
    "pageUnavailable": "Questa pagina di prenotazione non è disponibile",
    "pageUnavailableHelp": "La pagina potrebbe essere sospesa o il link scaduto. Chiedi un nuovo link all’organizzatore.",
    "contactTeam": "Contatta il team",
    "eventTypes": "Tipi di appuntamento",
    "yourName": "Il tuo nome",
    "emailAddress": "Indirizzo email",
    "website": "Sito web",
    "codeLabel": "Codice di verifica"
  },
  "pl": {
    "codeSent": "Wysłaliśmy sześciocyfrowy kod na {email}. Wygasa za 10 minut. Termin jest rezerwowany dopiero po potwierdzeniu.",
    "requestNewCode": "Zmień e-mail lub poproś o nowy kod",
    "verificationHelp": "Wyślemy kod przed utworzeniem zaproszenia w kalendarzu.",
    "sendCode": "Wyślij kod weryfikacyjny",
    "tooManyRequests": "Za dużo próśb. Spróbuj później.",
    "verificationFailed": "Nie można wysłać kodu. Odśwież stronę i spróbuj ponownie.",
    "invalidCode": "Kod jest błędny lub wygasł. Sprawdź e-mail lub poproś o nowy kod.",
    "savePrivateLink": "Zachowaj ten prywatny link do zarządzania rezerwacją.",
    "emailFailed": "Nie można wysłać e-maila do zarządzania; zaproszenie w kalendarzu nadal jest ważne.",
    "personalFooter": "Rezerwacja przez Sundae. Termin jest rezerwowany dopiero po potwierdzeniu.",
    "pageUnavailable": "Ta strona rezerwacji jest niedostępna",
    "pageUnavailableHelp": "Strona może być wstrzymana lub link wygasł. Poproś gospodarza o nowy link.",
    "contactTeam": "Skontaktuj się z zespołem",
    "eventTypes": "Typy spotkań",
    "yourName": "Twoje imię i nazwisko",
    "emailAddress": "Adres e-mail",
    "website": "Witryna",
    "codeLabel": "Kod weryfikacyjny"
  },
  "tr": {
    "codeSent": "{email} adresine altı haneli kod gönderdik. 10 dakika içinde geçerliliğini yitirir. Saatiniz yalnızca onaydan sonra ayrılır.",
    "requestNewCode": "E-postayı değiştir veya yeni kod iste",
    "verificationHelp": "Takvim davetini oluşturmadan önce doğrulama kodu göndereceğiz.",
    "sendCode": "Doğrulama kodu gönder",
    "tooManyRequests": "Çok fazla istek. Daha sonra tekrar deneyin.",
    "verificationFailed": "Kod gönderilemedi. Sayfayı yenileyip tekrar deneyin.",
    "invalidCode": "Kod yanlış veya süresi dolmuş. E-postanızı kontrol edin ya da yeni kod isteyin.",
    "savePrivateLink": "Rezervasyonunuzu yönetmek için bu özel bağlantıyı saklayın.",
    "emailFailed": "Yönetim e-postası gönderilemedi; takvim davetiniz hâlâ geçerli.",
    "personalFooter": "Sundae üzerinden rezerve edildi. Saat yalnızca onaydan sonra ayrılır.",
    "pageUnavailable": "Bu rezervasyon sayfası kullanılamıyor",
    "pageUnavailableHelp": "Sayfa duraklatılmış veya bağlantı süresi dolmuş olabilir. Ev sahibinden yeni bağlantı isteyin.",
    "contactTeam": "Ekiple iletişime geç",
    "eventTypes": "Toplantı türleri",
    "yourName": "Adınız",
    "emailAddress": "E-posta adresi",
    "website": "Web sitesi",
    "codeLabel": "Doğrulama kodu"
  },
  "ro": {
    "codeSent": "Am trimis un cod de șase cifre la {email}. Expiră în 10 minute. Intervalul se rezervă doar după confirmare.",
    "requestNewCode": "Schimbă e-mailul sau cere un cod nou",
    "verificationHelp": "Vom trimite un cod înainte de a crea invitația în calendar.",
    "sendCode": "Trimite codul de verificare",
    "tooManyRequests": "Prea multe cereri. Încearcă mai târziu.",
    "verificationFailed": "Nu am putut trimite codul. Reîncarcă pagina și reîncearcă.",
    "invalidCode": "Cod incorect sau expirat. Verifică e-mailul sau cere un cod nou.",
    "savePrivateLink": "Păstrează acest link privat pentru gestionarea programării.",
    "emailFailed": "Nu am putut trimite e-mailul de gestionare; invitația în calendar rămâne valabilă.",
    "personalFooter": "Programat prin Sundae. Intervalul se rezervă doar după confirmare.",
    "pageUnavailable": "Această pagină de programări nu este disponibilă",
    "pageUnavailableHelp": "Pagina poate fi suspendată sau linkul expirat. Cere gazdei un link nou.",
    "contactTeam": "Contactează echipa",
    "eventTypes": "Tipuri de întâlnire",
    "yourName": "Numele tău",
    "emailAddress": "Adresă de email",
    "website": "Site web",
    "codeLabel": "Cod de verificare"
  },
  "sv": {
    "codeSent": "Vi skickade en sexsiffrig kod till {email}. Den gäller i 10 minuter. Tiden reserveras först efter bekräftelse.",
    "requestNewCode": "Byt e-post eller begär ny kod",
    "verificationHelp": "Vi mejlar en kod innan kalenderinbjudan skapas.",
    "sendCode": "Skicka verifieringskod",
    "tooManyRequests": "För många förfrågningar. Försök senare.",
    "verificationFailed": "Koden kunde inte skickas. Ladda om sidan och försök igen.",
    "invalidCode": "Koden är fel eller har gått ut. Kontrollera din e-post eller begär en ny kod.",
    "savePrivateLink": "Spara denna privata länk för att hantera bokningen.",
    "emailFailed": "Hanteringsmejlet kunde inte skickas; kalenderinbjudan gäller fortfarande.",
    "personalFooter": "Bokat via Sundae. Tiden reserveras först efter bekräftelse.",
    "pageUnavailable": "Denna bokningssida är inte tillgänglig",
    "pageUnavailableHelp": "Sidan kan vara pausad eller länken utgången. Be värden om en ny länk.",
    "contactTeam": "Kontakta teamet",
    "eventTypes": "Mötestyper",
    "yourName": "Ditt namn",
    "emailAddress": "E-postadress",
    "website": "Webbplats",
    "codeLabel": "Verifieringskod"
  },
  "id": {
    "codeSent": "Kami mengirim kode enam digit ke {email}. Berlaku 10 menit. Slot belum dipesan hingga Anda mengonfirmasi.",
    "requestNewCode": "Ganti email atau minta kode baru",
    "verificationHelp": "Kami akan mengirim kode sebelum membuat undangan kalender.",
    "sendCode": "Kirim kode verifikasi",
    "tooManyRequests": "Terlalu banyak permintaan. Coba lagi nanti.",
    "verificationFailed": "Kode tidak dapat dikirim. Muat ulang halaman dan coba lagi.",
    "invalidCode": "Kode salah atau kedaluwarsa. Periksa email atau minta kode baru.",
    "savePrivateLink": "Simpan tautan pribadi ini untuk mengelola pemesanan.",
    "emailFailed": "Email pengelolaan tidak dapat dikirim; undangan kalender tetap berlaku.",
    "personalFooter": "Dipesan melalui Sundae. Slot dipesan hanya setelah konfirmasi.",
    "pageUnavailable": "Halaman pemesanan ini tidak tersedia",
    "pageUnavailableHelp": "Halaman mungkin dijeda atau tautan kedaluwarsa. Minta tautan baru kepada tuan rumah.",
    "contactTeam": "Hubungi tim",
    "eventTypes": "Jenis pertemuan",
    "yourName": "Nama Anda",
    "emailAddress": "Alamat email",
    "website": "Situs web",
    "codeLabel": "Kode verifikasi"
  },
  "ms": {
    "codeSent": "Kami menghantar kod enam digit ke {email}. Sah selama 10 minit. Slot hanya ditempah selepas pengesahan.",
    "requestNewCode": "Tukar e-mel atau minta kod baharu",
    "verificationHelp": "Kami akan menghantar kod sebelum mencipta jemputan kalendar.",
    "sendCode": "Hantar kod pengesahan",
    "tooManyRequests": "Terlalu banyak permintaan. Cuba lagi kemudian.",
    "verificationFailed": "Kod tidak dapat dihantar. Muat semula halaman dan cuba lagi.",
    "invalidCode": "Kod salah atau tamat tempoh. Semak e-mel atau minta kod baharu.",
    "savePrivateLink": "Simpan pautan peribadi ini untuk mengurus tempahan.",
    "emailFailed": "E-mel pengurusan tidak dapat dihantar; jemputan kalendar masih sah.",
    "personalFooter": "Ditempah melalui Sundae. Slot hanya ditempah selepas pengesahan.",
    "pageUnavailable": "Halaman tempahan ini tidak tersedia",
    "pageUnavailableHelp": "Halaman mungkin dijeda atau pautan tamat tempoh. Minta pautan baharu daripada hos.",
    "contactTeam": "Hubungi pasukan",
    "eventTypes": "Jenis mesyuarat",
    "yourName": "Nama anda",
    "emailAddress": "Alamat emel",
    "website": "Laman web",
    "codeLabel": "Kod pengesahan"
  },
  "vi": {
    "codeSent": "Chúng tôi đã gửi mã sáu chữ số đến {email}. Mã hết hạn sau 10 phút. Chỗ chỉ được giữ sau khi xác nhận.",
    "requestNewCode": "Đổi email hoặc yêu cầu mã mới",
    "verificationHelp": "Chúng tôi sẽ gửi mã trước khi tạo lời mời lịch.",
    "sendCode": "Gửi mã xác minh",
    "tooManyRequests": "Quá nhiều yêu cầu. Vui lòng thử lại sau.",
    "verificationFailed": "Không thể gửi mã. Tải lại trang và thử lại.",
    "invalidCode": "Mã sai hoặc hết hạn. Kiểm tra email hoặc yêu cầu mã mới.",
    "savePrivateLink": "Lưu liên kết riêng tư này để quản lý lịch hẹn.",
    "emailFailed": "Không thể gửi email quản lý; lời mời lịch vẫn hợp lệ.",
    "personalFooter": "Đặt lịch qua Sundae. Chỗ chỉ được giữ sau khi xác nhận.",
    "pageUnavailable": "Trang đặt lịch này không khả dụng",
    "pageUnavailableHelp": "Trang có thể tạm dừng hoặc liên kết hết hạn. Yêu cầu chủ trì gửi liên kết mới.",
    "contactTeam": "Liên hệ nhóm",
    "eventTypes": "Loại cuộc họp",
    "yourName": "Tên của bạn",
    "emailAddress": "Địa chỉ email",
    "website": "Trang web",
    "codeLabel": "Mã xác minh"
  },
  "zh-Hans": {
    "codeSent": "六位验证码已发送至 {email}，10 分钟后失效。确认前不会保留时段。",
    "requestNewCode": "更换邮箱或获取新验证码",
    "verificationHelp": "创建日历邀请前，我们会发送邮箱验证码。",
    "sendCode": "发送验证码",
    "tooManyRequests": "请求过多，请稍后再试。",
    "verificationFailed": "无法发送验证码，请刷新页面后重试。",
    "invalidCode": "验证码错误或已过期。请检查邮箱或获取新验证码。",
    "savePrivateLink": "请保存此私密链接，以便管理预约。",
    "emailFailed": "无法发送预约管理邮件，但日历邀请仍然有效。",
    "personalFooter": "通过 Sundae 预约。确认预约后才会保留时段。",
    "pageUnavailable": "此预约页面暂不可用",
    "pageUnavailableHelp": "页面可能已暂停或链接已过期。请联系预约主持人获取新链接。",
    "contactTeam": "联系团队",
    "eventTypes": "会议类型",
    "yourName": "您的姓名",
    "emailAddress": "电子邮箱地址",
    "website": "网站",
    "codeLabel": "验证码"
  },
  "ja": {
    "codeSent": "{email} に 6 桁のコードを送りました。10 分間有効です。確認するまでは時間枠は確保されません。",
    "requestNewCode": "メールを変更するか新しいコードを取得",
    "verificationHelp": "カレンダー招待を作成する前に認証コードを送ります。",
    "sendCode": "認証コードを送信",
    "tooManyRequests": "リクエストが多すぎます。後で再試行してください。",
    "verificationFailed": "コードを送信できませんでした。ページを再読み込みして再試行してください。",
    "invalidCode": "コードが誤っているか期限切れです。メールを確認するか新しいコードを取得してください。",
    "savePrivateLink": "予約管理用のこの非公開リンクを保存してください。",
    "emailFailed": "管理メールを送信できませんでしたが、カレンダー招待は有効です。",
    "personalFooter": "Sundae 経由の予約です。予約の確認後にのみ時間枠が確保されます。",
    "pageUnavailable": "この予約ページは利用できません",
    "pageUnavailableHelp": "ページが一時停止中かリンクが期限切れの可能性があります。主催者に新しいリンクを依頼してください。",
    "contactTeam": "チームに連絡",
    "eventTypes": "会議の種類",
    "yourName": "お名前",
    "emailAddress": "メールアドレス",
    "website": "ウェブサイト",
    "codeLabel": "認証コード"
  },
  "ko": {
    "codeSent": "{email}로 6자리 코드를 보냈습니다. 10분간 유효합니다. 확인 전에는 시간이 예약되지 않습니다.",
    "requestNewCode": "이메일 변경 또는 새 코드 요청",
    "verificationHelp": "캘린더 초대를 만들기 전에 인증 코드를 보냅니다.",
    "sendCode": "인증 코드 보내기",
    "tooManyRequests": "요청이 너무 많습니다. 나중에 다시 시도하세요.",
    "verificationFailed": "코드를 보내지 못했습니다. 페이지를 새로 고침한 후 다시 시도하세요.",
    "invalidCode": "코드가 틀리거나 만료되었습니다. 이메일을 확인하거나 새 코드를 요청하세요.",
    "savePrivateLink": "예약을 관리할 수 있도록 이 비공개 링크를 저장하세요.",
    "emailFailed": "관리 이메일을 보내지 못했지만 캘린더 초대는 여전히 유효합니다.",
    "personalFooter": "Sundae를 통한 예약입니다. 예약을 확인한 후에만 시간이 확보됩니다.",
    "pageUnavailable": "이 예약 페이지를 이용할 수 없습니다",
    "pageUnavailableHelp": "페이지가 일시 중지되었거나 링크가 만료되었을 수 있습니다. 주최자에게 새 링크를 요청하세요.",
    "contactTeam": "팀에 문의",
    "eventTypes": "회의 유형",
    "yourName": "이름",
    "emailAddress": "이메일 주소",
    "website": "웹사이트",
    "codeLabel": "인증 코드"
  },
  "hi": {
    "codeSent": "{email} पर छह अंकों का कोड भेजा है। यह 10 मिनट में समाप्त होगा। पुष्टि तक स्लॉट आरक्षित नहीं है।",
    "requestNewCode": "ईमेल बदलें या नया कोड माँगें",
    "verificationHelp": "कैलेंडर निमंत्रण बनाने से पहले ईमेल पर सत्यापन कोड भेजेंगे।",
    "sendCode": "सत्यापन कोड भेजें",
    "tooManyRequests": "बहुत अधिक अनुरोध। बाद में कोशिश करें।",
    "verificationFailed": "कोड नहीं भेज सके। पेज रीफ़्रेश करके फिर कोशिश करें।",
    "invalidCode": "कोड गलत है या समाप्त हो गया। ईमेल देखें या नया कोड माँगें।",
    "savePrivateLink": "बुकिंग प्रबंधित करने के लिए यह निजी लिंक सहेजें।",
    "emailFailed": "प्रबंधन ईमेल नहीं भेज सके; कैलेंडर निमंत्रण अभी भी मान्य है।",
    "personalFooter": "Sundae से बुकिंग। पुष्टि के बाद ही स्लॉट आरक्षित होता है।",
    "pageUnavailable": "यह बुकिंग पेज उपलब्ध नहीं है",
    "pageUnavailableHelp": "पेज रुका हो सकता है या लिंक समाप्त है। होस्ट से नया लिंक माँगें।",
    "contactTeam": "टीम से संपर्क करें",
    "eventTypes": "मीटिंग के प्रकार",
    "yourName": "आपका नाम",
    "emailAddress": "ईमेल पता",
    "website": "वेबसाइट",
    "codeLabel": "सत्यापन कोड"
  },
  "ur": {
    "codeSent": "{email} پر چھ ہندسوں کا کوڈ بھیجا ہے۔ 10 منٹ میں ختم ہوگا۔ تصدیق تک وقت محفوظ نہیں ہے۔",
    "requestNewCode": "ای میل بدلیں یا نیا کوڈ مانگیں",
    "verificationHelp": "کیلنڈر دعوت بنانے سے پہلے ای میل پر تصدیقی کوڈ بھیجیں گے۔",
    "sendCode": "تصدیقی کوڈ بھیجیں",
    "tooManyRequests": "بہت زیادہ درخواستیں۔ بعد میں کوشش کریں۔",
    "verificationFailed": "کوڈ نہیں بھیج سکے۔ صفحہ ریفریش کر کے دوبارہ کوشش کریں۔",
    "invalidCode": "کوڈ غلط یا ختم ہو چکا ہے۔ ای میل دیکھیں یا نیا کوڈ مانگیں۔",
    "savePrivateLink": "بکنگ سنبھالنے کے لیے یہ نجی لنک محفوظ کریں۔",
    "emailFailed": "انتظامی ای میل نہیں بھیج سکے؛ کیلنڈر دعوت اب بھی درست ہے۔",
    "personalFooter": "Sundae کے ذریعے بکنگ۔ تصدیق کے بعد ہی وقت محفوظ ہوتا ہے۔",
    "pageUnavailable": "یہ بکنگ صفحہ دستیاب نہیں",
    "pageUnavailableHelp": "صفحہ رکا ہو سکتا ہے یا لنک ختم ہے۔ میزبان سے نیا لنک مانگیں۔",
    "contactTeam": "ٹیم سے رابطہ کریں",
    "eventTypes": "میٹنگ کی اقسام",
    "yourName": "آپ کا نام",
    "emailAddress": "ای میل ایڈریس",
    "website": "ویب سائٹ",
    "codeLabel": "توثیقی کوڈ"
  },
  "bn": {
    "codeSent": "{email}-এ ছয় অঙ্কের কোড পাঠিয়েছি। ১০ মিনিটে মেয়াদ শেষ হবে। নিশ্চিত না করা পর্যন্ত সময় সংরক্ষিত নয়।",
    "requestNewCode": "ইমেইল বদলান বা নতুন কোড চান",
    "verificationHelp": "ক্যালেন্ডারের আমন্ত্রণ তৈরির আগে ইমেইলে যাচাই কোড পাঠাব।",
    "sendCode": "যাচাই কোড পাঠান",
    "tooManyRequests": "অনেক বেশি অনুরোধ। পরে চেষ্টা করুন।",
    "verificationFailed": "কোড পাঠানো যায়নি। পৃষ্ঠা রিফ্রেশ করে আবার চেষ্টা করুন।",
    "invalidCode": "কোড ভুল বা মেয়াদ শেষ। ইমেইল দেখুন বা নতুন কোড চান।",
    "savePrivateLink": "বুকিং পরিচালনার জন্য এই ব্যক্তিগত লিংক রাখুন।",
    "emailFailed": "পরিচালনার ইমেইল পাঠানো যায়নি; ক্যালেন্ডারের আমন্ত্রণ এখনো বৈধ।",
    "personalFooter": "Sundae দিয়ে বুকিং। নিশ্চিত করার পরেই সময় সংরক্ষিত হয়।",
    "pageUnavailable": "এই বুকিং পৃষ্ঠা পাওয়া যাচ্ছে না",
    "pageUnavailableHelp": "পৃষ্ঠা বন্ধ বা লিংকের মেয়াদ শেষ হতে পারে। হোস্টের কাছে নতুন লিংক চান।",
    "contactTeam": "দলের সঙ্গে যোগাযোগ করুন",
    "eventTypes": "মিটিংয়ের ধরন",
    "yourName": "আপনার নাম",
    "emailAddress": "ইমেইল ঠিকানা",
    "website": "ওয়েবসাইট",
    "codeLabel": "যাচাইকরণ কোড"
  },
  "th": {
    "codeSent": "ส่งรหัสหกหลักไปที่ {email} แล้ว รหัสหมดอายุใน 10 นาที ยังไม่กันเวลาไว้จนกว่าจะยืนยัน",
    "requestNewCode": "เปลี่ยนอีเมลหรือขอรหัสใหม่",
    "verificationHelp": "เราจะส่งรหัสยืนยันก่อนสร้างคำเชิญปฏิทิน",
    "sendCode": "ส่งรหัสยืนยัน",
    "tooManyRequests": "คำขอมากเกินไป กรุณาลองภายหลัง",
    "verificationFailed": "ส่งรหัสไม่ได้ รีเฟรชหน้าแล้วลองอีกครั้ง",
    "invalidCode": "รหัสไม่ถูกต้องหรือหมดอายุ ตรวจสอบอีเมลหรือขอรหัสใหม่",
    "savePrivateLink": "บันทึกลิงก์ส่วนตัวนี้เพื่อจัดการการจอง",
    "emailFailed": "ส่งอีเมลจัดการไม่ได้ แต่คำเชิญปฏิทินยังใช้ได้",
    "personalFooter": "จองผ่าน Sundae กันเวลาไว้เมื่อยืนยันการจองแล้วเท่านั้น",
    "pageUnavailable": "หน้าจองนี้ไม่พร้อมใช้งาน",
    "pageUnavailableHelp": "หน้าอาจถูกพักหรือลิงก์หมดอายุ ติดต่อผู้จัดเพื่อขอลิงก์ใหม่",
    "contactTeam": "ติดต่อทีม",
    "eventTypes": "ประเภทการประชุม",
    "yourName": "ชื่อของคุณ",
    "emailAddress": "ที่อยู่อีเมล",
    "website": "เว็บไซต์",
    "codeLabel": "รหัสยืนยัน"
  },
  pap: {
    codeSent: 'Nos a manda un codigo di seis cifra na {email}. E ta caduca den 10 minuut. Bo ora no ta reserva te ora bo confirma.',
    requestNewCode: 'Cambia e-mail of pidi un codigo nobo', verificationHelp: 'Nos lo manda un codigo di verificacion prome cu crea bo invitacion di kalender.',
    sendCode: 'Manda codigo di verificacion', tooManyRequests: 'Tin demasiado peticion. Purba atrobe mas despues.',
    verificationFailed: 'Nos no por a manda e codigo. Refresca e pagina y purba atrobe.', invalidCode: 'E codigo no ta corecto of a caduca. Check bo e-mail of pidi un codigo nobo.',
    savePrivateLink: 'Warda e link priva aki pa maneha bo reservacion despues.', emailFailed: 'Nos no por a manda e e-mail pa maneha bo reservacion; bo invitacion di kalender ainda ta valido.',
    personalFooter: 'Reserva via Sundae. E ora ta reserva solamente ora bo confirma e reservacion.',
    pageUnavailable: 'E pagina di reservacion no ta disponibel', pageUnavailableHelp: 'E pagina por ta pausa of e link a caduca. Pidi bo anfitrion un link nobo.',
    contactTeam: 'Contacta e team', eventTypes: 'Tipo di reunion', yourName: 'Bo nomber', emailAddress: 'Adres di e-mail', website: 'Website', codeLabel: 'Codigo di verificacion',
  },
  az: {
    codeSent: '{email} ünvanına altırəqəmli kod göndərdik. Kod 10 dəqiqə qüvvədədir. Təsdiqləyənədək vaxtınız rezerv edilmir.',
    requestNewCode: 'E-poçtu dəyişin və ya yeni kod istəyin', verificationHelp: 'Təqvim dəvətini yaratmazdan əvvəl təsdiq kodu göndərəcəyik.',
    sendCode: 'Təsdiq kodunu göndərin', tooManyRequests: 'Çox sayda sorğu göndərilib. Bir az sonra yenidən cəhd edin.',
    verificationFailed: 'Təsdiq kodunu göndərmək mümkün olmadı. Səhifəni yeniləyin və yenidən cəhd edin.', invalidCode: 'Kod yanlışdır və ya müddəti bitib. E-poçtunuzu yoxlayın və ya yeni kod istəyin.',
    savePrivateLink: 'Görüşünüzü sonradan idarə etmək üçün bu şəxsi keçidi saxlayın.', emailFailed: 'İdarəetmə e-poçtunu göndərmək mümkün olmadı; təqvim dəvətiniz hələ də etibarlıdır.',
    personalFooter: 'Sundae vasitəsilə rezerv edilib. Vaxt yalnız görüşü təsdiqlədiyinizdə rezerv edilir.',
    pageUnavailable: 'Bu rezervasiya səhifəsi əlçatan deyil', pageUnavailableHelp: 'Səhifə dayandırılmış və ya keçidin müddəti bitmiş ola bilər. Təşkilatçıdan yeni keçid istəyin.',
    contactTeam: 'Komanda ilə əlaqə saxlayın', eventTypes: 'Görüş növləri', yourName: 'Adınız', emailAddress: 'E-poçt ünvanı', website: 'Veb-sayt', codeLabel: 'Təsdiq kodu',
  },
  ru: {
    codeSent: 'Мы отправили шестизначный код на {email}. Он действует 10 минут. Время не резервируется до подтверждения.',
    requestNewCode: 'Изменить почту или запросить новый код', verificationHelp: 'Перед созданием приглашения в календаре мы отправим код подтверждения.',
    sendCode: 'Отправить код подтверждения', tooManyRequests: 'Слишком много запросов. Повторите попытку позже.',
    verificationFailed: 'Не удалось отправить код. Обновите страницу и попробуйте снова.', invalidCode: 'Код неверен или срок его действия истёк. Проверьте почту или запросите новый код.',
    savePrivateLink: 'Сохраните эту личную ссылку, чтобы управлять записью позже.', emailFailed: 'Не удалось отправить письмо для управления записью; приглашение в календаре остаётся действительным.',
    personalFooter: 'Запись через Sundae. Время резервируется только после подтверждения.',
    pageUnavailable: 'Эта страница записи недоступна', pageUnavailableHelp: 'Страница может быть приостановлена или ссылка просрочена. Попросите организатора прислать новую ссылку.',
    contactTeam: 'Связаться с командой', eventTypes: 'Типы встреч', yourName: 'Ваше имя', emailAddress: 'Электронная почта', website: 'Сайт', codeLabel: 'Код подтверждения',
  },
} satisfies Record<BookingLocale, PersonalBookingCopy>;
