// Generated auxiliary locale packs. Do not edit by hand; regenerate from /tmp/generate_aux_i18n.mjs.
export const generatedUiLabels = {
  "en": {
    "home": "Home",
    "howSundaeHelps": "HOW SUNDAE HELPS",
    "whatChanges": "WHAT CHANGES",
    "whatWeFound": "What we found:",
    "recommendation": "Recommendation:",
    "potentialImpact": "Potential Impact:",
    "whatYoullDo": "What You'll Do:",
    "timeline": "Timeline",
    "keyCapabilities": "Key capabilities:",
    "save18": "Save ~18% vs. individual",
    "seeWatchtowerPricing": "See Watchtower pricing for your operation",
    "watchWatchtowerDemo": "Watch Watchtower demo",
    "customWatchtowerConfiguration": "Custom Watchtower configuration",
    "applyNow": "Apply Now"
  },
  "ar": {
    "home": "بيت",
    "howSundaeHelps": "كيف تساعد المثلجات",
    "whatChanges": "ما التغييرات",
    "whatWeFound": "ما وجدناه:",
    "recommendation": "توصية:",
    "potentialImpact": "التأثير المحتمل:",
    "whatYoullDo": "ماذا ستفعل:",
    "timeline": "الجدول الزمني",
    "keyCapabilities": "القدرات الرئيسية:",
    "save18": "وفر ~18% مقابل الفرد",
    "seeWatchtowerPricing": "راجع تسعير برج المراقبة لعمليتك",
    "watchWatchtowerDemo": "شاهد عرض برج المراقبة",
    "customWatchtowerConfiguration": "تكوين برج المراقبة المخصص",
    "applyNow": "تقدم بطلبك الآن"
  },
  "fr": {
    "home": "Maison",
    "howSundaeHelps": "COMMENT SUNDAE AIDE",
    "whatChanges": "QUELS CHANGEMENTS",
    "whatWeFound": "Ce que nous avons trouvé :",
    "recommendation": "Recommandation:",
    "potentialImpact": "Impact potentiel :",
    "whatYoullDo": "Ce que vous ferez :",
    "timeline": "Chronologie",
    "keyCapabilities": "Capacités clés :",
    "save18": "Économisez ~18 % par rapport à un particulier",
    "seeWatchtowerPricing": "Voir les tarifs Watchtower pour votre opération",
    "watchWatchtowerDemo": "Regarder la démo de Watchtower",
    "customWatchtowerConfiguration": "Configuration personnalisée de la tour de guet",
    "applyNow": "Postulez maintenant"
  },
  "es": {
    "home": "Hogar",
    "howSundaeHelps": "CÓMO AYUDA EL SUNDAE",
    "whatChanges": "QUE CAMBIA",
    "whatWeFound": "Lo que encontramos:",
    "recommendation": "Recomendación:",
    "potentialImpact": "Impacto potencial:",
    "whatYoullDo": "Lo que harás:",
    "timeline": "Línea de tiempo",
    "keyCapabilities": "Capacidades clave:",
    "save18": "Ahorre ~18 % frente a un individuo",
    "seeWatchtowerPricing": "Vea los precios de Watchtower para su operación",
    "watchWatchtowerDemo": "Vea la demostración de La Atalaya",
    "customWatchtowerConfiguration": "Configuración personalizada de la Atalaya",
    "applyNow": "Aplicar ahora"
  },
  "de": {
    "home": "Heim",
    "howSundaeHelps": "WIE SUNDAE HILFT",
    "whatChanges": "WAS SICH VERÄNDERT",
    "whatWeFound": "Was wir gefunden haben:",
    "recommendation": "Empfehlung:",
    "potentialImpact": "Mögliche Auswirkungen:",
    "whatYoullDo": "Was Sie tun werden:",
    "timeline": "Zeitleiste",
    "keyCapabilities": "Hauptfunktionen:",
    "save18": "Sparen Sie ca. 18 % im Vergleich zur Einzelperson",
    "seeWatchtowerPricing": "Sehen Sie sich die Watchtower-Preise für Ihren Betrieb an",
    "watchWatchtowerDemo": "Sehen Sie sich die Watchtower-Demo an",
    "customWatchtowerConfiguration": "Benutzerdefinierte Watchtower-Konfiguration",
    "applyNow": "Bewerben Sie sich jetzt"
  },
  "nl": {
    "home": "Thuis",
    "howSundaeHelps": "HOE SUNDAE HELPT",
    "whatChanges": "WAT VERANDERT",
    "whatWeFound": "Wat we hebben gevonden:",
    "recommendation": "Aanbeveling:",
    "potentialImpact": "Potentiële impact:",
    "whatYoullDo": "Wat je gaat doen:",
    "timeline": "Tijdlijn",
    "keyCapabilities": "Belangrijkste mogelijkheden:",
    "save18": "Bespaar ~18% ten opzichte van individueel",
    "seeWatchtowerPricing": "Bekijk Watchtower-prijzen voor uw bedrijf",
    "watchWatchtowerDemo": "Bekijk de Watchtower-demo",
    "customWatchtowerConfiguration": "Aangepaste Watchtower-configuratie",
    "applyNow": "Solliciteer nu"
  },
  "pt": {
    "home": "Lar",
    "howSundaeHelps": "COMO O SUNDAE AJUDA",
    "whatChanges": "O QUE MUDA",
    "whatWeFound": "O que encontramos:",
    "recommendation": "Recomendação:",
    "potentialImpact": "Impacto potencial:",
    "whatYoullDo": "O que você fará:",
    "timeline": "Linha do tempo",
    "keyCapabilities": "Principais capacidades:",
    "save18": "Economize cerca de 18% em relação ao indivíduo",
    "seeWatchtowerPricing": "Veja os preços da Torre de Vigia para sua operação",
    "watchWatchtowerDemo": "Assista à demonstração da Torre de Vigia",
    "customWatchtowerConfiguration": "Configuração personalizada da Torre de Vigia",
    "applyNow": "Inscreva-se agora"
  },
  "hi": {
    "home": "घर",
    "howSundaeHelps": "संडे कैसे मदद करता है",
    "whatChanges": "कौन सा शुल्क",
    "whatWeFound": "हमने क्या पाया:",
    "recommendation": "सिफारिश:",
    "potentialImpact": "संभावित प्रभाव:",
    "whatYoullDo": "आप क्या करेंगे:",
    "timeline": "समय",
    "keyCapabilities": "प्रमुख क्षमताएं:",
    "save18": "व्यक्तिगत बनाम ~18% बचाएं",
    "seeWatchtowerPricing": "अपने ऑपरेशन के लिए वॉचटावर मूल्य निर्धारण देखें",
    "watchWatchtowerDemo": "वॉचटावर डेमो देखें",
    "customWatchtowerConfiguration": "कस्टम वॉचटावर कॉन्फ़िगरेशन",
    "applyNow": "अभी अप्लाई करें"
  },
  "ur": {
    "home": "گھر",
    "howSundaeHelps": "SUNDAE کس طرح مدد کرتا ہے۔",
    "whatChanges": "کیا تبدیلیاں",
    "whatWeFound": "ہمیں کیا ملا:",
    "recommendation": "سفارش:",
    "potentialImpact": "ممکنہ اثر:",
    "whatYoullDo": "آپ کیا کریں گے:",
    "timeline": "ٹائم لائن",
    "keyCapabilities": "کلیدی صلاحیتیں:",
    "save18": "~18% بچائیں بمقابلہ فرد",
    "seeWatchtowerPricing": "اپنے آپریشن کے لیے واچ ٹاور کی قیمتیں دیکھیں",
    "watchWatchtowerDemo": "واچ ٹاور ڈیمو دیکھیں",
    "customWatchtowerConfiguration": "اپنی مرضی کے مطابق واچ ٹاور کی ترتیب",
    "applyNow": "ابھی اپلائی کریں۔"
  },
  "it": {
    "home": "Casa",
    "howSundaeHelps": "COME AIUTA IL GELATO",
    "whatChanges": "COSA CAMBIA",
    "whatWeFound": "Cosa abbiamo trovato:",
    "recommendation": "Raccomandazione:",
    "potentialImpact": "Impatto potenziale:",
    "whatYoullDo": "Cosa farai:",
    "timeline": "Cronologia",
    "keyCapabilities": "Funzionalità chiave:",
    "save18": "Risparmia circa il 18% rispetto al singolo",
    "seeWatchtowerPricing": "Consulta i prezzi Watchtower per la tua operazione",
    "watchWatchtowerDemo": "Guarda la demo della Torre di Guardia",
    "customWatchtowerConfiguration": "Configurazione personalizzata della Torre di Guardia",
    "applyNow": "Candidati ora"
  },
  "pl": {
    "home": "Dom",
    "howSundaeHelps": "JAK SUNDAE POMAGA",
    "whatChanges": "CO ZMIENIA SIĘ",
    "whatWeFound": "Co znaleźliśmy:",
    "recommendation": "Zalecenie:",
    "potentialImpact": "Potencjalny wpływ:",
    "whatYoullDo": "Co zrobisz:",
    "timeline": "Oś czasu",
    "keyCapabilities": "Kluczowe możliwości:",
    "save18": "Zaoszczędź ~18% w porównaniu z osobą indywidualną",
    "seeWatchtowerPricing": "Zobacz ceny Strażnicy dla swojej operacji",
    "watchWatchtowerDemo": "Obejrzyj demonstrację Strażnicy",
    "customWatchtowerConfiguration": "Niestandardowa konfiguracja Strażnicy",
    "applyNow": "Złóż wniosek teraz"
  },
  "tr": {
    "home": "Ev",
    "howSundaeHelps": "SUNDAE NASIL YARDIMCI OLUR?",
    "whatChanges": "NE DEĞİŞİKLİKLER",
    "whatWeFound": "Ne bulduk:",
    "recommendation": "Tavsiye:",
    "potentialImpact": "Potansiyel Etki:",
    "whatYoullDo": "Ne Yapacaksınız:",
    "timeline": "Zaman çizelgesi",
    "keyCapabilities": "Anahtar yetenekler:",
    "save18": "Bireysele kıyasla ~%18 tasarruf edin",
    "seeWatchtowerPricing": "Operasyonunuz için Watchtower fiyatlandırmasına bakın",
    "watchWatchtowerDemo": "Watchtower demosunu izleyin",
    "customWatchtowerConfiguration": "Özel Gözetleme Kulesi yapılandırması",
    "applyNow": "Şimdi Başvurun"
  },
  "zh-Hans": {
    "home": "家",
    "howSundaeHelps": "圣代有何帮助",
    "whatChanges": "有什么变化",
    "whatWeFound": "我们发现了什么：",
    "recommendation": "推荐：",
    "potentialImpact": "潜在影响：",
    "whatYoullDo": "你会做什么：",
    "timeline": "时间轴",
    "keyCapabilities": "关键能力：",
    "save18": "与个人相比节省约 18%",
    "seeWatchtowerPricing": "查看您的运营的 Watchtower 定价",
    "watchWatchtowerDemo": "观看《瞭望塔》演示",
    "customWatchtowerConfiguration": "自定义了望塔配置",
    "applyNow": "立即申请"
  },
  "ja": {
    "home": "家",
    "howSundaeHelps": "サンデーはどのように役立つのか",
    "whatChanges": "何が変わるのか",
    "whatWeFound": "私たちが見つけたもの:",
    "recommendation": "おすすめ：",
    "potentialImpact": "潜在的な影響:",
    "whatYoullDo": "やること:",
    "timeline": "タイムライン",
    "keyCapabilities": "主な機能:",
    "save18": "個人と比較して最大 18% 節約",
    "seeWatchtowerPricing": "あなたの運営のためのWatchtowerの価格を参照してください",
    "watchWatchtowerDemo": "ものみの塔のデモを見る",
    "customWatchtowerConfiguration": "カスタム監視塔構成",
    "applyNow": "今すぐお申し込みください"
  },
  "ko": {
    "home": "집",
    "howSundaeHelps": "순대가 어떻게 도움이 되는지",
    "whatChanges": "무엇이 바뀌나요?",
    "whatWeFound": "우리가 발견한 것:",
    "recommendation": "추천:",
    "potentialImpact": "잠재적 영향:",
    "whatYoullDo": "당신이 할 일:",
    "timeline": "타임라인",
    "keyCapabilities": "주요 기능:",
    "save18": "개인 대비 ~18% 절약",
    "seeWatchtowerPricing": "귀하의 운영에 대한 Watchtower 가격을 확인하세요",
    "watchWatchtowerDemo": "Watchtower 데모 보기",
    "customWatchtowerConfiguration": "맞춤형 망루 구성",
    "applyNow": "지금 신청하세요"
  },
  "id": {
    "home": "Rumah",
    "howSundaeHelps": "BAGAIMANA SUNDAE MEMBANTU",
    "whatChanges": "PERUBAHAN APA",
    "whatWeFound": "Apa yang kami temukan:",
    "recommendation": "Rekomendasi:",
    "potentialImpact": "Potensi Dampak:",
    "whatYoullDo": "Apa yang akan Anda Lakukan:",
    "timeline": "Garis Waktu",
    "keyCapabilities": "Kemampuan utama:",
    "save18": "Hemat ~18% vs. individu",
    "seeWatchtowerPricing": "Lihat harga Menara Pengawal untuk operasi Anda",
    "watchWatchtowerDemo": "Tonton demo Menara Pengawal",
    "customWatchtowerConfiguration": "Konfigurasi Menara Pengawal khusus",
    "applyNow": "Lamar Sekarang"
  },
  "vi": {
    "home": "Trang chủ",
    "howSundaeHelps": "SUNDAE GIÚP ĐỠ NHƯ THẾ NÀO",
    "whatChanges": "THAY ĐỔI GÌ",
    "whatWeFound": "Những gì chúng tôi tìm thấy:",
    "recommendation": "Sự giới thiệu:",
    "potentialImpact": "Tác động tiềm tàng:",
    "whatYoullDo": "Bạn sẽ làm gì:",
    "timeline": "Dòng thời gian",
    "keyCapabilities": "Các khả năng chính:",
    "save18": "Tiết kiệm ~18% so với cá nhân",
    "seeWatchtowerPricing": "Xem giá Tháp Canh cho hoạt động của bạn",
    "watchWatchtowerDemo": "Xem bản demo Tháp Canh",
    "customWatchtowerConfiguration": "Cấu hình Tháp Canh tùy chỉnh",
    "applyNow": "Đăng ký ngay"
  },
  "ro": {
    "home": "Acasă",
    "howSundaeHelps": "CUM AJUTĂ SUNDAE",
    "whatChanges": "CE SE SCHIMBA",
    "whatWeFound": "Ce am gasit:",
    "recommendation": "Recomandare:",
    "potentialImpact": "Impact potențial:",
    "whatYoullDo": "Ce vei face:",
    "timeline": "Cronologie",
    "keyCapabilities": "Capabilitati cheie:",
    "save18": "Economisiți ~18% față de individual",
    "seeWatchtowerPricing": "Consultați prețurile Watchtower pentru operațiunea dvs",
    "watchWatchtowerDemo": "Urmăriți demonstrația Watchtower",
    "customWatchtowerConfiguration": "Configurație personalizată Watchtower",
    "applyNow": "Aplica acum"
  },
  "sv": {
    "home": "Hem",
    "howSundaeHelps": "HUR SUNDAE HJÄLPER",
    "whatChanges": "VAD FÖRÄNDRINGAR",
    "whatWeFound": "Vad vi hittade:",
    "recommendation": "Rekommendation:",
    "potentialImpact": "Potentiell påverkan:",
    "whatYoullDo": "Vad du ska göra:",
    "timeline": "Tidslinje",
    "keyCapabilities": "Nyckelfunktioner:",
    "save18": "Spara ~18 % jämfört med individen",
    "seeWatchtowerPricing": "Se Vakttornets priser för din verksamhet",
    "watchWatchtowerDemo": "Titta på Watchtower-demo",
    "customWatchtowerConfiguration": "Anpassad Watchtower-konfiguration",
    "applyNow": "Ansök nu"
  },
  "bn": {
    "home": "বাড়ি",
    "howSundaeHelps": "কিভাবে SUNDAE সাহায্য করে",
    "whatChanges": "কি পরিবর্তন",
    "whatWeFound": "আমরা যা পেয়েছি:",
    "recommendation": "সুপারিশ:",
    "potentialImpact": "সম্ভাব্য প্রভাব:",
    "whatYoullDo": "আপনি যা করবেন:",
    "timeline": "টাইমলাইন",
    "keyCapabilities": "মূল ক্ষমতা:",
    "save18": "ব্যক্তিগত বনাম ~18% সংরক্ষণ করুন",
    "seeWatchtowerPricing": "আপনার অপারেশন জন্য ওয়াচটাওয়ার মূল্য দেখুন",
    "watchWatchtowerDemo": "ওয়াচটাওয়ার ডেমো দেখুন",
    "customWatchtowerConfiguration": "কাস্টম ওয়াচটাওয়ার কনফিগারেশন",
    "applyNow": "এখনই আবেদন করুন"
  },
  "th": {
    "home": "บ้าน",
    "howSundaeHelps": "ซันเดย์ช่วยได้อย่างไร",
    "whatChanges": "มีการเปลี่ยนแปลงอะไรบ้าง",
    "whatWeFound": "สิ่งที่เราพบ:",
    "recommendation": "คำแนะนำ:",
    "potentialImpact": "ผลกระทบที่อาจเกิดขึ้น:",
    "whatYoullDo": "คุณจะทำอะไร:",
    "timeline": "ไทม์ไลน์",
    "keyCapabilities": "ความสามารถที่สำคัญ:",
    "save18": "ประหยัด ~18% เมื่อเทียบกับรายบุคคล",
    "seeWatchtowerPricing": "ดูราคาหอสังเกตการณ์สำหรับการดำเนินงานของคุณ",
    "watchWatchtowerDemo": "ชมการสาธิตหอสังเกตการณ์",
    "customWatchtowerConfiguration": "การกำหนดค่าหอสังเกตการณ์แบบกำหนดเอง",
    "applyNow": "สมัครตอนนี้"
  },
  "ms": {
    "home": "Rumah",
    "howSundaeHelps": "BAGAIMANA AHAD MEMBANTU",
    "whatChanges": "APA YANG BERUBAH",
    "whatWeFound": "Apa yang kami temui:",
    "recommendation": "Syor:",
    "potentialImpact": "Potensi Kesan:",
    "whatYoullDo": "Perkara yang Anda Akan Lakukan:",
    "timeline": "Garis masa",
    "keyCapabilities": "Keupayaan utama:",
    "save18": "Jimat ~18% berbanding individu",
    "seeWatchtowerPricing": "Lihat harga Menara Pengawal untuk operasi anda",
    "watchWatchtowerDemo": "Tonton demo Menara Pengawal",
    "customWatchtowerConfiguration": "Konfigurasi Menara Pengawal tersuai",
    "applyNow": "Mohon Sekarang"
  }
} as const
