// Generated by sundae-pricing/scripts/sync-pricing-handoff.ts. Edit the pricing copy source and resync.
export const pricingIntentCopy = {
  "en": {
    "title": "Your configuration",
    "scope": "Locations",
    "review": "Review your estimate",
    "note": "This is an estimate, not a final quote. We’ll confirm current prices and plan availability before you start.",
    "terms": [
      "Monthly · rolling",
      "Annual · paid quarterly",
      "Annual · paid upfront",
      "2 years · paid upfront"
    ],
    "workforce": "Unique employees across your locations",
    "payroll": "Payroll country"
  },
  "ar": {
    "title": "إعدادك",
    "scope": "المواقع",
    "review": "راجع تقديرك",
    "note": "هذا تقدير وليس عرض سعر ثابتًا. يُراجع السعر والأهلية قبل التفعيل.",
    "terms": [
      "شهري · متجدد",
      "سنوي · دفع ربع سنوي",
      "سنوي · دفع مقدم",
      "سنتان · دفع مقدم"
    ],
    "workforce": "عدد الموظفين الفريدين عبر مواقعك",
    "payroll": "بلد الرواتب"
  },
  "fr": {
    "title": "Votre configuration",
    "scope": "Sites",
    "review": "Vérifiez votre estimation",
    "note": "Il s’agit d’une estimation, pas d’un devis ferme. Tarifs et éligibilité seront revérifiés avant activation.",
    "terms": [
      "Mensuel · sans engagement annuel",
      "Annuel · payé par trimestre",
      "Annuel · payé à l’avance",
      "2 ans · payés à l’avance"
    ],
    "workforce": "Employés uniques dans l’ensemble de vos sites",
    "payroll": "Pays de paie"
  },
  "es": {
    "title": "Tu configuración",
    "scope": "Ubicaciones",
    "review": "Revisa tu estimación",
    "note": "Es una estimación, no una oferta fija. Los precios y la elegibilidad se revisan antes de activar.",
    "terms": [
      "Mensual · renovable",
      "Anual · pago trimestral",
      "Anual · pago anticipado",
      "2 años · pago anticipado"
    ],
    "workforce": "Empleados únicos en todas tus ubicaciones",
    "payroll": "País de nómina"
  },
  "de": {
    "title": "Ihre Konfiguration",
    "scope": "Standorte",
    "review": "Schätzung prüfen",
    "note": "Dies ist eine Schätzung, kein Festangebot. Preise und Berechtigung werden vor Aktivierung erneut geprüft.",
    "terms": [
      "Monatlich · laufend",
      "Jährlich · quartalsweise bezahlt",
      "Jährlich · im Voraus bezahlt",
      "2 Jahre · im Voraus bezahlt"
    ],
    "workforce": "Einmalig gezählte Mitarbeitende an allen Standorten",
    "payroll": "Land der Lohnabrechnung"
  },
  "nl": {
    "title": "Uw configuratie",
    "scope": "Locaties",
    "review": "Bekijk je raming",
    "note": "Dit is een raming, geen vaste offerte. Prijzen en geschiktheid worden vóór activering opnieuw gecontroleerd.",
    "terms": [
      "Maandelijks · doorlopend",
      "Jaarlijks · per kwartaal betaald",
      "Jaarlijks · vooruitbetaald",
      "2 jaar · vooruitbetaald"
    ],
    "workforce": "Unieke medewerkers op al je locaties",
    "payroll": "Land van loonadministratie"
  },
  "pt": {
    "title": "A sua configuração",
    "scope": "Localizações",
    "review": "Revise a estimativa",
    "note": "Esta é uma estimativa, não uma proposta fixa. Preços e elegibilidade são verificados antes da ativação.",
    "terms": [
      "Mensal · recorrente",
      "Anual · pago trimestralmente",
      "Anual · pago antecipadamente",
      "2 anos · pagos antecipadamente"
    ],
    "workforce": "Funcionários únicos em todas as unidades",
    "payroll": "País da folha de pagamento"
  },
  "hi": {
    "title": "आपका कॉन्फ़िगरेशन",
    "scope": "स्थान",
    "review": "अनुमान देखें",
    "note": "यह अनुमान है, निश्चित कोटेशन नहीं। सक्रिय करने से पहले कीमत और पात्रता दोबारा जाँची जाती है।",
    "terms": [
      "मासिक · जारी",
      "वार्षिक · तिमाही भुगतान",
      "वार्षिक · अग्रिम भुगतान",
      "2 वर्ष · अग्रिम भुगतान"
    ],
    "workforce": "सभी स्थानों पर अलग-अलग कर्मचारियों की संख्या",
    "payroll": "वेतन का देश"
  },
  "ur": {
    "title": "آپ کی کنفیگریشن",
    "scope": "مقامات",
    "review": "تخمینہ دیکھیں",
    "note": "یہ تخمینہ ہے، مقررہ کوٹیشن نہیں۔ فعال کرنے سے پہلے قیمت اور اہلیت دوبارہ جانچی جاتی ہے۔",
    "terms": [
      "ماہانہ · جاری",
      "سالانہ · سہ ماہی ادائیگی",
      "سالانہ · پیشگی ادائیگی",
      "2 سال · پیشگی ادائیگی"
    ],
    "workforce": "تمام مقامات پر منفرد ملازمین کی تعداد",
    "payroll": "تنخواہوں کا ملک"
  },
  "it": {
    "title": "La tua configurazione",
    "scope": "Località",
    "review": "Verifica la stima",
    "note": "È una stima, non un preventivo fisso. Prezzi e idoneità saranno verificati prima dell’attivazione.",
    "terms": [
      "Mensile · continuativo",
      "Annuale · pagato trimestralmente",
      "Annuale · pagato in anticipo",
      "2 anni · pagati in anticipo"
    ],
    "workforce": "Dipendenti unici in tutte le sedi",
    "payroll": "Paese delle paghe"
  },
  "pl": {
    "title": "Twoja konfiguracja",
    "scope": "Lokalizacje",
    "review": "Sprawdź szacunek",
    "note": "To szacunek, nie stała oferta. Ceny i uprawnienia są ponownie sprawdzane przed aktywacją.",
    "terms": [
      "Miesięcznie · odnawialnie",
      "Rocznie · płatność kwartalna",
      "Rocznie · płatność z góry",
      "2 lata · płatność z góry"
    ],
    "workforce": "Unikalni pracownicy we wszystkich lokalizacjach",
    "payroll": "Kraj rozliczania płac"
  },
  "tr": {
    "title": "Yapılandırmanız",
    "scope": "Lokasyonlar",
    "review": "Tahmini inceleyin",
    "note": "Bu bir tahmindir, sabit teklif değildir. Fiyatlar ve uygunluk etkinleştirmeden önce tekrar kontrol edilir.",
    "terms": [
      "Aylık · yenilenen",
      "Yıllık · üç ayda bir ödeme",
      "Yıllık · peşin ödeme",
      "2 yıl · peşin ödeme"
    ],
    "workforce": "Tüm lokasyonlardaki benzersiz çalışan sayısı",
    "payroll": "Bordro ülkesi"
  },
  "zh-Hans": {
    "title": "您的配置",
    "scope": "地点",
    "review": "查看估算",
    "note": "此为估算，不是固定报价。激活前将重新核实价格和资格。",
    "terms": [
      "按月 · 滚动续订",
      "按年 · 按季度付款",
      "按年 · 预付",
      "两年 · 预付"
    ],
    "workforce": "所有门店的独立员工人数",
    "payroll": "薪资所在国家"
  },
  "ja": {
    "title": "ご利用構成",
    "scope": "ロケーション",
    "review": "見積もりを確認",
    "note": "これは概算であり、確定見積もりではありません。有効化前に料金と適用資格を再確認します。",
    "terms": [
      "月単位・継続",
      "年契約・四半期払い",
      "年契約・前払い",
      "2年契約・前払い"
    ],
    "workforce": "全拠点の重複しない従業員数",
    "payroll": "給与計算の国"
  },
  "ko": {
    "title": "고객님의 구성",
    "scope": "위치",
    "review": "예상 비용 확인",
    "note": "이는 예상 금액이며 확정 견적이 아닙니다. 활성화 전 가격과 자격을 다시 확인합니다.",
    "terms": [
      "월간 · 갱신",
      "연간 · 분기별 결제",
      "연간 · 선불",
      "2년 · 선불"
    ],
    "workforce": "모든 지점의 중복 없는 직원 수",
    "payroll": "급여 국가"
  },
  "id": {
    "title": "Konfigurasi Anda",
    "scope": "Lokasi",
    "review": "Tinjau estimasi",
    "note": "Ini estimasi, bukan penawaran tetap. Harga dan kelayakan diperiksa kembali sebelum aktivasi.",
    "terms": [
      "Bulanan · berulang",
      "Tahunan · dibayar triwulanan",
      "Tahunan · dibayar di muka",
      "2 tahun · dibayar di muka"
    ],
    "workforce": "Jumlah karyawan unik di seluruh lokasi",
    "payroll": "Negara penggajian"
  },
  "vi": {
    "title": "Cấu hình của bạn",
    "scope": "Địa điểm",
    "review": "Xem ước tính",
    "note": "Đây là ước tính, không phải báo giá cố định. Giá và điều kiện được kiểm tra lại trước khi kích hoạt.",
    "terms": [
      "Hàng tháng · gia hạn",
      "Hàng năm · trả hàng quý",
      "Hàng năm · trả trước",
      "2 năm · trả trước"
    ],
    "workforce": "Số nhân viên không trùng lặp tại các địa điểm",
    "payroll": "Quốc gia tính lương"
  },
  "ro": {
    "title": "Configurația ta",
    "scope": "Locații",
    "review": "Verifică estimarea",
    "note": "Este o estimare, nu o ofertă fixă. Prețurile și eligibilitatea sunt reverificate înainte de activare.",
    "terms": [
      "Lunar · recurent",
      "Anual · plătit trimestrial",
      "Anual · plătit în avans",
      "2 ani · plătiți în avans"
    ],
    "workforce": "Angajați unici în toate locațiile",
    "payroll": "Țara salarizării"
  },
  "sv": {
    "title": "Din konfiguration",
    "scope": "Platser",
    "review": "Granska uppskattningen",
    "note": "Detta är en uppskattning, inte en fast offert. Priser och behörighet kontrolleras före aktivering.",
    "terms": [
      "Månadsvis · löpande",
      "Årligen · betalas kvartalsvis",
      "Årligen · betalas i förskott",
      "2 år · betalas i förskott"
    ],
    "workforce": "Unika medarbetare på alla platser",
    "payroll": "Löneland"
  },
  "bn": {
    "title": "আপনার কনফিগারেশন",
    "scope": "স্থান",
    "review": "আনুমানিক খরচ দেখুন",
    "note": "এটি অনুমান, স্থির কোটেশন নয়। সক্রিয় করার আগে মূল্য ও যোগ্যতা আবার যাচাই হবে।",
    "terms": [
      "মাসিক · চলমান",
      "বার্ষিক · ত্রৈমাসিক পরিশোধ",
      "বার্ষিক · অগ্রিম পরিশোধ",
      "২ বছর · অগ্রিম পরিশোধ"
    ],
    "workforce": "সব স্থানে অনন্য কর্মীর সংখ্যা",
    "payroll": "বেতন প্রদানের দেশ"
  },
  "th": {
    "title": "การกำหนดค่าของคุณ",
    "scope": "สถานที่",
    "review": "ตรวจสอบประมาณการ",
    "note": "นี่คือประมาณการ ไม่ใช่ใบเสนอราคาคงที่ จะตรวจสอบราคาและสิทธิ์อีกครั้งก่อนเปิดใช้งาน",
    "terms": [
      "รายเดือน · ต่อเนื่อง",
      "รายปี · ชำระรายไตรมาส",
      "รายปี · ชำระล่วงหน้า",
      "2 ปี · ชำระล่วงหน้า"
    ],
    "workforce": "จำนวนพนักงานไม่ซ้ำกันในทุกสาขา",
    "payroll": "ประเทศสำหรับเงินเดือน"
  },
  "ms": {
    "title": "Konfigurasi anda",
    "scope": "Lokasi",
    "review": "Semak anggaran",
    "note": "Ini anggaran, bukan sebut harga tetap. Harga dan kelayakan disemak semula sebelum pengaktifan.",
    "terms": [
      "Bulanan · berulang",
      "Tahunan · dibayar suku tahunan",
      "Tahunan · dibayar awal",
      "2 tahun · dibayar awal"
    ],
    "workforce": "Pekerja unik di semua lokasi",
    "payroll": "Negara penggajian"
  },
  "az": {
    "title": "Konfiqurasiyanız",
    "scope": "Məkanlar",
    "review": "Təxmini qiyməti yoxlayın",
    "note": "Bu təxmini qiymətdir, yekun təklif deyil. Başlamazdan əvvəl qiymət və uyğunluq təsdiqlənəcək.",
    "terms": [
      "Aylıq · davamlı",
      "İllik · rüblük ödəniş",
      "İllik · əvvəlcədən ödəniş",
      "2 il · əvvəlcədən ödəniş"
    ],
    "workforce": "Məkanlar üzrə unikal əməkdaşlar",
    "payroll": "Əməkhaqqı ölkəsi"
  },
  "ru": {
    "title": "Ваша конфигурация",
    "scope": "Локации",
    "review": "Проверьте расчёт",
    "note": "Это расчёт, а не окончательное предложение. Перед началом подтвердим цены и доступность плана.",
    "terms": [
      "Ежемесячно · с продлением",
      "Ежегодно · поквартально",
      "Ежегодно · предоплата",
      "2 года · предоплата"
    ],
    "workforce": "Уникальные сотрудники во всех локациях",
    "payroll": "Страна расчёта зарплаты"
  },
  "pap": {
    "title": "Bo konfigurashon",
    "scope": "Lokashonnan",
    "review": "Revisa bo estimashon",
    "note": "Esaki ta un estimashon, no un oferta final. Nos ta konfirmá preis i disponobilidat promé ku kuminsa.",
    "terms": [
      "Mensual · kontinua",
      "Anual · paga kada trimestre",
      "Anual · paga adelantá",
      "2 aña · paga adelantá"
    ],
    "workforce": "Empleadonan unik den tur lokashon",
    "payroll": "Pais di pago di salario"
  }
} as const;
export const pricingOfferNames: Record<string, string> = {
  "core_foundation": "Core Foundation",
  "core_margin": "Core Margin",
  "core_growth": "Core Growth",
  "core_performance": "Core Performance",
  "crew_lite": "Crew Starter",
  "crew_scheduling": "Crew Schedule",
  "crew_operations": "Crew Manage",
  "crew_tna": "Crew Time",
  "crew_payroll": "Crew Pay",
  "crew_people_intelligence": "Crew People",
  "concept_franchise": "Franchise",
  "concept_hotel_fb": "Hotel F&B",
  "concept_cloud_kitchen": "Cloud Kitchen",
  "concept_catering": "Catering",
  "concept_production": "Production",
  "concept_rental_commissary": "Rental Commissary",
  "foresight_action": "Foresight & Action",
  "competitive": "Competitive Intelligence",
  "events": "Event & Calendar Signals",
  "trends": "Market Trends",
  "bundle": "Full Watchtower Bundle"
};
