import type { WebsiteLocale } from '@/lib/i18n';

// Locale copy for the cinematic intro. Everything localizes, including the
// "See every layer. / Act in time." headline (native transcreation per locale).
export type CinematicLayer = { name: string; sub: string };
export type CinematicIntroCopy = { headline: string; tagline: string; eyebrow: string; sub: string; cta: string; layers: CinematicLayer[] };

export const cinematicIntroCopy: Record<WebsiteLocale, CinematicIntroCopy> = {
  en: {
    headline: 'See every layer.',
    tagline: 'Act in time.',
    eyebrow: 'Decision intelligence for multi-location operators',
    sub: 'Sundae connects every layer of the business - revenue, labor, inventory, guests, marketing, and outlet performance - so teams can see what changed and act while it still matters.',
    cta: 'Book a demo',
    layers: [
      { name: 'Foundation', sub: 'org topology' },
      { name: 'Revenue', sub: 'sales & mix' },
      { name: 'Labor', sub: 'crew & cost' },
      { name: 'Inventory', sub: 'stock & waste' },
      { name: 'Marketing', sub: 'reach & ROI' },
      { name: 'Guests', sub: 'CRM & loyalty' },
      { name: 'Next move', sub: 'what to do now' },
    ],
  },
  ar: {
    headline: 'اطّلع على كل طبقة.',
    tagline: 'وتحرّك في الوقت المناسب.',
    eyebrow: 'ذكاء قراري لمشغّلي المواقع المتعددة',
    sub: 'يربط Sundae كل طبقة من نشاطك - الإيرادات والعمالة والمخزون والضيوف والتسويق وأداء الفروع - ليرى الفريق ما تغيّر ويتصرّف وهو ما زال مهماً.',
    cta: 'احجز عرضاً',
    layers: [
      { name: 'الأساس', sub: 'هيكل المؤسسة' },
      { name: 'الإيرادات', sub: 'المبيعات والمزيج' },
      { name: 'العمالة', sub: 'الطاقم والتكلفة' },
      { name: 'المخزون', sub: 'المخزون والهدر' },
      { name: 'التسويق', sub: 'الوصول والعائد' },
      { name: 'الضيوف', sub: 'العملاء والولاء' },
      { name: 'الخطوة التالية', sub: 'ماذا تفعل الآن' },
    ],
  },
  fr: {
    headline: 'Voyez chaque couche.',
    tagline: 'Agissez à temps.',
    eyebrow: 'Intelligence décisionnelle pour opérateurs multi-sites',
    sub: 'Sundae relie chaque couche de l’activité - revenu, main-d’œuvre, stocks, clients, marketing et performance des points de vente - pour que les équipes voient ce qui a changé et agissent tant que ça compte.',
    cta: 'Réserver une démo',
    layers: [
      { name: 'Fondation', sub: 'topologie org' },
      { name: 'Revenu', sub: 'ventes & mix' },
      { name: 'Main-d’œuvre', sub: 'équipe & coût' },
      { name: 'Stocks', sub: 'stock & perte' },
      { name: 'Marketing', sub: 'portée & ROI' },
      { name: 'Clients', sub: 'CRM & fidélité' },
      { name: 'Prochaine action', sub: 'quoi faire maintenant' },
    ],
  },
  es: {
    headline: 'Ve cada capa.',
    tagline: 'Actúa a tiempo.',
    eyebrow: 'Inteligencia de decisión para operadores multilocal',
    sub: 'Sundae conecta cada capa del negocio - ingresos, personal, inventario, clientes, marketing y rendimiento de locales - para que los equipos vean qué cambió y actúen cuando aún importa.',
    cta: 'Reservar una demo',
    layers: [
      { name: 'Base', sub: 'topología org' },
      { name: 'Ingresos', sub: 'ventas y mix' },
      { name: 'Personal', sub: 'equipo y coste' },
      { name: 'Inventario', sub: 'stock y merma' },
      { name: 'Marketing', sub: 'alcance y ROI' },
      { name: 'Clientes', sub: 'CRM y lealtad' },
      { name: 'Próximo paso', sub: 'qué hacer ahora' },
    ],
  },
  de: {
    headline: 'Sieh jede Ebene.',
    tagline: 'Handle rechtzeitig.',
    eyebrow: 'Entscheidungsintelligenz für Betreiber mit mehreren Standorten',
    sub: 'Sundae verbindet jede Ebene des Betriebs - Umsatz, Personal, Inventar, Gäste, Marketing und Standortleistung - damit Teams sehen, was sich geändert hat, und handeln, solange es zählt.',
    cta: 'Demo buchen',
    layers: [
      { name: 'Fundament', sub: 'Org-Topologie' },
      { name: 'Umsatz', sub: 'Verkauf & Mix' },
      { name: 'Personal', sub: 'Team & Kosten' },
      { name: 'Inventar', sub: 'Bestand & Schwund' },
      { name: 'Marketing', sub: 'Reichweite & ROI' },
      { name: 'Gäste', sub: 'CRM & Treue' },
      { name: 'Nächster Schritt', sub: 'was jetzt zu tun ist' },
    ],
  },
  nl: {
    headline: 'Zie elke laag.',
    tagline: 'Handel op tijd.',
    eyebrow: 'Decision intelligence voor operators met meerdere vestigingen',
    sub: 'Sundae verbindt elke laag van de zaak - omzet, personeel, voorraad, gasten, marketing en vestigingsprestaties - zodat teams zien wat veranderde en handelen terwijl het nog telt.',
    cta: 'Demo boeken',
    layers: [
      { name: 'Fundament', sub: 'org-topologie' },
      { name: 'Omzet', sub: 'verkoop & mix' },
      { name: 'Personeel', sub: 'team & kosten' },
      { name: 'Voorraad', sub: 'voorraad & verlies' },
      { name: 'Marketing', sub: 'bereik & ROI' },
      { name: 'Gasten', sub: 'CRM & loyaliteit' },
      { name: 'Volgende zet', sub: 'wat nu te doen' },
    ],
  },
  pt: {
    headline: 'Veja cada camada.',
    tagline: 'Aja a tempo.',
    eyebrow: 'Decision intelligence para operadores multiunidade',
    sub: 'O Sundae conecta cada camada do negócio - receita, equipe, estoque, clientes, marketing e desempenho das unidades - para as equipes verem o que mudou e agirem enquanto ainda importa.',
    cta: 'Agendar demo',
    layers: [
      { name: 'Base', sub: 'topologia org' },
      { name: 'Receita', sub: 'vendas & mix' },
      { name: 'Equipe', sub: 'time & custo' },
      { name: 'Estoque', sub: 'estoque & perda' },
      { name: 'Marketing', sub: 'alcance & ROI' },
      { name: 'Clientes', sub: 'CRM & fidelidade' },
      { name: 'Próximo passo', sub: 'o que fazer agora' },
    ],
  },
  hi: {
    headline: 'हर परत देखें।',
    tagline: 'समय रहते कदम उठाएँ।',
    eyebrow: 'मल्टी-लोकेशन ऑपरेटरों के लिए डिसीज़न इंटेलिजेंस',
    sub: 'Sundae कारोबार की हर परत को जोड़ता है - रेवेन्यू, लेबर, इन्वेंटरी, मेहमान, मार्केटिंग और आउटलेट परफ़ॉर्मेंस - ताकि टीमें देखें क्या बदला और तब कदम उठाएँ जब यह मायने रखता है।',
    cta: 'डेमो बुक करें',
    layers: [
      { name: 'नींव', sub: 'ऑर्ग टोपोलॉजी' },
      { name: 'रेवेन्यू', sub: 'सेल्स और मिक्स' },
      { name: 'लेबर', sub: 'टीम और लागत' },
      { name: 'इन्वेंटरी', sub: 'स्टॉक और बर्बादी' },
      { name: 'मार्केटिंग', sub: 'पहुँच और ROI' },
      { name: 'मेहमान', sub: 'CRM और वफ़ादारी' },
      { name: 'अगला कदम', sub: 'अब क्या करें' },
    ],
  },
  ur: {
    headline: 'ہر پرت دیکھیں۔',
    tagline: 'وقت پر عمل کریں۔',
    eyebrow: 'متعدد مقامات والے آپریٹرز کے لیے ڈیسیژن انٹیلیجنس',
    sub: 'Sundae کاروبار کی ہر پرت کو جوڑتا ہے - ریونیو، لیبر، انوینٹری، مہمان، مارکیٹنگ اور آؤٹ لیٹ کارکردگی - تاکہ ٹیمیں دیکھیں کیا بدلا اور تب عمل کریں جب یہ اہم ہو۔',
    cta: 'ڈیمو بُک کریں',
    layers: [
      { name: 'بنیاد', sub: 'آرگ ٹوپولوجی' },
      { name: 'ریونیو', sub: 'سیلز اور مکس' },
      { name: 'لیبر', sub: 'ٹیم اور لاگت' },
      { name: 'انوینٹری', sub: 'اسٹاک اور ضیاع' },
      { name: 'مارکیٹنگ', sub: 'رسائی اور ROI' },
      { name: 'مہمان', sub: 'CRM اور وفاداری' },
      { name: 'اگلا قدم', sub: 'اب کیا کریں' },
    ],
  },
  it: {
    headline: 'Vedi ogni livello.',
    tagline: 'Agisci in tempo.',
    eyebrow: 'Decision intelligence per operatori multi-sede',
    sub: 'Sundae collega ogni livello dell’attività - ricavi, personale, magazzino, clienti, marketing e performance dei locali - così i team vedono cosa è cambiato e agiscono finché conta.',
    cta: 'Prenota una demo',
    layers: [
      { name: 'Base', sub: 'topologia org' },
      { name: 'Ricavi', sub: 'vendite & mix' },
      { name: 'Personale', sub: 'team & costo' },
      { name: 'Magazzino', sub: 'scorte & sprechi' },
      { name: 'Marketing', sub: 'reach & ROI' },
      { name: 'Clienti', sub: 'CRM & fedeltà' },
      { name: 'Prossima mossa', sub: 'cosa fare ora' },
    ],
  },
  pl: {
    headline: 'Zobacz każdą warstwę.',
    tagline: 'Działaj na czas.',
    eyebrow: 'Decision intelligence dla operatorów wielolokalizacyjnych',
    sub: 'Sundae łączy każdą warstwę biznesu - przychód, kadry, magazyn, gości, marketing i wyniki lokali - by zespoły widziały, co się zmieniło, i działały, póki to ma znaczenie.',
    cta: 'Umów demo',
    layers: [
      { name: 'Fundament', sub: 'topologia org' },
      { name: 'Przychód', sub: 'sprzedaż i miks' },
      { name: 'Kadry', sub: 'zespół i koszt' },
      { name: 'Magazyn', sub: 'zapas i strata' },
      { name: 'Marketing', sub: 'zasięg i ROI' },
      { name: 'Goście', sub: 'CRM i lojalność' },
      { name: 'Następny ruch', sub: 'co robić teraz' },
    ],
  },
  tr: {
    headline: 'Her katmanı gör.',
    tagline: 'Zamanında harekete geç.',
    eyebrow: 'Çok şubeli işletmeciler için decision intelligence',
    sub: 'Sundae işin her katmanını birbirine bağlar - gelir, personel, envanter, misafirler, pazarlama ve şube performansı - böylece ekipler neyin değiştiğini görür ve hâlâ önemliyken harekete geçer.',
    cta: 'Demo planlayın',
    layers: [
      { name: 'Temel', sub: 'org topolojisi' },
      { name: 'Gelir', sub: 'satış & mix' },
      { name: 'Personel', sub: 'ekip & maliyet' },
      { name: 'Envanter', sub: 'stok & fire' },
      { name: 'Pazarlama', sub: 'erişim & ROI' },
      { name: 'Misafirler', sub: 'CRM & sadakat' },
      { name: 'Sonraki adım', sub: 'şimdi ne yapmalı' },
    ],
  },
  'zh-Hans': {
    headline: '看见每一层。',
    tagline: '及时行动。',
    eyebrow: '面向多门店运营者的决策智能',
    sub: 'Sundae 连接业务的每一层 - 营收、用工、库存、客人、营销与门店表现 - 让团队看清变化，并在仍来得及时采取行动。',
    cta: '预约演示',
    layers: [
      { name: '根基', sub: '组织拓扑' },
      { name: '营收', sub: '销售与结构' },
      { name: '用工', sub: '团队与成本' },
      { name: '库存', sub: '库存与损耗' },
      { name: '营销', sub: '触达与 ROI' },
      { name: '客人', sub: 'CRM 与忠诚' },
      { name: '下一步', sub: '现在该做什么' },
    ],
  },
  ja: {
    headline: 'すべてのレイヤーを見る。',
    tagline: '間に合ううちに動く。',
    eyebrow: '多店舗オペレーター向けの意思決定インテリジェンス',
    sub: 'Sundae はビジネスのあらゆるレイヤー - 売上、労務、在庫、ゲスト、マーケティング、店舗パフォーマンス - をつなぎ、何が変わったかをチームが把握し、間に合ううちに動けるようにします。',
    cta: 'デモを予約',
    layers: [
      { name: '基盤', sub: '組織トポロジー' },
      { name: '売上', sub: '販売とミックス' },
      { name: '労務', sub: '人員とコスト' },
      { name: '在庫', sub: '在庫とロス' },
      { name: 'マーケ', sub: 'リーチと ROI' },
      { name: 'ゲスト', sub: 'CRM とロイヤルティ' },
      { name: '次の一手', sub: '今すべきこと' },
    ],
  },
  ko: {
    headline: '모든 계층을 보세요.',
    tagline: '제때 움직이세요.',
    eyebrow: '다점포 운영자를 위한 의사결정 인텔리전스',
    sub: 'Sundae는 비즈니스의 모든 계층 - 매출, 인력, 재고, 고객, 마케팅, 매장 성과 - 을 연결해 팀이 무엇이 바뀌었는지 보고 늦기 전에 움직이게 합니다.',
    cta: '데모 예약',
    layers: [
      { name: '기반', sub: '조직 구조' },
      { name: '매출', sub: '판매와 구성' },
      { name: '인력', sub: '팀과 비용' },
      { name: '재고', sub: '재고와 손실' },
      { name: '마케팅', sub: '도달과 ROI' },
      { name: '고객', sub: 'CRM과 충성도' },
      { name: '다음 수', sub: '지금 할 일' },
    ],
  },
  id: {
    headline: 'Lihat setiap lapisan.',
    tagline: 'Bertindak tepat waktu.',
    eyebrow: 'Decision intelligence untuk operator multi-lokasi',
    sub: 'Sundae menghubungkan setiap lapisan bisnis - pendapatan, tenaga kerja, inventaris, tamu, pemasaran, dan kinerja outlet - agar tim melihat apa yang berubah dan bertindak selagi masih penting.',
    cta: 'Pesan demo',
    layers: [
      { name: 'Fondasi', sub: 'topologi org' },
      { name: 'Pendapatan', sub: 'penjualan & mix' },
      { name: 'Tenaga kerja', sub: 'tim & biaya' },
      { name: 'Inventaris', sub: 'stok & susut' },
      { name: 'Pemasaran', sub: 'jangkauan & ROI' },
      { name: 'Tamu', sub: 'CRM & loyalitas' },
      { name: 'Langkah berikutnya', sub: 'apa yang harus dilakukan' },
    ],
  },
  vi: {
    headline: 'Thấy mọi tầng.',
    tagline: 'Hành động kịp thời.',
    eyebrow: 'Decision intelligence cho nhà điều hành nhiều chi nhánh',
    sub: 'Sundae kết nối mọi tầng của doanh nghiệp - doanh thu, nhân sự, tồn kho, khách, marketing và hiệu suất chi nhánh - để đội ngũ thấy điều gì đã đổi và hành động khi còn kịp.',
    cta: 'Đặt demo',
    layers: [
      { name: 'Nền tảng', sub: 'sơ đồ tổ chức' },
      { name: 'Doanh thu', sub: 'bán hàng & cơ cấu' },
      { name: 'Nhân sự', sub: 'đội & chi phí' },
      { name: 'Tồn kho', sub: 'tồn & hao hụt' },
      { name: 'Marketing', sub: 'tiếp cận & ROI' },
      { name: 'Khách', sub: 'CRM & trung thành' },
      { name: 'Bước tiếp theo', sub: 'làm gì bây giờ' },
    ],
  },
  ro: {
    headline: 'Vezi fiecare strat.',
    tagline: 'Acționează la timp.',
    eyebrow: 'Decision intelligence pentru operatori multi-locație',
    sub: 'Sundae conectează fiecare strat al afacerii - venit, personal, stocuri, clienți, marketing și performanța locațiilor - ca echipele să vadă ce s-a schimbat și să acționeze cât încă contează.',
    cta: 'Programează un demo',
    layers: [
      { name: 'Fundație', sub: 'topologie org' },
      { name: 'Venit', sub: 'vânzări & mix' },
      { name: 'Personal', sub: 'echipă & cost' },
      { name: 'Stocuri', sub: 'stoc & pierderi' },
      { name: 'Marketing', sub: 'acoperire & ROI' },
      { name: 'Clienți', sub: 'CRM & loialitate' },
      { name: 'Următoarea mișcare', sub: 'ce faci acum' },
    ],
  },
  sv: {
    headline: 'Se varje lager.',
    tagline: 'Agera i tid.',
    eyebrow: 'Decision intelligence för operatörer med flera enheter',
    sub: 'Sundae kopplar ihop varje lager av verksamheten - intäkter, personal, lager, gäster, marknadsföring och enhetsprestanda - så att team ser vad som ändrades och agerar medan det fortfarande spelar roll.',
    cta: 'Boka en demo',
    layers: [
      { name: 'Grund', sub: 'org-topologi' },
      { name: 'Intäkter', sub: 'försäljning & mix' },
      { name: 'Personal', sub: 'team & kostnad' },
      { name: 'Lager', sub: 'lager & svinn' },
      { name: 'Marknad', sub: 'räckvidd & ROI' },
      { name: 'Gäster', sub: 'CRM & lojalitet' },
      { name: 'Nästa drag', sub: 'vad du gör nu' },
    ],
  },
  bn: {
    headline: 'প্রতিটি স্তর দেখুন।',
    tagline: 'সময় থাকতেই পদক্ষেপ নিন।',
    eyebrow: 'মাল্টি-লোকেশন অপারেটরদের জন্য ডিসিশন ইন্টেলিজেন্স',
    sub: 'Sundae ব্যবসার প্রতিটি স্তর - রাজস্ব, কর্মী, ইনভেন্টরি, অতিথি, মার্কেটিং ও আউটলেট পারফরম্যান্স - যুক্ত করে, যাতে টিম দেখে কী বদলালো এবং সময় থাকতেই পদক্ষেপ নেয়।',
    cta: 'ডেমো বুক করুন',
    layers: [
      { name: 'ভিত্তি', sub: 'অর্গ টপোলজি' },
      { name: 'রাজস্ব', sub: 'বিক্রি ও মিক্স' },
      { name: 'কর্মী', sub: 'টিম ও খরচ' },
      { name: 'ইনভেন্টরি', sub: 'স্টক ও অপচয়' },
      { name: 'মার্কেটিং', sub: 'নাগাল ও ROI' },
      { name: 'অতিথি', sub: 'CRM ও আনুগত্য' },
      { name: 'পরের পদক্ষেপ', sub: 'এখন কী করবেন' },
    ],
  },
  th: {
    headline: 'เห็นทุกชั้น',
    tagline: 'ลงมือทันเวลา',
    eyebrow: 'Decision intelligence สำหรับผู้ดำเนินการหลายสาขา',
    sub: 'Sundae เชื่อมทุกชั้นของธุรกิจ - รายได้ แรงงาน สินค้าคงคลัง ลูกค้า การตลาด และผลงานสาขา - เพื่อให้ทีมเห็นว่าอะไรเปลี่ยนและลงมือก่อนจะสาย',
    cta: 'จองเดโม',
    layers: [
      { name: 'รากฐาน', sub: 'โครงสร้างองค์กร' },
      { name: 'รายได้', sub: 'ยอดขายและสัดส่วน' },
      { name: 'แรงงาน', sub: 'ทีมและต้นทุน' },
      { name: 'สินค้าคงคลัง', sub: 'สต๊อกและการสูญเสีย' },
      { name: 'การตลาด', sub: 'การเข้าถึงและ ROI' },
      { name: 'ลูกค้า', sub: 'CRM และความภักดี' },
      { name: 'ก้าวต่อไป', sub: 'ตอนนี้ควรทำอะไร' },
    ],
  },
  ms: {
    headline: 'Lihat setiap lapisan.',
    tagline: 'Bertindak tepat pada masanya.',
    eyebrow: 'Decision intelligence untuk pengendali berbilang lokasi',
    sub: 'Sundae menghubungkan setiap lapisan perniagaan - hasil, tenaga kerja, inventori, tetamu, pemasaran dan prestasi outlet - supaya pasukan nampak apa yang berubah dan bertindak semasa ia masih penting.',
    cta: 'Tempah demo',
    layers: [
      { name: 'Asas', sub: 'topologi org' },
      { name: 'Hasil', sub: 'jualan & mix' },
      { name: 'Tenaga kerja', sub: 'pasukan & kos' },
      { name: 'Inventori', sub: 'stok & susut' },
      { name: 'Pemasaran', sub: 'jangkauan & ROI' },
      { name: 'Tetamu', sub: 'CRM & kesetiaan' },
      { name: 'Langkah seterusnya', sub: 'apa nak buat sekarang' },
    ],
  },
};
