import type { WebsiteLocale } from '@/lib/i18n';

// Locale copy for the cinematic intro. Everything localizes, including the
// "See every layer. / Act in time." headline (native transcreation per locale).
export type CinematicLayer = { name: string; sub: string };
export type CinematicIntroCopy = { headline: string; tagline: string; eyebrow: string; sub: string; cta: string; layers: CinematicLayer[] };

export const cinematicIntroCopy: Record<WebsiteLocale, CinematicIntroCopy> = {
  en: {
    headline: 'Recover the profit.',
    tagline: 'Prove what worked.',
    eyebrow: 'The decision-intelligence platform for multi-location operators',
    sub: 'Sundae connects the systems you already run - finds the profit leaking across revenue, labour, inventory and guests - then gives each opportunity one owner and measures what came back.',
    cta: 'Book a demo',
    layers: [
      { name: 'Foundation', sub: 'org topology' },
      { name: 'Revenue', sub: 'sales & mix' },
      { name: 'Labour', sub: 'crew & cost' },
      { name: 'Inventory', sub: 'stock & waste' },
      { name: 'Marketing', sub: 'reach & ROI' },
      { name: 'Guests', sub: 'CRM & loyalty' },
      { name: 'Next move', sub: 'what to do now' },
    ],
  },
  ar: {
    headline: 'استرجع الأرباح.',
    tagline: 'وأثبت ما نجح.',
    eyebrow: 'منصّة الذكاء القراري لمشغّلي المواقع المتعددة',
    sub: 'يتصل Sundae بالأنظمة التي تشغّلها اليوم - ويكشف الأرباح المتسرّبة عبر الإيرادات والعمالة والمخزون والضيوف - ثم يسند كل فرصة إلى مسؤول واحد ويقيس ما استُرجع فعلاً.',
    cta: 'احجز عرضاً',
    layers: [
      { name: 'الأساس', sub: 'هيكل المؤسسة' },
      { name: 'الإيرادات', sub: 'المبيعات والمزيج' },
      { name: 'العمالة', sub: 'الطاقم والتكلفة' },
      { name: 'المخزون', sub: 'المخزون والهدر' },
      { name: 'التسويق', sub: 'الوصول والعائد' },
      { name: 'الضيوف', sub: 'العملاء والولاء' },
      { name: 'الخطوة التالية', sub: 'ماذا تفعل الآن' },
    ],
  },
  fr: {
    headline: 'Récupérez la marge.',
    tagline: 'Prouvez ce qui a marché.',
    eyebrow: 'La plateforme d’intelligence décisionnelle pour opérateurs multi-sites',
    sub: 'Sundae se connecte aux systèmes que vous utilisez déjà - repère la marge qui fuit sur les ventes, la main-d\'œuvre, les stocks et les clients - puis confie chaque opportunité à un responsable et mesure ce qui est revenu.',
    cta: 'Réserver une démo',
    layers: [
      { name: 'Fondation', sub: 'topologie org' },
      { name: 'Revenu', sub: 'ventes & mix' },
      { name: 'Main-d’œuvre', sub: 'équipe & coût' },
      { name: 'Stocks', sub: 'stock & perte' },
      { name: 'Marketing', sub: 'portée & ROI' },
      { name: 'Clients', sub: 'CRM & fidélité' },
      { name: 'Prochaine action', sub: 'quoi faire maintenant' },
    ],
  },
  es: {
    headline: 'Recupera el margen.',
    tagline: 'Demuestra qué funcionó.',
    eyebrow: 'La plataforma de inteligencia de decisión para operadores multilocal',
    sub: 'Sundae se conecta a los sistemas que ya usas - detecta el margen que se escapa en ventas, personal, inventario y clientes - y asigna cada oportunidad a un responsable, midiendo lo que se recuperó.',
    cta: 'Reservar una demo',
    layers: [
      { name: 'Base', sub: 'topología org' },
      { name: 'Ingresos', sub: 'ventas y mix' },
      { name: 'Personal', sub: 'equipo y coste' },
      { name: 'Inventario', sub: 'stock y merma' },
      { name: 'Marketing', sub: 'alcance y ROI' },
      { name: 'Clientes', sub: 'CRM y lealtad' },
      { name: 'Próximo paso', sub: 'qué hacer ahora' },
    ],
  },
  de: {
    headline: 'Holen Sie die Marge zurück.',
    tagline: 'Beweisen Sie, was gewirkt hat.',
    eyebrow: 'Die Entscheidungsintelligenz-Plattform für Betreiber mit mehreren Standorten',
    sub: 'Sundae verbindet die Systeme, die Sie ohnehin nutzen - findet die Marge, die über Umsatz, Personal, Bestand und Gäste verloren geht - und gibt jeder Chance einen Verantwortlichen und misst, was zurückkam.',
    cta: 'Demo buchen',
    layers: [
      { name: 'Fundament', sub: 'Org-Topologie' },
      { name: 'Umsatz', sub: 'Verkauf & Mix' },
      { name: 'Personal', sub: 'Team & Kosten' },
      { name: 'Inventar', sub: 'Bestand & Schwund' },
      { name: 'Marketing', sub: 'Reichweite & ROI' },
      { name: 'Gäste', sub: 'CRM & Treue' },
      { name: 'Nächster Schritt', sub: 'was jetzt zu tun ist' },
    ],
  },
  nl: {
    headline: 'Haal de marge terug.',
    tagline: 'Bewijs wat werkte.',
    eyebrow: 'Het decision intelligence-platform voor operators met meerdere vestigingen',
    sub: 'Sundae koppelt de systemen die je al gebruikt - vindt de marge die weglekt via omzet, personeel, voorraad en gasten - en geeft elke kans één eigenaar en meet wat er terugkwam.',
    cta: 'Demo boeken',
    layers: [
      { name: 'Fundament', sub: 'org-topologie' },
      { name: 'Omzet', sub: 'verkoop & mix' },
      { name: 'Personeel', sub: 'team & kosten' },
      { name: 'Voorraad', sub: 'voorraad & verlies' },
      { name: 'Marketing', sub: 'bereik & ROI' },
      { name: 'Gasten', sub: 'CRM & loyaliteit' },
      { name: 'Volgende zet', sub: 'wat nu te doen' },
    ],
  },
  pt: {
    headline: 'Recupere a margem.',
    tagline: 'Prove o que funcionou.',
    eyebrow: 'A plataforma de decision intelligence para operadores multiunidade',
    sub: 'A Sundae conecta os sistemas que você já usa - encontra a margem que escapa em vendas, mão de obra, estoque e clientes - e dá um responsável a cada oportunidade, medindo o que voltou.',
    cta: 'Agendar demo',
    layers: [
      { name: 'Base', sub: 'topologia org' },
      { name: 'Receita', sub: 'vendas & mix' },
      { name: 'Equipe', sub: 'time & custo' },
      { name: 'Estoque', sub: 'estoque & perda' },
      { name: 'Marketing', sub: 'alcance & ROI' },
      { name: 'Clientes', sub: 'CRM & fidelidade' },
      { name: 'Próximo passo', sub: 'o que fazer agora' },
    ],
  },
  hi: {
    headline: 'मुनाफ़ा वापस पाइए.',
    tagline: 'और साबित कीजिए क्या काम आया.',
    eyebrow: 'मल्टी-लोकेशन ऑपरेटरों के लिए डिसीज़न इंटेलिजेंस प्लेटफ़ॉर्म',
    sub: 'Sundae आपके मौजूदा सिस्टम से जुड़ता है - राजस्व, श्रम, इन्वेंट्री और मेहमानों में रिस रहे मुनाफ़े को पकड़ता है - फिर हर अवसर को एक ज़िम्मेदार सौंपकर मापता है कि कितना वापस आया.',
    cta: 'डेमो बुक करें',
    layers: [
      { name: 'नींव', sub: 'ऑर्ग टोपोलॉजी' },
      { name: 'रेवेन्यू', sub: 'सेल्स और मिक्स' },
      { name: 'लेबर', sub: 'टीम और लागत' },
      { name: 'इन्वेंटरी', sub: 'स्टॉक और बर्बादी' },
      { name: 'मार्केटिंग', sub: 'पहुँच और ROI' },
      { name: 'मेहमान', sub: 'CRM और वफ़ादारी' },
      { name: 'अगला कदम', sub: 'अब क्या करें' },
    ],
  },
  ur: {
    headline: 'منافع واپس حاصل کریں۔',
    tagline: 'اور ثابت کریں کیا کام آیا۔',
    eyebrow: 'متعدد مقامات والے آپریٹرز کے لیے ڈیسیژن انٹیلیجنس پلیٹ فارم',
    sub: 'Sundae آپ کے موجودہ نظاموں سے جڑتا ہے - آمدنی، محنت، انوینٹری اور مہمانوں میں ضائع ہوتا منافع تلاش کرتا ہے - پھر ہر موقع ایک ذمہ دار کے سپرد کر کے ماپتا ہے کہ کتنا واپس آیا۔',
    cta: 'ڈیمو بُک کریں',
    layers: [
      { name: 'بنیاد', sub: 'آرگ ٹوپولوجی' },
      { name: 'ریونیو', sub: 'سیلز اور مکس' },
      { name: 'لیبر', sub: 'ٹیم اور لاگت' },
      { name: 'انوینٹری', sub: 'اسٹاک اور ضیاع' },
      { name: 'مارکیٹنگ', sub: 'رسائی اور ROI' },
      { name: 'مہمان', sub: 'CRM اور وفاداری' },
      { name: 'اگلا قدم', sub: 'اب کیا کریں' },
    ],
  },
  it: {
    headline: 'Recupera il margine.',
    tagline: 'Dimostra cosa ha funzionato.',
    eyebrow: 'La piattaforma di decision intelligence per operatori multi-sede',
    sub: 'Sundae si collega ai sistemi che già usi - individua il margine che si perde tra ricavi, personale, magazzino e ospiti - poi assegna ogni opportunità a un responsabile e misura quanto è rientrato.',
    cta: 'Prenota una demo',
    layers: [
      { name: 'Base', sub: 'topologia org' },
      { name: 'Ricavi', sub: 'vendite & mix' },
      { name: 'Personale', sub: 'team & costo' },
      { name: 'Magazzino', sub: 'scorte & sprechi' },
      { name: 'Marketing', sub: 'reach & ROI' },
      { name: 'Clienti', sub: 'CRM & fedeltà' },
      { name: 'Prossima mossa', sub: 'cosa fare ora' },
    ],
  },
  pl: {
    headline: 'Odzyskaj marżę.',
    tagline: 'Udowodnij, co zadziałało.',
    eyebrow: 'Platforma decision intelligence dla operatorów wielolokalizacyjnych',
    sub: 'Sundae łączy się z systemami, których już używasz - znajduje marżę traconą w przychodach, pracy, zapasach i gościach - a potem przypisuje każdą szansę jednej osobie i mierzy, ile wróciło.',
    cta: 'Umów demo',
    layers: [
      { name: 'Fundament', sub: 'topologia org' },
      { name: 'Przychód', sub: 'sprzedaż i miks' },
      { name: 'Kadry', sub: 'zespół i koszt' },
      { name: 'Magazyn', sub: 'zapas i strata' },
      { name: 'Marketing', sub: 'zasięg i ROI' },
      { name: 'Goście', sub: 'CRM i lojalność' },
      { name: 'Następny ruch', sub: 'co robić teraz' },
    ],
  },
  tr: {
    headline: 'Kârı geri kazanın.',
    tagline: 'Neyin işe yaradığını kanıtlayın.',
    eyebrow: 'Çok şubeli işletmeciler için decision intelligence platformu',
    sub: 'Sundae hâlihazırda kullandığınız sistemlere bağlanır - ciro, işgücü, stok ve misafir tarafında sızan kârı bulur - sonra her fırsata tek bir sorumlu atar ve ne kadarının geri geldiğini ölçer.',
    cta: 'Demo planlayın',
    layers: [
      { name: 'Temel', sub: 'org topolojisi' },
      { name: 'Gelir', sub: 'satış & mix' },
      { name: 'Personel', sub: 'ekip & maliyet' },
      { name: 'Envanter', sub: 'stok & fire' },
      { name: 'Pazarlama', sub: 'erişim & ROI' },
      { name: 'Misafirler', sub: 'CRM & sadakat' },
      { name: 'Sonraki adım', sub: 'şimdi ne yapmalı' },
    ],
  },
  'zh-Hans': {
    headline: '把利润追回来。',
    tagline: '并证明什么真正奏效。',
    eyebrow: '面向多门店运营者的决策智能平台',
    sub: 'Sundae 接入你已在使用的系统，找出在营收、人力、库存与客户环节流失的利润，为每一个机会指定唯一负责人，并衡量真正追回了多少。',
    cta: '预约演示',
    layers: [
      { name: '根基', sub: '组织拓扑' },
      { name: '营收', sub: '销售与结构' },
      { name: '用工', sub: '团队与成本' },
      { name: '库存', sub: '库存与损耗' },
      { name: '营销', sub: '触达与 ROI' },
      { name: '客人', sub: 'CRM 与忠诚' },
      { name: '下一步', sub: '现在该做什么' },
    ],
  },
  ja: {
    headline: '利益を取り戻す。',
    tagline: '効果を証明する。',
    eyebrow: '多店舗オペレーター向けの意思決定インテリジェンス・プラットフォーム',
    sub: 'Sundae は既存のシステムに接続し、売上、人件費、在庫、顧客の各領域で漏れている利益を見つけ、機会ごとに担当者を一人定め、実際に戻った金額を測定します。',
    cta: 'デモを予約',
    layers: [
      { name: '基盤', sub: '組織トポロジー' },
      { name: '売上', sub: '販売とミックス' },
      { name: '労務', sub: '人員とコスト' },
      { name: '在庫', sub: '在庫とロス' },
      { name: 'マーケ', sub: 'リーチと ROI' },
      { name: 'ゲスト', sub: 'CRM とロイヤルティ' },
      { name: '次の一手', sub: '今すべきこと' },
    ],
  },
  ko: {
    headline: '이익을 되찾으세요.',
    tagline: '무엇이 효과가 있었는지 증명하세요.',
    eyebrow: '다점포 운영자를 위한 의사결정 인텔리전스 플랫폼',
    sub: 'Sundae는 이미 사용 중인 시스템에 연결해 매출, 인건비, 재고, 고객에서 새는 이익을 찾아내고, 기회마다 담당자를 한 명씩 지정하며, 실제로 얼마가 돌아왔는지 측정합니다.',
    cta: '데모 예약',
    layers: [
      { name: '기반', sub: '조직 구조' },
      { name: '매출', sub: '판매와 구성' },
      { name: '인력', sub: '팀과 비용' },
      { name: '재고', sub: '재고와 손실' },
      { name: '마케팅', sub: '도달과 ROI' },
      { name: '고객', sub: 'CRM과 충성도' },
      { name: '다음 수', sub: '지금 할 일' },
    ],
  },
  id: {
    headline: 'Rebut kembali laba Anda.',
    tagline: 'Lalu buktikan apa yang berhasil.',
    eyebrow: 'Platform decision intelligence untuk operator multi-lokasi',
    sub: 'Sundae terhubung ke sistem yang sudah Anda pakai - menemukan laba yang bocor di pendapatan, tenaga kerja, persediaan dan tamu - lalu memberi satu penanggung jawab bagi tiap peluang dan mengukur berapa yang kembali.',
    cta: 'Pesan demo',
    layers: [
      { name: 'Fondasi', sub: 'topologi org' },
      { name: 'Pendapatan', sub: 'penjualan & mix' },
      { name: 'Tenaga kerja', sub: 'tim & biaya' },
      { name: 'Inventaris', sub: 'stok & susut' },
      { name: 'Pemasaran', sub: 'jangkauan & ROI' },
      { name: 'Tamu', sub: 'CRM & loyalitas' },
      { name: 'Langkah berikutnya', sub: 'apa yang harus dilakukan' },
    ],
  },
  vi: {
    headline: 'Thu hồi lợi nhuận.',
    tagline: 'Và chứng minh điều gì hiệu quả.',
    eyebrow: 'Nền tảng decision intelligence cho nhà điều hành nhiều chi nhánh',
    sub: 'Sundae kết nối các hệ thống bạn đang dùng - tìm ra lợi nhuận thất thoát ở doanh thu, nhân công, tồn kho và khách hàng - rồi giao mỗi cơ hội cho một người chịu trách nhiệm và đo phần thu về.',
    cta: 'Đặt demo',
    layers: [
      { name: 'Nền tảng', sub: 'sơ đồ tổ chức' },
      { name: 'Doanh thu', sub: 'bán hàng & cơ cấu' },
      { name: 'Nhân sự', sub: 'đội & chi phí' },
      { name: 'Tồn kho', sub: 'tồn & hao hụt' },
      { name: 'Marketing', sub: 'tiếp cận & ROI' },
      { name: 'Khách', sub: 'CRM & trung thành' },
      { name: 'Bước tiếp theo', sub: 'làm gì bây giờ' },
    ],
  },
  ro: {
    headline: 'Recuperează marja.',
    tagline: 'Dovedește ce a funcționat.',
    eyebrow: 'Platforma de decision intelligence pentru operatori multi-locație',
    sub: 'Sundae se conectează la sistemele pe care le folosești deja - găsește marja pierdută în vânzări, forță de muncă, stocuri și oaspeți - apoi atribuie fiecare oportunitate unui responsabil și măsoară cât s-a recuperat.',
    cta: 'Programează un demo',
    layers: [
      { name: 'Fundație', sub: 'topologie org' },
      { name: 'Venit', sub: 'vânzări & mix' },
      { name: 'Personal', sub: 'echipă & cost' },
      { name: 'Stocuri', sub: 'stoc & pierderi' },
      { name: 'Marketing', sub: 'acoperire & ROI' },
      { name: 'Clienți', sub: 'CRM & loialitate' },
      { name: 'Următoarea mișcare', sub: 'ce faci acum' },
    ],
  },
  sv: {
    headline: 'Ta tillbaka marginalen.',
    tagline: 'Bevisa vad som fungerade.',
    eyebrow: 'Plattformen för decision intelligence för operatörer med flera enheter',
    sub: 'Sundae kopplar ihop systemen ni redan använder - hittar marginalen som läcker i försäljning, personal, lager och gäster - och ger varje möjlighet en ansvarig och mäter vad som kom tillbaka.',
    cta: 'Boka en demo',
    layers: [
      { name: 'Grund', sub: 'org-topologi' },
      { name: 'Intäkter', sub: 'försäljning & mix' },
      { name: 'Personal', sub: 'team & kostnad' },
      { name: 'Lager', sub: 'lager & svinn' },
      { name: 'Marknad', sub: 'räckvidd & ROI' },
      { name: 'Gäster', sub: 'CRM & lojalitet' },
      { name: 'Nästa drag', sub: 'vad du gör nu' },
    ],
  },
  bn: {
    headline: 'মুনাফা ফিরিয়ে আনুন।',
    tagline: 'আর প্রমাণ করুন কী কাজ করেছে।',
    eyebrow: 'মাল্টি-লোকেশন অপারেটরদের জন্য ডিসিশন ইন্টেলিজেন্স প্ল্যাটফর্ম',
    sub: 'Sundae আপনার বিদ্যমান সিস্টেমের সঙ্গে যুক্ত হয় - রাজস্ব, শ্রম, ইনভেন্টরি ও অতিথিদের মধ্যে বেরিয়ে যাওয়া মুনাফা খুঁজে বের করে - তারপর প্রতিটি সুযোগে একজন দায়িত্বপ্রাপ্ত দিয়ে মাপে কতটা ফিরে এল।',
    cta: 'ডেমো বুক করুন',
    layers: [
      { name: 'ভিত্তি', sub: 'অর্গ টপোলজি' },
      { name: 'রাজস্ব', sub: 'বিক্রি ও মিক্স' },
      { name: 'কর্মী', sub: 'টিম ও খরচ' },
      { name: 'ইনভেন্টরি', sub: 'স্টক ও অপচয়' },
      { name: 'মার্কেটিং', sub: 'নাগাল ও ROI' },
      { name: 'অতিথি', sub: 'CRM ও আনুগত্য' },
      { name: 'পরের পদক্ষেপ', sub: 'এখন কী করবেন' },
    ],
  },
  th: {
    headline: 'ดึงกำไรกลับคืนมา',
    tagline: 'และพิสูจน์ว่าอะไรได้ผล',
    eyebrow: 'แพลตฟอร์ม decision intelligence สำหรับผู้ดำเนินการหลายสาขา',
    sub: 'Sundae เชื่อมต่อกับระบบที่คุณใช้อยู่แล้ว - ค้นหากำไรที่รั่วไหลในรายได้ แรงงาน สินค้าคงคลัง และลูกค้า - แล้วมอบผู้รับผิดชอบหนึ่งคนต่อหนึ่งโอกาส และวัดว่ากลับคืนมาเท่าใด',
    cta: 'จองเดโม',
    layers: [
      { name: 'รากฐาน', sub: 'โครงสร้างองค์กร' },
      { name: 'รายได้', sub: 'ยอดขายและสัดส่วน' },
      { name: 'แรงงาน', sub: 'ทีมและต้นทุน' },
      { name: 'สินค้าคงคลัง', sub: 'สต๊อกและการสูญเสีย' },
      { name: 'การตลาด', sub: 'การเข้าถึงและ ROI' },
      { name: 'ลูกค้า', sub: 'CRM และความภักดี' },
      { name: 'ก้าวต่อไป', sub: 'ตอนนี้ควรทำอะไร' },
    ],
  },
  ms: {
    headline: 'Dapatkan semula keuntungan.',
    tagline: 'Buktikan apa yang berkesan.',
    eyebrow: 'Platform decision intelligence untuk pengendali berbilang lokasi',
    sub: 'Sundae menyambung sistem yang anda sudah guna - mengesan keuntungan yang bocor pada hasil, tenaga kerja, inventori dan tetamu - lalu memberikan satu penanggungjawab bagi setiap peluang dan mengukur berapa yang kembali.',
    cta: 'Tempah demo',
    layers: [
      { name: 'Asas', sub: 'topologi org' },
      { name: 'Hasil', sub: 'jualan & mix' },
      { name: 'Tenaga kerja', sub: 'pasukan & kos' },
      { name: 'Inventori', sub: 'stok & susut' },
      { name: 'Pemasaran', sub: 'jangkauan & ROI' },
      { name: 'Tetamu', sub: 'CRM & kesetiaan' },
      { name: 'Langkah seterusnya', sub: 'apa nak buat sekarang' },
    ],
  },
};
