import type { WebsiteLocale } from '@/lib/i18n';

/**
 * Copy for the signature "Watch the night turn" interaction - a scrubbable
 * service-night timeline that makes Sundae's whole thesis tangible: the signal
 * arrives at 7:15, while the shift is still yours to change, not in tomorrow's
 * report. It is the interactive proof of the manifesto + operator-voice copy.
 *
 * Same locale-keyed-with-en-fallback pattern as the other self-contained
 * homepage copy maps (outside the validated `messages` tree). Dash house-style:
 * spaced ASCII hyphen " - ", no em-dashes.
 */
export type ShiftMomentCopy = {
  eyebrow: string;
  heading: string;
  sub: string;
  frameLabel: string;
  withSundae: string;
  oldWay: string;
  paceLabel: string;
  coversLabel: string;
  laborLabel: string;
  forecastLabel: string;
  actualLabel: string;
  scrubHint: string;
  scrubAria: string;
  preSignal: string;
  signalTitle: string;
  signalBody: string;
  signalAction: string;
  oldTitle: string;
  oldBody: string;
  oldAction: string;
  /** Outcome copy shown near close (optional; falls back to English). */
  savedTitle?: string;
  savedBody?: string;
  projectedClose?: string;
};

export const shiftMomentCopy: Record<WebsiteLocale, ShiftMomentCopy> = {
  en: {
    eyebrow: 'Catch the leak turning.',
    heading: 'The leak shows at 7:15 - while the margin is still recoverable.',
    sub: 'Drag through a real service night. The old way, you read the loss tomorrow. With Sundae, you catch it at 7:15 - in time to fix it and measure the margin back.',
    frameLabel: 'Pulse - Live Shift',
    withSundae: 'With Sundae',
    oldWay: 'The old way',
    paceLabel: 'vs forecast pace',
    coversLabel: 'Covers / hr',
    laborLabel: 'Labor',
    forecastLabel: 'Forecast',
    actualLabel: 'Actual',
    scrubHint: 'Drag to scrub the night',
    scrubAria: 'Service-night timeline from 5 PM to close. Use the arrow keys to move through the evening.',
    preSignal: 'Service is on pace. Keep scrubbing toward 7:15.',
    signalTitle: 'Signal - 7:15 PM',
    signalBody: 'Section 3 is dragging. Covers are behind pace and labor is climbing past 30%. Move one server off prep now - and the margin is still recoverable.',
    signalAction: 'Own the fix now.',
    oldTitle: 'Tomorrow, 11:00 AM',
    oldBody: 'Last night ran behind pace in Section 3 and labor closed high. You are reading this now. The margin is already gone.',
    oldAction: 'Too late to recover anything.',
    savedTitle: 'Margin recovered',
    savedBody: 'Covers recovered to within a few points of forecast and labor came back on target - the recovery measured against forecast, because you caught Section 3 at 7:15.',
    projectedClose: 'Projected close',
  },
  ar: {
    eyebrow: 'تدارَك التسرّب وهو يتكوّن.',
    heading: 'التسرّب يظهر عند السابعة وربع - والهامش ما زال قابلاً للاسترداد.',
    sub: 'مرّر عبر ليلة خدمة حقيقية. بالطريقة القديمة تقرأ الخسارة غدًا. مع Sundae تلتقطها عند السابعة وربع - في الوقت المناسب لإصلاحها وقياس الهامش المستعاد.',
    frameLabel: 'Pulse - وردية مباشرة',
    withSundae: 'مع Sundae',
    oldWay: 'الطريقة القديمة',
    paceLabel: 'مقارنةً بالوتيرة المتوقعة',
    coversLabel: 'ضيوف / ساعة',
    laborLabel: 'العمالة',
    forecastLabel: 'المتوقع',
    actualLabel: 'الفعلي',
    scrubHint: 'اسحب لتتنقّل عبر الليلة',
    scrubAria: 'مخطّط زمني لليلة الخدمة من السابعة مساءً حتى الإغلاق. استخدم مفاتيح الأسهم للتنقّل عبر المساء.',
    preSignal: 'الخدمة على الوتيرة. واصل التمرير نحو السابعة وربع.',
    signalTitle: 'إشارة - 7:15 مساءً',
    signalBody: 'القسم 3 يتباطأ. الضيوف دون الوتيرة والعمالة تتجاوز 30%. انقل نادلًا من التحضير الآن - والهامش ما زال قابلاً للاسترداد.',
    signalAction: 'تولَّ الإصلاح الآن.',
    oldTitle: 'غدًا، 11:00 صباحًا',
    oldBody: 'الليلة الماضية جرت دون الوتيرة في القسم 3 وأغلقت العمالة مرتفعة. أنت تقرأ هذا الآن. والهامش قد ضاع بالفعل.',
    oldAction: 'فات الأوان على استرداد أي شيء.',
    savedTitle: 'تم استرداد الهامش',
    savedBody: 'تعافى عدد الضيوف ليقترب من المتوقع ببضع نقاط وعادت العمالة إلى هدفها - والاسترداد مقيسٌ مقابل المتوقع، لأنك تداركت القسم 3 عند السابعة وربع.',
    projectedClose: 'الإغلاق المتوقع',
  },
  fr: {
    eyebrow: 'Saisissez la fuite au moment où elle démarre.',
    heading: 'La fuite apparaît à 19 h 15 - tant que la marge est encore récupérable.',
    sub: "Parcourez une vraie soirée de service. À l'ancienne, vous lisez la perte demain. Avec Sundae, vous la saisissez à 19 h 15 - à temps pour la corriger et mesurer la marge récupérée.",
    frameLabel: 'Pulse - Service en direct',
    withSundae: 'Avec Sundae',
    oldWay: "À l'ancienne",
    paceLabel: 'vs cadence prévue',
    coversLabel: 'Couverts / h',
    laborLabel: "Main-d'œuvre",
    forecastLabel: 'Prévu',
    actualLabel: 'Réel',
    scrubHint: 'Glissez pour parcourir la soirée',
    scrubAria: "Frise de la soirée de service, de 19 h à la fermeture. Utilisez les flèches pour parcourir la soirée.",
    preSignal: 'Le service tient la cadence. Continuez jusqu’à 19 h 15.',
    signalTitle: 'Signal - 19 h 15',
    signalBody: "La salle 3 décroche. Les couverts sont en retard et la main-d'œuvre dépasse 30%. Sortez un serveur du prep maintenant - et la marge est encore récupérable.",
    signalAction: "Prenez la correction en main.",
    oldTitle: 'Demain, 11 h 00',
    oldBody: "Hier soir, la salle 3 a décroché et la main-d'œuvre a fini haut. Vous le lisez maintenant. La marge est déjà partie.",
    oldAction: 'Trop tard pour récupérer quoi que ce soit.',
    savedTitle: 'Marge récupérée',
    savedBody: "Les couverts sont revenus à quelques points de la prévision et la main-d'œuvre est repassée sur l'objectif - la reprise mesurée par rapport à la prévision, parce que vous avez rattrapé la salle 3 à 19 h 15.",
    projectedClose: 'Clôture prévue',
  },
  es: {
    eyebrow: 'Atrapa la fuga cuando empieza.',
    heading: 'La fuga aparece a las 7:15 - cuando el margen todavía es recuperable.',
    sub: 'Recorre una noche de servicio real. A la antigua, lees la pérdida mañana. Con Sundae, la atrapas a las 7:15 - a tiempo para corregirla y medir el margen recuperado.',
    frameLabel: 'Pulse - Turno en vivo',
    withSundae: 'Con Sundae',
    oldWay: 'A la antigua',
    paceLabel: 'vs ritmo previsto',
    coversLabel: 'Comensales / h',
    laborLabel: 'Personal',
    forecastLabel: 'Previsto',
    actualLabel: 'Real',
    scrubHint: 'Arrastra para recorrer la noche',
    scrubAria: 'Línea de tiempo de la noche de servicio, de 7 p. m. al cierre. Usa las flechas para avanzar por la noche.',
    preSignal: 'El servicio va a ritmo. Sigue avanzando hacia las 7:15.',
    signalTitle: 'Señal - 7:15 p. m.',
    signalBody: 'La sala 3 se está quedando atrás. Los comensales van por debajo del ritmo y el personal supera el 30%. Saca a un camarero del prep ahora - y el margen todavía es recuperable.',
    signalAction: 'Hazte cargo de la corrección ahora.',
    oldTitle: 'Mañana, 11:00 a. m.',
    oldBody: 'Anoche la sala 3 fue por debajo del ritmo y el personal cerró alto. Lo estás leyendo ahora. El margen ya se perdió.',
    oldAction: 'Demasiado tarde para recuperar nada.',
    savedTitle: 'Margen recuperado',
    savedBody: 'Los comensales se recuperaron hasta quedar a pocos puntos de lo previsto y el personal volvió al objetivo - la recuperación medida frente a lo previsto, porque atajaste la sala 3 a las 7:15.',
    projectedClose: 'Cierre previsto',
  },
  de: {
    eyebrow: 'Erwischen Sie das Leck, wenn es entsteht.',
    heading: 'Das Leck zeigt sich um 19:15 Uhr - solange die Marge noch rückholbar ist.',
    sub: 'Ziehen Sie sich durch einen echten Serviceabend. Früher lasen Sie den Verlust erst morgen. Mit Sundae erwischen Sie ihn um 19:15 Uhr - rechtzeitig, um ihn zu beheben und die zurückgeholte Marge zu messen.',
    frameLabel: 'Pulse - Schicht live',
    withSundae: 'Mit Sundae',
    oldWay: 'Der alte Weg',
    paceLabel: 'vs. Prognosetempo',
    coversLabel: 'Gedecke / Std.',
    laborLabel: 'Personal',
    forecastLabel: 'Prognose',
    actualLabel: 'Ist',
    scrubHint: 'Ziehen, um durch den Abend zu scrubben',
    scrubAria: 'Zeitstrahl des Serviceabends von 17 Uhr bis Betriebsschluss. Bewegen Sie sich mit den Pfeiltasten durch den Abend.',
    preSignal: 'Der Service liegt im Tempo. Scrubben Sie weiter Richtung 19:15 Uhr.',
    signalTitle: 'Signal - 19:15 Uhr',
    signalBody: 'Bereich 3 hängt zurück. Die Gedecke liegen hinter dem Tempo und das Personal klettert über 30%. Holen Sie jetzt einen Servicemitarbeiter aus der Vorbereitung - und die Marge ist noch rückholbar.',
    signalAction: 'Übernehmen Sie jetzt die Korrektur.',
    oldTitle: 'Morgen, 11 Uhr',
    oldBody: 'Gestern Abend lag Bereich 3 hinter dem Tempo und das Personal schloss hoch ab. Sie lesen das jetzt. Die Marge ist bereits weg.',
    oldAction: 'Zu spät, um noch etwas zurückzuholen.',
    savedTitle: 'Marge zurückgeholt',
    savedBody: 'Die Gedecke erholten sich bis auf wenige Punkte an die Prognose und das Personal kam wieder auf Kurs - die Erholung gemessen an der Prognose, weil Sie Bereich 3 um 19:15 Uhr erwischt haben.',
    projectedClose: 'Voraussichtlicher Abschluss',
  },
  nl: {
    eyebrow: 'Vang het lek op het moment dat het ontstaat.',
    heading: 'Het lek verschijnt om 19.15 uur - terwijl de marge nog terug te halen is.',
    sub: 'Sleep door een echte serviceavond. Vroeger las u het verlies pas morgen. Met Sundae vangt u het om 19.15 uur - op tijd om het te herstellen en de teruggehaalde marge te meten.',
    frameLabel: 'Pulse - Dienst live',
    withSundae: 'Met Sundae',
    oldWay: 'De oude manier',
    paceLabel: 'vs. verwacht tempo',
    coversLabel: 'Couverts / uur',
    laborLabel: 'Personeel',
    forecastLabel: 'Verwacht',
    actualLabel: 'Werkelijk',
    scrubHint: 'Sleep om door de avond te scrubben',
    scrubAria: 'Tijdlijn van de serviceavond, van 17.00 uur tot sluiting. Gebruik de pijltjestoetsen om door de avond te bewegen.',
    preSignal: 'De service ligt op tempo. Blijf scrubben richting 19.15 uur.',
    signalTitle: 'Signaal - 19.15 uur',
    signalBody: 'Zone 3 blijft achter. De couverts lopen achter op het tempo en het personeel klimt boven de 30%. Haal nu één bediende uit de mise-en-place - en de marge is nog terug te halen.',
    signalAction: 'Neem de correctie nu op u.',
    oldTitle: 'Morgen, 11.00 uur',
    oldBody: 'Gisteravond liep zone 3 achter op het tempo en sloot het personeel hoog. U leest dit nu. De marge is al weg.',
    oldAction: 'Te laat om nog iets terug te halen.',
    savedTitle: 'Marge teruggehaald',
    savedBody: 'De couverts kwamen terug tot op een paar punten van de prognose en het personeel kwam weer op koers - het herstel gemeten tegen de prognose, omdat u zone 3 om 19.15 uur opving.',
    projectedClose: 'Verwachte afsluiting',
  },
  pt: {
    eyebrow: 'Capture a fuga quando ela começa.',
    heading: 'A fuga aparece às 19h15 - enquanto a margem ainda é recuperável.',
    sub: 'Percorra uma noite de serviço real. Do jeito antigo, você lê a perda amanhã. Com o Sundae, você a captura às 19h15 - a tempo de corrigi-la e medir a margem recuperada.',
    frameLabel: 'Pulse - Turno ao vivo',
    withSundae: 'Com o Sundae',
    oldWay: 'Do jeito antigo',
    paceLabel: 'vs. ritmo previsto',
    coversLabel: 'Clientes / h',
    laborLabel: 'Mão de obra',
    forecastLabel: 'Previsto',
    actualLabel: 'Real',
    scrubHint: 'Arraste para percorrer a noite',
    scrubAria: 'Linha do tempo da noite de serviço, das 17h ao fechamento. Use as setas para avançar pela noite.',
    preSignal: 'O serviço está no ritmo. Continue avançando até as 19h15.',
    signalTitle: 'Sinal - 19h15',
    signalBody: 'A sala 3 está atrasando. Os clientes estão abaixo do ritmo e a mão de obra passa de 30%. Tire um garçom da praça agora - e a margem ainda é recuperável.',
    signalAction: 'Assuma a correção agora.',
    oldTitle: 'Amanhã, 11h00',
    oldBody: 'Ontem à noite a sala 3 ficou abaixo do ritmo e a mão de obra fechou alta. Você está lendo isto agora. A margem já se perdeu.',
    oldAction: 'Tarde demais para recuperar qualquer coisa.',
    savedTitle: 'Margem recuperada',
    savedBody: 'Os clientes se recuperaram para poucos pontos da previsão e a mão de obra voltou à meta - a recuperação medida contra a previsão, porque você pegou a sala 3 às 19h15.',
    projectedClose: 'Fechamento previsto',
  },
  hi: {
    eyebrow: 'रिसाव को बनते ही थाम लीजिए।',
    heading: 'रिसाव शाम 7:15 पर दिखता है - जब मार्जिन अब भी वापस पाया जा सकता है।',
    sub: 'एक असली सर्विस की रात में से गुज़रिए। पुराने तरीके में, आप नुक़सान कल पढ़ते हैं। Sundae के साथ, आप इसे शाम 7:15 बजे थाम लेते हैं - इसे ठीक करने और वापस आए मार्जिन को मापने का वक़्त रहते।',
    frameLabel: 'Pulse - लाइव शिफ्ट',
    withSundae: 'Sundae के साथ',
    oldWay: 'पुराना तरीका',
    paceLabel: 'अनुमानित रफ्तार बनाम',
    coversLabel: 'मेहमान / घंटा',
    laborLabel: 'स्टाफ',
    forecastLabel: 'अनुमान',
    actualLabel: 'वास्तविक',
    scrubHint: 'रात में से गुज़रने के लिए खींचें',
    scrubAria: 'सर्विस की रात की समयरेखा, शाम 5 बजे से बंद होने तक। शाम भर आगे बढ़ने के लिए ऐरो कुंजियों का उपयोग करें।',
    preSignal: 'सर्विस रफ्तार पर है। 7:15 की ओर खींचते रहिए।',
    signalTitle: 'सिग्नल - शाम 7:15',
    signalBody: 'सेक्शन 3 पिछड़ रहा है। मेहमान रफ्तार से पीछे हैं और स्टाफ खर्च 30% पार कर रहा है। एक वेटर को प्रेप से अभी हटाइए - और मार्जिन अब भी वापस पाया जा सकता है।',
    signalAction: 'फ़िक्स की ज़िम्मेदारी अभी लीजिए।',
    oldTitle: 'कल, सुबह 11:00',
    oldBody: 'कल रात सेक्शन 3 रफ्तार से पीछे रहा और स्टाफ खर्च ऊँचा बंद हुआ। आप यह अभी पढ़ रहे हैं। मार्जिन तो जा चुका।',
    oldAction: 'अब कुछ भी वापस पाने के लिए बहुत देर हो चुकी।',
    savedTitle: 'मार्जिन वापस आया',
    savedBody: 'मेहमानों की संख्या अनुमान से कुछ ही अंक दूर तक संभल गई और स्टाफ खर्च फिर लक्ष्य पर लौट आया - रिकवरी अनुमान के मुक़ाबले मापी गई, क्योंकि आपने सेक्शन 3 को शाम 7:15 बजे थाम लिया।',
    projectedClose: 'अनुमानित समापन',
  },
  ur: {
    eyebrow: 'رساؤ کو بنتے ہی تھام لیں۔',
    heading: 'رساؤ شام 7:15 پر ظاہر ہوتا ہے - جب مارجن اب بھی واپس پایا جا سکتا ہے۔',
    sub: 'ایک حقیقی سروس کی رات میں سے گزریے۔ پرانے طریقے میں، آپ نقصان کل پڑھتے ہیں۔ Sundae کے ساتھ، آپ اسے شام 7:15 بجے تھام لیتے ہیں - اسے درست کرنے اور واپس آئے مارجن کو ناپنے کا وقت رہتے۔',
    frameLabel: 'Pulse - لائیو شفٹ',
    withSundae: 'Sundae کے ساتھ',
    oldWay: 'پرانا طریقہ',
    paceLabel: 'متوقع رفتار کے مقابلے',
    coversLabel: 'مہمان / گھنٹہ',
    laborLabel: 'عملہ',
    forecastLabel: 'متوقع',
    actualLabel: 'حقیقی',
    scrubHint: 'رات میں سے گزرنے کے لیے کھینچیں',
    scrubAria: 'سروس کی رات کی ٹائم لائن، شام 5 بجے سے بندش تک۔ شام بھر آگے بڑھنے کے لیے ایرو کیز استعمال کریں۔',
    preSignal: 'سروس رفتار پر ہے۔ 7:15 کی طرف کھینچتے رہیں۔',
    signalTitle: 'سگنل - شام 7:15',
    signalBody: 'سیکشن 3 پیچھے رہ رہا ہے۔ مہمان رفتار سے پیچھے ہیں اور عملے کا خرچ 30% سے تجاوز کر رہا ہے۔ ایک ویٹر کو تیاری سے ابھی ہٹائیں - اور مارجن اب بھی واپس پایا جا سکتا ہے۔',
    signalAction: 'اصلاح کی ذمہ داری ابھی لیں۔',
    oldTitle: 'کل، صبح 11:00',
    oldBody: 'کل رات سیکشن 3 رفتار سے پیچھے رہا اور عملے کا خرچ بلند بند ہوا۔ آپ یہ اب پڑھ رہے ہیں۔ مارجن تو جا چکا۔',
    oldAction: 'اب کچھ بھی واپس پانے کے لیے بہت دیر ہو چکی۔',
    savedTitle: 'مارجن واپس آ گیا',
    savedBody: 'مہمانوں کی تعداد سنبھل کر پیش گوئی سے چند پوائنٹ کے فاصلے پر آ گئی اور عملے کا خرچ دوبارہ ہدف پر لوٹ آیا - ریکوری پیش گوئی کے مقابلے میں ناپی گئی، کیونکہ آپ نے سیکشن 3 کو شام 7:15 بجے تھام لیا۔',
    projectedClose: 'متوقع اختتام',
  },
  it: {
    eyebrow: 'Cogli la perdita nel momento in cui parte.',
    heading: 'La perdita si vede alle 19:15 - finché il margine è ancora recuperabile.',
    sub: 'Scorri una vera serata di servizio. Alla vecchia maniera, leggi la perdita domani. Con Sundae la cogli alle 19:15 - in tempo per correggerla e misurare il margine recuperato.',
    frameLabel: 'Pulse - Turno dal vivo',
    withSundae: 'Con Sundae',
    oldWay: 'Alla vecchia maniera',
    paceLabel: 'vs ritmo previsto',
    coversLabel: 'Coperti / h',
    laborLabel: 'Personale',
    forecastLabel: 'Previsto',
    actualLabel: 'Reale',
    scrubHint: 'Trascina per scorrere la serata',
    scrubAria: 'Linea temporale della serata di servizio, dalle 17 alla chiusura. Usa i tasti freccia per muoverti nella serata.',
    preSignal: 'Il servizio tiene il ritmo. Continua a scorrere verso le 19:15.',
    signalTitle: 'Segnale - 19:15',
    signalBody: "La sala 3 sta rallentando. I coperti sono sotto ritmo e il personale supera il 30%. Sposta subito un cameriere dalla preparazione - e il margine è ancora recuperabile.",
    signalAction: "Prendi in carico la correzione ora.",
    oldTitle: 'Domani, 11:00',
    oldBody: 'Ieri sera la sala 3 è andata sotto ritmo e il personale ha chiuso alto. Lo stai leggendo adesso. Il margine è già perso.',
    oldAction: 'Troppo tardi per recuperare qualcosa.',
    savedTitle: 'Margine recuperato',
    savedBody: 'I coperti sono risaliti a pochi punti dalla previsione e il personale è tornato in linea - il recupero misurato rispetto alla previsione, perché hai colto la sala 3 alle 19:15.',
    projectedClose: 'Chiusura prevista',
  },
  pl: {
    eyebrow: 'Uchwyć wyciek w chwili, gdy się zaczyna.',
    heading: 'Wyciek widać o 19:15 - póki marża wciąż jest do odzyskania.',
    sub: 'Przewiń przez prawdziwy wieczór serwisu. Po staremu czytasz stratę jutro. Z Sundae łapiesz ją o 19:15 - w porę, by ją naprawić i zmierzyć odzyskaną marżę.',
    frameLabel: 'Pulse - Zmiana na żywo',
    withSundae: 'Z Sundae',
    oldWay: 'Po staremu',
    paceLabel: 'vs prognozowane tempo',
    coversLabel: 'Goście / godz.',
    laborLabel: 'Obsada',
    forecastLabel: 'Prognoza',
    actualLabel: 'Rzeczywiste',
    scrubHint: 'Przeciągnij, aby przewinąć wieczór',
    scrubAria: 'Oś czasu wieczoru serwisu, od 17 do zamknięcia. Użyj strzałek, aby przesuwać się przez wieczór.',
    preSignal: 'Serwis trzyma tempo. Przewijaj dalej w stronę 19:15.',
    signalTitle: 'Sygnał - 19:15',
    signalBody: 'Sala 3 zostaje w tyle. Goście są poniżej tempa, a obsada przekracza 30%. Zabierz teraz jednego kelnera z mise en place - i marża wciąż jest do odzyskania.',
    signalAction: 'Weź korektę na siebie teraz.',
    oldTitle: 'Jutro, 11:00',
    oldBody: 'Wczoraj wieczorem sala 3 była poniżej tempa, a obsada zamknęła się wysoko. Czytasz to teraz. Marża już przepadła.',
    oldAction: 'Za późno, by cokolwiek odzyskać.',
    savedTitle: 'Marża odzyskana',
    savedBody: 'Goście wrócili do kilku punktów od prognozy, a obsada znów weszła na cel - odzysk zmierzony względem prognozy, bo uchwyciłeś salę 3 o 19:15.',
    projectedClose: 'Prognozowane zamknięcie',
  },
  tr: {
    eyebrow: 'Sızıntıyı oluşurken yakalayın.',
    heading: 'Sızıntı 19.15’te belli olur - marj hâlâ geri kazanılabilirken.',
    sub: "Gerçek bir servis gecesini sürükleyerek gezin. Eski yöntemle kaybı yarın okursunuz. Sundae ile 19.15'te yakalarsınız - düzeltmeye ve geri kazanılan marjı ölçmeye tam vaktinde.",
    frameLabel: 'Pulse - Canlı vardiya',
    withSundae: 'Sundae ile',
    oldWay: 'Eski yöntem',
    paceLabel: 'tahmini tempoya karşı',
    coversLabel: 'Misafir / saat',
    laborLabel: 'İş gücü',
    forecastLabel: 'Tahmin',
    actualLabel: 'Gerçek',
    scrubHint: 'Geceyi taramak için sürükleyin',
    scrubAria: "Servis gecesinin zaman çizelgesi, akşam 17.00'den kapanışa kadar. Akşam boyunca ilerlemek için ok tuşlarını kullanın.",
    preSignal: "Servis tempoda. 19.15'e doğru taramaya devam edin.",
    signalTitle: 'Sinyal - 19.15',
    signalBody: 'Bölüm 3 geride kalıyor. Misafirler tempodan geride ve iş gücü %30’u aşıyor. Bir garsonu hazırlıktan şimdi alın - ve marj hâlâ geri kazanılabilir.',
    signalAction: 'Düzeltmeyi şimdi üstlenin.',
    oldTitle: 'Yarın, 11.00',
    oldBody: 'Dün gece Bölüm 3 tempodan geride kaldı ve iş gücü yüksek kapandı. Bunu şimdi okuyorsunuz. Marj çoktan gitti.',
    oldAction: 'Bir şeyi geri kazanmak için artık çok geç.',
    savedTitle: 'Marj geri kazanıldı',
    savedBody: "Misafirler tahminin birkaç puan yakınına dek toparlandı ve iş gücü yeniden hedefe döndü - toparlanma tahmine göre ölçüldü, çünkü Bölüm 3'ü 19.15'te yakaladınız.",
    projectedClose: 'Öngörülen kapanış',
  },
  'zh-Hans': {
    eyebrow: '在泄漏成形的那一刻抓住它。',
    heading: '泄漏在 19:15 显现--此时利润还追得回来。',
    sub: '拖动浏览一个真实的服务之夜。老办法下，你明天才读到这笔损失。有了 Sundae，你在 19:15 就抓住它--来得及修复，并把追回的利润测量出来。',
    frameLabel: 'Pulse--实时班次',
    withSundae: '有了 Sundae',
    oldWay: '老办法',
    paceLabel: '对比预测节奏',
    coversLabel: '客人 / 小时',
    laborLabel: '人力',
    forecastLabel: '预测',
    actualLabel: '实际',
    scrubHint: '拖动以浏览这一夜',
    scrubAria: '服务之夜时间轴，从下午 5 点到打烊。用方向键在整晚之间移动。',
    preSignal: '服务节奏正常。继续拖动到 19:15。',
    signalTitle: '信号--19:15',
    signalBody: '3 区慢下来了。客人落后于节奏，人力正爬过 30%。现在从备餐调一名服务员过去--此时利润还追得回来。',
    signalAction: '现在就接手这次修复。',
    oldTitle: '明天，上午 11:00',
    oldBody: '昨晚 3 区落后于节奏，人力收得偏高。你现在才读到。利润早已流失。',
    oldAction: '想追回什么都太迟了。',
    savedTitle: '利润已追回',
    savedBody: '客人数回升到与预测仅差几个点，人力也重新回到目标线--这次追回是对照预测测量出来的，因为你在 19:15 抓住了 3 区。',
    projectedClose: '预计收尾',
  },
  ja: {
    eyebrow: '漏れが生まれるその瞬間をつかむ。',
    heading: '漏れは19:15に現れる--利益がまだ取り戻せるうちに。',
    sub: '本物のサービスの夜をドラッグして辿る。これまでなら、その損失を読むのは明日。Sundae なら19:15につかまえる--直して、取り戻した利益を測るのに間に合う。',
    frameLabel: 'Pulse--ライブシフト',
    withSundae: 'Sundae なら',
    oldWay: 'これまでのやり方',
    paceLabel: '予測ペース比',
    coversLabel: '客数 / 時',
    laborLabel: '人件費',
    forecastLabel: '予測',
    actualLabel: '実績',
    scrubHint: 'ドラッグして夜を辿る',
    scrubAria: 'サービスの夜のタイムライン、17時から閉店まで。矢印キーで夜を進めます。',
    preSignal: 'サービスはペース通り。19:15に向けてドラッグを続けてください。',
    signalTitle: '信号--19:15',
    signalBody: '3番セクションが遅れています。客数はペースに届かず、人件費は30%を超えつつあります。今すぐ仕込みからサーバーを1人回してください--まだ利益は取り戻せます。',
    signalAction: 'いま、この是正を引き受ける。',
    oldTitle: '明日、午前11:00',
    oldBody: '昨夜は3番セクションがペースに届かず、人件費は高く閉まりました。あなたが読んでいるのは今。利益はもう失われています。',
    oldAction: 'もう何も取り戻せません。',
    savedTitle: '利益を取り戻した',
    savedBody: '客数は予測との差が数ポイントまで戻り、人件費も目標に戻りました--取り戻しは予測に照らして測られています。あなたが19:15に3番セクションをつかんだからです。',
    projectedClose: '着地見込み',
  },
  ko: {
    eyebrow: '새는 순간을 붙잡으세요.',
    heading: '누수는 오후 7시 15분에 드러납니다 - 마진을 아직 되찾을 수 있을 때.',
    sub: '진짜 서비스의 밤을 끌어서 살펴보세요. 예전 방식이라면 그 손실을 내일 읽습니다. Sundae와 함께라면 오후 7시 15분에 붙잡습니다 - 바로잡고 되찾은 마진을 측정할 시간을 두고.',
    frameLabel: 'Pulse - 실시간 근무',
    withSundae: 'Sundae와 함께',
    oldWay: '예전 방식',
    paceLabel: '예측 페이스 대비',
    coversLabel: '손님 / 시간',
    laborLabel: '인건비',
    forecastLabel: '예측',
    actualLabel: '실제',
    scrubHint: '끌어서 밤을 살펴보세요',
    scrubAria: '서비스의 밤 타임라인, 오후 5시부터 마감까지. 화살표 키로 저녁을 이동하세요.',
    preSignal: '서비스는 페이스대로입니다. 오후 7시 15분 쪽으로 계속 끌어보세요.',
    signalTitle: '신호 - 오후 7시 15분',
    signalBody: '3번 구역이 처지고 있습니다. 손님은 페이스보다 뒤처지고 인건비는 30%를 넘어서고 있습니다. 지금 준비조에서 서버 한 명을 빼세요 - 그리고 마진은 아직 되찾을 수 있습니다.',
    signalAction: '지금 이 수정을 맡으세요.',
    oldTitle: '내일, 오전 11:00',
    oldBody: '어젯밤 3번 구역이 페이스보다 뒤처졌고 인건비는 높게 마감됐습니다. 당신은 지금 이걸 읽습니다. 마진은 이미 사라졌습니다.',
    oldAction: '이제 무엇도 되찾기엔 너무 늦었습니다.',
    savedTitle: '마진을 되찾았습니다',
    savedBody: '손님 수는 예측과 몇 포인트 차이까지 회복됐고 인건비도 다시 목표로 돌아왔습니다 - 회복은 예측 대비로 측정됐습니다. 당신이 오후 7시 15분에 3번 구역을 붙잡았기 때문입니다.',
    projectedClose: '예상 마감',
  },
  id: {
    eyebrow: 'Tangkap kebocoran saat mulai terjadi.',
    heading: 'Kebocoran muncul pukul 19.15 - selagi margin masih bisa dipulihkan.',
    sub: 'Geser melewati malam servis yang sebenarnya. Cara lama, Anda membaca kerugiannya besok. Dengan Sundae, Anda menangkapnya pukul 19.15 - tepat waktu untuk memperbaikinya dan mengukur margin yang dipulihkan.',
    frameLabel: 'Pulse - Shift langsung',
    withSundae: 'Dengan Sundae',
    oldWay: 'Cara lama',
    paceLabel: 'vs tempo perkiraan',
    coversLabel: 'Tamu / jam',
    laborLabel: 'Tenaga kerja',
    forecastLabel: 'Perkiraan',
    actualLabel: 'Aktual',
    scrubHint: 'Geser untuk menelusuri malam',
    scrubAria: 'Garis waktu malam servis, dari pukul 5 sore hingga tutup. Gunakan tombol panah untuk bergerak sepanjang malam.',
    preSignal: 'Servis sesuai tempo. Terus geser menuju pukul 19.15.',
    signalTitle: 'Sinyal - 19.15',
    signalBody: 'Seksi 3 mulai tertinggal. Tamu di bawah tempo dan tenaga kerja menanjak melewati 30%. Pindahkan satu pelayan dari prep sekarang - dan margin masih bisa dipulihkan.',
    signalAction: 'Ambil alih perbaikannya sekarang.',
    oldTitle: 'Besok, pukul 11.00',
    oldBody: 'Tadi malam Seksi 3 berjalan di bawah tempo dan tenaga kerja tutup tinggi. Anda baru membacanya sekarang. Marginnya sudah hilang.',
    oldAction: 'Terlambat untuk memulihkan apa pun.',
    savedTitle: 'Margin dipulihkan',
    savedBody: 'Tamu pulih hingga beberapa poin dari perkiraan dan tenaga kerja kembali sesuai target - pemulihan diukur terhadap perkiraan, karena Anda menangkap Seksi 3 pukul 19.15.',
    projectedClose: 'Perkiraan penutupan',
  },
  vi: {
    eyebrow: 'Bắt lấy buổi tối ngay khi nó lật chiều.',
    heading: 'Tín hiệu đến khi ca làm vẫn còn là của bạn để xoay chuyển.',
    sub: 'Kéo qua một buổi tối phục vụ có thật. Theo cách cũ, bạn thấy câu chuyện vào ngày mai. Với Sundae, bạn thấy nó lúc 19:15 - với thời gian để hành động.',
    frameLabel: 'Pulse - Ca trực tiếp',
    withSundae: 'Với Sundae',
    oldWay: 'Cách cũ',
    paceLabel: 'so với nhịp dự báo',
    coversLabel: 'Khách / giờ',
    laborLabel: 'Nhân sự',
    forecastLabel: 'Dự báo',
    actualLabel: 'Thực tế',
    scrubHint: 'Kéo để lướt qua buổi tối',
    scrubAria: 'Dòng thời gian của buổi tối phục vụ, từ 5 giờ chiều đến giờ đóng cửa. Dùng các phím mũi tên để di chuyển qua buổi tối.',
    preSignal: 'Phục vụ đang đúng nhịp. Hãy tiếp tục kéo tới 19:15.',
    signalTitle: 'Tín hiệu - 19:15',
    signalBody: 'Khu 3 đang chậm lại. Lượt khách tụt sau nhịp và nhân sự đang vượt 30%. Điều một phục vụ rời khu sơ chế ngay - bạn vẫn còn cứu được buổi tối.',
    signalAction: 'Đây là thời điểm để hành động.',
    oldTitle: 'Ngày mai, 11:00 sáng',
    oldBody: 'Tối qua Khu 3 chạy chậm hơn nhịp và nhân sự đóng ca ở mức cao. Bây giờ bạn mới đọc điều này. Ca làm đã kết thúc từ lâu.',
    oldAction: 'Quá muộn để thay đổi bất cứ điều gì.',
    savedTitle: 'Đã cứu được buổi tối',
    savedBody: 'Lượt khách hồi về chỉ còn cách dự báo vài điểm và nhân sự trở lại đúng mục tiêu - vì bạn đã bắt được Khu 3 lúc 19:15.',
    projectedClose: 'Kết ca dự kiến',
  },
  ro: {
    eyebrow: 'Prinde seara chiar în clipa în care se întoarce.',
    heading: 'Semnalul ajunge cât timp tura e încă a ta de schimbat.',
    sub: 'Derulează printr-o seară de serviciu reală. Pe vremuri, vedeai povestea mâine. Cu Sundae, o vezi la 19:15 - cu timp ca să acționezi.',
    frameLabel: 'Pulse - Tură live',
    withSundae: 'Cu Sundae',
    oldWay: 'Pe vremuri',
    paceLabel: 'vs ritmul prognozat',
    coversLabel: 'Clienți / oră',
    laborLabel: 'Personal',
    forecastLabel: 'Prognoză',
    actualLabel: 'Real',
    scrubHint: 'Trage pentru a derula seara',
    scrubAria: 'Cronologia serii de serviciu, de la ora 17 până la închidere. Folosește tastele săgeți pentru a parcurge seara.',
    preSignal: 'Serviciul ține ritmul. Continuă să derulezi spre 19:15.',
    signalTitle: 'Semnal - 19:15',
    signalBody: 'Sala 3 rămâne în urmă. Clienții sunt sub ritm și personalul urcă peste 30%. Mută acum un ospătar de la preparare - încă poți salva seara.',
    signalAction: 'Acesta e momentul să acționezi.',
    oldTitle: 'Mâine, 11:00',
    oldBody: 'Aseară, Sala 3 a rămas sub ritm și personalul a închis sus. Citești asta abia acum. Tura s-a terminat demult.',
    oldAction: 'Prea târziu pentru a mai schimba ceva.',
    savedTitle: 'Seară salvată',
    savedBody: 'Clienții și-au revenit la câteva puncte de prognoză și personalul a revenit pe țintă - pentru că ai prins Sala 3 la 19:15.',
    projectedClose: 'Închidere estimată',
  },
  sv: {
    eyebrow: 'Fånga kvällen just när den vänder.',
    heading: 'Signalen kommer medan passet fortfarande är ditt att ändra.',
    sub: 'Dra dig genom en riktig servicekväll. Förr såg du historien i morgon. Med Sundae ser du den klockan 19.15 - med tid att agera.',
    frameLabel: 'Pulse - Pass live',
    withSundae: 'Med Sundae',
    oldWay: 'Det gamla sättet',
    paceLabel: 'mot prognostiserat tempo',
    coversLabel: 'Gäster / tim',
    laborLabel: 'Bemanning',
    forecastLabel: 'Prognos',
    actualLabel: 'Faktiskt',
    scrubHint: 'Dra för att skrubba genom kvällen',
    scrubAria: 'Tidslinje för servicekvällen, från klockan 17 till stängning. Använd piltangenterna för att röra dig genom kvällen.',
    preSignal: 'Servicen håller tempot. Fortsätt skrubba mot 19.15.',
    signalTitle: 'Signal - 19.15',
    signalBody: 'Sektion 3 släpar efter. Gästerna ligger efter tempot och bemanningen klättrar förbi 30%. Flytta en servitör från förberedelsen nu - du kan fortfarande rädda kvällen.',
    signalAction: 'Det här är ögonblicket att agera.',
    oldTitle: 'I morgon, 11.00',
    oldBody: 'I går kväll låg sektion 3 efter tempot och bemanningen stängde högt. Du läser det här nu. Passet är sedan länge över.',
    oldAction: 'För sent att ändra något.',
    savedTitle: 'Kvällen räddad',
    savedBody: 'Gästerna återhämtade sig till några punkter från prognosen och bemanningen kom tillbaka på mål - eftersom du fångade sektion 3 klockan 19.15.',
    projectedClose: 'Beräknad stängning',
  },
  bn: {
    eyebrow: 'রাত যেই মুহূর্তে ঘুরে যায়, ঠিক তখনই ধরুন।',
    heading: 'সিগন্যাল আসে যখন শিফট এখনও বদলানোর জন্য আপনার হাতে।',
    sub: 'একটি সত্যিকারের সার্ভিসের রাত টেনে দেখুন। পুরনো উপায়ে, আপনি গল্পটা কাল দেখেন। Sundae-র সঙ্গে, আপনি এটি সন্ধ্যা ৭:১৫-তে দেখেন - পদক্ষেপ নেওয়ার সময় হাতে রেখে।',
    frameLabel: 'Pulse - লাইভ শিফট',
    withSundae: 'Sundae-র সঙ্গে',
    oldWay: 'পুরনো উপায়',
    paceLabel: 'পূর্বাভাসিত গতির তুলনায়',
    coversLabel: 'অতিথি / ঘণ্টা',
    laborLabel: 'জনবল',
    forecastLabel: 'পূর্বাভাস',
    actualLabel: 'প্রকৃত',
    scrubHint: 'রাত জুড়ে চলতে টেনে নিন',
    scrubAria: 'সার্ভিসের রাতের সময়রেখা, বিকেল ৫টা থেকে বন্ধ হওয়া পর্যন্ত। সন্ধ্যা জুড়ে এগোতে অ্যারো কী ব্যবহার করুন।',
    preSignal: 'সার্ভিস গতিতে আছে। ৭:১৫-র দিকে টানতে থাকুন।',
    signalTitle: 'সিগন্যাল - সন্ধ্যা ৭:১৫',
    signalBody: 'সেকশন ৩ পিছিয়ে পড়ছে। অতিথিরা গতির পেছনে এবং জনবল খরচ ৩০% ছাড়িয়ে যাচ্ছে। এখনই প্রস্তুতি থেকে একজন ওয়েটারকে সরান - আপনি এখনও রাতটি বাঁচাতে পারেন।',
    signalAction: 'এখনই পদক্ষেপ নেওয়ার মুহূর্ত।',
    oldTitle: 'আগামীকাল, সকাল ১১:০০',
    oldBody: 'গতকাল রাতে সেকশন ৩ গতির পেছনে চলল এবং জনবল খরচ উঁচুতে শেষ হলো। আপনি এটি এখন পড়ছেন। শিফট তো কবেই শেষ।',
    oldAction: 'এখন কিছু বদলানোর জন্য অনেক দেরি।',
    savedTitle: 'রাত বেঁচে গেল',
    savedBody: 'অতিথির সংখ্যা সামলে পূর্বাভাস থেকে মাত্র কয়েক পয়েন্ট দূরত্বে ফিরে এল এবং জনবল খরচ আবার লক্ষ্যে নেমে এল - কারণ আপনি সেকশন ৩-কে সন্ধ্যা ৭:১৫-তে ধরেছিলেন।',
    projectedClose: 'প্রত্যাশিত সমাপ্তি',
  },
  th: {
    eyebrow: 'คว้าค่ำคืนไว้ในจังหวะที่มันพลิกผัน',
    heading: 'สัญญาณมาถึงในขณะที่กะยังเป็นของคุณที่จะเปลี่ยนได้',
    sub: 'ลากดูค่ำคืนของการให้บริการจริง แบบเดิม คุณเห็นเรื่องราวนี้พรุ่งนี้ ด้วย Sundae คุณเห็นมันตอนหนึ่งทุ่มสิบห้า - โดยยังมีเวลาลงมือ',
    frameLabel: 'Pulse - กะแบบสด',
    withSundae: 'ด้วย Sundae',
    oldWay: 'แบบเดิม',
    paceLabel: 'เทียบกับจังหวะที่คาดไว้',
    coversLabel: 'ลูกค้า / ชม.',
    laborLabel: 'กำลังคน',
    forecastLabel: 'คาดการณ์',
    actualLabel: 'จริง',
    scrubHint: 'ลากเพื่อไล่ดูทั้งคืน',
    scrubAria: 'ไทม์ไลน์ค่ำคืนของการให้บริการ ตั้งแต่ห้าโมงเย็นจนถึงปิดร้าน ใช้ปุ่มลูกศรเพื่อเลื่อนไปตลอดทั้งค่ำคืน',
    preSignal: 'การให้บริการอยู่ในจังหวะ ลากต่อไปยังหนึ่งทุ่มสิบห้า',
    signalTitle: 'สัญญาณ - หนึ่งทุ่มสิบห้า',
    signalBody: 'โซน 3 กำลังหน่วง ลูกค้าตามจังหวะไม่ทันและกำลังคนกำลังไต่เกิน 30% ย้ายพนักงานเสิร์ฟหนึ่งคนออกจากครัวเตรียมตอนนี้ - คุณยังกู้ค่ำคืนนี้ได้',
    signalAction: 'นี่คือจังหวะที่ต้องลงมือ',
    oldTitle: 'พรุ่งนี้ สิบเอ็ดโมงเช้า',
    oldBody: 'เมื่อคืนโซน 3 ทำได้ต่ำกว่าจังหวะและกำลังคนปิดสูง คุณเพิ่งมาอ่านตอนนี้ กะนั้นจบไปนานแล้ว',
    oldAction: 'สายเกินกว่าจะเปลี่ยนอะไรได้',
    savedTitle: 'รักษาค่ำคืนนี้ไว้ได้',
    savedBody: 'ลูกค้าฟื้นกลับมาห่างจากที่คาดการณ์เพียงไม่กี่จุดและกำลังคนกลับเข้าเป้า - เพราะคุณคว้าโซน 3 ไว้ตอนหนึ่งทุ่มสิบห้า',
    projectedClose: 'คาดว่าจะปิดที่',
  },
  ms: {
    eyebrow: 'Tangkap malam itu pada saat ia berubah.',
    heading: 'Isyarat tiba selagi syif masih milik anda untuk diubah.',
    sub: 'Seret menerusi satu malam servis yang sebenar. Cara lama, anda lihat ceritanya esok. Dengan Sundae, anda lihat pada pukul 7.15 malam - dengan masa untuk bertindak.',
    frameLabel: 'Pulse - Syif langsung',
    withSundae: 'Dengan Sundae',
    oldWay: 'Cara lama',
    paceLabel: 'vs rentak unjuran',
    coversLabel: 'Tetamu / jam',
    laborLabel: 'Tenaga kerja',
    forecastLabel: 'Unjuran',
    actualLabel: 'Sebenar',
    scrubHint: 'Seret untuk menyusuri malam',
    scrubAria: 'Garis masa malam servis, dari pukul 5 petang hingga tutup. Gunakan kekunci anak panah untuk bergerak sepanjang malam.',
    preSignal: 'Servis mengikut rentak. Teruskan menyeret menuju pukul 7.15.',
    signalTitle: 'Isyarat - 7.15 malam',
    signalBody: 'Seksyen 3 mula ketinggalan. Tetamu di bawah rentak dan tenaga kerja menaik melepasi 30%. Alihkan seorang pelayan dari penyediaan sekarang - anda masih boleh menyelamatkan malam ini.',
    signalAction: 'Inilah saat untuk bertindak.',
    oldTitle: 'Esok, 11.00 pagi',
    oldBody: 'Malam tadi Seksyen 3 berjalan di bawah rentak dan tenaga kerja ditutup tinggi. Anda baru membacanya sekarang. Syif itu sudah lama berakhir.',
    oldAction: 'Terlalu lewat untuk mengubah apa-apa.',
    savedTitle: 'Malam terselamat',
    savedBody: 'Tetamu pulih hingga beberapa mata dari unjuran dan tenaga kerja kembali pada sasaran - kerana anda menangkap Seksyen 3 pada pukul 7.15 malam.',
    projectedClose: 'Anggaran penutupan',
  },
};
