import type { WebsiteLocale } from '@/lib/i18n';

/**
 * Copy for the signature "Watch the night turn" interaction - a scrubbable
 * service-night timeline that makes Sundae's whole thesis tangible: the signal
 * arrives at 7:15, while the shift is still yours to change, not in tomorrow's
 * report. It is the interactive proof of the manifesto + operator-voice copy.
 *
 * Same locale-keyed-with-en-fallback pattern as the other self-contained
 * homepage copy maps (outside the validated `messages` tree). Dash house-style:
 * spaced ASCII hyphen " - ", no em-dashes.
 */
export type ShiftMomentCopy = {
  eyebrow: string;
  heading: string;
  sub: string;
  frameLabel: string;
  withSundae: string;
  oldWay: string;
  paceLabel: string;
  coversLabel: string;
  laborLabel: string;
  forecastLabel: string;
  actualLabel: string;
  scrubHint: string;
  scrubAria: string;
  preSignal: string;
  signalTitle: string;
  signalBody: string;
  signalAction: string;
  oldTitle: string;
  oldBody: string;
  oldAction: string;
  /** Outcome copy shown near close (optional; falls back to English). */
  savedTitle?: string;
  savedBody?: string;
  projectedClose?: string;
};

export const shiftMomentCopy: Record<WebsiteLocale, ShiftMomentCopy> = {
  en: {
    eyebrow: 'Catch the night turning.',
    heading: 'The signal arrives while the shift is still yours to change.',
    sub: 'Drag through a real service night. The old way, you see the story tomorrow. With Sundae, you see it at 7:15 - with time to act.',
    frameLabel: 'Pulse - Live Shift',
    withSundae: 'With Sundae',
    oldWay: 'The old way',
    paceLabel: 'vs forecast pace',
    coversLabel: 'Covers / hr',
    laborLabel: 'Labor',
    forecastLabel: 'Forecast',
    actualLabel: 'Actual',
    scrubHint: 'Drag to scrub the night',
    scrubAria: 'Service-night timeline from 5 PM to close. Use the arrow keys to move through the evening.',
    preSignal: 'Service is on pace. Keep scrubbing toward 7:15.',
    signalTitle: 'Signal - 7:15 PM',
    signalBody: 'Section 3 is dragging. Covers are behind pace and labor is climbing past 30%. Move one server off prep now - you can still save the night.',
    signalAction: 'This is the moment to act.',
    oldTitle: 'Tomorrow, 11:00 AM',
    oldBody: 'Last night ran behind pace in Section 3 and labor closed high. You are reading this now. The shift is already over.',
    oldAction: 'Too late to change anything.',
    savedTitle: 'Night saved',
    savedBody: 'Covers recovered to within a few points of forecast and labor came back on target - because you caught Section 3 at 7:15.',
    projectedClose: 'Projected close',
  },
  ar: {
    eyebrow: 'تدارَك الليلة وهي تتبدّل.',
    heading: 'تصل الإشارة والوردية ما تزال قابلة للتغيير.',
    sub: 'مرّر عبر ليلة خدمة حقيقية. بالطريقة القديمة ترى القصة غدًا. مع Sundae تراها عند السابعة وربع - ومعك وقت للتصرّف.',
    frameLabel: 'Pulse - وردية مباشرة',
    withSundae: 'مع Sundae',
    oldWay: 'الطريقة القديمة',
    paceLabel: 'مقارنةً بالوتيرة المتوقعة',
    coversLabel: 'ضيوف / ساعة',
    laborLabel: 'العمالة',
    forecastLabel: 'المتوقع',
    actualLabel: 'الفعلي',
    scrubHint: 'اسحب لتتنقّل عبر الليلة',
    scrubAria: 'مخطّط زمني لليلة الخدمة من السابعة مساءً حتى الإغلاق. استخدم مفاتيح الأسهم للتنقّل عبر المساء.',
    preSignal: 'الخدمة على الوتيرة. واصل التمرير نحو السابعة وربع.',
    signalTitle: 'إشارة - 7:15 مساءً',
    signalBody: 'القسم 3 يتباطأ. الضيوف دون الوتيرة والعمالة تتجاوز 30%. انقل نادلًا من التحضير الآن - لا يزال بإمكانك إنقاذ الليلة.',
    signalAction: 'هذه هي لحظة التصرّف.',
    oldTitle: 'غدًا، 11:00 صباحًا',
    oldBody: 'الليلة الماضية جرت دون الوتيرة في القسم 3 وأغلقت العمالة مرتفعة. أنت تقرأ هذا الآن. والوردية قد انتهت بالفعل.',
    oldAction: 'فات الأوان على تغيير أي شيء.',
    savedTitle: 'تم إنقاذ الليلة',
    savedBody: 'تعافى عدد الضيوف ليقترب من المتوقع وعادت العمالة إلى هدفها - لأنك تداركت القسم 3 عند السابعة وربع.',
    projectedClose: 'الإغلاق المتوقع',
  },
  fr: {
    eyebrow: 'Saisissez la soirée qui bascule.',
    heading: 'Le signal arrive tant que le service peut encore être sauvé.',
    sub: "Parcourez une vraie soirée de service. À l'ancienne, vous voyez l'histoire demain. Avec Sundae, vous la voyez à 19 h 15 - avec le temps d'agir.",
    frameLabel: 'Pulse - Service en direct',
    withSundae: 'Avec Sundae',
    oldWay: "À l'ancienne",
    paceLabel: 'vs cadence prévue',
    coversLabel: 'Couverts / h',
    laborLabel: "Main-d'œuvre",
    forecastLabel: 'Prévu',
    actualLabel: 'Réel',
    scrubHint: 'Glissez pour parcourir la soirée',
    scrubAria: "Frise de la soirée de service, de 19 h à la fermeture. Utilisez les flèches pour parcourir la soirée.",
    preSignal: 'Le service tient la cadence. Continuez jusqu’à 19 h 15.',
    signalTitle: 'Signal - 19 h 15',
    signalBody: "La salle 3 décroche. Les couverts sont en retard et la main-d'œuvre dépasse 30%. Sortez un serveur du prep maintenant - vous pouvez encore sauver la soirée.",
    signalAction: "C'est le moment d'agir.",
    oldTitle: 'Demain, 11 h 00',
    oldBody: "Hier soir, la salle 3 a décroché et la main-d'œuvre a fini haut. Vous le lisez maintenant. Le service est déjà terminé.",
    oldAction: 'Trop tard pour changer quoi que ce soit.',
    savedTitle: 'Soirée sauvée',
    savedBody: "Les couverts sont revenus à quelques points de la prévision et la main-d'œuvre est repassée sur l'objectif - parce que vous avez rattrapé la salle 3 à 19 h 15.",
    projectedClose: 'Clôture prévue',
  },
  es: {
    eyebrow: 'Atrapa la noche cuando cambia.',
    heading: 'La señal llega cuando todavía puedes cambiar el turno.',
    sub: 'Recorre una noche de servicio real. A la antigua, ves la historia mañana. Con Sundae, la ves a las 7:15 - con tiempo para actuar.',
    frameLabel: 'Pulse - Turno en vivo',
    withSundae: 'Con Sundae',
    oldWay: 'A la antigua',
    paceLabel: 'vs ritmo previsto',
    coversLabel: 'Comensales / h',
    laborLabel: 'Personal',
    forecastLabel: 'Previsto',
    actualLabel: 'Real',
    scrubHint: 'Arrastra para recorrer la noche',
    scrubAria: 'Línea de tiempo de la noche de servicio, de 7 p. m. al cierre. Usa las flechas para avanzar por la noche.',
    preSignal: 'El servicio va a ritmo. Sigue avanzando hacia las 7:15.',
    signalTitle: 'Señal - 7:15 p. m.',
    signalBody: 'La sala 3 se está quedando atrás. Los comensales van por debajo del ritmo y el personal supera el 30%. Saca a un camarero del prep ahora - todavía puedes salvar la noche.',
    signalAction: 'Este es el momento de actuar.',
    oldTitle: 'Mañana, 11:00 a. m.',
    oldBody: 'Anoche la sala 3 fue por debajo del ritmo y el personal cerró alto. Lo estás leyendo ahora. El turno ya terminó.',
    oldAction: 'Demasiado tarde para cambiar nada.',
    savedTitle: 'Noche salvada',
    savedBody: 'Los comensales se recuperaron hasta quedar a pocos puntos de lo previsto y el personal volvió al objetivo - porque atajaste la sala 3 a las 7:15.',
    projectedClose: 'Cierre previsto',
  },
  de: {
    eyebrow: 'Erwischen Sie den Abend, wenn er kippt.',
    heading: 'Das Signal kommt, solange die Schicht noch in Ihrer Hand liegt.',
    sub: 'Ziehen Sie sich durch einen echten Serviceabend. Früher sahen Sie die Geschichte erst morgen. Mit Sundae sehen Sie sie um 19:15 Uhr - mit Zeit zum Handeln.',
    frameLabel: 'Pulse - Schicht live',
    withSundae: 'Mit Sundae',
    oldWay: 'Der alte Weg',
    paceLabel: 'vs. Prognosetempo',
    coversLabel: 'Gedecke / Std.',
    laborLabel: 'Personal',
    forecastLabel: 'Prognose',
    actualLabel: 'Ist',
    scrubHint: 'Ziehen, um durch den Abend zu scrubben',
    scrubAria: 'Zeitstrahl des Serviceabends von 17 Uhr bis Betriebsschluss. Bewegen Sie sich mit den Pfeiltasten durch den Abend.',
    preSignal: 'Der Service liegt im Tempo. Scrubben Sie weiter Richtung 19:15 Uhr.',
    signalTitle: 'Signal - 19:15 Uhr',
    signalBody: 'Bereich 3 hängt zurück. Die Gedecke liegen hinter dem Tempo und das Personal klettert über 30%. Holen Sie jetzt einen Servicemitarbeiter aus der Vorbereitung - Sie können den Abend noch retten.',
    signalAction: 'Jetzt ist der Moment zu handeln.',
    oldTitle: 'Morgen, 11 Uhr',
    oldBody: 'Gestern Abend lag Bereich 3 hinter dem Tempo und das Personal schloss hoch ab. Sie lesen das jetzt. Die Schicht ist längst vorbei.',
    oldAction: 'Zu spät, um noch etwas zu ändern.',
    savedTitle: 'Abend gerettet',
    savedBody: 'Die Gedecke erholten sich bis auf wenige Punkte an die Prognose und das Personal kam wieder auf Kurs - weil Sie Bereich 3 um 19:15 Uhr erwischt haben.',
    projectedClose: 'Voraussichtlicher Abschluss',
  },
  nl: {
    eyebrow: 'Vang de avond op het moment dat hij kantelt.',
    heading: 'Het signaal komt terwijl de dienst nog van u is om bij te sturen.',
    sub: 'Sleep door een echte serviceavond. Vroeger zag u het verhaal pas morgen. Met Sundae ziet u het om 19.15 uur - met tijd om te handelen.',
    frameLabel: 'Pulse - Dienst live',
    withSundae: 'Met Sundae',
    oldWay: 'De oude manier',
    paceLabel: 'vs. verwacht tempo',
    coversLabel: 'Couverts / uur',
    laborLabel: 'Personeel',
    forecastLabel: 'Verwacht',
    actualLabel: 'Werkelijk',
    scrubHint: 'Sleep om door de avond te scrubben',
    scrubAria: 'Tijdlijn van de serviceavond, van 17.00 uur tot sluiting. Gebruik de pijltjestoetsen om door de avond te bewegen.',
    preSignal: 'De service ligt op tempo. Blijf scrubben richting 19.15 uur.',
    signalTitle: 'Signaal - 19.15 uur',
    signalBody: 'Zone 3 blijft achter. De couverts lopen achter op het tempo en het personeel klimt boven de 30%. Haal nu één bediende uit de mise-en-place - u kunt de avond nog redden.',
    signalAction: 'Dit is het moment om te handelen.',
    oldTitle: 'Morgen, 11.00 uur',
    oldBody: 'Gisteravond liep zone 3 achter op het tempo en sloot het personeel hoog. U leest dit nu. De dienst is allang voorbij.',
    oldAction: 'Te laat om nog iets te veranderen.',
    savedTitle: 'Avond gered',
    savedBody: 'De couverts kwamen terug tot op een paar punten van de prognose en het personeel kwam weer op koers - omdat u zone 3 om 19.15 uur opving.',
    projectedClose: 'Verwachte afsluiting',
  },
  pt: {
    eyebrow: 'Capture a noite quando ela vira.',
    heading: 'O sinal chega enquanto o turno ainda é seu para mudar.',
    sub: 'Percorra uma noite de serviço real. Do jeito antigo, você vê a história amanhã. Com o Sundae, você a vê às 19h15 - com tempo para agir.',
    frameLabel: 'Pulse - Turno ao vivo',
    withSundae: 'Com o Sundae',
    oldWay: 'Do jeito antigo',
    paceLabel: 'vs. ritmo previsto',
    coversLabel: 'Clientes / h',
    laborLabel: 'Mão de obra',
    forecastLabel: 'Previsto',
    actualLabel: 'Real',
    scrubHint: 'Arraste para percorrer a noite',
    scrubAria: 'Linha do tempo da noite de serviço, das 17h ao fechamento. Use as setas para avançar pela noite.',
    preSignal: 'O serviço está no ritmo. Continue avançando até as 19h15.',
    signalTitle: 'Sinal - 19h15',
    signalBody: 'A sala 3 está atrasando. Os clientes estão abaixo do ritmo e a mão de obra passa de 30%. Tire um garçom da praça agora - você ainda pode salvar a noite.',
    signalAction: 'Este é o momento de agir.',
    oldTitle: 'Amanhã, 11h00',
    oldBody: 'Ontem à noite a sala 3 ficou abaixo do ritmo e a mão de obra fechou alta. Você está lendo isto agora. O turno já acabou.',
    oldAction: 'Tarde demais para mudar qualquer coisa.',
    savedTitle: 'Noite salva',
    savedBody: 'Os clientes se recuperaram para poucos pontos da previsão e a mão de obra voltou à meta - porque você pegou a sala 3 às 19h15.',
    projectedClose: 'Fechamento previsto',
  },
  hi: {
    eyebrow: 'रात को उसी पल थाम लीजिए जब वह पलटती है।',
    heading: 'सिग्नल तब आता है जब शिफ्ट अब भी बदलने के लिए आपके हाथ में है।',
    sub: 'एक असली सर्विस की रात में से गुज़रिए। पुराने तरीके में, आप कहानी कल देखते हैं। Sundae के साथ, आप इसे शाम 7:15 बजे देखते हैं - कुछ करने का वक़्त रहते।',
    frameLabel: 'Pulse - लाइव शिफ्ट',
    withSundae: 'Sundae के साथ',
    oldWay: 'पुराना तरीका',
    paceLabel: 'अनुमानित रफ्तार बनाम',
    coversLabel: 'मेहमान / घंटा',
    laborLabel: 'स्टाफ',
    forecastLabel: 'अनुमान',
    actualLabel: 'वास्तविक',
    scrubHint: 'रात में से गुज़रने के लिए खींचें',
    scrubAria: 'सर्विस की रात की समयरेखा, शाम 5 बजे से बंद होने तक। शाम भर आगे बढ़ने के लिए ऐरो कुंजियों का उपयोग करें।',
    preSignal: 'सर्विस रफ्तार पर है। 7:15 की ओर खींचते रहिए।',
    signalTitle: 'सिग्नल - शाम 7:15',
    signalBody: 'सेक्शन 3 पिछड़ रहा है। मेहमान रफ्तार से पीछे हैं और स्टाफ खर्च 30% पार कर रहा है। एक वेटर को प्रेप से अभी हटाइए - आप अब भी रात बचा सकते हैं।',
    signalAction: 'यही कुछ करने का पल है।',
    oldTitle: 'कल, सुबह 11:00',
    oldBody: 'कल रात सेक्शन 3 रफ्तार से पीछे रहा और स्टाफ खर्च ऊँचा बंद हुआ। आप यह अभी पढ़ रहे हैं। शिफ्ट तो कब की खत्म हो चुकी।',
    oldAction: 'अब कुछ बदलने के लिए बहुत देर हो चुकी।',
    savedTitle: 'रात बच गई',
    savedBody: 'मेहमानों की संख्या अनुमान से कुछ ही अंक दूर तक संभल गई और स्टाफ खर्च फिर लक्ष्य पर लौट आया - क्योंकि आपने सेक्शन 3 को शाम 7:15 बजे थाम लिया।',
    projectedClose: 'अनुमानित समापन',
  },
  ur: {
    eyebrow: 'رات کو اُسی لمحے تھام لیں جب وہ پلٹتی ہے۔',
    heading: 'سگنل تب آتا ہے جب شفٹ اب بھی بدلنے کے لیے آپ کے ہاتھ میں ہے۔',
    sub: 'ایک حقیقی سروس کی رات میں سے گزریے۔ پرانے طریقے میں، آپ کہانی کل دیکھتے ہیں۔ Sundae کے ساتھ، آپ اسے شام 7:15 بجے دیکھتے ہیں - کچھ کرنے کا وقت رہتے۔',
    frameLabel: 'Pulse - لائیو شفٹ',
    withSundae: 'Sundae کے ساتھ',
    oldWay: 'پرانا طریقہ',
    paceLabel: 'متوقع رفتار کے مقابلے',
    coversLabel: 'مہمان / گھنٹہ',
    laborLabel: 'عملہ',
    forecastLabel: 'متوقع',
    actualLabel: 'حقیقی',
    scrubHint: 'رات میں سے گزرنے کے لیے کھینچیں',
    scrubAria: 'سروس کی رات کی ٹائم لائن، شام 5 بجے سے بندش تک۔ شام بھر آگے بڑھنے کے لیے ایرو کیز استعمال کریں۔',
    preSignal: 'سروس رفتار پر ہے۔ 7:15 کی طرف کھینچتے رہیں۔',
    signalTitle: 'سگنل - شام 7:15',
    signalBody: 'سیکشن 3 پیچھے رہ رہا ہے۔ مہمان رفتار سے پیچھے ہیں اور عملے کا خرچ 30% سے تجاوز کر رہا ہے۔ ایک ویٹر کو تیاری سے ابھی ہٹائیں - آپ اب بھی رات بچا سکتے ہیں۔',
    signalAction: 'یہی کچھ کرنے کا لمحہ ہے۔',
    oldTitle: 'کل، صبح 11:00',
    oldBody: 'کل رات سیکشن 3 رفتار سے پیچھے رہا اور عملے کا خرچ بلند بند ہوا۔ آپ یہ اب پڑھ رہے ہیں۔ شفٹ تو کب کی ختم ہو چکی۔',
    oldAction: 'اب کچھ بدلنے کے لیے بہت دیر ہو چکی۔',
    savedTitle: 'رات بچ گئی',
    savedBody: 'مہمانوں کی تعداد سنبھل کر پیش گوئی سے چند پوائنٹ کے فاصلے پر آ گئی اور عملے کا خرچ دوبارہ ہدف پر لوٹ آیا - کیونکہ آپ نے سیکشن 3 کو شام 7:15 بجے تھام لیا۔',
    projectedClose: 'متوقع اختتام',
  },
  it: {
    eyebrow: 'Cogli la serata nel momento in cui cambia.',
    heading: 'Il segnale arriva mentre il turno è ancora tuo da cambiare.',
    sub: 'Scorri una vera serata di servizio. Alla vecchia maniera, vedi la storia domani. Con Sundae la vedi alle 19:15 - con il tempo per agire.',
    frameLabel: 'Pulse - Turno dal vivo',
    withSundae: 'Con Sundae',
    oldWay: 'Alla vecchia maniera',
    paceLabel: 'vs ritmo previsto',
    coversLabel: 'Coperti / h',
    laborLabel: 'Personale',
    forecastLabel: 'Previsto',
    actualLabel: 'Reale',
    scrubHint: 'Trascina per scorrere la serata',
    scrubAria: 'Linea temporale della serata di servizio, dalle 17 alla chiusura. Usa i tasti freccia per muoverti nella serata.',
    preSignal: 'Il servizio tiene il ritmo. Continua a scorrere verso le 19:15.',
    signalTitle: 'Segnale - 19:15',
    signalBody: "La sala 3 sta rallentando. I coperti sono sotto ritmo e il personale supera il 30%. Sposta subito un cameriere dalla preparazione - puoi ancora salvare la serata.",
    signalAction: "È il momento di agire.",
    oldTitle: 'Domani, 11:00',
    oldBody: 'Ieri sera la sala 3 è andata sotto ritmo e il personale ha chiuso alto. Lo stai leggendo adesso. Il turno è già finito.',
    oldAction: 'Troppo tardi per cambiare qualcosa.',
    savedTitle: 'Serata salvata',
    savedBody: 'I coperti sono risaliti a pochi punti dalla previsione e il personale è tornato in linea - perché hai colto la sala 3 alle 19:15.',
    projectedClose: 'Chiusura prevista',
  },
  pl: {
    eyebrow: 'Uchwyć wieczór w chwili, gdy się przechyla.',
    heading: 'Sygnał przychodzi, póki zmiana wciąż jest twoja do zmienienia.',
    sub: 'Przewiń przez prawdziwy wieczór serwisu. Po staremu widzisz tę historię jutro. Z Sundae widzisz ją o 19:15 - z czasem, by zadziałać.',
    frameLabel: 'Pulse - Zmiana na żywo',
    withSundae: 'Z Sundae',
    oldWay: 'Po staremu',
    paceLabel: 'vs prognozowane tempo',
    coversLabel: 'Goście / godz.',
    laborLabel: 'Obsada',
    forecastLabel: 'Prognoza',
    actualLabel: 'Rzeczywiste',
    scrubHint: 'Przeciągnij, aby przewinąć wieczór',
    scrubAria: 'Oś czasu wieczoru serwisu, od 17 do zamknięcia. Użyj strzałek, aby przesuwać się przez wieczór.',
    preSignal: 'Serwis trzyma tempo. Przewijaj dalej w stronę 19:15.',
    signalTitle: 'Sygnał - 19:15',
    signalBody: 'Sala 3 zostaje w tyle. Goście są poniżej tempa, a obsada przekracza 30%. Zabierz teraz jednego kelnera z mise en place - wciąż możesz uratować wieczór.',
    signalAction: 'To jest moment, żeby działać.',
    oldTitle: 'Jutro, 11:00',
    oldBody: 'Wczoraj wieczorem sala 3 była poniżej tempa, a obsada zamknęła się wysoko. Czytasz to teraz. Zmiana już dawno się skończyła.',
    oldAction: 'Za późno, by cokolwiek zmienić.',
    savedTitle: 'Wieczór uratowany',
    savedBody: 'Goście wrócili do kilku punktów od prognozy, a obsada znów weszła na cel - bo uchwyciłeś salę 3 o 19:15.',
    projectedClose: 'Prognozowane zamknięcie',
  },
  tr: {
    eyebrow: 'Geceyi döndüğü anda yakalayın.',
    heading: 'Sinyal, vardiya hâlâ sizin değiştirebileceğiniz haldeyken gelir.',
    sub: "Gerçek bir servis gecesini sürükleyerek gezin. Eski yöntemle hikâyeyi yarın görürsünüz. Sundae ile 19.15'te görürsünüz - harekete geçecek vakitle.",
    frameLabel: 'Pulse - Canlı vardiya',
    withSundae: 'Sundae ile',
    oldWay: 'Eski yöntem',
    paceLabel: 'tahmini tempoya karşı',
    coversLabel: 'Misafir / saat',
    laborLabel: 'İş gücü',
    forecastLabel: 'Tahmin',
    actualLabel: 'Gerçek',
    scrubHint: 'Geceyi taramak için sürükleyin',
    scrubAria: "Servis gecesinin zaman çizelgesi, akşam 17.00'den kapanışa kadar. Akşam boyunca ilerlemek için ok tuşlarını kullanın.",
    preSignal: "Servis tempoda. 19.15'e doğru taramaya devam edin.",
    signalTitle: 'Sinyal - 19.15',
    signalBody: 'Bölüm 3 geride kalıyor. Misafirler tempodan geride ve iş gücü %30’u aşıyor. Bir garsonu hazırlıktan şimdi alın - geceyi hâlâ kurtarabilirsiniz.',
    signalAction: 'Harekete geçme anı bu.',
    oldTitle: 'Yarın, 11.00',
    oldBody: 'Dün gece Bölüm 3 tempodan geride kaldı ve iş gücü yüksek kapandı. Bunu şimdi okuyorsunuz. Vardiya çoktan bitti.',
    oldAction: 'Bir şeyi değiştirmek için artık çok geç.',
    savedTitle: 'Gece kurtarıldı',
    savedBody: "Misafirler tahminin birkaç puan yakınına dek toparlandı ve iş gücü yeniden hedefe döndü - çünkü Bölüm 3'ü 19.15'te yakaladınız.",
    projectedClose: 'Öngörülen kapanış',
  },
  'zh-Hans': {
    eyebrow: '在夜色翻转的那一刻抓住它。',
    heading: '信号在班次还由你来改变时就已抵达。',
    sub: '拖动浏览一个真实的服务之夜。老办法下，你明天才看到这个故事。有了 Sundae，你在 19:15 就看到--还有时间行动。',
    frameLabel: 'Pulse--实时班次',
    withSundae: '有了 Sundae',
    oldWay: '老办法',
    paceLabel: '对比预测节奏',
    coversLabel: '客人 / 小时',
    laborLabel: '人力',
    forecastLabel: '预测',
    actualLabel: '实际',
    scrubHint: '拖动以浏览这一夜',
    scrubAria: '服务之夜时间轴，从下午 5 点到打烊。用方向键在整晚之间移动。',
    preSignal: '服务节奏正常。继续拖动到 19:15。',
    signalTitle: '信号--19:15',
    signalBody: '3 区慢下来了。客人落后于节奏，人力正爬过 30%。现在从备餐调一名服务员过去--这一夜还救得回来。',
    signalAction: '现在正是出手的时刻。',
    oldTitle: '明天，上午 11:00',
    oldBody: '昨晚 3 区落后于节奏，人力收得偏高。你现在才读到。这个班次早已结束。',
    oldAction: '想改什么都太迟了。',
    savedTitle: '这一夜守住了',
    savedBody: '客人数回升到与预测仅差几个点，人力也重新回到目标线--因为你在 19:15 抓住了 3 区。',
    projectedClose: '预计收尾',
  },
  ja: {
    eyebrow: '夜が傾くその瞬間をつかむ。',
    heading: 'まだ変えられるうちに届く、シフトの信号。',
    sub: '本物のサービスの夜をドラッグして辿る。これまでなら、その物語を見るのは明日。Sundae なら19:15に見える--動くための時間を残して。',
    frameLabel: 'Pulse--ライブシフト',
    withSundae: 'Sundae なら',
    oldWay: 'これまでのやり方',
    paceLabel: '予測ペース比',
    coversLabel: '客数 / 時',
    laborLabel: '人件費',
    forecastLabel: '予測',
    actualLabel: '実績',
    scrubHint: 'ドラッグして夜を辿る',
    scrubAria: 'サービスの夜のタイムライン、17時から閉店まで。矢印キーで夜を進めます。',
    preSignal: 'サービスはペース通り。19:15に向けてドラッグを続けてください。',
    signalTitle: '信号--19:15',
    signalBody: '3番セクションが遅れています。客数はペースに届かず、人件費は30%を超えつつあります。今すぐ仕込みからサーバーを1人回してください--まだこの夜は立て直せます。',
    signalAction: 'いまが動くべき瞬間です。',
    oldTitle: '明日、午前11:00',
    oldBody: '昨夜は3番セクションがペースに届かず、人件費は高く閉まりました。あなたが読んでいるのは今。シフトはとうに終わっています。',
    oldAction: 'もう何も変えられません。',
    savedTitle: '夜を守った',
    savedBody: '客数は予測との差が数ポイントまで戻り、人件費も目標に戻りました--あなたが19:15に3番セクションをつかんだからです。',
    projectedClose: '着地見込み',
  },
  ko: {
    eyebrow: '밤이 뒤집히는 그 순간을 붙잡으세요.',
    heading: '아직 근무를 바꿀 수 있을 때 신호가 옵니다.',
    sub: '진짜 서비스의 밤을 끌어서 살펴보세요. 예전 방식이라면 그 이야기를 내일 봅니다. Sundae와 함께라면 오후 7시 15분에 봅니다 - 움직일 시간을 남긴 채.',
    frameLabel: 'Pulse - 실시간 근무',
    withSundae: 'Sundae와 함께',
    oldWay: '예전 방식',
    paceLabel: '예측 페이스 대비',
    coversLabel: '손님 / 시간',
    laborLabel: '인건비',
    forecastLabel: '예측',
    actualLabel: '실제',
    scrubHint: '끌어서 밤을 살펴보세요',
    scrubAria: '서비스의 밤 타임라인, 오후 5시부터 마감까지. 화살표 키로 저녁을 이동하세요.',
    preSignal: '서비스는 페이스대로입니다. 오후 7시 15분 쪽으로 계속 끌어보세요.',
    signalTitle: '신호 - 오후 7시 15분',
    signalBody: '3번 구역이 처지고 있습니다. 손님은 페이스보다 뒤처지고 인건비는 30%를 넘어서고 있습니다. 지금 준비조에서 서버 한 명을 빼세요 - 아직 이 밤을 살릴 수 있습니다.',
    signalAction: '지금이 움직일 순간입니다.',
    oldTitle: '내일, 오전 11:00',
    oldBody: '어젯밤 3번 구역이 페이스보다 뒤처졌고 인건비는 높게 마감됐습니다. 당신은 지금 이걸 읽습니다. 근무는 이미 끝났습니다.',
    oldAction: '이제 무엇도 바꾸기엔 너무 늦었습니다.',
    savedTitle: '밤을 지켰습니다',
    savedBody: '손님 수는 예측과 몇 포인트 차이까지 회복됐고 인건비도 다시 목표로 돌아왔습니다 - 당신이 오후 7시 15분에 3번 구역을 붙잡았기 때문입니다.',
    projectedClose: '예상 마감',
  },
  id: {
    eyebrow: 'Tangkap malam itu saat ia berbalik.',
    heading: 'Sinyal datang selagi shift masih milik Anda untuk diubah.',
    sub: 'Geser melewati malam servis yang sebenarnya. Cara lama, Anda melihat ceritanya besok. Dengan Sundae, Anda melihatnya pukul 19.15 - dengan waktu untuk bertindak.',
    frameLabel: 'Pulse - Shift langsung',
    withSundae: 'Dengan Sundae',
    oldWay: 'Cara lama',
    paceLabel: 'vs tempo perkiraan',
    coversLabel: 'Tamu / jam',
    laborLabel: 'Tenaga kerja',
    forecastLabel: 'Perkiraan',
    actualLabel: 'Aktual',
    scrubHint: 'Geser untuk menelusuri malam',
    scrubAria: 'Garis waktu malam servis, dari pukul 5 sore hingga tutup. Gunakan tombol panah untuk bergerak sepanjang malam.',
    preSignal: 'Servis sesuai tempo. Terus geser menuju pukul 19.15.',
    signalTitle: 'Sinyal - 19.15',
    signalBody: 'Seksi 3 mulai tertinggal. Tamu di bawah tempo dan tenaga kerja menanjak melewati 30%. Pindahkan satu pelayan dari prep sekarang - Anda masih bisa menyelamatkan malam ini.',
    signalAction: 'Inilah saatnya bertindak.',
    oldTitle: 'Besok, pukul 11.00',
    oldBody: 'Tadi malam Seksi 3 berjalan di bawah tempo dan tenaga kerja tutup tinggi. Anda baru membacanya sekarang. Shift sudah lama berakhir.',
    oldAction: 'Terlambat untuk mengubah apa pun.',
    savedTitle: 'Malam terselamatkan',
    savedBody: 'Tamu pulih hingga beberapa poin dari perkiraan dan tenaga kerja kembali sesuai target - karena Anda menangkap Seksi 3 pukul 19.15.',
    projectedClose: 'Perkiraan penutupan',
  },
  vi: {
    eyebrow: 'Bắt lấy buổi tối ngay khi nó lật chiều.',
    heading: 'Tín hiệu đến khi ca làm vẫn còn là của bạn để xoay chuyển.',
    sub: 'Kéo qua một buổi tối phục vụ có thật. Theo cách cũ, bạn thấy câu chuyện vào ngày mai. Với Sundae, bạn thấy nó lúc 19:15 - với thời gian để hành động.',
    frameLabel: 'Pulse - Ca trực tiếp',
    withSundae: 'Với Sundae',
    oldWay: 'Cách cũ',
    paceLabel: 'so với nhịp dự báo',
    coversLabel: 'Khách / giờ',
    laborLabel: 'Nhân sự',
    forecastLabel: 'Dự báo',
    actualLabel: 'Thực tế',
    scrubHint: 'Kéo để lướt qua buổi tối',
    scrubAria: 'Dòng thời gian của buổi tối phục vụ, từ 5 giờ chiều đến giờ đóng cửa. Dùng các phím mũi tên để di chuyển qua buổi tối.',
    preSignal: 'Phục vụ đang đúng nhịp. Hãy tiếp tục kéo tới 19:15.',
    signalTitle: 'Tín hiệu - 19:15',
    signalBody: 'Khu 3 đang chậm lại. Lượt khách tụt sau nhịp và nhân sự đang vượt 30%. Điều một phục vụ rời khu sơ chế ngay - bạn vẫn còn cứu được buổi tối.',
    signalAction: 'Đây là thời điểm để hành động.',
    oldTitle: 'Ngày mai, 11:00 sáng',
    oldBody: 'Tối qua Khu 3 chạy chậm hơn nhịp và nhân sự đóng ca ở mức cao. Bây giờ bạn mới đọc điều này. Ca làm đã kết thúc từ lâu.',
    oldAction: 'Quá muộn để thay đổi bất cứ điều gì.',
    savedTitle: 'Đã cứu được buổi tối',
    savedBody: 'Lượt khách hồi về chỉ còn cách dự báo vài điểm và nhân sự trở lại đúng mục tiêu - vì bạn đã bắt được Khu 3 lúc 19:15.',
    projectedClose: 'Kết ca dự kiến',
  },
  ro: {
    eyebrow: 'Prinde seara chiar în clipa în care se întoarce.',
    heading: 'Semnalul ajunge cât timp tura e încă a ta de schimbat.',
    sub: 'Derulează printr-o seară de serviciu reală. Pe vremuri, vedeai povestea mâine. Cu Sundae, o vezi la 19:15 - cu timp ca să acționezi.',
    frameLabel: 'Pulse - Tură live',
    withSundae: 'Cu Sundae',
    oldWay: 'Pe vremuri',
    paceLabel: 'vs ritmul prognozat',
    coversLabel: 'Clienți / oră',
    laborLabel: 'Personal',
    forecastLabel: 'Prognoză',
    actualLabel: 'Real',
    scrubHint: 'Trage pentru a derula seara',
    scrubAria: 'Cronologia serii de serviciu, de la ora 17 până la închidere. Folosește tastele săgeți pentru a parcurge seara.',
    preSignal: 'Serviciul ține ritmul. Continuă să derulezi spre 19:15.',
    signalTitle: 'Semnal - 19:15',
    signalBody: 'Sala 3 rămâne în urmă. Clienții sunt sub ritm și personalul urcă peste 30%. Mută acum un ospătar de la preparare - încă poți salva seara.',
    signalAction: 'Acesta e momentul să acționezi.',
    oldTitle: 'Mâine, 11:00',
    oldBody: 'Aseară, Sala 3 a rămas sub ritm și personalul a închis sus. Citești asta abia acum. Tura s-a terminat demult.',
    oldAction: 'Prea târziu pentru a mai schimba ceva.',
    savedTitle: 'Seară salvată',
    savedBody: 'Clienții și-au revenit la câteva puncte de prognoză și personalul a revenit pe țintă - pentru că ai prins Sala 3 la 19:15.',
    projectedClose: 'Închidere estimată',
  },
  sv: {
    eyebrow: 'Fånga kvällen just när den vänder.',
    heading: 'Signalen kommer medan passet fortfarande är ditt att ändra.',
    sub: 'Dra dig genom en riktig servicekväll. Förr såg du historien i morgon. Med Sundae ser du den klockan 19.15 - med tid att agera.',
    frameLabel: 'Pulse - Pass live',
    withSundae: 'Med Sundae',
    oldWay: 'Det gamla sättet',
    paceLabel: 'mot prognostiserat tempo',
    coversLabel: 'Gäster / tim',
    laborLabel: 'Bemanning',
    forecastLabel: 'Prognos',
    actualLabel: 'Faktiskt',
    scrubHint: 'Dra för att skrubba genom kvällen',
    scrubAria: 'Tidslinje för servicekvällen, från klockan 17 till stängning. Använd piltangenterna för att röra dig genom kvällen.',
    preSignal: 'Servicen håller tempot. Fortsätt skrubba mot 19.15.',
    signalTitle: 'Signal - 19.15',
    signalBody: 'Sektion 3 släpar efter. Gästerna ligger efter tempot och bemanningen klättrar förbi 30%. Flytta en servitör från förberedelsen nu - du kan fortfarande rädda kvällen.',
    signalAction: 'Det här är ögonblicket att agera.',
    oldTitle: 'I morgon, 11.00',
    oldBody: 'I går kväll låg sektion 3 efter tempot och bemanningen stängde högt. Du läser det här nu. Passet är sedan länge över.',
    oldAction: 'För sent att ändra något.',
    savedTitle: 'Kvällen räddad',
    savedBody: 'Gästerna återhämtade sig till några punkter från prognosen och bemanningen kom tillbaka på mål - eftersom du fångade sektion 3 klockan 19.15.',
    projectedClose: 'Beräknad stängning',
  },
  bn: {
    eyebrow: 'রাত যেই মুহূর্তে ঘুরে যায়, ঠিক তখনই ধরুন।',
    heading: 'সিগন্যাল আসে যখন শিফট এখনও বদলানোর জন্য আপনার হাতে।',
    sub: 'একটি সত্যিকারের সার্ভিসের রাত টেনে দেখুন। পুরনো উপায়ে, আপনি গল্পটা কাল দেখেন। Sundae-র সঙ্গে, আপনি এটি সন্ধ্যা ৭:১৫-তে দেখেন - পদক্ষেপ নেওয়ার সময় হাতে রেখে।',
    frameLabel: 'Pulse - লাইভ শিফট',
    withSundae: 'Sundae-র সঙ্গে',
    oldWay: 'পুরনো উপায়',
    paceLabel: 'পূর্বাভাসিত গতির তুলনায়',
    coversLabel: 'অতিথি / ঘণ্টা',
    laborLabel: 'জনবল',
    forecastLabel: 'পূর্বাভাস',
    actualLabel: 'প্রকৃত',
    scrubHint: 'রাত জুড়ে চলতে টেনে নিন',
    scrubAria: 'সার্ভিসের রাতের সময়রেখা, বিকেল ৫টা থেকে বন্ধ হওয়া পর্যন্ত। সন্ধ্যা জুড়ে এগোতে অ্যারো কী ব্যবহার করুন।',
    preSignal: 'সার্ভিস গতিতে আছে। ৭:১৫-র দিকে টানতে থাকুন।',
    signalTitle: 'সিগন্যাল - সন্ধ্যা ৭:১৫',
    signalBody: 'সেকশন ৩ পিছিয়ে পড়ছে। অতিথিরা গতির পেছনে এবং জনবল খরচ ৩০% ছাড়িয়ে যাচ্ছে। এখনই প্রস্তুতি থেকে একজন ওয়েটারকে সরান - আপনি এখনও রাতটি বাঁচাতে পারেন।',
    signalAction: 'এখনই পদক্ষেপ নেওয়ার মুহূর্ত।',
    oldTitle: 'আগামীকাল, সকাল ১১:০০',
    oldBody: 'গতকাল রাতে সেকশন ৩ গতির পেছনে চলল এবং জনবল খরচ উঁচুতে শেষ হলো। আপনি এটি এখন পড়ছেন। শিফট তো কবেই শেষ।',
    oldAction: 'এখন কিছু বদলানোর জন্য অনেক দেরি।',
    savedTitle: 'রাত বেঁচে গেল',
    savedBody: 'অতিথির সংখ্যা সামলে পূর্বাভাস থেকে মাত্র কয়েক পয়েন্ট দূরত্বে ফিরে এল এবং জনবল খরচ আবার লক্ষ্যে নেমে এল - কারণ আপনি সেকশন ৩-কে সন্ধ্যা ৭:১৫-তে ধরেছিলেন।',
    projectedClose: 'প্রত্যাশিত সমাপ্তি',
  },
  th: {
    eyebrow: 'คว้าค่ำคืนไว้ในจังหวะที่มันพลิกผัน',
    heading: 'สัญญาณมาถึงในขณะที่กะยังเป็นของคุณที่จะเปลี่ยนได้',
    sub: 'ลากดูค่ำคืนของการให้บริการจริง แบบเดิม คุณเห็นเรื่องราวนี้พรุ่งนี้ ด้วย Sundae คุณเห็นมันตอนหนึ่งทุ่มสิบห้า - โดยยังมีเวลาลงมือ',
    frameLabel: 'Pulse - กะแบบสด',
    withSundae: 'ด้วย Sundae',
    oldWay: 'แบบเดิม',
    paceLabel: 'เทียบกับจังหวะที่คาดไว้',
    coversLabel: 'ลูกค้า / ชม.',
    laborLabel: 'กำลังคน',
    forecastLabel: 'คาดการณ์',
    actualLabel: 'จริง',
    scrubHint: 'ลากเพื่อไล่ดูทั้งคืน',
    scrubAria: 'ไทม์ไลน์ค่ำคืนของการให้บริการ ตั้งแต่ห้าโมงเย็นจนถึงปิดร้าน ใช้ปุ่มลูกศรเพื่อเลื่อนไปตลอดทั้งค่ำคืน',
    preSignal: 'การให้บริการอยู่ในจังหวะ ลากต่อไปยังหนึ่งทุ่มสิบห้า',
    signalTitle: 'สัญญาณ - หนึ่งทุ่มสิบห้า',
    signalBody: 'โซน 3 กำลังหน่วง ลูกค้าตามจังหวะไม่ทันและกำลังคนกำลังไต่เกิน 30% ย้ายพนักงานเสิร์ฟหนึ่งคนออกจากครัวเตรียมตอนนี้ - คุณยังกู้ค่ำคืนนี้ได้',
    signalAction: 'นี่คือจังหวะที่ต้องลงมือ',
    oldTitle: 'พรุ่งนี้ สิบเอ็ดโมงเช้า',
    oldBody: 'เมื่อคืนโซน 3 ทำได้ต่ำกว่าจังหวะและกำลังคนปิดสูง คุณเพิ่งมาอ่านตอนนี้ กะนั้นจบไปนานแล้ว',
    oldAction: 'สายเกินกว่าจะเปลี่ยนอะไรได้',
    savedTitle: 'รักษาค่ำคืนนี้ไว้ได้',
    savedBody: 'ลูกค้าฟื้นกลับมาห่างจากที่คาดการณ์เพียงไม่กี่จุดและกำลังคนกลับเข้าเป้า - เพราะคุณคว้าโซน 3 ไว้ตอนหนึ่งทุ่มสิบห้า',
    projectedClose: 'คาดว่าจะปิดที่',
  },
  ms: {
    eyebrow: 'Tangkap malam itu pada saat ia berubah.',
    heading: 'Isyarat tiba selagi syif masih milik anda untuk diubah.',
    sub: 'Seret menerusi satu malam servis yang sebenar. Cara lama, anda lihat ceritanya esok. Dengan Sundae, anda lihat pada pukul 7.15 malam - dengan masa untuk bertindak.',
    frameLabel: 'Pulse - Syif langsung',
    withSundae: 'Dengan Sundae',
    oldWay: 'Cara lama',
    paceLabel: 'vs rentak unjuran',
    coversLabel: 'Tetamu / jam',
    laborLabel: 'Tenaga kerja',
    forecastLabel: 'Unjuran',
    actualLabel: 'Sebenar',
    scrubHint: 'Seret untuk menyusuri malam',
    scrubAria: 'Garis masa malam servis, dari pukul 5 petang hingga tutup. Gunakan kekunci anak panah untuk bergerak sepanjang malam.',
    preSignal: 'Servis mengikut rentak. Teruskan menyeret menuju pukul 7.15.',
    signalTitle: 'Isyarat - 7.15 malam',
    signalBody: 'Seksyen 3 mula ketinggalan. Tetamu di bawah rentak dan tenaga kerja menaik melepasi 30%. Alihkan seorang pelayan dari penyediaan sekarang - anda masih boleh menyelamatkan malam ini.',
    signalAction: 'Inilah saat untuk bertindak.',
    oldTitle: 'Esok, 11.00 pagi',
    oldBody: 'Malam tadi Seksyen 3 berjalan di bawah rentak dan tenaga kerja ditutup tinggi. Anda baru membacanya sekarang. Syif itu sudah lama berakhir.',
    oldAction: 'Terlalu lewat untuk mengubah apa-apa.',
    savedTitle: 'Malam terselamat',
    savedBody: 'Tetamu pulih hingga beberapa mata dari unjuran dan tenaga kerja kembali pada sasaran - kerana anda menangkap Seksyen 3 pada pukul 7.15 malam.',
    projectedClose: 'Anggaran penutupan',
  },
};
