export const asiaDiagnosticOptionPacks = {
  "zh-Hans": {
    segment: {
      qsr: "QSR / 快餐",
      fast_casual: "休闲快餐",
      casual: "休闲正餐",
      fine_dining: "高端餐饮",
      cloud: "云厨房 / 暗厨房",
      hotel_fb: "酒店 F&B",
      cafe_bakery: "咖啡馆 / 烘焙",
      bar_nightlife: "酒吧 / 夜生活",
      catering: "宴会餐饮 / 活动",
      ghost_brand: "幽灵 / 虚拟品牌",
      franchise: "特许经营 / 总特许经营商",
    },
    outlets: {
      "1": "1 家门店",
      "2_5": "2-5 家门店",
      "6_15": "6-15 家门店",
      "16_50": "16-50 家门店",
      "51_150": "51-150 家门店",
      "150_plus": "150+ 家门店",
    },
    avg_unit_volume: {
      under_500k: "低于 $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "美国",
      canada: "加拿大",
      uk: "英国",
      ireland: "爱尔兰",
      europe_west: "欧洲（西部）",
      europe_nord: "欧洲（北欧）",
      europe_east: "欧洲（东部）",
      uae: "UAE",
      ksa: "沙特阿拉伯",
      qatar: "卡塔尔",
      kuwait: "科威特",
      bahrain: "巴林",
      oman: "阿曼",
      egypt: "埃及",
      africa: "非洲（其他）",
      sea: "东南亚",
      india: "印度",
      japan: "日本",
      korea: "韩国",
      china_hk: "中国 / 香港",
      anzac: "澳大利亚 / 新西兰",
      mexico: "墨西哥",
      brazil: "巴西",
      latam_other: "拉丁美洲（其他）",
    },
    scheduling_tool: {
      manual: "人工 / 电子表格",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "内部 / 定制工具",
      pos_built_in: "内置于 POS",
      none: "没有系统化流程",
      other: "其他",
    },
    labor_pain: {
      overstaffing: "低峰时段人员配置过多",
      no_show: "缺勤 / 临时请假",
      ot_leakage: "加班成本流失",
      buddy_punching: "代打卡 / 工时盗用",
      payroll_errors: "薪资核算错误",
      compliance: "合规 / 法定规则",
      turnover: "人员流失 / 重新培训",
      none: "目前不是首要关注点",
    },
    payroll_regions: {
      us: "美国",
      canada: "加拿大",
      uk: "英国",
      eu: "欧盟",
      uae: "UAE",
      ksa: "沙特阿拉伯",
      qatar: "卡塔尔 / 巴林 / 阿曼",
      other: "其他（请在下方填写）",
    },
    kpis_measured: {
      labor_pct: "人工成本 %",
      food_cost: "食材成本 %",
      void_comp: "作废 / 赠送",
      avg_check: "平均客单价",
      upsell: "追加销售 / 附加率",
      guest_retention: "顾客留存",
      ebitda: "单店 EBITDA",
      forecast_acc: "预测准确率",
      compset: "竞争定位",
    },
    kpis_wished: {
      real_time_margin: "每班次实时利润率",
      daypart_leak: "分时段人工成本流失",
      labor_productivity: "实时劳动生产率（每人工小时销售额）",
      live_labor_vs_demand: "实时人工配置与需求匹配（实时 staffing pace）",
      overtime_leakage: "实时加班风险与成本流失",
      daypart_revpash: "分时段 RevPASH (Revenue per Available Seat Hour)",
      hourly_food_cost: "小时级食材成本差异",
      theoretical_actual: "理论与实际 COGS 差异",
      item_profitability: "真实菜品级盈利能力",
      menu_engineering: "菜单工程矩阵 (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "服务员级追加销售附加率",
      cannibalization: "跨日期 / 跨渠道蚕食效应",
      promo_roi: "按渠道划分的促销 ROI",
      delivery_margin: "外卖渠道利润率（第三方佣金拖累）",
      guest_ltv: "顾客生命周期价值",
      cohort_retention: "顾客群组留存曲线",
      noshow_prediction: "预订爽约预测",
      inventory_shrinkage: "按品类划分的库存损耗",
      cash_variance: "现金与收入保障差异（舞弊识别）",
      peer_benchmark: "匿名同业基准",
      competitor_pricing: "竞争对手定价追踪",
      forecast_per_outlet: "单店每日预测",
      scheduling_eff: "排班效率与需求对比",
      decision_replay: "决策到结果的闭环评分",
      cross_module: "跨模块相关性洞察",
      multi_brand_pnl: "多品牌合并 P&L",
      compliance_drift: "合规 / 品牌标准偏移",
      payroll_readiness: "实时薪资就绪度",
      speed_of_service: "按工位划分的服务速度 / 出单时间",
      food_waste: "食物浪费与报损追踪",
      gratuity_distribution: "小费 / 服务费分配与合规",
      guest_sentiment: "顾客情绪 / 评论趋势追踪",
    },
    decision_data: {
      gut: "经验 / 直觉",
      spreadsheet: "分析师整理的电子表格",
      pos_report: "POS 标准报表",
      bi_dashboard: "BI 仪表板 (Power BI / Tableau / Looker / Domo)",
      in_house_data: "内部数据仓库 / SQL 查询",
      external: "外部顾问 / 咨询顾问",
      ai_tool: "AI 工具 (ChatGPT / Claude / Gemini)",
      industry_report: "行业报告 / 基准研究",
      board_packet: "董事会 / 管理层汇报包",
    },
    forecasting: {
      lyear_gut: "去年数据 + 经验判断",
      spreadsheet: "内部维护的电子表格模型",
      pos_system: "内置于 POS / 会计系统",
      bi_tool: "带自定义模型的 BI 工具",
      ai_tool: "专用 AI / 预测工具",
      none: "我们不做正式预测",
    },
    scenario_wish: {
      new_location: "开设新门店",
      menu_change: "菜单 / 定价调整影响",
      promo_impact: "促销 / 折扣影响",
      staffing_model: "人员配置模型调整",
      season_event: "季节性 / 活动影响",
      competitor: "竞争对手进入 / 退出",
      macro: "通胀 / 工资法规 / 税务变化",
    },
    pos: {
      other: "其他",
    },
    ops_tools: {
      scheduling: "劳动力排班",
      payroll: "薪资服务商",
      purchasing: "采购 / 库存",
      delivery: "外卖聚合平台管理",
      reservations: "预订 / 桌位管理",
      crm: "顾客 CRM / 会员忠诚度",
      bi: "BI 工具 (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "现在 - 正在积极评估",
      next_quarter: "下个季度",
      next_6_months: "未来 6 个月",
      this_year: "年底前",
      exploring: "仅在探索 · 暂无时间表",
    },
    decision_lag: {
      minutes: "分钟 - 我们在班次中即时响应",
      hours: "小时 - 当天处理",
      days: "天 - 每周复盘周期",
      weeks: "周 - 月度结账周期",
      months: "月 - 仅季度复盘",
    },
    budget_band: {
      under_10k: "低于 $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "不确定",
    },
    tech_headcount: {
      none: "无人 - 我们没有专职人员",
      fractional: "兼职 / 与其他职能共享",
      one: "1 人",
      two_three: "2-3 人",
      four_eight: "4-8 人",
      nine_twenty: "9-20 人",
      twenty_plus: "20+ 人",
    },
  },
  ja: {
    segment: {
      qsr: "QSR / ファストフード",
      fast_casual: "ファストカジュアル",
      casual: "カジュアルダイニング",
      fine_dining: "ファインダイニング",
      cloud: "クラウドキッチン / ダークキッチン",
      hotel_fb: "ホテル F&B",
      cafe_bakery: "カフェ / ベーカリー",
      bar_nightlife: "バー / ナイトライフ",
      catering: "ケータリング / イベント",
      ghost_brand: "ゴースト / バーチャルブランド",
      franchise: "フランチャイズ / マスターフランチャイジー",
    },
    outlets: {
      "1": "1 店舗",
      "2_5": "2-5 店舗",
      "6_15": "6-15 店舗",
      "16_50": "16-50 店舗",
      "51_150": "51-150 店舗",
      "150_plus": "150+ 店舗",
    },
    avg_unit_volume: {
      under_500k: "$500K 未満",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "米国",
      canada: "カナダ",
      uk: "英国",
      ireland: "アイルランド",
      europe_west: "欧州（西部）",
      europe_nord: "欧州（北欧）",
      europe_east: "欧州（東部）",
      uae: "UAE",
      ksa: "サウジアラビア",
      qatar: "カタール",
      kuwait: "クウェート",
      bahrain: "バーレーン",
      oman: "オマーン",
      egypt: "エジプト",
      africa: "アフリカ（その他）",
      sea: "東南アジア",
      india: "インド",
      japan: "日本",
      korea: "韓国",
      china_hk: "中国 / 香港",
      anzac: "オーストラリア / ニュージーランド",
      mexico: "メキシコ",
      brazil: "ブラジル",
      latam_other: "ラテンアメリカ（その他）",
    },
    scheduling_tool: {
      manual: "手作業 / スプレッドシート",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "社内 / カスタムツール",
      pos_built_in: "POS 内蔵",
      none: "体系的な運用なし",
      other: "その他",
    },
    labor_pain: {
      overstaffing: "閑散時間帯の過剰人員",
      no_show: "無断欠勤 / 当日欠勤連絡",
      ot_leakage: "残業コストの漏れ",
      buddy_punching: "代理打刻 / 勤怠不正",
      payroll_errors: "給与計算ミス",
      compliance: "コンプライアンス / 法定ルール",
      turnover: "離職 / 再トレーニング",
      none: "現時点では最優先課題ではない",
    },
    payroll_regions: {
      us: "米国",
      canada: "カナダ",
      uk: "英国",
      eu: "欧州連合",
      uae: "UAE",
      ksa: "サウジアラビア",
      qatar: "カタール / バーレーン / オマーン",
      other: "その他（下に記入）",
    },
    kpis_measured: {
      labor_pct: "人件費率 %",
      food_cost: "食材原価率 %",
      void_comp: "取消 / 無償提供",
      avg_check: "平均客単価",
      upsell: "アップセル / アタッチ率",
      guest_retention: "顧客維持率",
      ebitda: "店舗別 EBITDA",
      forecast_acc: "予測精度",
      compset: "競合ポジション",
    },
    kpis_wished: {
      real_time_margin: "シフト別リアルタイム利益率",
      daypart_leak: "時間帯別の人件費漏れ",
      labor_productivity: "リアルタイム労働生産性（労働時間あたり売上）",
      live_labor_vs_demand: "需要に対するリアルタイム人員配置（リアルタイム staffing pace）",
      overtime_leakage: "残業リスクと漏れのリアルタイム把握",
      daypart_revpash: "時間帯別 RevPASH (Revenue per Available Seat Hour)",
      hourly_food_cost: "時間単位の食材原価差異",
      theoretical_actual: "理論値と実績の COGS 差異",
      item_profitability: "実質的な商品別収益性",
      menu_engineering: "メニューエンジニアリングマトリクス (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "スタッフ別アップセルアタッチ率",
      cannibalization: "曜日間 / チャネル間カニバリゼーション",
      promo_roi: "チャネル別プロモーション ROI",
      delivery_margin: "デリバリーチャネル利益率（第三者手数料の影響）",
      guest_ltv: "顧客生涯価値",
      cohort_retention: "顧客コホート維持曲線",
      noshow_prediction: "予約ノーショー予測",
      inventory_shrinkage: "商品カテゴリ別在庫ロス",
      cash_variance: "現金および売上保証差異（不正検知）",
      peer_benchmark: "匿名同業ベンチマーク",
      competitor_pricing: "競合価格トラッキング",
      forecast_per_outlet: "店舗別の日次予測",
      scheduling_eff: "需要に対するシフト作成効率",
      decision_replay: "意思決定から結果までのクローズドループ採点",
      cross_module: "モジュール横断の相関インサイト",
      multi_brand_pnl: "複数ブランド統合 P&L",
      compliance_drift: "コンプライアンス / ブランド基準の逸脱",
      payroll_readiness: "リアルタイム給与計算準備状況",
      speed_of_service: "ステーション別サービス速度 / チケットタイム",
      food_waste: "食品廃棄とロスのトラッキング",
      gratuity_distribution: "チップ / サービス料の配分とコンプライアンス",
      guest_sentiment: "顧客感情 / レビュー傾向トラッキング",
    },
    decision_data: {
      gut: "経験 / 勘",
      spreadsheet: "アナリストが作成したスプレッドシート",
      pos_report: "POS 標準レポート",
      bi_dashboard: "BI ダッシュボード (Power BI / Tableau / Looker / Domo)",
      in_house_data: "社内データウェアハウス / SQL クエリ",
      external: "外部コンサルタント / アドバイザー",
      ai_tool: "AI ツール (ChatGPT / Claude / Gemini)",
      industry_report: "業界レポート / ベンチマーク調査",
      board_packet: "取締役会 / 経営層向け資料",
    },
    forecasting: {
      lyear_gut: "前年実績 + 経験則",
      spreadsheet: "社内で管理しているスプレッドシートモデル",
      pos_system: "POS / 会計システム内蔵",
      bi_tool: "カスタムモデル付き BI ツール",
      ai_tool: "専用 AI / 予測ツール",
      none: "正式な予測は行っていない",
    },
    scenario_wish: {
      new_location: "新規店舗の出店",
      menu_change: "メニュー / 価格変更の影響",
      promo_impact: "プロモーション / 割引の影響",
      staffing_model: "人員配置モデルの変更",
      season_event: "季節要因 / イベントの影響",
      competitor: "競合の参入 / 撤退",
      macro: "インフレ / 賃金法 / 税制変更",
    },
    pos: {
      other: "その他",
    },
    ops_tools: {
      scheduling: "ワークフォーススケジューリング",
      payroll: "給与計算プロバイダー",
      purchasing: "購買 / 在庫",
      delivery: "デリバリーアグリゲーター管理",
      reservations: "予約 / テーブル管理",
      crm: "顧客 CRM / ロイヤルティ",
      bi: "BI ツール (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "今すぐ - 積極的に評価中",
      next_quarter: "次四半期",
      next_6_months: "今後 6 か月",
      this_year: "年末まで",
      exploring: "情報収集中 · 具体的な時期は未定",
    },
    decision_lag: {
      minutes: "分単位 - シフト中に対応",
      hours: "時間単位 - 当日中",
      days: "日単位 - 週次レビューサイクル",
      weeks: "週単位 - 月次締めサイクル",
      months: "月単位 - 四半期レビューのみ",
    },
    budget_band: {
      under_10k: "$10K 未満",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "未定 / 不明",
    },
    tech_headcount: {
      none: "なし - 専任者はいない",
      fractional: "兼任 / 他部門と共有",
      one: "1 名",
      two_three: "2-3 名",
      four_eight: "4-8 名",
      nine_twenty: "9-20 名",
      twenty_plus: "20+ 名",
    },
  },
  ko: {
    segment: {
      qsr: "QSR / 패스트푸드",
      fast_casual: "패스트 캐주얼",
      casual: "캐주얼 다이닝",
      fine_dining: "파인 다이닝",
      cloud: "클라우드 키친 / 다크 키친",
      hotel_fb: "호텔 F&B",
      cafe_bakery: "카페 / 베이커리",
      bar_nightlife: "바 / 나이트라이프",
      catering: "케이터링 / 이벤트",
      ghost_brand: "고스트 / 가상 브랜드",
      franchise: "프랜차이즈 / 마스터 프랜차이지",
    },
    outlets: {
      "1": "1개 매장",
      "2_5": "2-5개 매장",
      "6_15": "6-15개 매장",
      "16_50": "16-50개 매장",
      "51_150": "51-150개 매장",
      "150_plus": "150+개 매장",
    },
    avg_unit_volume: {
      under_500k: "$500K 미만",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "미국",
      canada: "캐나다",
      uk: "영국",
      ireland: "아일랜드",
      europe_west: "유럽(서부)",
      europe_nord: "유럽(북유럽)",
      europe_east: "유럽(동부)",
      uae: "UAE",
      ksa: "사우디아라비아",
      qatar: "카타르",
      kuwait: "쿠웨이트",
      bahrain: "바레인",
      oman: "오만",
      egypt: "이집트",
      africa: "아프리카(기타)",
      sea: "동남아시아",
      india: "인도",
      japan: "일본",
      korea: "한국",
      china_hk: "중국 / 홍콩",
      anzac: "호주 / 뉴질랜드",
      mexico: "멕시코",
      brazil: "브라질",
      latam_other: "라틴아메리카(기타)",
    },
    scheduling_tool: {
      manual: "수기 / 스프레드시트",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "내부 / 맞춤형 도구",
      pos_built_in: "POS 내장",
      none: "체계적인 방식 없음",
      other: "기타",
    },
    labor_pain: {
      overstaffing: "비수기 시간대 과잉 인력",
      no_show: "노쇼 / 당일 결근",
      ot_leakage: "초과근무 비용 누수",
      buddy_punching: "대리 출퇴근 기록 / 근태 부정",
      payroll_errors: "급여 오류",
      compliance: "컴플라이언스 / 법정 규정",
      turnover: "이직 / 재교육",
      none: "현재 최우선 이슈는 아님",
    },
    payroll_regions: {
      us: "미국",
      canada: "캐나다",
      uk: "영국",
      eu: "유럽연합",
      uae: "UAE",
      ksa: "사우디아라비아",
      qatar: "카타르 / 바레인 / 오만",
      other: "기타(아래에 입력)",
    },
    kpis_measured: {
      labor_pct: "인건비 %",
      food_cost: "식재료비 %",
      void_comp: "취소 / 무료 제공",
      avg_check: "평균 객단가",
      upsell: "업셀 / 부가 판매율",
      guest_retention: "고객 유지율",
      ebitda: "매장별 EBITDA",
      forecast_acc: "예측 정확도",
      compset: "경쟁 포지션",
    },
    kpis_wished: {
      real_time_margin: "교대근무별 실시간 마진",
      daypart_leak: "시간대별 인건비 누수",
      labor_productivity: "실시간 노동 생산성(노동 시간당 매출)",
      live_labor_vs_demand: "실시간 인력 대비 수요(실시간 staffing pace)",
      overtime_leakage: "실시간 초과근무 리스크 및 누수",
      daypart_revpash: "시간대별 RevPASH (Revenue per Available Seat Hour)",
      hourly_food_cost: "시간 단위 식재료비 차이",
      theoretical_actual: "이론 대비 실제 COGS 차이",
      item_profitability: "실제 메뉴 품목별 수익성",
      menu_engineering: "메뉴 엔지니어링 매트릭스 (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "직원별 업셀 부가 판매율",
      cannibalization: "요일 간 / 채널 간 카니벌라이제이션",
      promo_roi: "채널별 프로모션 ROI",
      delivery_margin: "배달 채널 마진(서드파티 수수료 영향)",
      guest_ltv: "고객 생애 가치",
      cohort_retention: "고객 코호트 유지 곡선",
      noshow_prediction: "예약 노쇼 예측",
      inventory_shrinkage: "품목 카테고리별 재고 손실",
      cash_variance: "현금 및 매출 보증 차이(부정 탐지)",
      peer_benchmark: "익명 동종업계 벤치마크",
      competitor_pricing: "경쟁사 가격 추적",
      forecast_per_outlet: "매장별 일일 예측",
      scheduling_eff: "수요 대비 스케줄링 효율",
      decision_replay: "의사결정-결과 폐쇄 루프 스코어링",
      cross_module: "모듈 간 상관 인사이트",
      multi_brand_pnl: "멀티브랜드 통합 P&L",
      compliance_drift: "컴플라이언스 / 브랜드 기준 이탈",
      payroll_readiness: "실시간 급여 준비 상태",
      speed_of_service: "스테이션별 서비스 속도 / 티켓 시간",
      food_waste: "음식물 폐기 및 부패 추적",
      gratuity_distribution: "팁 / 봉사료 배분 및 컴플라이언스",
      guest_sentiment: "고객 정서 / 리뷰 트렌드 추적",
    },
    decision_data: {
      gut: "경험 / 직감",
      spreadsheet: "애널리스트가 추출한 스프레드시트",
      pos_report: "POS 표준 리포트",
      bi_dashboard: "BI 대시보드 (Power BI / Tableau / Looker / Domo)",
      in_house_data: "사내 데이터 웨어하우스 / SQL 쿼리",
      external: "외부 컨설턴트 / 어드바이저",
      ai_tool: "AI 도구 (ChatGPT / Claude / Gemini)",
      industry_report: "업계 리포트 / 벤치마크 연구",
      board_packet: "이사회 / 리더십 보고 패키지",
    },
    forecasting: {
      lyear_gut: "전년도 실적 + 경험적 판단",
      spreadsheet: "내부 관리 스프레드시트 모델",
      pos_system: "POS / 회계 시스템 내장",
      bi_tool: "맞춤형 모델이 있는 BI 도구",
      ai_tool: "전용 AI / 예측 도구",
      none: "공식적인 예측은 하지 않음",
    },
    scenario_wish: {
      new_location: "신규 매장 오픈",
      menu_change: "메뉴 / 가격 변경 영향",
      promo_impact: "프로모션 / 할인 영향",
      staffing_model: "인력 운영 모델 변경",
      season_event: "계절성 / 이벤트 영향",
      competitor: "경쟁사 진입 / 철수",
      macro: "인플레이션 / 임금법 / 세금 변경",
    },
    pos: {
      other: "기타",
    },
    ops_tools: {
      scheduling: "인력 스케줄링",
      payroll: "급여 제공업체",
      purchasing: "구매 / 재고",
      delivery: "배달 애그리게이터 관리",
      reservations: "예약 / 테이블 관리",
      crm: "고객 CRM / 로열티",
      bi: "BI 도구 (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "지금 - 적극적으로 검토 중",
      next_quarter: "다음 분기",
      next_6_months: "향후 6개월",
      this_year: "연말 전",
      exploring: "탐색 중 · 일정 없음",
    },
    decision_lag: {
      minutes: "분 - 교대근무 중 대응",
      hours: "시간 - 당일",
      days: "일 - 주간 리뷰 주기",
      weeks: "주 - 월간 마감 주기",
      months: "개월 - 분기 리뷰만",
    },
    budget_band: {
      under_10k: "$10K 미만",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "확실하지 않음",
    },
    tech_headcount: {
      none: "없음 - 전담 인력이 없음",
      fractional: "파트타임 / 다른 기능과 공유",
      one: "1명",
      two_three: "2-3명",
      four_eight: "4-8명",
      nine_twenty: "9-20명",
      twenty_plus: "20+명",
    },
  },
  id: {
    segment: {
      qsr: "QSR / Makanan cepat saji",
      fast_casual: "Fast-casual",
      casual: "Casual dining",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / Dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Kafe / Toko roti",
      bar_nightlife: "Bar / Hiburan malam",
      catering: "Katering / Acara",
      ghost_brand: "Ghost / Merek virtual",
      franchise: "Waralaba / Master franchisee",
    },
    outlets: {
      "1": "1 gerai",
      "2_5": "2-5 gerai",
      "6_15": "6-15 gerai",
      "16_50": "16-50 gerai",
      "51_150": "51-150 gerai",
      "150_plus": "150+ gerai",
    },
    avg_unit_volume: {
      under_500k: "Di bawah $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Amerika Serikat",
      canada: "Kanada",
      uk: "Britania Raya",
      ireland: "Irlandia",
      europe_west: "Eropa (Barat)",
      europe_nord: "Eropa (Nordik)",
      europe_east: "Eropa (Timur)",
      uae: "UAE",
      ksa: "Arab Saudi",
      qatar: "Qatar",
      kuwait: "Kuwait",
      bahrain: "Bahrain",
      oman: "Oman",
      egypt: "Mesir",
      africa: "Afrika (lainnya)",
      sea: "Asia Tenggara",
      india: "India",
      japan: "Jepang",
      korea: "Korea",
      china_hk: "Tiongkok / Hong Kong",
      anzac: "Australia / Selandia Baru",
      mexico: "Meksiko",
      brazil: "Brasil",
      latam_other: "Amerika Latin (lainnya)",
    },
    scheduling_tool: {
      manual: "Manual / Spreadsheet",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Alat internal / kustom",
      pos_built_in: "Bawaan di POS",
      none: "Belum ada proses sistematis",
      other: "Lainnya",
    },
    labor_pain: {
      overstaffing: "Kelebihan staf saat jam sepi",
      no_show: "Tidak hadir / Pembatalan mendadak",
      ot_leakage: "Kebocoran biaya lembur",
      buddy_punching: "Titip absen / Pencurian waktu kerja",
      payroll_errors: "Kesalahan payroll",
      compliance: "Kepatuhan / Aturan ketenagakerjaan",
      turnover: "Turnover / Pelatihan ulang",
      none: "Bukan perhatian utama saat ini",
    },
    payroll_regions: {
      us: "Amerika Serikat",
      canada: "Kanada",
      uk: "Britania Raya",
      eu: "Uni Eropa",
      uae: "UAE",
      ksa: "Arab Saudi",
      qatar: "Qatar / Bahrain / Oman",
      other: "Lainnya (tulis di bawah)",
    },
    kpis_measured: {
      labor_pct: "Biaya tenaga kerja %",
      food_cost: "Biaya makanan %",
      void_comp: "Void / Comp",
      avg_check: "Rata-rata bill",
      upsell: "Upsell / Attach rate",
      guest_retention: "Retensi tamu",
      ebitda: "EBITDA per gerai",
      forecast_acc: "Akurasi forecast",
      compset: "Posisi kompetitif",
    },
    kpis_wished: {
      real_time_margin: "Margin real-time per shift",
      daypart_leak: "Kebocoran biaya tenaga kerja per daypart",
      labor_productivity: "Produktivitas tenaga kerja real-time (penjualan per jam kerja)",
      live_labor_vs_demand: "Tenaga kerja vs permintaan secara live (real-time staffing pace)",
      overtime_leakage: "Risiko dan kebocoran lembur secara live",
      daypart_revpash: "RevPASH per daypart (Revenue per Available Seat Hour)",
      hourly_food_cost: "Varians biaya makanan per jam",
      theoretical_actual: "Varians COGS teoretis vs aktual",
      item_profitability: "Profitabilitas nyata per item menu",
      menu_engineering: "Matriks rekayasa menu (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Attach rate upsell per server",
      cannibalization: "Kanibalisasi lintas hari / lintas kanal",
      promo_roi: "ROI promo per kanal",
      delivery_margin: "Margin kanal delivery (dampak komisi pihak ketiga)",
      guest_ltv: "Nilai seumur hidup tamu",
      cohort_retention: "Kurva retensi kohort pelanggan",
      noshow_prediction: "Prediksi no-show reservasi",
      inventory_shrinkage: "Shrinkage inventori per kategori item",
      cash_variance: "Varians kas dan revenue assurance (deteksi skim)",
      peer_benchmark: "Benchmark anonim sesama operator",
      competitor_pricing: "Pelacakan harga kompetitor",
      forecast_per_outlet: "Forecast harian per gerai",
      scheduling_eff: "Efisiensi penjadwalan vs permintaan",
      decision_replay: "Skoring closed-loop dari keputusan ke hasil",
      cross_module: "Insight korelasi lintas modul",
      multi_brand_pnl: "P&L konsolidasi multi-brand",
      compliance_drift: "Deviasi kepatuhan / standar brand",
      payroll_readiness: "Kesiapan payroll real-time",
      speed_of_service: "Kecepatan layanan / ticket time per station",
      food_waste: "Pelacakan food waste dan spoilage",
      gratuity_distribution: "Distribusi tip / gratuity dan kepatuhan",
      guest_sentiment: "Sentimen tamu / pelacakan tren ulasan",
    },
    decision_data: {
      gut: "Insting / Pengalaman",
      spreadsheet: "Spreadsheet yang ditarik analis",
      pos_report: "Laporan standar POS",
      bi_dashboard: "Dashboard BI (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Data warehouse internal / kueri SQL",
      external: "Konsultan / advisor eksternal",
      ai_tool: "Alat AI (ChatGPT / Claude / Gemini)",
      industry_report: "Laporan industri / Studi benchmark",
      board_packet: "Paket dewan / leadership",
    },
    forecasting: {
      lyear_gut: "Tahun lalu + intuisi operasional",
      spreadsheet: "Model spreadsheet yang dikelola internal",
      pos_system: "Bawaan di POS / sistem akuntansi",
      bi_tool: "Alat BI dengan model kustom",
      ai_tool: "Alat AI / forecasting khusus",
      none: "Kami belum melakukan forecast formal",
    },
    scenario_wish: {
      new_location: "Membuka lokasi baru",
      menu_change: "Dampak perubahan menu / harga",
      promo_impact: "Dampak promosi / diskon",
      staffing_model: "Perubahan model staffing",
      season_event: "Dampak musiman / event",
      competitor: "Kompetitor masuk / keluar",
      macro: "Inflasi / aturan upah / perubahan pajak",
    },
    pos: {
      other: "Lainnya",
    },
    ops_tools: {
      scheduling: "Penjadwalan tenaga kerja",
      payroll: "Penyedia payroll",
      purchasing: "Pembelian / Inventori",
      delivery: "Manajer aggregator delivery",
      reservations: "Reservasi / Manajemen meja",
      crm: "CRM tamu / Loyalty",
      bi: "Alat BI (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Sekarang - sedang aktif mengevaluasi",
      next_quarter: "Kuartal berikutnya",
      next_6_months: "6 bulan ke depan",
      this_year: "Sebelum akhir tahun",
      exploring: "Masih eksplorasi · Belum ada timeline",
    },
    decision_lag: {
      minutes: "Menit - kami bereaksi saat shift berjalan",
      hours: "Jam - hari yang sama",
      days: "Hari - siklus review mingguan",
      weeks: "Minggu - siklus tutup buku bulanan",
      months: "Bulan - hanya review kuartalan",
    },
    budget_band: {
      under_10k: "Di bawah $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Belum yakin",
    },
    tech_headcount: {
      none: "Tidak ada - belum ada orang khusus",
      fractional: "Fractional / berbagi dengan fungsi lain",
      one: "1 orang",
      two_three: "2-3 orang",
      four_eight: "4-8 orang",
      nine_twenty: "9-20 orang",
      twenty_plus: "20+ orang",
    },
  },
  vi: {
    segment: {
      qsr: "QSR / Đồ ăn nhanh",
      fast_casual: "Fast-casual",
      casual: "Nhà hàng casual dining",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / Dark kitchen",
      hotel_fb: "Khách sạn F&B",
      cafe_bakery: "Cà phê / Tiệm bánh",
      bar_nightlife: "Bar / Nightlife",
      catering: "Catering / Sự kiện",
      ghost_brand: "Ghost / Thương hiệu ảo",
      franchise: "Nhượng quyền / Master franchisee",
    },
    outlets: {
      "1": "1 cửa hàng",
      "2_5": "2-5 cửa hàng",
      "6_15": "6-15 cửa hàng",
      "16_50": "16-50 cửa hàng",
      "51_150": "51-150 cửa hàng",
      "150_plus": "150+ cửa hàng",
    },
    avg_unit_volume: {
      under_500k: "Dưới $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Hoa Kỳ",
      canada: "Canada",
      uk: "Vương quốc Anh",
      ireland: "Ireland",
      europe_west: "Châu Âu (Tây Âu)",
      europe_nord: "Châu Âu (Bắc Âu)",
      europe_east: "Châu Âu (Đông Âu)",
      uae: "UAE",
      ksa: "Ả Rập Xê Út",
      qatar: "Qatar",
      kuwait: "Kuwait",
      bahrain: "Bahrain",
      oman: "Oman",
      egypt: "Ai Cập",
      africa: "Châu Phi (khác)",
      sea: "Đông Nam Á",
      india: "Ấn Độ",
      japan: "Nhật Bản",
      korea: "Hàn Quốc",
      china_hk: "Trung Quốc / Hong Kong",
      anzac: "Úc / New Zealand",
      mexico: "Mexico",
      brazil: "Brazil",
      latam_other: "Mỹ Latinh (khác)",
    },
    scheduling_tool: {
      manual: "Thủ công / Bảng tính",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Công cụ nội bộ / tùy chỉnh",
      pos_built_in: "Tích hợp sẵn trong POS",
      none: "Chưa có quy trình hệ thống",
      other: "Khác",
    },
    labor_pain: {
      overstaffing: "Dư nhân sự trong khung giờ vắng",
      no_show: "Không đến ca / Báo nghỉ đột xuất",
      ot_leakage: "Rò rỉ chi phí tăng ca",
      buddy_punching: "Chấm công hộ / Gian lận thời gian",
      payroll_errors: "Sai sót payroll",
      compliance: "Tuân thủ / Quy định pháp lý",
      turnover: "Nghỉ việc / Đào tạo lại",
      none: "Hiện chưa phải mối quan tâm hàng đầu",
    },
    payroll_regions: {
      us: "Hoa Kỳ",
      canada: "Canada",
      uk: "Vương quốc Anh",
      eu: "Liên minh Châu Âu",
      uae: "UAE",
      ksa: "Ả Rập Xê Út",
      qatar: "Qatar / Bahrain / Oman",
      other: "Khác (ghi bên dưới)",
    },
    kpis_measured: {
      labor_pct: "Chi phí nhân công %",
      food_cost: "Chi phí thực phẩm %",
      void_comp: "Hủy món / Tặng miễn phí",
      avg_check: "Giá trị hóa đơn trung bình",
      upsell: "Upsell / Attach rate",
      guest_retention: "Giữ chân khách",
      ebitda: "EBITDA theo cửa hàng",
      forecast_acc: "Độ chính xác dự báo",
      compset: "Vị thế cạnh tranh",
    },
    kpis_wished: {
      real_time_margin: "Biên lợi nhuận real-time theo ca",
      daypart_leak: "Rò rỉ chi phí nhân công theo daypart",
      labor_productivity: "Năng suất lao động real-time (doanh thu trên mỗi giờ công)",
      live_labor_vs_demand: "Nhân sự so với nhu cầu theo thời gian thực (real-time staffing pace)",
      overtime_leakage: "Rủi ro và rò rỉ tăng ca theo thời gian thực",
      daypart_revpash: "RevPASH theo daypart (Revenue per Available Seat Hour)",
      hourly_food_cost: "Chênh lệch chi phí thực phẩm theo giờ",
      theoretical_actual: "Chênh lệch COGS lý thuyết so với thực tế",
      item_profitability: "Lợi nhuận thực theo từng món",
      menu_engineering: "Ma trận menu engineering (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Attach rate upsell theo nhân viên phục vụ",
      cannibalization: "Cannibalization chéo ngày / chéo kênh",
      promo_roi: "ROI khuyến mãi theo kênh",
      delivery_margin: "Biên lợi nhuận kênh giao hàng (tác động hoa hồng bên thứ ba)",
      guest_ltv: "Giá trị vòng đời khách",
      cohort_retention: "Đường cong giữ chân cohort khách hàng",
      noshow_prediction: "Dự đoán no-show đặt bàn",
      inventory_shrinkage: "Hao hụt tồn kho theo danh mục món",
      cash_variance: "Chênh lệch tiền mặt và revenue assurance (phát hiện skim)",
      peer_benchmark: "Benchmark ẩn danh với đơn vị cùng ngành",
      competitor_pricing: "Theo dõi giá đối thủ",
      forecast_per_outlet: "Dự báo hằng ngày theo cửa hàng",
      scheduling_eff: "Hiệu quả xếp lịch so với nhu cầu",
      decision_replay: "Chấm điểm closed-loop từ quyết định đến kết quả",
      cross_module: "Insight tương quan liên module",
      multi_brand_pnl: "P&L hợp nhất đa thương hiệu",
      compliance_drift: "Lệch chuẩn tuân thủ / tiêu chuẩn thương hiệu",
      payroll_readiness: "Mức sẵn sàng payroll theo thời gian thực",
      speed_of_service: "Tốc độ phục vụ / ticket time theo station",
      food_waste: "Theo dõi lãng phí thực phẩm và hư hỏng",
      gratuity_distribution: "Phân bổ tip / gratuity và tuân thủ",
      guest_sentiment: "Cảm xúc khách / theo dõi xu hướng đánh giá",
    },
    decision_data: {
      gut: "Trực giác / Kinh nghiệm",
      spreadsheet: "Bảng tính do analyst trích xuất",
      pos_report: "Báo cáo chuẩn từ POS",
      bi_dashboard: "Dashboard BI (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Data warehouse nội bộ / truy vấn SQL",
      external: "Tư vấn / cố vấn bên ngoài",
      ai_tool: "Công cụ AI (ChatGPT / Claude / Gemini)",
      industry_report: "Báo cáo ngành / Nghiên cứu benchmark",
      board_packet: "Bộ tài liệu cho hội đồng / leadership",
    },
    forecasting: {
      lyear_gut: "Năm trước + phán đoán kinh nghiệm",
      spreadsheet: "Mô hình bảng tính do nội bộ duy trì",
      pos_system: "Tích hợp sẵn trong POS / hệ thống kế toán",
      bi_tool: "Công cụ BI có mô hình tùy chỉnh",
      ai_tool: "Công cụ AI / forecasting chuyên dụng",
      none: "Chúng tôi chưa dự báo chính thức",
    },
    scenario_wish: {
      new_location: "Mở địa điểm mới",
      menu_change: "Tác động thay đổi menu / giá",
      promo_impact: "Tác động khuyến mãi / giảm giá",
      staffing_model: "Thay đổi mô hình nhân sự",
      season_event: "Tác động mùa vụ / sự kiện",
      competitor: "Đối thủ gia nhập / rút lui",
      macro: "Lạm phát / luật lương / thay đổi thuế",
    },
    pos: {
      other: "Khác",
    },
    ops_tools: {
      scheduling: "Xếp lịch nhân sự",
      payroll: "Nhà cung cấp payroll",
      purchasing: "Mua hàng / Tồn kho",
      delivery: "Quản lý aggregator giao hàng",
      reservations: "Đặt bàn / Quản lý bàn",
      crm: "CRM khách / Loyalty",
      bi: "Công cụ BI (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Ngay bây giờ - đang tích cực đánh giá",
      next_quarter: "Quý tới",
      next_6_months: "6 tháng tới",
      this_year: "Trước cuối năm",
      exploring: "Chỉ đang tìm hiểu · Chưa có timeline",
    },
    decision_lag: {
      minutes: "Phút - chúng tôi phản ứng ngay trong ca",
      hours: "Giờ - trong cùng ngày",
      days: "Ngày - chu kỳ review hằng tuần",
      weeks: "Tuần - chu kỳ chốt sổ hằng tháng",
      months: "Tháng - chỉ review hằng quý",
    },
    budget_band: {
      under_10k: "Dưới $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Chưa chắc",
    },
    tech_headcount: {
      none: "Không có - chưa có người phụ trách riêng",
      fractional: "Bán thời gian / chia sẻ với bộ phận khác",
      one: "1 người",
      two_three: "2-3 người",
      four_eight: "4-8 người",
      nine_twenty: "9-20 người",
      twenty_plus: "20+ người",
    },
  },
  th: {
    segment: {
      qsr: "QSR / อาหารจานด่วน",
      fast_casual: "ฟาสต์แคชชวล",
      casual: "ร้านอาหารแคชชวล",
      fine_dining: "ไฟน์ไดนิ่ง",
      cloud: "คลาวด์คิทเชน / ดาร์กคิทเชน",
      hotel_fb: "โรงแรม F&B",
      cafe_bakery: "คาเฟ่ / เบเกอรี่",
      bar_nightlife: "บาร์ / ไนต์ไลฟ์",
      catering: "จัดเลี้ยง / อีเวนต์",
      ghost_brand: "โกสต์ / แบรนด์เสมือน",
      franchise: "แฟรนไชส์ / มาสเตอร์แฟรนไชซี",
    },
    outlets: {
      "1": "1 สาขา",
      "2_5": "2-5 สาขา",
      "6_15": "6-15 สาขา",
      "16_50": "16-50 สาขา",
      "51_150": "51-150 สาขา",
      "150_plus": "150+ สาขา",
    },
    avg_unit_volume: {
      under_500k: "ต่ำกว่า $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "สหรัฐอเมริกา",
      canada: "แคนาดา",
      uk: "สหราชอาณาจักร",
      ireland: "ไอร์แลนด์",
      europe_west: "ยุโรป (ตะวันตก)",
      europe_nord: "ยุโรป (นอร์ดิก)",
      europe_east: "ยุโรป (ตะวันออก)",
      uae: "UAE",
      ksa: "ซาอุดีอาระเบีย",
      qatar: "กาตาร์",
      kuwait: "คูเวต",
      bahrain: "บาห์เรน",
      oman: "โอมาน",
      egypt: "อียิปต์",
      africa: "แอฟริกา (อื่นๆ)",
      sea: "เอเชียตะวันออกเฉียงใต้",
      india: "อินเดีย",
      japan: "ญี่ปุ่น",
      korea: "เกาหลี",
      china_hk: "จีน / ฮ่องกง",
      anzac: "ออสเตรเลีย / นิวซีแลนด์",
      mexico: "เม็กซิโก",
      brazil: "บราซิล",
      latam_other: "ลาตินอเมริกา (อื่นๆ)",
    },
    scheduling_tool: {
      manual: "ทำเอง / สเปรดชีต",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "เครื่องมือภายใน / เครื่องมือปรับแต่ง",
      pos_built_in: "มีอยู่ใน POS",
      none: "ยังไม่มีระบบที่ชัดเจน",
      other: "อื่นๆ",
    },
    labor_pain: {
      overstaffing: "จัดพนักงานเกินในช่วงเวลายอดขายต่ำ",
      no_show: "ไม่มาเข้ากะ / ลากะกะทันหัน",
      ot_leakage: "ต้นทุนล่วงเวลารั่วไหล",
      buddy_punching: "ตอกบัตรแทน / ทุจริตเวลา",
      payroll_errors: "ข้อผิดพลาด payroll",
      compliance: "การปฏิบัติตามกฎ / ข้อกำหนดตามกฎหมาย",
      turnover: "พนักงานลาออก / ต้องฝึกอบรมใหม่",
      none: "ยังไม่ใช่ประเด็นหลักในตอนนี้",
    },
    payroll_regions: {
      us: "สหรัฐอเมริกา",
      canada: "แคนาดา",
      uk: "สหราชอาณาจักร",
      eu: "สหภาพยุโรป",
      uae: "UAE",
      ksa: "ซาอุดีอาระเบีย",
      qatar: "กาตาร์ / บาห์เรน / โอมาน",
      other: "อื่นๆ (เขียนด้านล่าง)",
    },
    kpis_measured: {
      labor_pct: "ต้นทุนแรงงาน %",
      food_cost: "ต้นทุนอาหาร %",
      void_comp: "Void / Comp",
      avg_check: "ยอดเฉลี่ยต่อบิล",
      upsell: "Upsell / Attach rate",
      guest_retention: "การรักษาลูกค้า",
      ebitda: "EBITDA ต่อสาขา",
      forecast_acc: "ความแม่นยำของการพยากรณ์",
      compset: "ตำแหน่งการแข่งขัน",
    },
    kpis_wished: {
      real_time_margin: "มาร์จินแบบเรียลไทม์ต่อกะ",
      daypart_leak: "ต้นทุนแรงงานรั่วไหลตาม daypart",
      labor_productivity: "ผลิตภาพแรงงานแบบเรียลไทม์ (ยอดขายต่อชั่วโมงแรงงาน)",
      live_labor_vs_demand: "แรงงานเทียบกับดีมานด์แบบสด (real-time staffing pace)",
      overtime_leakage: "ความเสี่ยงและการรั่วไหลของโอทีแบบสด",
      daypart_revpash: "RevPASH ตาม daypart (Revenue per Available Seat Hour)",
      hourly_food_cost: "ส่วนต่างต้นทุนอาหารรายชั่วโมง",
      theoretical_actual: "ส่วนต่าง COGS ตามทฤษฎีเทียบกับจริง",
      item_profitability: "กำไรจริงระดับรายการเมนู",
      menu_engineering: "เมทริกซ์ menu engineering (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Attach rate ของ upsell รายพนักงานเสิร์ฟ",
      cannibalization: "Cannibalization ข้ามวัน / ข้ามช่องทาง",
      promo_roi: "ROI โปรโมชันตามช่องทาง",
      delivery_margin: "มาร์จินช่องทางเดลิเวอรี (ผลกระทบค่าคอมมิชชันบุคคลที่สาม)",
      guest_ltv: "มูลค่าตลอดอายุของลูกค้า",
      cohort_retention: "เส้นโค้งการรักษาลูกค้าตาม cohort",
      noshow_prediction: "การคาดการณ์ no-show ของการจอง",
      inventory_shrinkage: "การหดหายของสต็อกตามหมวดรายการ",
      cash_variance: "ส่วนต่างเงินสดและ revenue assurance (ตรวจจับ skim)",
      peer_benchmark: "Benchmark ไม่ระบุตัวตนกับผู้ประกอบการกลุ่มเดียวกัน",
      competitor_pricing: "ติดตามราคาคู่แข่ง",
      forecast_per_outlet: "พยากรณ์รายวันต่อสาขา",
      scheduling_eff: "ประสิทธิภาพการจัดตารางเทียบกับดีมานด์",
      decision_replay: "การให้คะแนน closed-loop จากการตัดสินใจสู่ผลลัพธ์",
      cross_module: "Insight ความสัมพันธ์ข้ามโมดูล",
      multi_brand_pnl: "P&L รวมหลายแบรนด์",
      compliance_drift: "การเบี่ยงเบนด้าน compliance / มาตรฐานแบรนด์",
      payroll_readiness: "ความพร้อม payroll แบบเรียลไทม์",
      speed_of_service: "ความเร็วบริการ / ticket time ตาม station",
      food_waste: "ติดตาม food waste และการเสื่อมเสีย",
      gratuity_distribution: "การจัดสรรทิป / gratuity และ compliance",
      guest_sentiment: "Sentiment ลูกค้า / ติดตามแนวโน้มรีวิว",
    },
    decision_data: {
      gut: "สัญชาตญาณ / ประสบการณ์",
      spreadsheet: "สเปรดชีตที่ analyst ดึงข้อมูล",
      pos_report: "รายงานมาตรฐานจาก POS",
      bi_dashboard: "แดชบอร์ด BI (Power BI / Tableau / Looker / Domo)",
      in_house_data: "คลังข้อมูลภายใน / คิวรี SQL",
      external: "ที่ปรึกษา / advisor ภายนอก",
      ai_tool: "เครื่องมือ AI (ChatGPT / Claude / Gemini)",
      industry_report: "รายงานอุตสาหกรรม / การศึกษา benchmark",
      board_packet: "แพ็กเกจสำหรับบอร์ด / leadership",
    },
    forecasting: {
      lyear_gut: "ปีก่อน + ประสบการณ์หน้างาน",
      spreadsheet: "โมเดลสเปรดชีตที่ดูแลภายใน",
      pos_system: "มีอยู่ใน POS / ระบบบัญชี",
      bi_tool: "เครื่องมือ BI พร้อมโมเดลปรับแต่ง",
      ai_tool: "เครื่องมือ AI / forecasting เฉพาะทาง",
      none: "เรายังไม่ได้ทำ forecast อย่างเป็นทางการ",
    },
    scenario_wish: {
      new_location: "เปิดสาขาใหม่",
      menu_change: "ผลกระทบจากการเปลี่ยนเมนู / ราคา",
      promo_impact: "ผลกระทบจากโปรโมชัน / ส่วนลด",
      staffing_model: "เปลี่ยนโมเดลการจัดพนักงาน",
      season_event: "ผลกระทบตามฤดูกาล / อีเวนต์",
      competitor: "คู่แข่งเข้ามา / ออกจากตลาด",
      macro: "เงินเฟ้อ / กฎหมายค่าจ้าง / การเปลี่ยนภาษี",
    },
    pos: {
      other: "อื่นๆ",
    },
    ops_tools: {
      scheduling: "การจัดตารางพนักงาน",
      payroll: "ผู้ให้บริการ payroll",
      purchasing: "จัดซื้อ / สต็อก",
      delivery: "จัดการ aggregator เดลิเวอรี",
      reservations: "การจอง / จัดการโต๊ะ",
      crm: "CRM ลูกค้า / Loyalty",
      bi: "เครื่องมือ BI (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "ตอนนี้ - กำลังประเมินอย่างจริงจัง",
      next_quarter: "ไตรมาสหน้า",
      next_6_months: "อีก 6 เดือนข้างหน้า",
      this_year: "ก่อนสิ้นปี",
      exploring: "กำลังสำรวจเท่านั้น · ยังไม่มีไทม์ไลน์",
    },
    decision_lag: {
      minutes: "นาที - เราตอบสนองระหว่างกะ",
      hours: "ชั่วโมง - ภายในวันเดียวกัน",
      days: "วัน - รอบรีวิวรายสัปดาห์",
      weeks: "สัปดาห์ - รอบปิดบัญชีรายเดือน",
      months: "เดือน - รีวิวรายไตรมาสเท่านั้น",
    },
    budget_band: {
      under_10k: "ต่ำกว่า $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "ยังไม่แน่ใจ",
    },
    tech_headcount: {
      none: "ไม่มี - เรายังไม่มีคนดูแลเฉพาะ",
      fractional: "บางส่วน / แชร์กับฟังก์ชันอื่น",
      one: "1 คน",
      two_three: "2-3 คน",
      four_eight: "4-8 คน",
      nine_twenty: "9-20 คน",
      twenty_plus: "20+ คน",
    },
  },
  ms: {
    segment: {
      qsr: "QSR / Makanan segera",
      fast_casual: "Fast-casual",
      casual: "Casual dining",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / Dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Kafe / Bakeri",
      bar_nightlife: "Bar / Hiburan malam",
      catering: "Katering / Acara",
      ghost_brand: "Ghost / Jenama maya",
      franchise: "Francais / Master franchisee",
    },
    outlets: {
      "1": "1 cawangan",
      "2_5": "2-5 cawangan",
      "6_15": "6-15 cawangan",
      "16_50": "16-50 cawangan",
      "51_150": "51-150 cawangan",
      "150_plus": "150+ cawangan",
    },
    avg_unit_volume: {
      under_500k: "Di bawah $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Amerika Syarikat",
      canada: "Kanada",
      uk: "United Kingdom",
      ireland: "Ireland",
      europe_west: "Eropah (Barat)",
      europe_nord: "Eropah (Nordik)",
      europe_east: "Eropah (Timur)",
      uae: "UAE",
      ksa: "Arab Saudi",
      qatar: "Qatar",
      kuwait: "Kuwait",
      bahrain: "Bahrain",
      oman: "Oman",
      egypt: "Mesir",
      africa: "Afrika (lain-lain)",
      sea: "Asia Tenggara",
      india: "India",
      japan: "Jepun",
      korea: "Korea",
      china_hk: "China / Hong Kong",
      anzac: "Australia / New Zealand",
      mexico: "Mexico",
      brazil: "Brazil",
      latam_other: "Amerika Latin (lain-lain)",
    },
    scheduling_tool: {
      manual: "Manual / Hamparan",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Alat dalaman / tersuai",
      pos_built_in: "Terbina dalam POS",
      none: "Tiada proses sistematik",
      other: "Lain-lain",
    },
    labor_pain: {
      overstaffing: "Lebihan staf pada waktu perlahan",
      no_show: "Tidak hadir / Panggilan batal syif",
      ot_leakage: "Kebocoran kos lebih masa",
      buddy_punching: "Punch-in wakil / Kecurian masa",
      payroll_errors: "Ralat payroll",
      compliance: "Pematuhan / Peraturan berkanun",
      turnover: "Turnover / Latihan semula",
      none: "Bukan kebimbangan utama hari ini",
    },
    payroll_regions: {
      us: "Amerika Syarikat",
      canada: "Kanada",
      uk: "United Kingdom",
      eu: "Kesatuan Eropah",
      uae: "UAE",
      ksa: "Arab Saudi",
      qatar: "Qatar / Bahrain / Oman",
      other: "Lain-lain (tulis di bawah)",
    },
    kpis_measured: {
      labor_pct: "Kos buruh %",
      food_cost: "Kos makanan %",
      void_comp: "Void / Comp",
      avg_check: "Purata bil",
      upsell: "Upsell / Attach rate",
      guest_retention: "Pengekalan tetamu",
      ebitda: "EBITDA setiap cawangan",
      forecast_acc: "Ketepatan forecast",
      compset: "Kedudukan kompetitif",
    },
    kpis_wished: {
      real_time_margin: "Margin masa nyata setiap syif",
      daypart_leak: "Kebocoran kos buruh mengikut daypart",
      labor_productivity: "Produktiviti buruh masa nyata (jualan setiap jam buruh)",
      live_labor_vs_demand: "Buruh vs permintaan secara live (real-time staffing pace)",
      overtime_leakage: "Risiko dan kebocoran lebih masa secara live",
      daypart_revpash: "RevPASH mengikut daypart (Revenue per Available Seat Hour)",
      hourly_food_cost: "Varians kos makanan mengikut jam",
      theoretical_actual: "Varians COGS teori vs sebenar",
      item_profitability: "Keuntungan sebenar per item menu",
      menu_engineering: "Matriks menu engineering (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Attach rate upsell mengikut server",
      cannibalization: "Cannibalization rentas hari / rentas saluran",
      promo_roi: "ROI promo mengikut saluran",
      delivery_margin: "Margin saluran penghantaran (kesan komisen pihak ketiga)",
      guest_ltv: "Nilai hayat tetamu",
      cohort_retention: "Keluk pengekalan kohort pelanggan",
      noshow_prediction: "Ramalan no-show tempahan",
      inventory_shrinkage: "Shrinkage inventori mengikut kategori item",
      cash_variance: "Varians tunai dan revenue assurance (pengesanan skim)",
      peer_benchmark: "Benchmark rakan industri tanpa nama",
      competitor_pricing: "Penjejakan harga pesaing",
      forecast_per_outlet: "Forecast harian setiap cawangan",
      scheduling_eff: "Kecekapan penjadualan vs permintaan",
      decision_replay: "Skor closed-loop daripada keputusan kepada hasil",
      cross_module: "Insight korelasi rentas modul",
      multi_brand_pnl: "P&L disatukan pelbagai jenama",
      compliance_drift: "Drift pematuhan / standard jenama",
      payroll_readiness: "Kesediaan payroll masa nyata",
      speed_of_service: "Kelajuan servis / ticket time mengikut station",
      food_waste: "Penjejakan food waste dan spoilage",
      gratuity_distribution: "Agihan tip / gratuity dan pematuhan",
      guest_sentiment: "Sentimen tetamu / penjejakan trend ulasan",
    },
    decision_data: {
      gut: "Gerak hati / Pengalaman",
      spreadsheet: "Hamparan yang ditarik oleh analyst",
      pos_report: "Laporan standard POS",
      bi_dashboard: "Dashboard BI (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Data warehouse dalaman / kueri SQL",
      external: "Perunding / advisor luar",
      ai_tool: "Alat AI (ChatGPT / Claude / Gemini)",
      industry_report: "Laporan industri / Kajian benchmark",
      board_packet: "Paket lembaga / leadership",
    },
    forecasting: {
      lyear_gut: "Tahun lepas + pertimbangan pengalaman",
      spreadsheet: "Model hamparan yang diselenggara dalaman",
      pos_system: "Terbina dalam POS / sistem perakaunan",
      bi_tool: "Alat BI dengan model tersuai",
      ai_tool: "Alat AI / forecasting khusus",
      none: "Kami tidak membuat forecast formal",
    },
    scenario_wish: {
      new_location: "Membuka lokasi baharu",
      menu_change: "Kesan perubahan menu / harga",
      promo_impact: "Kesan promosi / diskaun",
      staffing_model: "Perubahan model staffing",
      season_event: "Kesan bermusim / acara",
      competitor: "Pesaing masuk / keluar",
      macro: "Inflasi / undang-undang gaji / perubahan cukai",
    },
    pos: {
      other: "Lain-lain",
    },
    ops_tools: {
      scheduling: "Penjadualan tenaga kerja",
      payroll: "Penyedia payroll",
      purchasing: "Pembelian / Inventori",
      delivery: "Pengurus aggregator penghantaran",
      reservations: "Tempahan / Pengurusan meja",
      crm: "CRM tetamu / Loyalty",
      bi: "Alat BI (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Sekarang - sedang menilai secara aktif",
      next_quarter: "Suku tahun depan",
      next_6_months: "6 bulan akan datang",
      this_year: "Sebelum akhir tahun",
      exploring: "Sekadar meneroka · Tiada timeline",
    },
    decision_lag: {
      minutes: "Minit - kami bertindak balas semasa syif",
      hours: "Jam - hari yang sama",
      days: "Hari - kitaran semakan mingguan",
      weeks: "Minggu - kitaran penutupan bulanan",
      months: "Bulan - semakan suku tahunan sahaja",
    },
    budget_band: {
      under_10k: "Di bawah $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Belum pasti",
    },
    tech_headcount: {
      none: "Tiada - kami belum ada orang khusus",
      fractional: "Fractional / dikongsi dengan fungsi lain",
      one: "1 orang",
      two_three: "2-3 orang",
      four_eight: "4-8 orang",
      nine_twenty: "9-20 orang",
      twenty_plus: "20+ orang",
    },
  },
} as const;

export type DiagnosticAsiaOptionPackLocale = keyof typeof asiaDiagnosticOptionPacks;
