export const europeDiagnosticOptionPacks = {
  nl: {
    segment: {
      qsr: "QSR / fastfood",
      fast_casual: "Fast-casual",
      casual: "Casual dining",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Café / bakkerij",
      bar_nightlife: "Bar / nightlife",
      catering: "Catering / events",
      ghost_brand: "Ghost / virtueel merk",
      franchise: "Franchise / masterfranchisenemer",
    },
    outlets: {
      "1": "1 vestiging",
      "2_5": "2-5 vestigingen",
      "6_15": "6-15 vestigingen",
      "16_50": "16-50 vestigingen",
      "51_150": "51-150 vestigingen",
      "150_plus": "150+ vestigingen",
    },
    avg_unit_volume: {
      under_500k: "Minder dan $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Verenigde Staten",
      canada: "Canada",
      uk: "Verenigd Koninkrijk",
      ireland: "Ierland",
      europe_west: "Europa (West)",
      europe_nord: "Europa (Noord)",
      europe_east: "Europa (Oost)",
      uae: "UAE",
      ksa: "Saoedi-Arabië",
      qatar: "Qatar",
      kuwait: "Koeweit",
      bahrain: "Bahrein",
      oman: "Oman",
      egypt: "Egypte",
      africa: "Afrika (overig)",
      sea: "Zuidoost-Azië",
      india: "India",
      japan: "Japan",
      korea: "Korea",
      china_hk: "China / Hongkong",
      anzac: "Australië / Nieuw-Zeeland",
      mexico: "Mexico",
      brazil: "Brazilië",
      latam_other: "Latijns-Amerika (overig)",
    },
    scheduling_tool: {
      manual: "Handmatig / spreadsheets",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Interne / maatwerktool",
      pos_built_in: "Ingebouwd in POS",
      none: "Geen systematische aanpak",
      other: "Anders",
    },
    labor_pain: {
      overstaffing: "Overbezetting tijdens rustige momenten",
      no_show: "No-shows / afmeldingen",
      ot_leakage: "Lekkage door overuren",
      buddy_punching: "Buddy-punching / tijdsdiefstal",
      payroll_errors: "Fouten in de loonadministratie",
      compliance: "Compliance / wettelijke regels",
      turnover: "Verloop / opnieuw inwerken",
      none: "Vandaag geen topprioriteit",
    },
    payroll_regions: {
      us: "Verenigde Staten",
      canada: "Canada",
      uk: "Verenigd Koninkrijk",
      eu: "Europese Unie",
      uae: "UAE",
      ksa: "Saoedi-Arabië",
      qatar: "Qatar / Bahrein / Oman",
      other: "Anders (hieronder invullen)",
    },
    kpis_measured: {
      labor_pct: "Arbeidskosten %",
      food_cost: "Food cost %",
      void_comp: "Annuleringen / compensaties",
      avg_check: "Gemiddelde besteding",
      upsell: "Upsell / attach rate",
      guest_retention: "Gastretentie",
      ebitda: "EBITDA per vestiging",
      forecast_acc: "Forecastnauwkeurigheid",
      compset: "Concurrentiepositie",
    },
    kpis_wished: {
      real_time_margin: "Realtime marge per shift",
      daypart_leak: "Arbeidslekkage per dagdeel",
      labor_productivity: "Realtime arbeidsproductiviteit (omzet per arbeidsuur)",
      live_labor_vs_demand: "Live bezetting versus vraag (realtime staffing pace)",
      overtime_leakage: "Overurenrisico en lekkage, live",
      daypart_revpash: "RevPASH per dagdeel (omzet per beschikbaar stoeluur)",
      hourly_food_cost: "Food-costafwijking per uur",
      theoretical_actual: "Theoretische versus werkelijke COGS-afwijking",
      item_profitability: "Werkelijke winstgevendheid per artikel",
      menu_engineering: "Menu-engineeringmatrix (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Upsell-attach rate per medewerker",
      cannibalization: "Kannibalisatie over dagen en kanalen",
      promo_roi: "Promotie-ROI per kanaal",
      delivery_margin: "Marge per bezorgkanaal (druk van commissies van derden)",
      guest_ltv: "Levenslange gastwaarde",
      cohort_retention: "Retentiecurves per klantcohort",
      noshow_prediction: "Voorspelling van no-shows bij reserveringen",
      inventory_shrinkage: "Voorraadkrimp per artikelcategorie",
      cash_variance: "Kas- en revenue-assuranceafwijking (detectie van afroming)",
      peer_benchmark: "Anonieme peerbenchmark",
      competitor_pricing: "Tracking van concurrentieprijzen",
      forecast_per_outlet: "Dagelijkse forecast per vestiging",
      scheduling_eff: "Roosterefficiëntie versus vraag",
      decision_replay: "Closed-loop scoring van beslissing naar resultaat",
      cross_module: "Cross-module correlatie-inzichten",
      multi_brand_pnl: "Geconsolideerde P&L over meerdere merken",
      compliance_drift: "Afwijking in compliance / merkstandaarden",
      payroll_readiness: "Realtime gereedheid voor payroll",
      speed_of_service: "Servicesnelheid / tickettijden per station",
      food_waste: "Tracking van voedselverspilling en bederf",
      gratuity_distribution: "Fooi- / gratuityverdeling en compliance",
      guest_sentiment: "Gastsentiment / trendanalyse van reviews",
    },
    decision_data: {
      gut: "Intuïtie / ervaring",
      spreadsheet: "Spreadsheet opgesteld door een analist",
      pos_report: "Standaard POS-rapport",
      bi_dashboard: "BI-dashboard (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Intern datawarehouse / SQL-query's",
      external: "Externe consultant / adviseur",
      ai_tool: "AI-tool (ChatGPT / Claude / Gemini)",
      industry_report: "Sectorrapport / benchmarkstudie",
      board_packet: "Board- / managementpakket",
    },
    forecasting: {
      lyear_gut: "Vorig jaar + inschatting op ervaring",
      spreadsheet: "Intern beheerd spreadsheetmodel",
      pos_system: "Ingebouwd in POS / boekhoudsysteem",
      bi_tool: "BI-tool met maatwerkmodel",
      ai_tool: "Specifieke AI- / forecastingtool",
      none: "We forecasten niet formeel",
    },
    scenario_wish: {
      new_location: "Een nieuwe locatie openen",
      menu_change: "Impact van menu- / prijswijzigingen",
      promo_impact: "Impact van promoties / kortingen",
      staffing_model: "Wijziging in het personeelsmodel",
      season_event: "Seizoens- / eventimpact",
      competitor: "Toetreding / vertrek van een concurrent",
      macro: "Inflatie / loonwetgeving / belastingwijziging",
    },
    pos: {
      other: "Anders",
    },
    ops_tools: {
      scheduling: "Personeelsplanning",
      payroll: "Payrollprovider",
      purchasing: "Inkoop / voorraad",
      delivery: "Manager voor delivery-aggregators",
      reservations: "Reserveringen / tafelbeheer",
      crm: "Gast-CRM / loyaliteit",
      bi: "BI-tool (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Nu - actief aan het evalueren",
      next_quarter: "Volgend kwartaal",
      next_6_months: "De komende 6 maanden",
      this_year: "Voor het einde van het jaar",
      exploring: "Alleen aan het verkennen · geen planning",
    },
    decision_lag: {
      minutes: "Minuten - we reageren tijdens de shift",
      hours: "Uren - dezelfde dag",
      days: "Dagen - wekelijkse reviewcyclus",
      weeks: "Weken - maandelijkse afsluitcyclus",
      months: "Maanden - alleen kwartaalreviews",
    },
    budget_band: {
      under_10k: "Minder dan $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Niet zeker",
    },
    tech_headcount: {
      none: "Geen - we hebben niemand toegewezen",
      fractional: "Fractioneel / gedeeld met andere functies",
      one: "1 persoon",
      two_three: "2-3 personen",
      four_eight: "4-8 personen",
      nine_twenty: "9-20 personen",
      twenty_plus: "20+ personen",
    },
  },
  pt: {
    segment: {
      qsr: "QSR / fast food",
      fast_casual: "Fast-casual",
      casual: "Restauração casual",
      fine_dining: "Fine dining",
      cloud: "Cozinha cloud / dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Café / pastelaria",
      bar_nightlife: "Bar / vida noturna",
      catering: "Catering / eventos",
      ghost_brand: "Marca ghost / virtual",
      franchise: "Franchise / master franchisee",
    },
    outlets: {
      "1": "1 unidade",
      "2_5": "2-5 unidades",
      "6_15": "6-15 unidades",
      "16_50": "16-50 unidades",
      "51_150": "51-150 unidades",
      "150_plus": "150+ unidades",
    },
    avg_unit_volume: {
      under_500k: "Menos de $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Estados Unidos",
      canada: "Canadá",
      uk: "Reino Unido",
      ireland: "Irlanda",
      europe_west: "Europa (Ocidental)",
      europe_nord: "Europa (Nórdica)",
      europe_east: "Europa (Oriental)",
      uae: "UAE",
      ksa: "Arábia Saudita",
      qatar: "Qatar",
      kuwait: "Kuwait",
      bahrain: "Bahrein",
      oman: "Omã",
      egypt: "Egito",
      africa: "África (outros)",
      sea: "Sudeste Asiático",
      india: "Índia",
      japan: "Japão",
      korea: "Coreia",
      china_hk: "China / Hong Kong",
      anzac: "Austrália / Nova Zelândia",
      mexico: "México",
      brazil: "Brasil",
      latam_other: "América Latina (outros)",
    },
    scheduling_tool: {
      manual: "Manual / folhas de cálculo",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Ferramenta interna / personalizada",
      pos_built_in: "Integrado no POS",
      none: "Sem processo sistemático",
      other: "Outro",
    },
    labor_pain: {
      overstaffing: "Excesso de equipa em períodos de baixa procura",
      no_show: "No-shows / faltas de última hora",
      ot_leakage: "Fuga em horas extra",
      buddy_punching: "Registo de ponto por terceiros / fraude de horas",
      payroll_errors: "Erros de processamento salarial",
      compliance: "Compliance / regras legais",
      turnover: "Rotatividade / nova formação",
      none: "Não é uma prioridade hoje",
    },
    payroll_regions: {
      us: "Estados Unidos",
      canada: "Canadá",
      uk: "Reino Unido",
      eu: "União Europeia",
      uae: "UAE",
      ksa: "Arábia Saudita",
      qatar: "Qatar / Bahrein / Omã",
      other: "Outro (indique abaixo)",
    },
    kpis_measured: {
      labor_pct: "Custo de pessoal %",
      food_cost: "Food cost %",
      void_comp: "Anulações / ofertas",
      avg_check: "Ticket médio",
      upsell: "Upsell / attach rate",
      guest_retention: "Retenção de clientes",
      ebitda: "EBITDA por unidade",
      forecast_acc: "Precisão da previsão",
      compset: "Posição competitiva",
    },
    kpis_wished: {
      real_time_margin: "Margem em tempo real por turno",
      daypart_leak: "Fuga de custo de pessoal por período do dia",
      labor_productivity: "Produtividade de pessoal em tempo real (vendas por hora de trabalho)",
      live_labor_vs_demand: "Equipa em direto versus procura (ritmo de staffing em tempo real)",
      overtime_leakage: "Risco e fuga de horas extra, em direto",
      daypart_revpash: "RevPASH por período do dia (receita por hora de lugar disponível)",
      hourly_food_cost: "Variação de food cost por hora",
      theoretical_actual: "Variação entre COGS teórico e real",
      item_profitability: "Rentabilidade real por artigo",
      menu_engineering: "Matriz de engenharia de menu (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Attach rate de upsell por colaborador",
      cannibalization: "Canibalização entre dias / canais",
      promo_roi: "ROI de promoções por canal",
      delivery_margin: "Margem por canal de delivery (impacto das comissões de terceiros)",
      guest_ltv: "Valor vitalício do cliente",
      cohort_retention: "Curvas de retenção por coorte de clientes",
      noshow_prediction: "Previsão de no-shows em reservas",
      inventory_shrinkage: "Quebras de inventário por categoria de artigo",
      cash_variance: "Variação de caixa e revenue assurance (deteção de desvios)",
      peer_benchmark: "Benchmark anónimo entre pares",
      competitor_pricing: "Monitorização de preços da concorrência",
      forecast_per_outlet: "Previsão diária por unidade",
      scheduling_eff: "Eficiência de escalas versus procura",
      decision_replay: "Scoring em ciclo fechado entre decisão e resultado",
      cross_module: "Insights de correlação entre módulos",
      multi_brand_pnl: "P&L consolidado multi-marca",
      compliance_drift: "Desvio de compliance / standards da marca",
      payroll_readiness: "Prontidão de payroll em tempo real",
      speed_of_service: "Velocidade de serviço / tempos de pedido por estação",
      food_waste: "Monitorização de desperdício alimentar e deterioração",
      gratuity_distribution: "Distribuição de gorjetas / gratificações e compliance",
      guest_sentiment: "Sentimento do cliente / tendências de avaliações",
    },
    decision_data: {
      gut: "Intuição / experiência",
      spreadsheet: "Folha de cálculo preparada por analista",
      pos_report: "Relatório standard do POS",
      bi_dashboard: "Dashboard de BI (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Data warehouse interno / consultas SQL",
      external: "Consultor / assessor externo",
      ai_tool: "Ferramenta de AI (ChatGPT / Claude / Gemini)",
      industry_report: "Relatório setorial / estudo de benchmark",
      board_packet: "Pacote para administração / liderança",
    },
    forecasting: {
      lyear_gut: "Ano anterior + intuição operacional",
      spreadsheet: "Modelo em folha de cálculo mantido internamente",
      pos_system: "Integrado no POS / sistema contabilístico",
      bi_tool: "Ferramenta de BI com modelo personalizado",
      ai_tool: "Ferramenta dedicada de AI / previsão",
      none: "Não fazemos previsão formal",
    },
    scenario_wish: {
      new_location: "Abrir uma nova localização",
      menu_change: "Impacto de alterações de menu / preços",
      promo_impact: "Impacto de promoções / descontos",
      staffing_model: "Alteração do modelo de equipa",
      season_event: "Impacto sazonal / de evento",
      competitor: "Entrada / saída de concorrente",
      macro: "Inflação / legislação salarial / alteração fiscal",
    },
    pos: {
      other: "Outro",
    },
    ops_tools: {
      scheduling: "Escalas de equipa",
      payroll: "Fornecedor de payroll",
      purchasing: "Compras / inventário",
      delivery: "Gestor de agregadores de delivery",
      reservations: "Reservas / gestão de mesas",
      crm: "CRM de clientes / fidelização",
      bi: "Ferramenta de BI (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Agora - estamos a avaliar ativamente",
      next_quarter: "Próximo trimestre",
      next_6_months: "Próximos 6 meses",
      this_year: "Antes do final do ano",
      exploring: "Apenas a explorar · sem calendário",
    },
    decision_lag: {
      minutes: "Minutos - reagimos durante o turno",
      hours: "Horas - no próprio dia",
      days: "Dias - ciclo de revisão semanal",
      weeks: "Semanas - ciclo de fecho mensal",
      months: "Meses - apenas revisão trimestral",
    },
    budget_band: {
      under_10k: "Menos de $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Não sei",
    },
    tech_headcount: {
      none: "Nenhuma - não temos ninguém dedicado",
      fractional: "Parcial / partilhado com outras funções",
      one: "1 pessoa",
      two_three: "2-3 pessoas",
      four_eight: "4-8 pessoas",
      nine_twenty: "9-20 pessoas",
      twenty_plus: "20+ pessoas",
    },
  },
  it: {
    segment: {
      qsr: "QSR / fast food",
      fast_casual: "Fast-casual",
      casual: "Ristorazione casual",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Caffè / panetteria",
      bar_nightlife: "Bar / nightlife",
      catering: "Catering / eventi",
      ghost_brand: "Brand ghost / virtuale",
      franchise: "Franchise / master franchisee",
    },
    outlets: {
      "1": "1 punto vendita",
      "2_5": "2-5 punti vendita",
      "6_15": "6-15 punti vendita",
      "16_50": "16-50 punti vendita",
      "51_150": "51-150 punti vendita",
      "150_plus": "150+ punti vendita",
    },
    avg_unit_volume: {
      under_500k: "Meno di $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Stati Uniti",
      canada: "Canada",
      uk: "Regno Unito",
      ireland: "Irlanda",
      europe_west: "Europa (occidentale)",
      europe_nord: "Europa (nordica)",
      europe_east: "Europa (orientale)",
      uae: "UAE",
      ksa: "Arabia Saudita",
      qatar: "Qatar",
      kuwait: "Kuwait",
      bahrain: "Bahrein",
      oman: "Oman",
      egypt: "Egitto",
      africa: "Africa (altro)",
      sea: "Sud-est asiatico",
      india: "India",
      japan: "Giappone",
      korea: "Corea",
      china_hk: "Cina / Hong Kong",
      anzac: "Australia / Nuova Zelanda",
      mexico: "Messico",
      brazil: "Brasile",
      latam_other: "America Latina (altro)",
    },
    scheduling_tool: {
      manual: "Manuale / fogli di calcolo",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Strumento interno / personalizzato",
      pos_built_in: "Integrato nel POS",
      none: "Nessun processo sistematico",
      other: "Altro",
    },
    labor_pain: {
      overstaffing: "Sovraorganico nelle fasce di bassa domanda",
      no_show: "No-show / assenze comunicate all'ultimo",
      ot_leakage: "Dispersione da straordinari",
      buddy_punching: "Timbratura per conto terzi / furto di tempo",
      payroll_errors: "Errori nelle paghe",
      compliance: "Compliance / norme di legge",
      turnover: "Turnover / nuova formazione",
      none: "Oggi non è una priorità",
    },
    payroll_regions: {
      us: "Stati Uniti",
      canada: "Canada",
      uk: "Regno Unito",
      eu: "Unione Europea",
      uae: "UAE",
      ksa: "Arabia Saudita",
      qatar: "Qatar / Bahrein / Oman",
      other: "Altro (specificare sotto)",
    },
    kpis_measured: {
      labor_pct: "Costo del lavoro %",
      food_cost: "Food cost %",
      void_comp: "Annullamenti / omaggi",
      avg_check: "Scontrino medio",
      upsell: "Upsell / attach rate",
      guest_retention: "Retention degli ospiti",
      ebitda: "EBITDA per punto vendita",
      forecast_acc: "Accuratezza del forecast",
      compset: "Posizionamento competitivo",
    },
    kpis_wished: {
      real_time_margin: "Margine in tempo reale per turno",
      daypart_leak: "Dispersione del lavoro per fascia oraria",
      labor_productivity: "Produttività del lavoro in tempo reale (vendite per ora lavorata)",
      live_labor_vs_demand: "Lavoro live rispetto alla domanda (ritmo di staffing in tempo reale)",
      overtime_leakage: "Rischio e dispersione da straordinari, live",
      daypart_revpash: "RevPASH per fascia oraria (ricavo per ora di posto disponibile)",
      hourly_food_cost: "Scostamento del food cost per ora",
      theoretical_actual: "Scostamento tra COGS teorico e reale",
      item_profitability: "Redditività reale a livello di articolo",
      menu_engineering: "Matrice di menu engineering (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Attach rate di upsell per cameriere",
      cannibalization: "Cannibalizzazione tra giorni / canali",
      promo_roi: "ROI delle promo per canale",
      delivery_margin: "Margine del canale delivery (impatto delle commissioni di terzi)",
      guest_ltv: "Valore del ciclo di vita dell'ospite",
      cohort_retention: "Curve di retention per coorte clienti",
      noshow_prediction: "Previsione dei no-show sulle prenotazioni",
      inventory_shrinkage: "Calo inventariale per categoria articolo",
      cash_variance: "Scostamento cassa e revenue assurance (rilevamento ammanchi)",
      peer_benchmark: "Benchmark anonimo tra pari",
      competitor_pricing: "Monitoraggio dei prezzi dei concorrenti",
      forecast_per_outlet: "Forecast giornaliero per punto vendita",
      scheduling_eff: "Efficienza della pianificazione rispetto alla domanda",
      decision_replay: "Scoring closed-loop da decisione a risultato",
      cross_module: "Insight di correlazione cross-module",
      multi_brand_pnl: "P&L consolidato multi-brand",
      compliance_drift: "Deriva di compliance / standard di brand",
      payroll_readiness: "Prontezza payroll in tempo reale",
      speed_of_service: "Velocità di servizio / tempi ticket per postazione",
      food_waste: "Monitoraggio di sprechi alimentari e deterioramento",
      gratuity_distribution: "Distribuzione mance / gratuity e compliance",
      guest_sentiment: "Sentiment degli ospiti / trend delle recensioni",
    },
    decision_data: {
      gut: "Intuito / esperienza",
      spreadsheet: "Foglio di calcolo preparato da un analista",
      pos_report: "Report standard del POS",
      bi_dashboard: "Dashboard BI (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Data warehouse interno / query SQL",
      external: "Consulente / advisor esterno",
      ai_tool: "Strumento AI (ChatGPT / Claude / Gemini)",
      industry_report: "Report di settore / studio benchmark",
      board_packet: "Pacchetto per board / leadership",
    },
    forecasting: {
      lyear_gut: "Anno precedente + intuito operativo",
      spreadsheet: "Modello su foglio di calcolo gestito internamente",
      pos_system: "Integrato nel POS / sistema contabile",
      bi_tool: "Strumento BI con modello personalizzato",
      ai_tool: "Strumento AI / forecasting dedicato",
      none: "Non facciamo forecast formali",
    },
    scenario_wish: {
      new_location: "Aprire una nuova sede",
      menu_change: "Impatto di modifiche a menu / prezzi",
      promo_impact: "Impatto di promozioni / sconti",
      staffing_model: "Modifica del modello di staffing",
      season_event: "Impatto stagionale / evento",
      competitor: "Ingresso / uscita di un concorrente",
      macro: "Inflazione / legge salariale / modifica fiscale",
    },
    pos: {
      other: "Altro",
    },
    ops_tools: {
      scheduling: "Pianificazione del personale",
      payroll: "Provider payroll",
      purchasing: "Acquisti / inventario",
      delivery: "Gestore aggregatori delivery",
      reservations: "Prenotazioni / gestione tavoli",
      crm: "CRM ospiti / loyalty",
      bi: "Strumento BI (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Subito - stiamo valutando attivamente",
      next_quarter: "Prossimo trimestre",
      next_6_months: "Prossimi 6 mesi",
      this_year: "Entro fine anno",
      exploring: "Solo esplorazione · nessuna timeline",
    },
    decision_lag: {
      minutes: "Minuti - reagiamo durante il turno",
      hours: "Ore - nella stessa giornata",
      days: "Giorni - ciclo di revisione settimanale",
      weeks: "Settimane - ciclo di chiusura mensile",
      months: "Mesi - solo revisione trimestrale",
    },
    budget_band: {
      under_10k: "Meno di $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Non so",
    },
    tech_headcount: {
      none: "Nessuno - non abbiamo una persona dedicata",
      fractional: "Fractional / condiviso con altre funzioni",
      one: "1 persona",
      two_three: "2-3 persone",
      four_eight: "4-8 persone",
      nine_twenty: "9-20 persone",
      twenty_plus: "20+ persone",
    },
  },
  pl: {
    segment: {
      qsr: "QSR / fast food",
      fast_casual: "Fast-casual",
      casual: "Restauracja casual dining",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Kawiarnia / piekarnia",
      bar_nightlife: "Bar / nightlife",
      catering: "Catering / eventy",
      ghost_brand: "Ghost / marka wirtualna",
      franchise: "Franczyza / master franchisee",
    },
    outlets: {
      "1": "1 lokal",
      "2_5": "2-5 lokali",
      "6_15": "6-15 lokali",
      "16_50": "16-50 lokali",
      "51_150": "51-150 lokali",
      "150_plus": "150+ lokali",
    },
    avg_unit_volume: {
      under_500k: "Poniżej $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Stany Zjednoczone",
      canada: "Kanada",
      uk: "Wielka Brytania",
      ireland: "Irlandia",
      europe_west: "Europa (Zachodnia)",
      europe_nord: "Europa (Nordycka)",
      europe_east: "Europa (Wschodnia)",
      uae: "UAE",
      ksa: "Arabia Saudyjska",
      qatar: "Katar",
      kuwait: "Kuwejt",
      bahrain: "Bahrajn",
      oman: "Oman",
      egypt: "Egipt",
      africa: "Afryka (pozostałe)",
      sea: "Azja Południowo-Wschodnia",
      india: "Indie",
      japan: "Japonia",
      korea: "Korea",
      china_hk: "Chiny / Hongkong",
      anzac: "Australia / Nowa Zelandia",
      mexico: "Meksyk",
      brazil: "Brazylia",
      latam_other: "Ameryka Łacińska (pozostałe)",
    },
    scheduling_tool: {
      manual: "Ręcznie / arkusze kalkulacyjne",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Narzędzie wewnętrzne / niestandardowe",
      pos_built_in: "Wbudowane w POS",
      none: "Brak systematycznego procesu",
      other: "Inne",
    },
    labor_pain: {
      overstaffing: "Nadmiar personelu w spokojnych godzinach",
      no_show: "No-show / odwołania zmian",
      ot_leakage: "Ucieczka kosztów nadgodzin",
      buddy_punching: "Odbijanie karty za kogoś / kradzież czasu",
      payroll_errors: "Błędy płacowe",
      compliance: "Compliance / wymogi prawne",
      turnover: "Rotacja / ponowne szkolenia",
      none: "Dziś nie jest to kluczowy problem",
    },
    payroll_regions: {
      us: "Stany Zjednoczone",
      canada: "Kanada",
      uk: "Wielka Brytania",
      eu: "Unia Europejska",
      uae: "UAE",
      ksa: "Arabia Saudyjska",
      qatar: "Katar / Bahrajn / Oman",
      other: "Inne (wpisz poniżej)",
    },
    kpis_measured: {
      labor_pct: "Koszt pracy %",
      food_cost: "Food cost %",
      void_comp: "Anulacje / gratisy",
      avg_check: "Średni rachunek",
      upsell: "Upsell / attach rate",
      guest_retention: "Retencja gości",
      ebitda: "EBITDA na lokal",
      forecast_acc: "Dokładność prognoz",
      compset: "Pozycja konkurencyjna",
    },
    kpis_wished: {
      real_time_margin: "Marża w czasie rzeczywistym na zmianę",
      daypart_leak: "Ucieczka kosztów pracy według pory dnia",
      labor_productivity: "Produktywność pracy w czasie rzeczywistym (sprzedaż na godzinę pracy)",
      live_labor_vs_demand: "Personel live względem popytu (tempo obsady w czasie rzeczywistym)",
      overtime_leakage: "Ryzyko i ucieczka nadgodzin, live",
      daypart_revpash: "RevPASH według pory dnia (przychód na dostępną godzinę miejsca)",
      hourly_food_cost: "Odchylenie food cost na poziomie godziny",
      theoretical_actual: "Odchylenie teoretycznego i rzeczywistego COGS",
      item_profitability: "Rzeczywista rentowność na poziomie pozycji menu",
      menu_engineering: "Macierz menu engineering (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Attach rate upsellu na poziomie kelnera",
      cannibalization: "Kanibalizacja między dniami / kanałami",
      promo_roi: "ROI promocji według kanału",
      delivery_margin: "Marża kanału delivery (wpływ prowizji stron trzecich)",
      guest_ltv: "Wartość życiowa gościa",
      cohort_retention: "Krzywe retencji kohort klientów",
      noshow_prediction: "Predykcja no-show dla rezerwacji",
      inventory_shrinkage: "Ubytki magazynowe według kategorii pozycji",
      cash_variance: "Odchylenia gotówki i revenue assurance (wykrywanie nadużyć)",
      peer_benchmark: "Anonimowy benchmark peerów",
      competitor_pricing: "Monitoring cen konkurencji",
      forecast_per_outlet: "Dzienna prognoza na lokal",
      scheduling_eff: "Efektywność grafików względem popytu",
      decision_replay: "Closed-loop scoring od decyzji do wyniku",
      cross_module: "Insight korelacji cross-module",
      multi_brand_pnl: "Skonsolidowany P&L dla wielu marek",
      compliance_drift: "Odchylenia od compliance / standardów marki",
      payroll_readiness: "Gotowość payroll w czasie rzeczywistym",
      speed_of_service: "Szybkość obsługi / czasy ticketów według stanowiska",
      food_waste: "Śledzenie marnowania i psucia się żywności",
      gratuity_distribution: "Dystrybucja napiwków / gratuity i compliance",
      guest_sentiment: "Sentyment gości / trendy opinii",
    },
    decision_data: {
      gut: "Intuicja / doświadczenie",
      spreadsheet: "Arkusz przygotowany przez analityka",
      pos_report: "Standardowy raport POS",
      bi_dashboard: "Dashboard BI (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Wewnętrzna hurtownia danych / zapytania SQL",
      external: "Zewnętrzny konsultant / doradca",
      ai_tool: "Narzędzie AI (ChatGPT / Claude / Gemini)",
      industry_report: "Raport branżowy / badanie benchmarkowe",
      board_packet: "Pakiet dla zarządu / leadershipu",
    },
    forecasting: {
      lyear_gut: "Poprzedni rok + intuicja operacyjna",
      spreadsheet: "Model arkuszowy utrzymywany wewnętrznie",
      pos_system: "Wbudowane w POS / system księgowy",
      bi_tool: "Narzędzie BI z modelem niestandardowym",
      ai_tool: "Dedykowane narzędzie AI / forecastingowe",
      none: "Nie prognozujemy formalnie",
    },
    scenario_wish: {
      new_location: "Otwarcie nowej lokalizacji",
      menu_change: "Wpływ zmian menu / cen",
      promo_impact: "Wpływ promocji / rabatów",
      staffing_model: "Zmiana modelu obsady",
      season_event: "Wpływ sezonu / wydarzenia",
      competitor: "Wejście / wyjście konkurenta",
      macro: "Inflacja / przepisy płacowe / zmiany podatkowe",
    },
    pos: {
      other: "Inne",
    },
    ops_tools: {
      scheduling: "Planowanie personelu",
      payroll: "Dostawca payroll",
      purchasing: "Zakupy / magazyn",
      delivery: "Menedżer agregatorów delivery",
      reservations: "Rezerwacje / zarządzanie stolikami",
      crm: "CRM gości / lojalność",
      bi: "Narzędzie BI (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Teraz - aktywnie oceniamy rozwiązania",
      next_quarter: "W następnym kwartale",
      next_6_months: "W ciągu najbliższych 6 miesięcy",
      this_year: "Przed końcem roku",
      exploring: "Tylko rozpoznanie · brak harmonogramu",
    },
    decision_lag: {
      minutes: "Minuty - reagujemy w trakcie zmiany",
      hours: "Godziny - tego samego dnia",
      days: "Dni - tygodniowy cykl przeglądu",
      weeks: "Tygodnie - miesięczny cykl zamknięcia",
      months: "Miesiące - tylko przegląd kwartalny",
    },
    budget_band: {
      under_10k: "Poniżej $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Nie wiem",
    },
    tech_headcount: {
      none: "Brak - nie mamy dedykowanej osoby",
      fractional: "Częściowo / współdzielone z innymi funkcjami",
      one: "1 osoba",
      two_three: "2-3 osoby",
      four_eight: "4-8 osób",
      nine_twenty: "9-20 osób",
      twenty_plus: "20+ osób",
    },
  },
  tr: {
    segment: {
      qsr: "QSR / fast food",
      fast_casual: "Fast-casual",
      casual: "Casual dining",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Kafe / fırın",
      bar_nightlife: "Bar / gece hayatı",
      catering: "Catering / etkinlikler",
      ghost_brand: "Ghost / sanal marka",
      franchise: "Franchise / master franchisee",
    },
    outlets: {
      "1": "1 şube",
      "2_5": "2-5 şube",
      "6_15": "6-15 şube",
      "16_50": "16-50 şube",
      "51_150": "51-150 şube",
      "150_plus": "150+ şube",
    },
    avg_unit_volume: {
      under_500k: "$500K altında",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Amerika Birleşik Devletleri",
      canada: "Kanada",
      uk: "Birleşik Krallık",
      ireland: "İrlanda",
      europe_west: "Avrupa (Batı)",
      europe_nord: "Avrupa (Nordik)",
      europe_east: "Avrupa (Doğu)",
      uae: "UAE",
      ksa: "Suudi Arabistan",
      qatar: "Katar",
      kuwait: "Kuveyt",
      bahrain: "Bahreyn",
      oman: "Umman",
      egypt: "Mısır",
      africa: "Afrika (diğer)",
      sea: "Güneydoğu Asya",
      india: "Hindistan",
      japan: "Japonya",
      korea: "Kore",
      china_hk: "Çin / Hong Kong",
      anzac: "Avustralya / Yeni Zelanda",
      mexico: "Meksika",
      brazil: "Brezilya",
      latam_other: "Latin Amerika (diğer)",
    },
    scheduling_tool: {
      manual: "Manuel / elektronik tablolar",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Dahili / özel araç",
      pos_built_in: "POS içinde yerleşik",
      none: "Sistematik bir süreç yok",
      other: "Diğer",
    },
    labor_pain: {
      overstaffing: "Sakin saatlerde fazla personel",
      no_show: "No-show / vardiya iptalleri",
      ot_leakage: "Fazla mesai kaçağı",
      buddy_punching: "Başkası adına giriş / zaman hırsızlığı",
      payroll_errors: "Bordro hataları",
      compliance: "Uyum / yasal kurallar",
      turnover: "Personel devri / yeniden eğitim",
      none: "Bugün öncelikli bir konu değil",
    },
    payroll_regions: {
      us: "Amerika Birleşik Devletleri",
      canada: "Kanada",
      uk: "Birleşik Krallık",
      eu: "Avrupa Birliği",
      uae: "UAE",
      ksa: "Suudi Arabistan",
      qatar: "Katar / Bahreyn / Umman",
      other: "Diğer (aşağıya yazın)",
    },
    kpis_measured: {
      labor_pct: "İş gücü maliyeti %",
      food_cost: "Food cost %",
      void_comp: "İptaller / ikramlar",
      avg_check: "Ortalama fiş",
      upsell: "Upsell / attach rate",
      guest_retention: "Misafir elde tutma",
      ebitda: "Şube başına EBITDA",
      forecast_acc: "Forecast doğruluğu",
      compset: "Rekabetçi konum",
    },
    kpis_wished: {
      real_time_margin: "Vardiya başına gerçek zamanlı marj",
      daypart_leak: "Gün bölümü bazında iş gücü kaçağı",
      labor_productivity: "Gerçek zamanlı iş gücü verimliliği (işçilik saati başına satış)",
      live_labor_vs_demand: "Canlı iş gücü ve talep karşılaştırması (gerçek zamanlı staffing temposu)",
      overtime_leakage: "Fazla mesai riski ve kaçağı, canlı",
      daypart_revpash: "Gün bölümüne göre RevPASH (kullanılabilir koltuk saati başına gelir)",
      hourly_food_cost: "Saatlik food cost sapması",
      theoretical_actual: "Teorik ve fiili COGS sapması",
      item_profitability: "Ürün bazında gerçek kârlılık",
      menu_engineering: "Menü mühendisliği matrisi (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Garson bazında upsell attach rate",
      cannibalization: "Günler / kanallar arası kanibalizasyon",
      promo_roi: "Kanala göre promosyon ROI",
      delivery_margin: "Delivery kanal marjı (üçüncü taraf komisyon etkisi)",
      guest_ltv: "Misafir yaşam boyu değeri",
      cohort_retention: "Müşteri kohortu elde tutma eğrileri",
      noshow_prediction: "Rezervasyon no-show tahmini",
      inventory_shrinkage: "Ürün kategorisine göre stok fireleri",
      cash_variance: "Nakit ve revenue assurance sapması (eksik tahsilat tespiti)",
      peer_benchmark: "Anonim emsal benchmark",
      competitor_pricing: "Rakip fiyat takibi",
      forecast_per_outlet: "Şube başına günlük forecast",
      scheduling_eff: "Talebe karşı vardiya planlama verimliliği",
      decision_replay: "Karardan sonuca closed-loop scoring",
      cross_module: "Cross-module korelasyon içgörüleri",
      multi_brand_pnl: "Çok markalı konsolide P&L",
      compliance_drift: "Uyum / marka standardı sapması",
      payroll_readiness: "Gerçek zamanlı payroll hazırlığı",
      speed_of_service: "İstasyon bazında servis hızı / ticket süreleri",
      food_waste: "Gıda atığı ve bozulma takibi",
      gratuity_distribution: "Bahşiş / gratuity dağıtımı ve uyum",
      guest_sentiment: "Misafir duyarlılığı / yorum trendi takibi",
    },
    decision_data: {
      gut: "Sezgi / deneyim",
      spreadsheet: "Analistin hazırladığı elektronik tablo",
      pos_report: "Standart POS raporu",
      bi_dashboard: "BI dashboard (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Dahili veri ambarı / SQL sorguları",
      external: "Harici danışman / advisor",
      ai_tool: "AI aracı (ChatGPT / Claude / Gemini)",
      industry_report: "Sektör raporu / benchmark çalışması",
      board_packet: "Yönetim kurulu / liderlik paketi",
    },
    forecasting: {
      lyear_gut: "Geçen yıl + operasyonel sezgi",
      spreadsheet: "Dahili yönetilen elektronik tablo modeli",
      pos_system: "POS / muhasebe sisteminde yerleşik",
      bi_tool: "Özel modele sahip BI aracı",
      ai_tool: "Özel AI / forecasting aracı",
      none: "Resmi forecast yapmıyoruz",
    },
    scenario_wish: {
      new_location: "Yeni bir lokasyon açmak",
      menu_change: "Menü / fiyat değişikliği etkisi",
      promo_impact: "Promosyon / indirim etkisi",
      staffing_model: "Staffing modeli değişikliği",
      season_event: "Sezon / etkinlik etkisi",
      competitor: "Rakibin pazara girişi / çıkışı",
      macro: "Enflasyon / ücret yasası / vergi değişikliği",
    },
    pos: {
      other: "Diğer",
    },
    ops_tools: {
      scheduling: "İş gücü vardiya planlama",
      payroll: "Payroll sağlayıcısı",
      purchasing: "Satın alma / stok",
      delivery: "Delivery aggregator yöneticisi",
      reservations: "Rezervasyon / masa yönetimi",
      crm: "Misafir CRM / sadakat",
      bi: "BI aracı (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Hemen - aktif olarak değerlendiriyoruz",
      next_quarter: "Önümüzdeki çeyrek",
      next_6_months: "Önümüzdeki 6 ay",
      this_year: "Yıl sonundan önce",
      exploring: "Sadece araştırıyoruz · takvim yok",
    },
    decision_lag: {
      minutes: "Dakikalar - vardiya içinde tepki veriyoruz",
      hours: "Saatler - aynı gün",
      days: "Günler - haftalık değerlendirme döngüsü",
      weeks: "Haftalar - aylık kapanış döngüsü",
      months: "Aylar - yalnızca çeyreklik değerlendirme",
    },
    budget_band: {
      under_10k: "$10K altında",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Emin değilim",
    },
    tech_headcount: {
      none: "Yok - adanmış kimsemiz yok",
      fractional: "Kısmi / diğer fonksiyonlarla paylaşımlı",
      one: "1 kişi",
      two_three: "2-3 kişi",
      four_eight: "4-8 kişi",
      nine_twenty: "9-20 kişi",
      twenty_plus: "20+ kişi",
    },
  },
  ro: {
    segment: {
      qsr: "QSR / fast food",
      fast_casual: "Fast-casual",
      casual: "Casual dining",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Cafenea / brutărie",
      bar_nightlife: "Bar / nightlife",
      catering: "Catering / evenimente",
      ghost_brand: "Brand ghost / virtual",
      franchise: "Franciză / master franchisee",
    },
    outlets: {
      "1": "1 locație",
      "2_5": "2-5 locații",
      "6_15": "6-15 locații",
      "16_50": "16-50 locații",
      "51_150": "51-150 locații",
      "150_plus": "150+ locații",
    },
    avg_unit_volume: {
      under_500k: "Sub $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "Statele Unite",
      canada: "Canada",
      uk: "Regatul Unit",
      ireland: "Irlanda",
      europe_west: "Europa (Vest)",
      europe_nord: "Europa (Nordică)",
      europe_east: "Europa (Est)",
      uae: "UAE",
      ksa: "Arabia Saudită",
      qatar: "Qatar",
      kuwait: "Kuweit",
      bahrain: "Bahrain",
      oman: "Oman",
      egypt: "Egipt",
      africa: "Africa (altele)",
      sea: "Asia de Sud-Est",
      india: "India",
      japan: "Japonia",
      korea: "Coreea",
      china_hk: "China / Hong Kong",
      anzac: "Australia / Noua Zeelandă",
      mexico: "Mexic",
      brazil: "Brazilia",
      latam_other: "America Latină (altele)",
    },
    scheduling_tool: {
      manual: "Manual / foi de calcul",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Instrument intern / personalizat",
      pos_built_in: "Integrat în POS",
      none: "Niciun proces sistematic",
      other: "Altul",
    },
    labor_pain: {
      overstaffing: "Supra-acoperire cu personal în intervalele lente",
      no_show: "No-show / anulări de tură",
      ot_leakage: "Pierderi din ore suplimentare",
      buddy_punching: "Pontaj pentru altcineva / furt de timp",
      payroll_errors: "Erori de salarizare",
      compliance: "Compliance / reguli legale",
      turnover: "Fluctuație de personal / recalificare",
      none: "Nu este o prioritate azi",
    },
    payroll_regions: {
      us: "Statele Unite",
      canada: "Canada",
      uk: "Regatul Unit",
      eu: "Uniunea Europeană",
      uae: "UAE",
      ksa: "Arabia Saudită",
      qatar: "Qatar / Bahrain / Oman",
      other: "Altul (scrieți mai jos)",
    },
    kpis_measured: {
      labor_pct: "Costul forței de muncă %",
      food_cost: "Food cost %",
      void_comp: "Anulări / compensații",
      avg_check: "Bon mediu",
      upsell: "Upsell / attach rate",
      guest_retention: "Retenția oaspeților",
      ebitda: "EBITDA per locație",
      forecast_acc: "Acuratețea forecastului",
      compset: "Poziție competitivă",
    },
    kpis_wished: {
      real_time_margin: "Marjă în timp real per tură",
      daypart_leak: "Pierdere de cost cu personalul pe interval al zilei",
      labor_productivity: "Productivitatea forței de muncă în timp real (vânzări per oră de muncă)",
      live_labor_vs_demand: "Personal live versus cerere (ritm de staffing în timp real)",
      overtime_leakage: "Risc și pierdere din ore suplimentare, live",
      daypart_revpash: "RevPASH pe interval al zilei (venit per oră de loc disponibil)",
      hourly_food_cost: "Variație food cost la nivel de oră",
      theoretical_actual: "Variație între COGS teoretic și real",
      item_profitability: "Profitabilitate reală la nivel de articol",
      menu_engineering: "Matrice de menu engineering (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Attach rate de upsell la nivel de ospătar",
      cannibalization: "Canibalizare între zile / canale",
      promo_roi: "ROI promoțional pe canal",
      delivery_margin: "Marja canalului delivery (impactul comisioanelor terților)",
      guest_ltv: "Valoarea pe durata de viață a oaspetelui",
      cohort_retention: "Curbe de retenție pe cohorte de clienți",
      noshow_prediction: "Predicție no-show pentru rezervări",
      inventory_shrinkage: "Pierderi de stoc pe categorie de articol",
      cash_variance: "Variație numerar și revenue assurance (detectarea sustragerilor)",
      peer_benchmark: "Benchmark anonim între operatori similari",
      competitor_pricing: "Monitorizarea prețurilor concurenților",
      forecast_per_outlet: "Forecast zilnic per locație",
      scheduling_eff: "Eficiența programării versus cerere",
      decision_replay: "Scoring closed-loop de la decizie la rezultat",
      cross_module: "Insighturi de corelație cross-module",
      multi_brand_pnl: "P&L consolidat multi-brand",
      compliance_drift: "Deviație de la compliance / standardele de brand",
      payroll_readiness: "Pregătire payroll în timp real",
      speed_of_service: "Viteză de servire / timpi de bon pe stație",
      food_waste: "Monitorizarea risipei alimentare și alterării",
      gratuity_distribution: "Distribuția bacșișurilor / gratuity și compliance",
      guest_sentiment: "Sentimentul oaspeților / tendințe din recenzii",
    },
    decision_data: {
      gut: "Intuiție / experiență",
      spreadsheet: "Foaie de calcul pregătită de analist",
      pos_report: "Raport standard POS",
      bi_dashboard: "Dashboard BI (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Data warehouse intern / interogări SQL",
      external: "Consultant / advisor extern",
      ai_tool: "Instrument AI (ChatGPT / Claude / Gemini)",
      industry_report: "Raport de industrie / studiu de benchmark",
      board_packet: "Pachet pentru board / leadership",
    },
    forecasting: {
      lyear_gut: "Anul trecut + intuiție operațională",
      spreadsheet: "Model în foaie de calcul menținut intern",
      pos_system: "Integrat în POS / sistem contabil",
      bi_tool: "Instrument BI cu model personalizat",
      ai_tool: "Instrument dedicat de AI / forecasting",
      none: "Nu facem forecast formal",
    },
    scenario_wish: {
      new_location: "Deschiderea unei locații noi",
      menu_change: "Impactul modificărilor de meniu / prețuri",
      promo_impact: "Impactul promoțiilor / reducerilor",
      staffing_model: "Schimbarea modelului de staffing",
      season_event: "Impact sezonier / de eveniment",
      competitor: "Intrarea / ieșirea unui competitor",
      macro: "Inflație / lege salarială / modificare fiscală",
    },
    pos: {
      other: "Altul",
    },
    ops_tools: {
      scheduling: "Programarea personalului",
      payroll: "Furnizor payroll",
      purchasing: "Achiziții / inventar",
      delivery: "Manager pentru agregatori delivery",
      reservations: "Rezervări / managementul meselor",
      crm: "CRM oaspeți / loialitate",
      bi: "Instrument BI (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Acum - evaluăm activ",
      next_quarter: "Trimestrul următor",
      next_6_months: "Următoarele 6 luni",
      this_year: "Înainte de finalul anului",
      exploring: "Doar explorăm · fără calendar",
    },
    decision_lag: {
      minutes: "Minute - reacționăm în timpul turei",
      hours: "Ore - în aceeași zi",
      days: "Zile - ciclu de analiză săptămânal",
      weeks: "Săptămâni - ciclu de închidere lunară",
      months: "Luni - doar analiză trimestrială",
    },
    budget_band: {
      under_10k: "Sub $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Nu sunt sigur",
    },
    tech_headcount: {
      none: "Nimeni - nu avem pe cineva dedicat",
      fractional: "Fracțional / partajat cu alte funcții",
      one: "1 persoană",
      two_three: "2-3 persoane",
      four_eight: "4-8 persoane",
      nine_twenty: "9-20 persoane",
      twenty_plus: "20+ persoane",
    },
  },
  sv: {
    segment: {
      qsr: "QSR / fast food",
      fast_casual: "Fast-casual",
      casual: "Casual dining",
      fine_dining: "Fine dining",
      cloud: "Cloud kitchen / dark kitchen",
      hotel_fb: "Hotel F&B",
      cafe_bakery: "Café / bageri",
      bar_nightlife: "Bar / nightlife",
      catering: "Catering / events",
      ghost_brand: "Ghost / virtuellt varumärke",
      franchise: "Franchise / master franchisee",
    },
    outlets: {
      "1": "1 enhet",
      "2_5": "2-5 enheter",
      "6_15": "6-15 enheter",
      "16_50": "16-50 enheter",
      "51_150": "51-150 enheter",
      "150_plus": "150+ enheter",
    },
    avg_unit_volume: {
      under_500k: "Under $500K",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "USA",
      canada: "Kanada",
      uk: "Storbritannien",
      ireland: "Irland",
      europe_west: "Europa (västra)",
      europe_nord: "Europa (nordiska)",
      europe_east: "Europa (östra)",
      uae: "UAE",
      ksa: "Saudiarabien",
      qatar: "Qatar",
      kuwait: "Kuwait",
      bahrain: "Bahrain",
      oman: "Oman",
      egypt: "Egypten",
      africa: "Afrika (övrigt)",
      sea: "Sydostasien",
      india: "Indien",
      japan: "Japan",
      korea: "Korea",
      china_hk: "Kina / Hongkong",
      anzac: "Australien / Nya Zeeland",
      mexico: "Mexiko",
      brazil: "Brasilien",
      latam_other: "Latinamerika (övrigt)",
    },
    scheduling_tool: {
      manual: "Manuellt / kalkylblad",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "Internt / anpassat verktyg",
      pos_built_in: "Inbyggt i POS",
      none: "Ingen systematisk process",
      other: "Annat",
    },
    labor_pain: {
      overstaffing: "Överbemanning under lugna perioder",
      no_show: "No-shows / sena avbokningar",
      ot_leakage: "Läckage från övertid",
      buddy_punching: "Stämpling åt någon annan / tidsstöld",
      payroll_errors: "Lönefel",
      compliance: "Compliance / lagstadgade regler",
      turnover: "Personalomsättning / ny utbildning",
      none: "Inte en huvudfråga idag",
    },
    payroll_regions: {
      us: "USA",
      canada: "Kanada",
      uk: "Storbritannien",
      eu: "Europeiska unionen",
      uae: "UAE",
      ksa: "Saudiarabien",
      qatar: "Qatar / Bahrain / Oman",
      other: "Annat (skriv nedan)",
    },
    kpis_measured: {
      labor_pct: "Personalkostnad %",
      food_cost: "Food cost %",
      void_comp: "Makulerade köp / kompensationer",
      avg_check: "Genomsnittligt kvitto",
      upsell: "Upsell / attach rate",
      guest_retention: "Gästretention",
      ebitda: "EBITDA per enhet",
      forecast_acc: "Forecastnoggrannhet",
      compset: "Konkurrensposition",
    },
    kpis_wished: {
      real_time_margin: "Realtidsmarginal per skift",
      daypart_leak: "Personalläckage per dagdel",
      labor_productivity: "Realtidsproduktivitet för personal (försäljning per arbetstimme)",
      live_labor_vs_demand: "Live personal mot efterfrågan (bemanningstakt i realtid)",
      overtime_leakage: "Övertidsrisk och läckage, live",
      daypart_revpash: "RevPASH per dagdel (intäkt per tillgänglig stolstimme)",
      hourly_food_cost: "Food-costavvikelse på timnivå",
      theoretical_actual: "Avvikelse mellan teoretisk och faktisk COGS",
      item_profitability: "Verklig lönsamhet på artikelnivå",
      menu_engineering: "Menu-engineeringmatris (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "Upsell attach rate per serveringsmedarbetare",
      cannibalization: "Kannibalisering mellan dagar / kanaler",
      promo_roi: "Kampanj-ROI per kanal",
      delivery_margin: "Marginal per deliverykanal (effekt av tredjepartskommissioner)",
      guest_ltv: "Gästens livstidsvärde",
      cohort_retention: "Retentionskurvor per kundkohort",
      noshow_prediction: "Prognos för no-shows vid bokningar",
      inventory_shrinkage: "Lagersvinn per artikelkategori",
      cash_variance: "Kassa- och revenue-assuranceavvikelse (detektion av svinn)",
      peer_benchmark: "Anonym peerbenchmark",
      competitor_pricing: "Bevakning av konkurrentpriser",
      forecast_per_outlet: "Daglig forecast per enhet",
      scheduling_eff: "Schemaläggningseffektivitet mot efterfrågan",
      decision_replay: "Closed-loop scoring från beslut till resultat",
      cross_module: "Cross-module korrelationsinsikter",
      multi_brand_pnl: "Konsoliderad P&L för flera varumärken",
      compliance_drift: "Avvikelse från compliance / varumärkesstandarder",
      payroll_readiness: "Realtidsberedskap för payroll",
      speed_of_service: "Servicehastighet / tickettider per station",
      food_waste: "Spårning av matsvinn och förstörelse",
      gratuity_distribution: "Dricks- / gratuityfördelning och compliance",
      guest_sentiment: "Gästsentiment / trendspårning av recensioner",
    },
    decision_data: {
      gut: "Intuition / erfarenhet",
      spreadsheet: "Kalkylblad framtaget av analytiker",
      pos_report: "Standardrapport från POS",
      bi_dashboard: "BI-dashboard (Power BI / Tableau / Looker / Domo)",
      in_house_data: "Internt datalager / SQL-frågor",
      external: "Extern konsult / rådgivare",
      ai_tool: "AI-verktyg (ChatGPT / Claude / Gemini)",
      industry_report: "Branschrapport / benchmarkstudie",
      board_packet: "Styrelse- / ledningsunderlag",
    },
    forecasting: {
      lyear_gut: "Föregående år + operativ magkänsla",
      spreadsheet: "Internt underhållen kalkylbladsmodell",
      pos_system: "Inbyggt i POS / ekonomisystem",
      bi_tool: "BI-verktyg med anpassad modell",
      ai_tool: "Dedikerat AI- / forecastingverktyg",
      none: "Vi gör ingen formell forecast",
    },
    scenario_wish: {
      new_location: "Öppna en ny plats",
      menu_change: "Effekt av meny- / prisändring",
      promo_impact: "Effekt av kampanj / rabatt",
      staffing_model: "Ändring av bemanningsmodell",
      season_event: "Säsongs- / eventeffekt",
      competitor: "Konkurrent som går in / ut",
      macro: "Inflation / lönelagstiftning / skatteändring",
    },
    pos: {
      other: "Annat",
    },
    ops_tools: {
      scheduling: "Personalschemaläggning",
      payroll: "Payrollleverantör",
      purchasing: "Inköp / lager",
      delivery: "Manager för deliveryaggregatorer",
      reservations: "Bokningar / bordshantering",
      crm: "Gäst-CRM / lojalitet",
      bi: "BI-verktyg (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "Nu - utvärderar aktivt",
      next_quarter: "Nästa kvartal",
      next_6_months: "Nästa 6 månader",
      this_year: "Före årets slut",
      exploring: "Bara utforskar · ingen tidsplan",
    },
    decision_lag: {
      minutes: "Minuter - vi agerar under skiftet",
      hours: "Timmar - samma dag",
      days: "Dagar - veckovis granskningscykel",
      weeks: "Veckor - månadsvis stängningscykel",
      months: "Månader - endast kvartalsvis granskning",
    },
    budget_band: {
      under_10k: "Under $10K",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "Inte säker",
    },
    tech_headcount: {
      none: "Ingen - vi har ingen dedikerad person",
      fractional: "Fractional / delad med andra funktioner",
      one: "1 person",
      two_three: "2-3 personer",
      four_eight: "4-8 personer",
      nine_twenty: "9-20 personer",
      twenty_plus: "20+ personer",
    },
  },
} as const;

export type DiagnosticEuropeOptionPackLocale = keyof typeof europeDiagnosticOptionPacks;
