export const indicDiagnosticOptionPacks = {
  hi: {
    segment: {
      qsr: "QSR / फास्ट फूड",
      fast_casual: "फास्ट-कैज़ुअल",
      casual: "कैज़ुअल डाइनिंग",
      fine_dining: "फाइन डाइनिंग",
      cloud: "क्लाउड किचन / डार्क किचन",
      hotel_fb: "होटल F&B",
      cafe_bakery: "कैफ़े / बेकरी",
      bar_nightlife: "बार / नाइटलाइफ़",
      catering: "केटरिंग / इवेंट्स",
      ghost_brand: "घोस्ट / वर्चुअल ब्रांड",
      franchise: "फ्रेंचाइज़ / मास्टर फ्रेंचाइज़ी",
    },
    outlets: {
      "1": "1 आउटलेट",
      "2_5": "2-5 आउटलेट",
      "6_15": "6-15 आउटलेट",
      "16_50": "16-50 आउटलेट",
      "51_150": "51-150 आउटलेट",
      "150_plus": "150+ आउटलेट",
    },
    avg_unit_volume: {
      under_500k: "$500K से कम",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "संयुक्त राज्य अमेरिका",
      canada: "कनाडा",
      uk: "यूनाइटेड किंगडम",
      ireland: "आयरलैंड",
      europe_west: "यूरोप (पश्चिमी)",
      europe_nord: "यूरोप (नॉर्डिक)",
      europe_east: "यूरोप (पूर्वी)",
      uae: "UAE",
      ksa: "सऊदी अरब",
      qatar: "क़तर",
      kuwait: "कुवैत",
      bahrain: "बहरीन",
      oman: "ओमान",
      egypt: "मिस्र",
      africa: "अफ्रीका (अन्य)",
      sea: "दक्षिण-पूर्व एशिया",
      india: "भारत",
      japan: "जापान",
      korea: "कोरिया",
      china_hk: "चीन / हांगकांग",
      anzac: "ऑस्ट्रेलिया / न्यूज़ीलैंड",
      mexico: "मेक्सिको",
      brazil: "ब्राज़ील",
      latam_other: "लैटिन अमेरिका (अन्य)",
    },
    scheduling_tool: {
      manual: "मैनुअल / स्प्रेडशीट्स",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "आंतरिक / कस्टम टूल",
      pos_built_in: "POS में अंतर्निहित",
      none: "कोई व्यवस्थित प्रक्रिया नहीं",
      other: "अन्य",
    },
    labor_pain: {
      overstaffing: "धीमे समय में ज़रूरत से ज़्यादा स्टाफ़",
      no_show: "नो-शो / कॉल-आउट",
      ot_leakage: "ओवरटाइम लीकेज",
      buddy_punching: "बडी-पंचिंग / समय की चोरी",
      payroll_errors: "पेरोल त्रुटियां",
      compliance: "अनुपालन / वैधानिक नियम",
      turnover: "कर्मचारी छोड़ना / फिर से प्रशिक्षण",
      none: "आज यह शीर्ष चिंता नहीं है",
    },
    payroll_regions: {
      us: "संयुक्त राज्य अमेरिका",
      canada: "कनाडा",
      uk: "यूनाइटेड किंगडम",
      eu: "यूरोपीय संघ",
      uae: "UAE",
      ksa: "सऊदी अरब",
      qatar: "क़तर / बहरीन / ओमान",
      other: "अन्य (नीचे लिखें)",
    },
    kpis_measured: {
      labor_pct: "लेबर कॉस्ट %",
      food_cost: "फूड कॉस्ट %",
      void_comp: "Voids / Comps",
      avg_check: "औसत चेक",
      upsell: "अपसेल / अटैच रेट",
      guest_retention: "गेस्ट रिटेंशन",
      ebitda: "प्रति आउटलेट EBITDA",
      forecast_acc: "फोरकास्ट सटीकता",
      compset: "प्रतिस्पर्धी स्थिति",
    },
    kpis_wished: {
      real_time_margin: "प्रति शिफ्ट रियल-टाइम मार्जिन",
      daypart_leak: "डेपार्ट-स्तर का लेबर लीकेज",
      labor_productivity: "रियल-टाइम लेबर उत्पादकता (प्रति लेबर घंटे बिक्री)",
      live_labor_vs_demand: "लाइव लेबर बनाम मांग (रियल-टाइम स्टाफ़िंग गति)",
      overtime_leakage: "ओवरटाइम जोखिम और लीकेज, लाइव",
      daypart_revpash: "डेपार्ट RevPASH (Revenue per Available Seat Hour)",
      hourly_food_cost: "घंटे-स्तर का फूड कॉस्ट वैरिएंस",
      theoretical_actual: "सैद्धांतिक बनाम वास्तविक COGS वैरिएंस",
      item_profitability: "वास्तविक आइटम-स्तर लाभप्रदता",
      menu_engineering: "मेन्यू इंजीनियरिंग मैट्रिक्स (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "सर्वर-स्तर अपसेल अटैच रेट",
      cannibalization: "क्रॉस-डे / क्रॉस-चैनल कैनिबलाइज़ेशन",
      promo_roi: "चैनल के अनुसार प्रोमो ROI",
      delivery_margin: "डिलीवरी चैनल मार्जिन (थर्ड-पार्टी कमीशन ड्रैग)",
      guest_ltv: "गेस्ट लाइफ़टाइम वैल्यू",
      cohort_retention: "कस्टमर कोहोर्ट रिटेंशन कर्व्स",
      noshow_prediction: "रिज़र्वेशन नो-शो प्रेडिक्शन",
      inventory_shrinkage: "आइटम श्रेणी के अनुसार इन्वेंटरी श्रिंकेज",
      cash_variance: "कैश और रेवेन्यू-अश्योरेंस वैरिएंस (स्किम डिटेक्शन)",
      peer_benchmark: "अनाम पीयर बेंचमार्क",
      competitor_pricing: "प्रतिस्पर्धी प्राइसिंग ट्रैकिंग",
      forecast_per_outlet: "प्रति आउटलेट दैनिक फोरकास्ट",
      scheduling_eff: "मांग के मुकाबले शेड्यूलिंग दक्षता",
      decision_replay: "निर्णय-से-परिणाम क्लोज़्ड-लूप स्कोरिंग",
      cross_module: "क्रॉस-मॉड्यूल कोरिलेशन इनसाइट्स",
      multi_brand_pnl: "मल्टी-ब्रांड समेकित P&L",
      compliance_drift: "अनुपालन / ब्रांड-स्टैंडर्ड ड्रिफ्ट",
      payroll_readiness: "रियल-टाइम पेरोल रेडीनेस",
      speed_of_service: "स्टेशन के अनुसार सेवा गति / टिकट टाइम्स",
      food_waste: "फूड वेस्ट और खराबी ट्रैकिंग",
      gratuity_distribution: "टिप / ग्रेच्युटी वितरण और अनुपालन",
      guest_sentiment: "गेस्ट सेंटिमेंट / रिव्यू-ट्रेंड ट्रैकिंग",
    },
    decision_data: {
      gut: "अनुभव / सहज निर्णय",
      spreadsheet: "एनालिस्ट द्वारा निकाली गई स्प्रेडशीट",
      pos_report: "POS स्टैंडर्ड रिपोर्ट",
      bi_dashboard: "BI डैशबोर्ड (Power BI / Tableau / Looker / Domo)",
      in_house_data: "इन-हाउस डेटा वेयरहाउस / SQL क्वेरीज़",
      external: "बाहरी कंसल्टेंट / सलाहकार",
      ai_tool: "AI टूल (ChatGPT / Claude / Gemini)",
      industry_report: "इंडस्ट्री रिपोर्ट / बेंचमार्क अध्ययन",
      board_packet: "बोर्ड / लीडरशिप पैकेट",
    },
    forecasting: {
      lyear_gut: "पिछला साल + अनुभवजन्य अनुमान",
      spreadsheet: "आंतरिक रूप से बनाए रखा गया स्प्रेडशीट मॉडल",
      pos_system: "POS / अकाउंटिंग सिस्टम में अंतर्निहित",
      bi_tool: "कस्टम मॉडल वाला BI टूल",
      ai_tool: "समर्पित AI / फोरकास्टिंग टूल",
      none: "हम औपचारिक फोरकास्ट नहीं करते",
    },
    scenario_wish: {
      new_location: "नया लोकेशन खोलना",
      menu_change: "मेन्यू / प्राइसिंग बदलाव का प्रभाव",
      promo_impact: "प्रमोशन / डिस्काउंट का प्रभाव",
      staffing_model: "स्टाफ़िंग मॉडल में बदलाव",
      season_event: "सीज़नल / इवेंट प्रभाव",
      competitor: "प्रतिस्पर्धी का प्रवेश / निकास",
      macro: "महंगाई / वेज लॉ / टैक्स बदलाव",
    },
    pos: {
      other: "अन्य",
    },
    ops_tools: {
      scheduling: "वर्कफ़ोर्स शेड्यूलिंग",
      payroll: "पेरोल प्रदाता",
      purchasing: "खरीद / इन्वेंटरी",
      delivery: "डिलीवरी एग्रीगेटर मैनेजर",
      reservations: "रिज़र्वेशन / टेबल मैनेजमेंट",
      crm: "गेस्ट CRM / लॉयल्टी",
      bi: "BI टूल (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "अभी - सक्रिय रूप से मूल्यांकन कर रहे हैं",
      next_quarter: "अगली तिमाही",
      next_6_months: "अगले 6 महीने",
      this_year: "साल के अंत से पहले",
      exploring: "सिर्फ़ खोज रहे हैं · कोई टाइमलाइन नहीं",
    },
    decision_lag: {
      minutes: "मिनट - हम शिफ्ट के दौरान प्रतिक्रिया देते हैं",
      hours: "घंटे - उसी दिन",
      days: "दिन - साप्ताहिक समीक्षा चक्र",
      weeks: "हफ़्ते - मासिक क्लोज़ चक्र",
      months: "महीने - केवल तिमाही समीक्षा",
    },
    budget_band: {
      under_10k: "$10K से कम",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "पक्का नहीं",
    },
    tech_headcount: {
      none: "कोई नहीं - हमारे पास समर्पित व्यक्ति नहीं है",
      fractional: "फ्रैक्शनल / अन्य फ़ंक्शंस के साथ साझा",
      one: "1 व्यक्ति",
      two_three: "2-3 लोग",
      four_eight: "4-8 लोग",
      nine_twenty: "9-20 लोग",
      twenty_plus: "20+ लोग",
    },
  },
  ur: {
    segment: {
      qsr: "QSR / فاسٹ فوڈ",
      fast_casual: "فاسٹ کیژول",
      casual: "کیژول ڈائننگ",
      fine_dining: "فائن ڈائننگ",
      cloud: "کلاؤڈ کچن / ڈارک کچن",
      hotel_fb: "ہوٹل F&B",
      cafe_bakery: "کیفے / بیکری",
      bar_nightlife: "بار / نائٹ لائف",
      catering: "کیٹرنگ / ایونٹس",
      ghost_brand: "گھوسٹ / ورچوئل برانڈ",
      franchise: "فرنچائز / ماسٹر فرنچائزی",
    },
    outlets: {
      "1": "1 آؤٹ لیٹ",
      "2_5": "2-5 آؤٹ لیٹس",
      "6_15": "6-15 آؤٹ لیٹس",
      "16_50": "16-50 آؤٹ لیٹس",
      "51_150": "51-150 آؤٹ لیٹس",
      "150_plus": "150+ آؤٹ لیٹس",
    },
    avg_unit_volume: {
      under_500k: "$500K سے کم",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "ریاستہائے متحدہ",
      canada: "کینیڈا",
      uk: "یونائیٹڈ کنگڈم",
      ireland: "آئرلینڈ",
      europe_west: "یورپ (مغربی)",
      europe_nord: "یورپ (نورڈک)",
      europe_east: "یورپ (مشرقی)",
      uae: "UAE",
      ksa: "سعودی عرب",
      qatar: "قطر",
      kuwait: "کویت",
      bahrain: "بحرین",
      oman: "عمان",
      egypt: "مصر",
      africa: "افریقہ (دیگر)",
      sea: "جنوب مشرقی ایشیا",
      india: "بھارت",
      japan: "جاپان",
      korea: "کوریا",
      china_hk: "چین / ہانگ کانگ",
      anzac: "آسٹریلیا / نیوزی لینڈ",
      mexico: "میکسیکو",
      brazil: "برازیل",
      latam_other: "لاطینی امریکہ (دیگر)",
    },
    scheduling_tool: {
      manual: "مینوئل / اسپریڈشیٹس",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "اندرونی / کسٹم ٹول",
      pos_built_in: "POS میں شامل",
      none: "کوئی باقاعدہ نظام نہیں",
      other: "دیگر",
    },
    labor_pain: {
      overstaffing: "سست اوقات میں ضرورت سے زیادہ اسٹاف",
      no_show: "نو شو / کال آؤٹس",
      ot_leakage: "اوور ٹائم لیکیج",
      buddy_punching: "بڈی پنچنگ / وقت کی چوری",
      payroll_errors: "پے رول کی غلطیاں",
      compliance: "کمپلائنس / قانونی قواعد",
      turnover: "عملے کا چھوڑ جانا / دوبارہ تربیت",
      none: "آج یہ بڑی تشویش نہیں ہے",
    },
    payroll_regions: {
      us: "ریاستہائے متحدہ",
      canada: "کینیڈا",
      uk: "یونائیٹڈ کنگڈم",
      eu: "یورپی یونین",
      uae: "UAE",
      ksa: "سعودی عرب",
      qatar: "قطر / بحرین / عمان",
      other: "دیگر (نیچے لکھیں)",
    },
    kpis_measured: {
      labor_pct: "لیبر لاگت %",
      food_cost: "فوڈ لاگت %",
      void_comp: "Voids / Comps",
      avg_check: "اوسط چیک",
      upsell: "اپ سیل / اٹیچ ریٹ",
      guest_retention: "گیسٹ ریٹینشن",
      ebitda: "فی آؤٹ لیٹ EBITDA",
      forecast_acc: "فورکاسٹ کی درستگی",
      compset: "مسابقتی پوزیشن",
    },
    kpis_wished: {
      real_time_margin: "فی شفٹ رئیل ٹائم مارجن",
      daypart_leak: "ڈے پارٹ سطح کا لیبر لیکیج",
      labor_productivity: "رئیل ٹائم لیبر پیداواری صلاحیت (فی لیبر گھنٹہ سیلز)",
      live_labor_vs_demand: "لائیو لیبر بمقابلہ ڈیمانڈ (رئیل ٹائم اسٹافنگ رفتار)",
      overtime_leakage: "اوور ٹائم رسک اور لیکیج، لائیو",
      daypart_revpash: "ڈے پارٹ RevPASH (Revenue per Available Seat Hour)",
      hourly_food_cost: "گھنٹے کی سطح پر فوڈ لاگت ویریئنس",
      theoretical_actual: "تھیوریٹیکل بمقابلہ ایکچوئل COGS ویریئنس",
      item_profitability: "حقیقی آئٹم سطح منافع بخشی",
      menu_engineering: "مینو انجینئرنگ میٹرکس (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "سرور سطح کا اپ سیل اٹیچ ریٹ",
      cannibalization: "کراس ڈے / کراس چینل کینیبلائزیشن",
      promo_roi: "چینل کے حساب سے پرومو ROI",
      delivery_margin: "ڈیلیوری چینل مارجن (تھرڈ پارٹی کمیشن ڈریگ)",
      guest_ltv: "گیسٹ لائف ٹائم ویلیو",
      cohort_retention: "کسٹمر کوہورٹ ریٹینشن کروز",
      noshow_prediction: "ریزرویشن نو شو پریڈکشن",
      inventory_shrinkage: "آئٹم کیٹیگری کے حساب سے انوینٹری شرنکیج",
      cash_variance: "کیش اور ریونیو اشورنس ویریئنس (اسکم ڈٹیکشن)",
      peer_benchmark: "گمنام پیئر بینچ مارک",
      competitor_pricing: "مسابقتی پرائسنگ ٹریکنگ",
      forecast_per_outlet: "فی آؤٹ لیٹ روزانہ فورکاسٹ",
      scheduling_eff: "ڈیمانڈ کے مقابلے میں شیڈولنگ ایفیشنسی",
      decision_replay: "فیصلے سے نتیجے تک کلوزڈ لوپ اسکورنگ",
      cross_module: "کراس ماڈیول کوریلیشن انسائٹس",
      multi_brand_pnl: "ملٹی برانڈ کنسولیڈیٹڈ P&L",
      compliance_drift: "کمپلائنس / برانڈ اسٹینڈرڈ ڈرفٹ",
      payroll_readiness: "رئیل ٹائم پے رول ریڈینیس",
      speed_of_service: "اسٹیشن کے حساب سے سروس کی رفتار / ٹکٹ ٹائمز",
      food_waste: "فوڈ ویسٹ اور خراب ہونے کی ٹریکنگ",
      gratuity_distribution: "ٹپ / گریچیوٹی تقسیم اور کمپلائنس",
      guest_sentiment: "گیسٹ سینٹیمنٹ / ریویو ٹرینڈ ٹریکنگ",
    },
    decision_data: {
      gut: "تجربہ / اندرونی اندازہ",
      spreadsheet: "اینالسٹ کی نکالی ہوئی اسپریڈشیٹ",
      pos_report: "POS اسٹینڈرڈ رپورٹ",
      bi_dashboard: "BI ڈیش بورڈ (Power BI / Tableau / Looker / Domo)",
      in_house_data: "ان ہاؤس ڈیٹا ویئر ہاؤس / SQL کوئریز",
      external: "بیرونی کنسلٹنٹ / مشیر",
      ai_tool: "AI ٹول (ChatGPT / Claude / Gemini)",
      industry_report: "انڈسٹری رپورٹ / بینچ مارک اسٹڈی",
      board_packet: "بورڈ / لیڈرشپ پیکٹ",
    },
    forecasting: {
      lyear_gut: "پچھلا سال + تجرباتی اندازہ",
      spreadsheet: "اندرونی طور پر برقرار رکھا گیا اسپریڈشیٹ ماڈل",
      pos_system: "POS / اکاؤنٹنگ سسٹم میں شامل",
      bi_tool: "کسٹم ماڈل والا BI ٹول",
      ai_tool: "مخصوص AI / فورکاسٹنگ ٹول",
      none: "ہم رسمی فورکاسٹ نہیں کرتے",
    },
    scenario_wish: {
      new_location: "نئی لوکیشن کھولنا",
      menu_change: "مینو / پرائسنگ تبدیلی کا اثر",
      promo_impact: "پروموشن / ڈسکاؤنٹ کا اثر",
      staffing_model: "اسٹافنگ ماڈل میں تبدیلی",
      season_event: "سیزنل / ایونٹ اثر",
      competitor: "مسابقتی ادارے کا داخلہ / اخراج",
      macro: "مہنگائی / ویج لا / ٹیکس تبدیلی",
    },
    pos: {
      other: "دیگر",
    },
    ops_tools: {
      scheduling: "ورک فورس شیڈولنگ",
      payroll: "پے رول فراہم کنندہ",
      purchasing: "خریداری / انوینٹری",
      delivery: "ڈیلیوری ایگریگیٹر مینیجر",
      reservations: "ریزرویشنز / ٹیبل مینجمنٹ",
      crm: "گیسٹ CRM / لائلٹی",
      bi: "BI ٹول (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "ابھی - فعال طور پر جائزہ لے رہے ہیں",
      next_quarter: "اگلی سہ ماہی",
      next_6_months: "اگلے 6 ماہ",
      this_year: "سال کے اختتام سے پہلے",
      exploring: "صرف جائزہ لے رہے ہیں · کوئی ٹائم لائن نہیں",
    },
    decision_lag: {
      minutes: "منٹ - ہم شفٹ کے دوران ردعمل دیتے ہیں",
      hours: "گھنٹے - اسی دن",
      days: "دن - ہفتہ وار ریویو سائیکل",
      weeks: "ہفتے - ماہانہ کلوز سائیکل",
      months: "مہینے - صرف سہ ماہی ریویو",
    },
    budget_band: {
      under_10k: "$10K سے کم",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "یقین نہیں",
    },
    tech_headcount: {
      none: "کوئی نہیں - ہمارے پاس کوئی مخصوص فرد نہیں",
      fractional: "جزوی / دیگر فنکشنز کے ساتھ مشترک",
      one: "1 فرد",
      two_three: "2-3 افراد",
      four_eight: "4-8 افراد",
      nine_twenty: "9-20 افراد",
      twenty_plus: "20+ افراد",
    },
  },
  bn: {
    segment: {
      qsr: "QSR / ফাস্ট ফুড",
      fast_casual: "ফাস্ট-ক্যাজুয়াল",
      casual: "ক্যাজুয়াল ডাইনিং",
      fine_dining: "ফাইন ডাইনিং",
      cloud: "ক্লাউড কিচেন / ডার্ক কিচেন",
      hotel_fb: "হোটেল F&B",
      cafe_bakery: "ক্যাফে / বেকারি",
      bar_nightlife: "বার / নাইটলাইফ",
      catering: "কেটারিং / ইভেন্টস",
      ghost_brand: "ঘোস্ট / ভার্চুয়াল ব্র্যান্ড",
      franchise: "ফ্র্যাঞ্চাইজি / মাস্টার ফ্র্যাঞ্চাইজি",
    },
    outlets: {
      "1": "1 আউটলেট",
      "2_5": "2-5 আউটলেট",
      "6_15": "6-15 আউটলেট",
      "16_50": "16-50 আউটলেট",
      "51_150": "51-150 আউটলেট",
      "150_plus": "150+ আউটলেট",
    },
    avg_unit_volume: {
      under_500k: "$500K-এর কম",
      "500k_1m": "$500K-1M",
      "1m_2m": "$1-2M",
      "2m_4m": "$2-4M",
      "4m_7m": "$4-7M",
      "7m_plus": "$7M+",
    },
    region: {
      us: "যুক্তরাষ্ট্র",
      canada: "কানাডা",
      uk: "যুক্তরাজ্য",
      ireland: "আয়ারল্যান্ড",
      europe_west: "ইউরোপ (পশ্চিম)",
      europe_nord: "ইউরোপ (নর্ডিক)",
      europe_east: "ইউরোপ (পূর্ব)",
      uae: "UAE",
      ksa: "সৌদি আরব",
      qatar: "কাতার",
      kuwait: "কুয়েত",
      bahrain: "বাহরাইন",
      oman: "ওমান",
      egypt: "মিশর",
      africa: "আফ্রিকা (অন্যান্য)",
      sea: "দক্ষিণ-পূর্ব এশিয়া",
      india: "ভারত",
      japan: "জাপান",
      korea: "কোরিয়া",
      china_hk: "চীন / হংকং",
      anzac: "অস্ট্রেলিয়া / নিউজিল্যান্ড",
      mexico: "মেক্সিকো",
      brazil: "ব্রাজিল",
      latam_other: "লাতিন আমেরিকা (অন্যান্য)",
    },
    scheduling_tool: {
      manual: "ম্যানুয়াল / স্প্রেডশিট",
      "7shifts": "7shifts",
      deputy: "Deputy",
      homebase: "Homebase",
      when_i_work: "When I Work",
      sling: "Sling",
      humanity: "Humanity",
      workforce_com: "Workforce.com",
      hotschedules: "HotSchedules / Fourth",
      quinyx: "Quinyx",
      connecteam: "Connecteam",
      crunchtime: "Crunchtime",
      r365_sched: "Restaurant365 (R365)",
      push_ops: "Push Operations",
      bayzat: "Bayzat (MEA)",
      internal: "ইন্টারনাল / কাস্টম টুল",
      pos_built_in: "POS-এ বিল্ট-ইন",
      none: "কোনো পদ্ধতিগত ব্যবস্থা নেই",
      other: "অন্যান্য",
    },
    labor_pain: {
      overstaffing: "ধীর সময়ে অতিরিক্ত স্টাফিং",
      no_show: "নো-শো / কল-আউট",
      ot_leakage: "ওভারটাইম লিকেজ",
      buddy_punching: "বাডি-পাঞ্চিং / সময় চুরি",
      payroll_errors: "পেরোল ত্রুটি",
      compliance: "কমপ্লায়েন্স / আইনগত নিয়ম",
      turnover: "কর্মী ছেড়ে যাওয়া / পুনঃপ্রশিক্ষণ",
      none: "আজ এটি প্রধান উদ্বেগ নয়",
    },
    payroll_regions: {
      us: "যুক্তরাষ্ট্র",
      canada: "কানাডা",
      uk: "যুক্তরাজ্য",
      eu: "ইউরোপীয় ইউনিয়ন",
      uae: "UAE",
      ksa: "সৌদি আরব",
      qatar: "কাতার / বাহরাইন / ওমান",
      other: "অন্যান্য (নিচে লিখুন)",
    },
    kpis_measured: {
      labor_pct: "লেবার কস্ট %",
      food_cost: "ফুড কস্ট %",
      void_comp: "Voids / Comps",
      avg_check: "গড় চেক",
      upsell: "আপসেল / অ্যাটাচ রেট",
      guest_retention: "গেস্ট রিটেনশন",
      ebitda: "প্রতি আউটলেট EBITDA",
      forecast_acc: "ফোরকাস্ট নির্ভুলতা",
      compset: "প্রতিযোগিতামূলক অবস্থান",
    },
    kpis_wished: {
      real_time_margin: "প্রতি শিফটে রিয়েল-টাইম মার্জিন",
      daypart_leak: "ডেপার্ট-স্তরের লেবার লিকেজ",
      labor_productivity: "রিয়েল-টাইম লেবার প্রোডাক্টিভিটি (প্রতি লেবার আওয়ারে সেলস)",
      live_labor_vs_demand: "লাইভ লেবার বনাম ডিমান্ড (রিয়েল-টাইম স্টাফিং পেস)",
      overtime_leakage: "ওভারটাইম ঝুঁকি ও লিকেজ, লাইভ",
      daypart_revpash: "ডেপার্ট RevPASH (Revenue per Available Seat Hour)",
      hourly_food_cost: "ঘণ্টা-স্তরের ফুড কস্ট ভ্যারিয়েন্স",
      theoretical_actual: "থিওরেটিক্যাল বনাম অ্যাকচুয়াল COGS ভ্যারিয়েন্স",
      item_profitability: "সত্যিকারের আইটেম-স্তরের প্রফিটেবিলিটি",
      menu_engineering: "মেনু ইঞ্জিনিয়ারিং ম্যাট্রিক্স (Stars / Plowhorses / Puzzles / Dogs)",
      server_upsell: "সার্ভার-স্তরের আপসেল অ্যাটাচ রেট",
      cannibalization: "ক্রস-ডে / ক্রস-চ্যানেল ক্যানিবালাইজেশন",
      promo_roi: "চ্যানেল অনুযায়ী প্রোমো ROI",
      delivery_margin: "ডেলিভারি চ্যানেল মার্জিন (থার্ড-পার্টি কমিশন ড্র্যাগ)",
      guest_ltv: "গেস্ট লাইফটাইম ভ্যালু",
      cohort_retention: "কাস্টমার কোহর্ট রিটেনশন কার্ভ",
      noshow_prediction: "রিজার্ভেশন নো-শো প্রেডিকশন",
      inventory_shrinkage: "আইটেম ক্যাটেগরি অনুযায়ী ইনভেন্টরি শ্রিঙ্কেজ",
      cash_variance: "ক্যাশ ও রেভেনিউ-অ্যাশিওরেন্স ভ্যারিয়েন্স (স্কিম ডিটেকশন)",
      peer_benchmark: "অ্যানোনিমাস পিয়ার বেঞ্চমার্ক",
      competitor_pricing: "প্রতিযোগীর প্রাইসিং ট্র্যাকিং",
      forecast_per_outlet: "প্রতি আউটলেট দৈনিক ফোরকাস্ট",
      scheduling_eff: "ডিমান্ডের বিপরীতে শেডিউলিং দক্ষতা",
      decision_replay: "ডিসিশন-টু-আউটকাম ক্লোজড-লুপ স্কোরিং",
      cross_module: "ক্রস-মডিউল কোরিলেশন ইনসাইটস",
      multi_brand_pnl: "মাল্টি-ব্র্যান্ড কনসোলিডেটেড P&L",
      compliance_drift: "কমপ্লায়েন্স / ব্র্যান্ড-স্ট্যান্ডার্ড ড্রিফট",
      payroll_readiness: "রিয়েল-টাইম পেরোল রেডিনেস",
      speed_of_service: "স্টেশন অনুযায়ী সার্ভিসের গতি / টিকিট টাইমস",
      food_waste: "ফুড ওয়েস্ট ও স্পয়লেজ ট্র্যাকিং",
      gratuity_distribution: "টিপ / গ্র্যাচুইটি বিতরণ ও কমপ্লায়েন্স",
      guest_sentiment: "গেস্ট সেন্টিমেন্ট / রিভিউ-ট্রেন্ড ট্র্যাকিং",
    },
    decision_data: {
      gut: "অভিজ্ঞতা / অন্তর্দৃষ্টি",
      spreadsheet: "অ্যানালিস্টের তোলা স্প্রেডশিট",
      pos_report: "POS স্ট্যান্ডার্ড রিপোর্ট",
      bi_dashboard: "BI ড্যাশবোর্ড (Power BI / Tableau / Looker / Domo)",
      in_house_data: "ইন-হাউস ডেটা ওয়্যারহাউস / SQL কুয়েরি",
      external: "বাইরের কনসালট্যান্ট / অ্যাডভাইজার",
      ai_tool: "AI টুল (ChatGPT / Claude / Gemini)",
      industry_report: "ইন্ডাস্ট্রি রিপোর্ট / বেঞ্চমার্ক স্টাডি",
      board_packet: "বোর্ড / লিডারশিপ প্যাকেট",
    },
    forecasting: {
      lyear_gut: "গত বছর + অভিজ্ঞতার অনুমান",
      spreadsheet: "ইন্টারনালি রক্ষণাবেক্ষণ করা স্প্রেডশিট মডেল",
      pos_system: "POS / অ্যাকাউন্টিং সিস্টেমে বিল্ট-ইন",
      bi_tool: "কাস্টম মডেলসহ BI টুল",
      ai_tool: "ডেডিকেটেড AI / ফোরকাস্টিং টুল",
      none: "আমরা আনুষ্ঠানিকভাবে ফোরকাস্ট করি না",
    },
    scenario_wish: {
      new_location: "নতুন লোকেশন খোলা",
      menu_change: "মেনু / প্রাইসিং পরিবর্তনের প্রভাব",
      promo_impact: "প্রোমোশন / ডিসকাউন্টের প্রভাব",
      staffing_model: "স্টাফিং মডেল পরিবর্তন",
      season_event: "সিজনাল / ইভেন্ট প্রভাব",
      competitor: "প্রতিযোগীর প্রবেশ / প্রস্থান",
      macro: "মুদ্রাস্ফীতি / মজুরি আইন / কর পরিবর্তন",
    },
    pos: {
      other: "অন্যান্য",
    },
    ops_tools: {
      scheduling: "ওয়ার্কফোর্স শেডিউলিং",
      payroll: "পেরোল প্রদানকারী",
      purchasing: "পারচেজিং / ইনভেন্টরি",
      delivery: "ডেলিভারি অ্যাগ্রিগেটর ম্যানেজার",
      reservations: "রিজার্ভেশন / টেবিল ম্যানেজমেন্ট",
      crm: "গেস্ট CRM / লয়্যালটি",
      bi: "BI টুল (Power BI / Tableau / Looker)",
    },
    timeline: {
      asap: "এখনই - সক্রিয়ভাবে মূল্যায়ন করছি",
      next_quarter: "পরবর্তী ত্রৈমাসিক",
      next_6_months: "পরবর্তী 6 মাস",
      this_year: "বছর শেষের আগে",
      exploring: "শুধু অনুসন্ধান করছি · কোনো টাইমলাইন নেই",
    },
    decision_lag: {
      minutes: "মিনিট - আমরা শিফটের মধ্যেই প্রতিক্রিয়া দিই",
      hours: "ঘণ্টা - একই দিন",
      days: "দিন - সাপ্তাহিক রিভিউ সাইকেল",
      weeks: "সপ্তাহ - মাসিক ক্লোজ সাইকেল",
      months: "মাস - শুধু ত্রৈমাসিক রিভিউ",
    },
    budget_band: {
      under_10k: "$10K-এর কম",
      "10_25k": "$10-25K",
      "25_50k": "$25-50K",
      "50_100k": "$50-100K",
      "100_250k": "$100-250K",
      "250_500k": "$250-500K",
      "500k_1m": "$500K-1M",
      "1m_plus": "$1M+",
      unsure: "নিশ্চিত নই",
    },
    tech_headcount: {
      none: "কেউ নেই - আমাদের কোনো নিবেদিত ব্যক্তি নেই",
      fractional: "ফ্র্যাকশনাল / অন্যান্য ফাংশনের সঙ্গে শেয়ারড",
      one: "1 জন",
      two_three: "2-3 জন",
      four_eight: "4-8 জন",
      nine_twenty: "9-20 জন",
      twenty_plus: "20+ জন",
    },
  },
} as const;

export type DiagnosticOptionPackLocale = keyof typeof indicDiagnosticOptionPacks;
